### ISSUE TITLE
BluetoothAdapter

### ISSUE THREAD

**Issue by TETRA2000** [mozilla-japan/translation#101]
~~訳します
2016/2/6~~
https://developer.mozilla.org/en-US/docs/Web/API/BluetoothAdapter_%28Firefox_OS%29

**Comment by Uemmra3** [comment]
こちら、まだ日本語版がないですが、途中まででも良いので、保存できるものはないでしょうか？
このままでは、他の人の作業と重複する場合があります。

**Comment by TETRA2000** [comment]
@Uemmra3 すみません。ほとんど手がつけられていないので、一旦保留にします。

**Comment by dynamis** [comment]
API 自体が deprecated になってると思うので close します
