### ISSUE TITLE
[MDN] CSS3 - CSS

### ISSUE THREAD

**Issue by aokashi** [mozilla-japan/translation#103]
- https://developer.mozilla.org/ja/docs/Web/CSS/CSS3

自分一人で済むのは難しいため、とりあえずIssueとして置いておきます。

**Comment by YuichiNukiyama** [comment]
気になっているページではありました。微力ながら余裕があるときに翻訳を追加していきます。

**Comment by YuichiNukiyama** [comment]
翻訳しました。JSばかりやっていたため、下手です。。。かなりお手間をかけると思いますが、お手すきの際に修正をお願いします。

**Comment by momdo** [comment]
「モジュールと標準化プロセス」節の、最初の段落の日付が誤っていたので修正しておきました。

iterationの訳出は個人的にはバージョンの方がしっくりくる気がします（が手を加えてません。） http://eow.alc.co.jp/search?q=iteration

あと英語版自体が微妙（Snapshot 2015に触れてなかったり、Selectors 4がpublic draftを出してない子扱いを受けてたり）なので、英語圏の皆さんに大鉈を振るっていただきたいですね……。

**Comment by YuichiNukiyama** [comment]
@momdo さん　レビューありがとうございます。たしかにiterationはバージョンでもよいかもしれませんね。致命的ではないのでそのままにしておきますが、気になる方は修正していただければと思います。

**Comment by Uemmra3** [comment]
ちょっと自習のために編集レビューしてみます。

**Comment by Uemmra3** [comment]
obsoleとしてアーカイブされていたので、閉じます。
