### ISSUE TITLE
this page need fix typo

### ISSUE THREAD

**Issue by lv7777** [mozilla-japan/translation#104]
https://developer.mozilla.org/en-US/docs/Template:訳注

自分では権限が無いのでfix出来ません。
この程度なら自分で権限を申請するよりは権限を持っている人になおしてもらうほうが適切かと思ってissueに出しました。

**Comment by lv7777** [comment]
修正箇所は真ん中当たりの)が抜けているとこです。

**Comment by marsf** [comment]
報告ありがとうございます。
修正しました。
