### ISSUE TITLE
[MDN] NSPR_LOG_MODULES

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#105]
先日調べてデバッグに便利な情報:
- https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR/Reference/NSPR_LOG_MODULES

こんな解説記事が書かれてるけど公式ドキュメントもあるとなおよいかな？ということで Good Firest Translation として登録します
- http://poly.hatenablog.com/entry/20080925/p1

**Comment by lv7777** [comment]
一応終わりましたが技術的に怪しいのでレビューお願いします。

**Comment by hmatrjp** [comment]
@lv7777 さん、翻訳ありがとうございました。
主に日本語の表現について、全体的に手を入れました。
編集レビューを終了とし、技術レビューフラグは立てたままにしてあります。

**Comment by Uemmra3** [comment]
英語版で技術レビューフラグが外れているので、対応が取れているようなのでフラグを外しました。
