### ISSUE TITLE
[MDN] Microdata

### ISSUE THREAD

**Issue by momdo** [mozilla-japan/translation#109]
https://developer.mozilla.org/ja/docs/Web/HTML/Microdata
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/itemid
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/itemprop
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/itemref
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/itemscope
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/itemtype

必要に迫られて翻訳しようと思いますが、technical reviewのフラグが立っていても構わず翻訳して問題ないでしょうか。

**Comment by Uemmra3** [comment]
主にFirefoxOS周りを訳してるうえむらです。

技術レビュー待ちの記事を訳しても、問題ないです。

ただし原文（en-US）が技術レビューを経て様変わりして、大幅に中身が変わる（訳し直すのが大変になる）可能性はあります。

MDN右上の設定アイコン（歯車）に、原文が変わったらメール通知を受ける設定がありますので、そうしておくと変更が追いやすいかも。
2016年3月10日(木) 21:37 Momdo Nakamura <notifications@github.com>:

**Comment by momdo** [comment]
@Uemmra3 
早速のコメントありがとうございます。可能であれば追随できるようにしておきます。

**Comment by momdo** [comment]
少し間が開きましたが、<code>itemtype</code>以外訳出完了しました。
<code>itemtype</code>に関しては私がサボっていた間に@lv7777さんが手を付けておられたのでお願いしています（<a href="https://twitter.com/levena_evenas/status/713712957499293696">Twitterでのやりとり</a>）。

**Comment by hmatrjp** [comment]
[itemid](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/itemid) の中の注で、no doubt の解釈が間違っているようでしたので、修正しておきました。

**Comment by momdo** [comment]
https://twitter.com/levena_evenas/status/716462045953073152 に基づいて未訳部分を訳出し、あわせて以下についても変更しました。

- 仕様書EditEditという英語版の不明な記述をコメントアウト
- MDN内リンクを`en-US`から`ja`に変更
- 英語版のフッターが余分に挿入されているものを削除

**Comment by momdo** [comment]
Firefox 49でサポートが打ち切られるようですね。

Microdata API が削除されました | Firefox サイト互換性情報 
https://www.fxsitecompat.com/ja/docs/2016/microdata-api-has-been-removed/

MDNも`en`が変更されたので追随しました。
積極的にメンテナンスされることもないと思われます。
