### ISSUE TITLE
[MDN]JavaScript error reference

### ISSUE THREAD

**Issue by YuichiNukiyama** [mozilla-japan/translation#110]
MDNにerror関連ページが増えていました（そういえば今までなかった）。
それぞれのページは分量も少ないですし。手始めの翻訳には良いのではないでしょうか。
[JavaScript error reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors)

**Comment by YuichiNukiyama** [comment]
あらかた翻訳が完了しました。レビューをお願いします。
MDN自体に未レビュー項目が多いので、Issueとしてはクローズしておきます。

[JavaScript エラーリファレンス](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Errors)

**Comment by hmatrjp** [comment]
いくつか見ました。
@lv7777 さん:
各エラーのページで共通して出てくる小見出し　例えば Error Type の訳は、合わせておいた方がいいと思います。
