### ISSUE TITLE
「Mac OS X ビルド環境の準備」リンクページ無し？

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#111]
[Firefox の簡単なビルド方法](
https://developer.mozilla.org/ja/docs/Mozilla/Developer_Guide/Build_Documentation/Simple_Firefox_build)
上記ページ、[Mac OS X ビルド環境の準備](https://developer.mozilla.org/ja/docs/Mozilla/Developer_guide/Build_Instructions/Mac_OS_X_Prerequisites)をクリックすると「新しいドキュメント」に遷移します。

単純にページが作成されていないのか、リンク間違いかご存知の方いたら、教えて下さい。
余談ですが、下記リンクは大丈夫でした
・[Windows ビルド環境の準備](https://developer.mozilla.org/en-US/docs/Developer_Guide/Build_Instructions/Windows_Prerequisites)
・[Linux ビルド環境の準備](https://developer.mozilla.org/ja/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation)

宜しくお願いします。

**Comment by hashedhyphen** [comment]
[ja の Linux 用ページ](https://developer.mozilla.org/ja/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation) については「この記事はまだボランティアによって 日本語 に翻訳されていません。」と表示されているので、まだ翻訳されていないはずです（あいにく私の手元には Windows 機しかなく、翻訳していただけると非常に助かります…）

ただし OS X については、言語間のリンクに問題があるのかもしれません。というのも、en-US 版の URL を Windows / Linux / Mac OS X の順に並べると

* /en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites
* /en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation
* /en-US/docs/Mozilla/Developer_guide/Build_Instructions/Mac_OS_X_Prerequisites

となり、元々は同じ記事だった Linux と Mac OS が分離され、その後 Windows と　Mac OS X にはリンク構造の修正が入ったように感じます。

言語間リンクの問題だとすると、権限を持っていらっしゃる @hamatrjp さんや @potappo さんが詳しいと思いますが、いかがでしょうか？

**Comment by hmatrjp** [comment]
Mac OS X については、
調べてみたところ、ページが作成されていない　と　リンク間違い　の合わせ技のようです。

/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Mac_OS_X_Prerequisites
から日本語訳を作成しようとすると、すでに内容があって、
REDIRECT ja/Developer_Guide/Build_Instructions/Mac_OS_X_Build_Prerequisites
となっています。

1度試しに（原文で）上書きしてみたのですが、リダイレクトが止まりませんでした。
例のごとく、時間が経てば反映されるのかもしれませんが、今はREDIRECTに戻してあります。

Linux については、リンクが切れている（古い）翻訳が見つかりましたので、つなげておきました。
1) MDN の検索窓から、 Linux  ビルド  で検索
2) 編集し、翻訳元のページを指定
（実は、この2ステップは、特別な権限なしの一般ユーザーでも可能です）

**Comment by gurezo** [comment]
:+1:

**Comment by hmatrjp** [comment]
よくよく考えたら、REDIRECT のままにしておく理由はないので、
（原文で上書きのリビジョンを）復活させました。
今の時点で、新しいページの生成ページに飛ぶ動作は変わっていませんが、
（MDN のページキャッシュの動きなのか、他の理由なのか・・・）
1日くらい、様子を見てみたいと思います。
解決しないようなら、teoli さんに相談しようかと思います。

以下、何が起きているか見てみたい人向けです：
ページの履歴は、
https://developer.mozilla.org/ja/docs/Mozilla/Developer_Guide/Build_Documentation/Mac_OS_X_Build_Prerequisites%24history
で表示可能です。

なお、内容自体の表示は、リダイレクトを無効にするため ?redirect=no を付けて
https://developer.mozilla.org/ja/docs/Mozilla/Developer_Guide/Build_Documentation/Mac_OS_X_Build_Prerequisites?redirect=no
とします。

**Comment by gurezo** [comment]
この issue の close タイミングは、どうしましょう？

**Comment by hmatrjp** [comment]
もう閉じていいと思います。
3/26 10:26 (JST)でコメントした上書きが有効になったようで、REDIRECT →Not Found にならなくなっています（私の手元で確認した限りでは）。
@gurezo さんと、@hashedhyphen さんにも確認していてただけると安心です。

**Comment by gurezo** [comment]
確認出来ましたので、クローズします。
