### ISSUE TITLE
[MFSA] Mozilla Foundation セキュリティアドバイザリにおけるtypo

### ISSUE THREAD

**Issue by llamakko** [mozilla-japan/translation#113]
* http://www.mozilla-japan.org/security/announce/2016/mfsa2016-27.html
* http://www.mozilla-japan.org/security/announce/2016/mfsa2016-25.html
* http://www.mozilla-japan.org/security/announce/2016/mfsa2016-24.html
* http://www.mozilla-japan.org/security/announce/2016/mfsa2016-23.html

上記全ての記事のタイトルにおいて、以下のtypoを発見しました。

誤: `解放後仕様`
正: `解放後使用`

**Comment by hashedhyphen** [comment]
ご指摘ありがとうございます！このリポジトリ内における過去の Issue 等々を現在確認しておりますので、またご連絡いたします！ c.f. #14

**Comment by hashedhyphen** [comment]
現時点では @kyoshino さんが翻訳を担当されているようです。

@kyoshino さん、セキュリティアドバイザリの typo 修正はどうしたら良いでしょうか…？

**Comment by kyoshino** [comment]
ご指摘ありがとうございます。修正しました。

**Comment by hashedhyphen** [comment]
kyoshino さん修正ありがとうございます！

@llamakko さん、修正された内容を確認していただき、特に問題ないようでしたら Issue を Close していただければと思います。この度はありがとうございました！

**Comment by llamakko** [comment]
早速のご対応、ありがとうございました。
修正していただいた内容に問題がないことを確認できたため、IssueをCloseさせていただきます！
