### ISSUE TITLE
[MDN] Subresource Integrityの記事におけるtypo

### ISSUE THREAD

**Issue by llamakko** [mozilla-japan/translation#114]
https://developer.mozilla.org/ja/docs/Web/Security/Subresource_Integrity

上記の記事において、以下のtypoを発見しました。

誤: しかし、`CND`はリスクにもなりえます。
正: しかし、`CDN`はリスクにもなりえます。

自分で修正をしようと思ったのですが、現在MDNの新規の登録は無効化されているようで自分では編集ができないため、こちらにて報告をさせていただきます。

**Comment by hashedhyphen** [comment]
ご指摘ありがとうございます！先ほど修正いたしましたので、ご確認いただけますでしょうか？

**Comment by llamakko** [comment]
ご対応ありがとうございます。
修正されていることを確認できました！
