### ISSUE TITLE
The History of MDN

### ISSUE THREAD

**Issue by lv7777** [mozilla-japan/translation#115]
https://developer.mozilla.org/ja/docs/MDN_at_ten/History_of_MDN

お願いします。

**Comment by hmatrjp** [comment]
@lv7777 さん
日本語になっていたところは一通り見ました。全体的に手を加えています。
冒頭の EmbedLiveSample マクロによる音声再生が、例のごとくファイル位置の指定の問題がらみでうまく機能していません。

**Comment by momdo** [comment]
@lv7777さん
私もよくやらかしますが、表現が微妙にふらついているので、可能な範囲で統一等を試みました。

- 「～さん」を「～氏」に
- コミュニティー? と長音あるなしが混じっていたので、ありに。
- web→Web、wiki→Wikiに
- 日本語の単語間のスペースを削除
- 日本語の文で括弧を全角に
- 外国の地名をカナのみに


MDNの翻訳方針を私は知らないのでわかりませんが、日本語と英語との間に半角スペースを設けるなら設けるように統一すべきでしょう。また、`id`属性値を書き換えなくてもいいのかなと個人的には思います。このあたりは@lv7777さんの意志を尊重して触っていません。

**Comment by hmatrjp** [comment]
@momdo さん　ありがとうございます。

> - コミュニティー? と長音あるなしが混じっていたので、ありに。
> -  web→Web、wiki→Wikiに
> -  外国の地名をカナのみに

このあたりは、私も部分的に触っており、不統一を持ち込んだのは私である可能性が高いです。また

> - 日本語と英語との間に半角スペースを設ける

これについては、昔作成された [www.mozilla-japan.org の和訳ガイド](http://www.mozilla-japan.org/jp/td/guide.html#section-5)ではそのようになっていまして、
私は MDN で作業するときも入れるようにしています。
id属性値については、MDN のエディタが自動的にいじる部分があり、必ずしも編集者の意向が反映されません。→参考 [MDN 技術ドキュメントの翻訳について](https://developer.mozilla.org/ja/docs/Project:Translation#.E8.8B.B1.E8.AA.9E.E7.89.88.E3.83.89.E3.82.AD.E3.83.A5.E3.83.A1.E3.83.B3.E3.83.88.E3.82.92.E7.BF.BB.E8.A8.B3.E3.81.99.E3.82.8B)

**Comment by lv7777** [comment]
@momdo さん、ありがとうございます。

表記揺れも多少は意識してたのですが、結構ありますね・・・以後気を付けます。

> id属性値を書き換えなくてもいいのかな

id属性値というのはcssのアレですか？

**Comment by lv7777** [comment]
@hmatrjp さん、ありがとうございます。

> 日本語と英語との間に半角スペースを設ける

なるほど。

idについては初めて知りました。また試してみようと思います。

**Comment by momdo** [comment]
@hmatrjp さん

ありがとうございます。Linuxのプロジェクトを基にした翻訳方針があるわけですね。
（MDNでスペースを入れるのが流儀であれば、今後は私も従うようにします。
ちなみに、入れないというやり方は『JTF日本語標準スタイルガイド』
https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf#page=20&zoom=auto,69,539
に依ります。）

idの方はエディタの仕業なわけですか。了解しました（普段HTMLソースで直接作業してしまうので、気がつきませんでした）。

**Comment by Uemmra3** [comment]
ちょっとだけ英語のままの部分があったので、すべて日本語にして翻訳中フラグを外しました。
どなたか全体的なレビューしていただけると良いかと。

**Comment by lv7777** [comment]
@Uemmra3 ありがとうございます・・・！当初はMDNの歴史を知りたいと思って訳し始めたのですが、
ワッフルフラグに関する部分がよくわからなくて（ググっても出てこなくて）放置してしまってました。。。

**Comment by Uemmra3** [comment]
私もMDN歴は浅いので、ワッフルフラグはよく分かってません(汗
図にあるような食べるワッフルの形をした旗なのかな？とは思いますが、MDNの中での意味付けはわからないです。
どなたかフォローやレビューお願いしますf(^^;

**Comment by hmatrjp** [comment]
まずは、Waffle にあまり気を取られずに、原文にある Feature flag または Feature Toggle を調べた方が理解が早いと思います。

Google で、MDN's feature flag system で検索して出てきたページから、次のものを読みました。
http://stackoverflow.com/questions/7707383/what-is-a-feature-flag
この中で数人が回答しているのは、「コードの実装とユーザー向けの機能公開を分離する」
というコンセプトです。

MDN のコードベースの中を探したら、該当しそうな説明がありました。
https://github.com/mozilla/kuma/blob/master/docs/feature-toggles.rst
Python のライブラリである django-waffle が使われているそうです。

（ほとんど読んでませんが、Wikipedia にも項目があります。
　https://en.wikipedia.org/wiki/Feature_toggle　）

Waffle という言葉が使われているのは、
あの凹凸が、複数の凹凸スイッチを並べて機能のオンオフを切り替えることができるパネル　を連想させるからではないでしょうか。

**Comment by Uemmra3** [comment]
とりあえずざっと見て良さそうなので、編集レビュー済みとして閉じますね。
