### ISSUE TITLE
[Hacks] How to implement SRI in your build process

### ISSUE THREAD

**Issue by hashedhyphen** [mozilla-japan/translation#116]
[How to implement SRI in your build process](https://hacks.mozilla.org/2016/04/how-to-implement-sri-into-your-build-process/) を翻訳します。

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/04/how-to-implement-sri-into-your-build-process/ すみません。入れ違いで翻訳してしまいました。

**Comment by hashedhyphen** [comment]
まだ翻訳進んでいない段階だったので大丈夫です！

**Comment by hmatrjp** [comment]
結論　の直後、脱字があります。
Subresource Interity
→Subresource Integrity
