### ISSUE TITLE
HTML 5 game development video series 

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#117]
https://hacks.mozilla.org/2016/02/html-5-game-development-video-series/ 訳します

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/04/html-5-game-development-video-series/ で公開済み

**Comment by hmatrjp** [comment]
これ、MDNの記事ではないのでは？（ラベル）

それから、重複、脱字を見つけました。

　Web 向けにゲームを開発するる理由
→Web 向けにゲームを開発する理由

　私もなんどとなく参加しる大会ですが、
→私も何度となく参加している大会ですが、
