### ISSUE TITLE
[Hacks] Google Analytics, Privacy, and Event Tracking

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#119]
プライバシー系です：
https://hacks.mozilla.org/2016/01/google-analytics-privacy-and-event-tracking/

**Comment by hashedhyphen** [comment]
翻訳します！

**Comment by hashedhyphen** [comment]
翻訳が終わりました。
[Google アナリティクスとプライバシー・イベントトラッキング](https://dev.mozilla.jp/2016/04/google-analytics-privacy-and-event-tracking/)

**Comment by chikoski** [comment]
ありがとうございます！！！めっちゃわかりやすかったです！
