### ISSUE TITLE
[Hacks] Developer Edition 46 – More memory tooling, improved @media sidebar and more

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#120]
Developer Edition 46 について：
https://hacks.mozilla.org/2016/02/developer-edition-46-more-memory-tooling-improved-media-sidebar-and-more/

担当します

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/04/developer-edition-46-more-memory-tooling-improved-media-sidebar-and-more/ で公開しました。

**Comment by hmatrjp** [comment]
@chikoski さん、公開された和訳、読みました
可能であれば、次の2か所を修正した方がよいと思います。

メモリの使用状況をプロファイリングに有用な新機能を
→メモリの使用状況をプロファイリングするのに有用な新機能を

Emscripten に起因する機能
→Emscripten 関数名を復元する機能
mangling がコンパイラによる関数名等の変更のことで、 demangling はその逆です。

**Comment by chikoski** [comment]
ありがとうございます。

> メモリの使用状況をプロファイリングに有用な新機能を
> →メモリの使用状況をプロファイリングするのに有用な新機能を

「メモリ使用状況のプロファイリングに有用な新機能を」に修正しました。

> Emscripten に起因する機能
> →Emscripten 関数名を復元する機能

ああ、これは demangling をdemanding と見間違えていました。
ご提案通りに修正しておきました。
