### ISSUE TITLE
[Hacks] WebGL Off the Main Thread

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#121]
WebGL: https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/

**Comment by chikoski** [comment]
終了

**Comment by hmatrjp** [comment]
最後の[トラッキングバグ](https://bugzilla.mozilla.org/show_bug.cgi?id=1203382)へのリンクが、和訳ではなくなっているようです。

**Comment by chikoski** [comment]
ありがとうございます。修正しておきました。
