### ISSUE TITLE
[MDN] Functions and classes available to Web Workers

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#122]
- Worker から利用出来る関数とクラスの一覧
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers

**Comment by YuichiNukiyama** [comment]
よいページですね。週末にでも翻訳します。
Service Worker周りは未翻訳が多いので、一気にやりたいですね。。。

**Comment by chikoski** [comment]
おねがいします。

ServiceWorker 周りは確かに一気にやってしまいたいですね。
翻訳祭かイベントか、そんな形で一気にやりましょう・・・

**Comment by YuichiNukiyama** [comment]
翻訳しました。
https://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers

翻訳祭り良いですね。新しい技術は日本語情報が少ないものもあるので、まとまって翻訳されていると喜ばれると思います。

**Comment by hmatrjp** [comment]
@YuichiNukiyama さん 翻訳ありがとうございます。
比較表の上だけ見ました。表内は、技術的に正しいかどうか判別する自信がないので。

冒頭の set of functions にある set は 設定 ではなく 集合 の方の意味です。
日本語では、なしでも意味が通ってしまうので省きました。

**Comment by Uemmra3** [comment]
概ね良さそうなので閉じます
