### ISSUE TITLE
[MDN]CSSの変数を使う

### ISSUE THREAD

**Issue by lv7777** [mozilla-japan/translation#125]
firefox,chrome,opera,safariなどいろいろな場所で使えるようになってきました。

https://developer.mozilla.org/ja/docs/Web/CSS/Using_CSS_variables

**Comment by YuichiNukiyama** [comment]
未翻訳部分の対応をしました。本家のリビジョンが大幅に変わっていたので、バッサリと減っているところがあります。

**Comment by hmatrjp** [comment]
ありがとうございます。
#162 の対応を含めて、いくつか訳に手を入れました。

**Comment by lv7777** [comment]
翻訳お疲れ様です。ありがとうございました。
closed.
