### ISSUE TITLE
W^X JIT-code enabled in Firefox

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#126]
http://jandemooij.nl/blog/2015/12/29/wx-jit-code-enabled-in-firefox/

46.0 のリリースノートから参照されているブログ。セキュリティ系です。

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/04/wx-jit-code-enabled-in-firefox/ で公開しました。

**Comment by hmatrjp** [comment]
@chikoski さん、読みました。わかりやすかったです。

W^X 保護の動作　の節にある
land の訳（2か所）は、この場合対象がパッチなので、取り込む でいいと思います。

しかしランドされることはありませんでした。
→しかし取り込まれることはありませんでした。

オーバーヘッドもあるため、ランドされませんでした。
→オーバーヘッドもあるため、取り込まれませんでした。

でいかがでしょう？

**Comment by chikoski** [comment]
@hmatrjp 

ありがとうございます！landの訳には困っていたので、めっちゃ助かりました。
直させていただきます。
