### ISSUE TITLE
Developer Edition 48 – Firebug features, editable storage, inspector improvements and more…

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#129]
* https://hacks.mozilla.org/2016/04/developer-edition-48-firebug-features-editable-storage-inspector-improvements-and-more/

やります

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/05/developer-edition-48-firebug-features-editable-storage-inspector-improvements-and-more/ で公開しました。

**Comment by hmatrjp** [comment]
翻訳ありがとうございます。いくつか気づいた点を書きます。

ストレージ中の要素をを
→ストレージ中の要素を

長い値　と訳されている long value については、 long 値　の方が一般的だと思います。

about:debugging の画面から、
アドオンの再読み込みです。
→about:debugging の画面からのアドオンの再読み込みです。

アドオンを再インストールすることなく
→アドオンに手を加えるたびに再インストールすることなく

ここのワーカの削除機能も
→個々のワーカの削除機能も
