### ISSUE TITLE
 A Taste of JavaScript’s New Parallel Primitives

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#130]
* https://hacks.mozilla.org/2016/05/a-taste-of-javascripts-new-parallel-primitives/
* SharedArrayBuffer のお話です

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/05/a-taste-of-javascripts-new-parallel-primitives/ で公開しました

**Comment by hmatrjp** [comment]
こんばんは。@chikoski さん翻訳ありがとうございます。読みました。
JavaScript にも並列化の波が押し寄せて来ているんですね。

計算中のブラウザに対してユーザが可能な操作の範囲　　と訳されている
the extent to which the user can interact with the browser while it’s computing
は、
ユーザーが計算中のブラウザとやり取りできる度合い　　と訳した方がしっくり来ると思います。　
to the extent ... という熟語があり、これは 範囲 でなく　〜程度　と訳されることが多いようです。
the extent to which は、ここではこの変形として使われているのだと思います。

検証することも難しなります。
→検証することも難しくなります。

コア上のいくつかのリソースをきょうゆうします。
→コア上のいくつかのリソースを共有します。
