### ISSUE TITLE
[MDN]動的なスタイル情報の利用

### ISSUE THREAD

**Issue by unarist** [mozilla-japan/translation#131]
https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information

[CSSカテゴリのトップページ](https://developer.mozilla.org/ja/docs/Web/CSS)に載っていたので訳し始めましたが、トップページが書かれたころからURLが変更されていてリンクにならない上に、英語版のトップページでは個別の記事を列挙しなくなってますね・・・。

**Comment by hmatrjp** [comment]
本来なら、CSSカテゴリのトップページにあるリンク [動的なスタイル情報の利用](https://developer.mozilla.org/ja/docs/DOM/Using_dynamic_styling_information)から、unarist さんが訳し始めたリンクにリダイレクトがかかり、自動的に飛ぶ所（en-USではそうなっている模様）ですが、ja では
https://developer.mozilla.org/ja/docs/DOM/Using_dynamic_styling_information?redirect=no
が別途作られており、英語に飛ばしている様子です。
訳はそのまま進めてもらって、余裕があれば後に（または並行して） [CSS カテゴリのトップページ](https://developer.mozilla.org/ja/docs/Web/CSS)と、現在のリンク元である
[HTMLElement.style](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style)の原文に日本語訳を追随してもらうのが良いのではないかと思います。

**Comment by hmatrjp** [comment]
[CSS カテゴリのトップページ](https://developer.mozilla.org/ja/docs/Web/CSS)にあるリンクについて、
https://developer.mozilla.org/ja/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information
に飛ぶよう修正しました。

放置しておくと、元のリンクから飛んだ英語ページから、@unarist さんが翻訳中の日本語ページとは別の
日本語ページが作成できてしまうことに気づいたからです。
CSS のトップページと、その配下の CSS development guide の日本語訳が原文に追いついた時には削除されるリンクですが、衝突事故防止にということで。

**Comment by unarist** [comment]
@hmatrjp さん、トップページの修正ありがとうございます。関連ページの件も了解しました。

ひとまず本ページについては一通り訳しました。個人的に気になる点としては、 (style) rule の訳に悩んで微妙な感じになっています。

その他MDN日本語版の作法やローカライズフラグやレビューフラグの使い方等、おかしな点がありましたらご指摘いただけると助かります。

**Comment by hmatrjp** [comment]
@unarist さん：翻訳ありがとうございました。

まずフラグについて。
一通り訳し終えたなら、　翻訳中　のフラグは外していいです。
ただ、サンプルコードの中に（ボタンに表示される文字など）、まだ日本語訳が可能な部分があるので
できれば訳してしまってください。（その意味で、翻訳中のフラグが立っているのは不自然ではありません）

記事翻訳後のレビューリクエストのフラグについては、
・編集レビューフラグは、例えば日本語の言い回しで気になる点がある場合に
・技術レビューフラグは、訳が技術的に正確か不安な場合に
立てておきます。両方立つ場合もあります。

**Comment by unarist** [comment]
サンプルコード内のテキストを翻訳して翻訳中フラグを外し、編集レビューフラグを立ててみました。

**Comment by hmatrjp** [comment]
遅くなりましたが、一通り見ました。
rule については、CSSでの xxx : yyyy のような一文での指定、 style は、その rule が集まったものと解釈して読んでいくと、ほぼ通じるように思いました。

**Comment by unarist** [comment]
修正点確認しました。レビューありがとうございます！
