### ISSUE TITLE
Exporting An Indie Unity Game to WebVR

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#132]
Unity コンテンツを WebVR に対応させるには、という記事です。
担当します。

**Comment by lv7777** [comment]
おお、ありがとうございます。
webVR興味あるので。

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/06/exporting-an-indie-unity-game-to-webvr/ に公開しました。

**Comment by hmatrjp** [comment]
@chikoski さん、翻訳ありがとうございます。
大した間違いではないですが、読んでいて、脱字と誤字を1つずつ見つけました。
・エディタ内でテスする
　→エディタ内でテストする
・SECVRITY が SERVRITY　になっているところが1ヶ所あります。

**Comment by chikoski** [comment]
@hmatrjp さん、誤字が多くてお恥ずかしい。でもおかげで修正できました。
ありがとうございました。

**Comment by Uemmra3** [comment]
ＶＲからはオフですが、誤字や「てにおは」とかを直すのを、l10nハンズオンとかでやるのも良いかと思いました。流れをつかむ意味で。

**Comment by hmatrjp** [comment]
ほんとは 別Issue を立てるかなにかするほうがいいと思うのですが、ここに返信してしまいます。
@Uemmra3 さん：
> 誤字や「てにおは」とかを直すのを、l10nハンズオンとかで
確かに、「日本語だけでも参加できるMDN」 を推してユーザー層を広げるという意味で、いいと思います。
（なお、@chikoski さんが訳してくれている一連の記事は、公開先が modest （ブログシステム）で、
　記事の編集は原則、本人にしかできません。）

**Comment by chikoski** [comment]
#146 に issue 立てました。MDN についてはこちらで、議論しましょう。
