### ISSUE TITLE
{{firefoxOSSidebar}} の中身の日本語化

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#138]
左右のインデックスが統一のものになったのは良いのだが、英語表記なのでもんにょりする。

仕組みはよくわかってません…想像の範疇ですが、
- マルチロケールにする
- 個々の見出しを日本語化する

とかになるのかなぁ。

**Comment by hmatrjp** [comment]
@Uemmra3 さん：　仕組みについてだけ、回答します。ほぼ、ご想像のとおりです。

このマクロのソースコードは
https://developer.mozilla.org/en-US/docs/Template:firefoxOSSidebar
にあり、閲覧は誰でもできます。編集するには権限が必要です。

16-57行目に en-US のメッセージ定義部分がありますね。
ja についての定義を、このうしろに追加すればOKです。

**Comment by Uemmra3** [comment]
Firefox OS がアーカイブされたので閉じますね。
