### ISSUE TITLE
[MDN] position:static が「既定の振る舞い」？

### ISSUE THREAD

**Issue by unarist** [mozilla-japan/translation#140]
https://developer.mozilla.org/ja/docs/Web/CSS/position

> **static**
> 規定の振る舞いです。フロー内の現在の位置に配置されます。top、right、bottom、left、z-index プロパティは適用されません。

原文では次のようになっています。

> **static**
> This keyword lets the element use the normal behavior, that is it is laid out in its current position in the flow.  The top, right, bottom, left and z-index properties do not apply.

normal behavior は「規定の振る舞い」というより「既定の振る舞い」でしょうか？

**Comment by momdo** [comment]
Weblioによれば、

>1 (⇔abnormal)
>a標準の，規定の，正規の.
>http://ejje.weblio.jp/content/normal

ということなので、これを訳出した人は辞書の訳語を使ったと言うことではないかと。
この訳語でよいのかどうかはまた別問題ですが、かといって既定とするのも個人的にはどうなのかなあとは。
要するに通常フローだと言うことが言えればいいので、もし変えるならそのようにするのがよいのかなと。

参考：https://developer.mozilla.org/ja/docs/Web/CSS/Visual_formatting_model#Positioning_schemes

**Comment by unarist** [comment]
ああなるほど。改めて読むと「通常」という言葉がしっくり来るので、

> フロー内の現在の位置に配置される、通常の挙動です。top、right、bottom、left、z-index プロパティは適用されません。

というのを考えましたが、現在の訳のように normal behavior に相当する文が頭にあった方がいいでしょうか。

**Comment by momdo** [comment]
@unarist 
> フロー内の現在の位置に配置される、通常の挙動です。top、right、bottom、left、z-index プロパティは適用されません。

これでいいと思います。

**Comment by unarist** [comment]
適用しました： https://developer.mozilla.org/ja/docs/Web/CSS/position$revision/1130803
