### ISSUE TITLE
「Firefox OS のビルドとインストール」のタイトルをB2G OSに変更していく

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#151]
https://developer.mozilla.org/ja/Firefox_OS/Building_and_installing_Firefox_OS
以下のページの
Firefox OS のビルドとインストール
などを
B2G OS のビルドとインストール
などにえんえんと変更していく。
単純作業ではあります。

**Comment by Uemmra3** [comment]
とりあえずタイトルは B2G OS へと変更しました。
(左側のサイドバーに出てくるものは一通り対応したハズです)

**Comment by hmatrjp** [comment]
@Uemmra3 さん、地道な作業をありがとうございます。
さきほど
https://developer.mozilla.org/ja/Firefox_OS
を
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS
に移動するリクエストを出し、
無事に complete したというMDNシステムからのメールが届きました。

今回はサブページが 149 あると表示されたので、影響の範囲も大きいです。
ページによっては、多重のリダイレクトが残っていたり、
すんなり動いてくれていないものもあるかもしれません。
何かおかしなところに気づきましたら、お知らせください。
