### ISSUE TITLE
Fetch API 

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#153]
そろそろ Fetch API も使う準備ができてきたと思うので、MDN の記事を翻訳していったほうが良いように思います。
- [x] [Fetch API](https://developer.mozilla.org/ja/docs/Web/API/Fetch_API)
- [x] [Headers](https://developer.mozilla.org/ja/docs/Web/API/Headers)
- [x] [Request](https://developer.mozilla.org/ja/docs/Web/API/Request)
- [x] [Response](https://developer.mozilla.org/ja/docs/Web/API/Response)
- [x] [Body](https://developer.mozilla.org/ja/docs/Web/API/Body)
- [x] [GlobalFetch](https://developer.mozilla.org/ja/docs/Web/API/GlobalFetch)
- [x] [GlobalFetch.fetch()](https://developer.mozilla.org/ja/docs/Web/API/GlobalFetch/fetch)
- [x] [FetchEvent](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent)
- [x] [FetchEvent.respondWith()](https://developer.mozilla.org/ja/docs/Web/API/FetchEvent/respondWith)
- [x] [Using Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)
- [x] [Fetch basic concepts](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Basic_concepts)

**Comment by YuichiNukiyama** [comment]
一時期、よく翻訳してました。レビューしていただけたところもあるようでありがとうございます。エラー周りの翻訳が終わったら、一部お手伝いします。取り急ぎ、[FetchEvent.respondWith()](https://developer.mozilla.org/ja/docs/Web/API/FetchEvent/respondWith)だけ翻訳しておきました。

**Comment by chikoski** [comment]
ありがとうございます。レビューしておきました。

**Comment by YuichiNukiyama** [comment]
[Body](https://developer.mozilla.org/ja/docs/Web/API/Body)

**Comment by YuichiNukiyama** [comment]
[Fetch の基本コンセプト](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Basic_concepts)

**Comment by YuichiNukiyama** [comment]
[Headers](https://developer.mozilla.org/ja/docs/Web/API/Headers) まで訳しました。残りの部分は @chikoski  さんと @lv7777 さんが手を付けているようなので、これで未着手はなしですね。

**Comment by chikoski** [comment]
ありがとうございます！！

**Comment by lv7777** [comment]
Some of these operations are only useful in {{domxref("ServiceWorker_API","ServiceWorkers")}}, but they provide a much nicer API for manipulating headers.

という記述があったんですが探してもそれっぽいapiがありませんでした。誰か知ってる方いませんか?

Fetch概要の記事です

**Comment by lv7777** [comment]
Fetch概要だいたい終わったんでレビューしてくれると助かります。(未翻訳のところは英文がわからなかったり技術的に謎なところです。)

**Comment by YuichiNukiyama** [comment]
@lv7777 さん
ServiceWokerには Header API は実装されていないはずです。ServiceWokerでヘッダーをカスタマイズしようとすると、Header用のオブジェクトを自作しないといけないので、Headers interfaceと組み合わせた方が便利ですよ～程度のことを言いたいんだと思います。ちなみに、Header用オブジェクトを自作している例は[Using Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Custom_responses_to_requests)に載っています。（手順2のところです）

**Comment by lv7777** [comment]
なるほどそういう意味だったんですね！ありがとうございました。

元記事のほうも確認しました。とても分かりやすい翻訳でした。一件、`webに公開されません`というのを`リクエストやレスポンスに含まれません`に修正しました。

**Comment by Uemmra3** [comment]
閉じてもよいのかしら？

**Comment by hmatrjp** [comment]
チェックの付いていない3つには、未訳部分が残っているようです。
現行APIなら、開けておいても良いのでは。

- [ ] [GlobalFetch.fetch](https://developer.mozilla.org/ja/docs/Web/API/WindowOrWorkerGlobalScope/fetch)　末尾の注記のみ残り
- [ ] [FetchEvent](https://developer.mozilla.org/ja/docs/Web/API/FetchEvent)　ほとんど手付かず
- [ ] [Using Fetch](https://developer.mozilla.org/ja/docs/Web/API/Fetch_API/Using_Fetch)　末尾の注記のみ残り

**Comment by hmatrjp** [comment]
とりあえず、GlobalFetch.fetch を見ます。

**Comment by hmatrjp** [comment]
[GlobalFetch.fetch()](https://developer.mozilla.org/ja/docs/Web/API/WindowOrWorkerGlobalScope/fetch) 、最新の原文版に追随しました。

**Comment by marsf** [comment]
Using Fetch の更新と残りを翻訳しました。

**Comment by Uemmra3** [comment]
FetchEvent まで翻訳完了しました。お疲れ様でしたー。
