### ISSUE TITLE
SUMO: I found a fake Firefox update

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#156]
* 偽のアップデート情報が通知された場合の対処方法について
* [こちら](https://support.mozilla.org/ja/kb/i-found-fake-firefox-update/translate) から翻訳できます。

**Comment by dskmori** [comment]
done.
https://support.mozilla.org/ja/kb/i-found-fake-firefox-update/revision/129345

**Comment by chikoski** [comment]
ありがとうございます！
