### ISSUE TITLE
What’s Next for Multi-process Firefox

### ISSUE THREAD

**Issue by elie-j** [mozilla-japan/translation#158]
Future Releases Blog に掲載されたマルチプロセスについての記事です。どなたかご興味がある方がいればぜひ。
https://blog.mozilla.org/futurereleases/2016/08/02/whats-next-for-multi-process-firefox/

**Comment by chikoski** [comment]
Mozilla Japan で翻訳します

**Comment by chikoski** [comment]
https://dev.mozilla.jp/2016/08/firefox-%e3%83%9e%e3%83%ab%e3%83%81%e3%83%97%e3%83%ad%e3%82%bb%e3%82%b9%e5%8c%96%e3%81%ae%e4%bb%8a%e5%be%8c/ で公開
