### ISSUE TITLE
Enhancing Download Protection in Firefox

### ISSUE THREAD

**Issue by elie-j** [mozilla-japan/translation#159]
セキュリティブログに掲載されたダウンロード保護機能についての記事です。
https://blog.mozilla.org/security/2016/08/01/enhancing-download-protection-in-firefox/

**Comment by dynamis** [comment]
#- (hashedhyphen) さんが翻訳＆公開してくれましたので close します:
http://mozsec-jp.hatenablog.jp/entry/2016/08/08/000943
