### ISSUE TITLE
B2G OS Architecture

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#166]
[B2G OS Architecture](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/B2G_OS_Architecture) の翻訳をします。

**Comment by gurezo** [comment]
どなたかレビューをお願い致します。

**Comment by hmatrjp** [comment]
上のリンクから、日本語ベージに飛ぶと、[Firefox OS のアーキテクチャ](https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform/Architecture) （← @gurezo さんが 貢献者に含まれていない）に飛びます。

[原文の履歴](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Architecture$history)を見ると、9/14 に Firefox OS の時代のものを Archive から取り出している様子。

**Comment by gurezo** [comment]
リンクの飛び先
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform/Architecture

自分が翻訳
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/B2G_OS_Architecture

> 9/14 に Firefox OS の時代のものを Archive から取り出している様子。

今回翻訳していないページを見つけてからの作業でした。
この場合、どうしたら良いのでしょうか？
Archive のモノだからボツ？でしょうか？

履歴もちょっと確認してみました
英語版
https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Architecture$history

日本語（自分の修正履歴）
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/B2G_OS_Architecture$history

**Comment by gurezo** [comment]
原文みたら、全く違う・・・。

9/15の履歴記載の事を @hmatrjp さんは、教えて下さったのですね。
 Archive/Firefox_OS/Platform/Architecture => Mozilla/B2G_OS/Architecture 

ボツで、翻訳し直しですね・・・・。
しかもボリュームが・・・・。

**Comment by hmatrjp** [comment]
今の（長くなった方の）原文に追随しようと思うと、
9/14 に@gurezo さんが新たに訳してくれた結果の日本語ベージは、残念ですがボツとし、
今後の進め方としては、次のようになるかと思います。

1. @gurezo さんの新しい方の訳を退避する (3. のため。MDN では、基本的にページの削除はしない)
2. 和訳のベースは、今 https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform/Architecture　にあるものとする。（FirefoxOS → B2G OS への書き換えなど）
3. 2.の URL を変更する（原文のツリーと合わせる）
4. https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS　の SubNav 節にあるリンクを書き換える

（1. と 3. は、ベージの移動権限が必要）

> 原文が全く違っている（驚

このIssue のできた直後に私も1度見てます。確かに原文がとても短くなっていました。
今回、Archive から表に引っ張り出されたのは、
ツリーの再構成と、1度 Archive に入れたものの中から使えるものを探した結果ではないかと思います。

**Comment by gurezo** [comment]
@hmatrjp さん、アドバイスありがとうございます。
> 1. @gurezo さんの新しい方の訳を退避する (3. のため。MDN では、基本的にページの削除はしない)
これは、具体的にどのような作業をすれば良いですか  ?（例えば、複製？）

今すぐ着手出来る作業は、2と4ですね！
ちょっと長文になったので、内容と照らし合わせながらやってみます。

**Comment by gurezo** [comment]
下記リンクの単語置換を行いました
Firefox OS => B2G OS
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform/Architecture
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform

**Comment by hmatrjp** [comment]
1. , 3. とも、想定している作業は、ページの移動 です。

単独ページでの移動を考えていましたが、ページ間リンクを追っていて気が変わりました。
Firefox_OS → B2G_OS への変更に際して、ドキュメントの構成もいくつか変化があったようでして。
英語ページでは [Firefox_OS/Platform](https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform) がまるごと [Archive内](https://developer.mozilla.org/en-US/docs/Archive/Firefox_OS/Platform) に移っています。
その中から必要なものを [B2G_OS/](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS) 以下に移しているようですので、日本語ベージでもまず [B2G_OS/Platform](https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform) を Archive/Firefox_OS/Platform に移すつもりです。影響を受けるページは、以下の28ページです。

ただ、この移動は Archive/Firefox_OS が存在しないと実行できないので、B2G_OS への変更が入る直前の版、
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS$revision/1001497 を、Archive/Firefox_OS に複製します。


-    /ja/docs/Mozilla/B2G_OS/Platform/Gaia (Gaia)
-     /ja/docs/Mozilla/B2G_OS/Platform/Gaia/Gaia_apps (Gaia アプリ)
-     /ja/docs/Mozilla/B2G_OS/Platform/Gaia/Gaia_apps/Window_Management (Window Management)
-     /ja/docs/Mozilla/B2G_OS/Platform/Gaia/Gaia_apps/%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6 (ブラウザ)
-     /ja/docs/Mozilla/B2G_OS/Platform/Gaia/Gaia_apps/%E8%A8%AD%E5%AE%9A%E3%82%A2%E3%83%97%E3%83%AA (設定アプリ)
-     /ja/docs/Mozilla/B2G_OS/Platform/Apps_architecture (Firefox OS アプリのアーキテクチャ)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing (Firefox OSの自動テスト)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/Setting_up_Marionette (Firefox OSのMarionetteの設定)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/XPCShell (XPCShell)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests (Gaia UI テストの導入)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Gaia_UI_Tests_Run_Tests (Gaia UI Tests: Running Tests)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_1_Marionette_Firefox_OS_start (パート 1: Marionette と Firefox OS を開始する)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_2_Marionette_Firefox_OS_interactions (パート 2: Marionette を使って Firefox OS と基本的なやりとりをする)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_3_Reusable_tests (パート 3: コードを再利用可能テストに更新する)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_4_Reusing_commands_Firefox_OS_setup (パート 4: Firefox OS をセットアップする再利用コマンド)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_5_Introducing_a_test_runner (パート 5: テストランナーを導入する)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_6_Marionette_By_class (パート 6: クラスによって、タプルと Marionette を使う)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_7_Writing_your_own_tests (パート 7: 自分自身のテストを書く)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_8_Using_a_base_class (パート 8: ベースクラスを使用する)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/gaia-ui-tests/Part_9_app_objects (パート 9: アプリオブジェクトの複製を抑える)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/Gaia_unit_tests (Gaiaユニットテスト)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/Gaia_performance_tests (Gaia パフォーマンステスト)
-     /ja/docs/Mozilla/B2G_OS/Platform/Testing/Raptor (Raptor: Gaia用パフォーマンスツール)
-     /ja/docs/Mozilla/B2G_OS/Platform/Architecture (Firefox OS のアーキテクチャ)
-     /ja/docs/Mozilla/B2G_OS/Platform/Gonk (Gonk)
-     /ja/docs/Mozilla/B2G_OS/Platform/Out_of_memory_management_on_Firefox_OS (Firefox OSの低メモリ管理)
-     /ja/docs/Mozilla/B2G_OS/Platform/Feature_support_chart (機能サポート表)
-     /ja/docs/Mozilla/B2G_OS/Platform/Keyboard_events_across_browser_elements (ブラウザ要素をまたいだキーボードイベント)

**Comment by gurezo** [comment]
-  /ja/docs/Mozilla/B2G_OS/Platform/Gaia (Gaia)
- /ja/docs/Mozilla/B2G_OS/Platform/Gaia/Gaia_apps (Gaia アプリ)

上記２記事置き換えてしまいましたが、ページ移動が終わってからの方がよいですか？

**Comment by gurezo** [comment]
ページ移動が完了したら、教えてくださいませ。
その後に単語の置き換えを行います。

**Comment by hmatrjp** [comment]
@gurezo さん、お待たせしました。
Platform 以下の Archive への移動と、その中の B2G OS Architectureの 移動（前述の3. のページ移動）が完了しました。1. は必要なかった（URL が違うため、退避の必要がなかった）ため触っていません。

タイトルが「Firefox OS のアーキテクチャ」のままですが、これは編集ページの　翻訳についての説明　をクリックすると変更できますので、お願いします。

@gurezo さん含め、みなさま：
というわけで、Platform 以下にあったページのほとんどが Archive 入りしています。アーキテクチャのページの他に、Archive から表に出す必要のページが含まれていましたらお知らせください。

**Comment by gurezo** [comment]
> タイトルが「Firefox OS のアーキテクチャ」のままですが、これは編集ページの　翻訳についての説明　をクリックすると変更できますので、お願いします。

承知しました、対応します。
他のページも同様に着手します。

**Comment by gurezo** [comment]
ja/docs/Mozilla/B2G_OS/Platform/Testing
が
ja/docs/Archive/Firefox_OS/Platform/Testing
リダイレクトされてしまいます

リンク修正をお願いできますでしょうか。

**Comment by gurezo** [comment]
@hmatrjp さん
よく理解出来てないようなので、確認させて下さい。

https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform
上記リンクを編集しようとしています。

実際リンクを入力後、移動すると
https://developer.mozilla.org/ja/docs/Archive/Firefox_OS/Platform

Archiveされたページへ移動して、それに気が付かずに
Firefox OS => B2G OSと変更してました。

今回の場合、どのような対応が正しいのでしょうか？

https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/Platform
などの上記リンクが存在していれば、そこから、通常の通り
言語追加・編集できるのですが・・・。

どのような手順が正しいのでしょうか？

**Comment by hmatrjp** [comment]
文書の構造（ツリー）と内容とが変化しているケースですので、ちょっと厄介かもしれません。

> https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Platform
> 上記リンクを編集しようとしています。

お気づきのように、現在、英文側に、これに対応する階層(Platform) が存在しません。
- 以前、この下にあった B2G OS Architecture は、1階層上がった B2G_OS 直下に動いています。
- それ以外の内容については、英文側ではそのまま Archive 内に捨て置かれるか、タイトル・URL を変えて Archive の外に取り出される（あるいはすでに取り出されている？）ことになると思います。特に、Firefox OS → B2G OS という名前のみが変わっただけで、内容が変わらない部分は、今後取り出される可能性が高いです。
- 日本語ページについては、できるだけ英語ページの構造に追随したいと思っています（できていないところも多いですが）。つまり、英文側で Archive 内に移されたページについては、日本語ベージについてもそうするということです。
- すでに英文側で取り出されているページ、または内容を流用することで英文側での新しい構造への追随が楽になるページがあればお知らせください。
- 日本語ベージについて、何らかの理由で、英文側の構造と異なる形での、特別な取り扱いが必要になるページがあればお知らせください。

> Archiveされたページへ移動して、それに気が付かずに
> Firefox OS => B2G OSと変更してました。

もしも変更前の状態に戻す必要があれば、履歴のページ→戻したいリビジョン→下の方にある　このリビジョンに戻す　ボタンで版を戻せます。

**Comment by gurezo** [comment]
@hmatrjp さん、回答有難うございます。
Archiveされたページは念の為、元に戻します。

英語リンクからArchiveされたページと照らし合わせながら、翻訳しようと思います。

**Comment by hmatrjp** [comment]
翻訳ミートアップを機に状況の確認をしました。
B2G OS 関連文書の原文がすべて Archive 入りしているようです。この Issue は close します。
必要に応じて、 reopen してください。
