### ISSUE TITLE
MDNを「てにをは」から修正するハンズオンをOSC東京で開催

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#167]
#146 からの続きで…

OSC東京ですが、とりあえず申し込みしようと思います。
11/5(土)、11/6(日)のいずれか、チューター/スタッフとしてご参加いかがでしょうか？
@chikoski 
まだどなたからもレスがないですが、できれば(人とPCが集まれば)
展示ブースとは別室でハンズオンを企画したいと思います。

**Comment by meco300** [comment]
上村さん
11/6でしたら参加できますよ！
お手伝いします！

**Comment by Uemmra3** [comment]
うぉう！さっそく参加表明ありがとうございます。
私も行ったことないですが、多摩地区は高崎よりも遠いらしいので、お気をつけください(何

引き続き、参加表明お待ちしてます。

2016年9月15日(木) 18:50 ANNA Takao <notifications@github.com>:

**Comment by hmatrjp** [comment]
11/6ならお手伝いできるかもしれません。11/5 は無理です。

**Comment by chikoski** [comment]
11/5 はお手伝いしに行きますね。

機材はだせるかな…持って来ていただくのは前提となりますが、
いくつか用意したほうが良いですよね。
どれくらい必要でしょうかね…

**Comment by Uemmra3** [comment]
ここまでまとめると
11/5 清水さん、上村
11/6 めこさん、(濱崎さん)、上村
ですね。

機材(PC)は、持ち込みを前提とするととりあえず4台～5台くらいあればいいでしょうか。PCよりもスマホ～タブレットで身軽に動く人が多いのでは？と予想してます。当日は紙袋とか資料とかもらったりするし。なのである程度台数欲しいですが、不足したら個人のPCをつかってもらっても良いかもしれません。

2016年9月16日(金) 13:45 N. Shimizu <notifications@github.com>:

**Comment by chikoski** [comment]
両日ともやる感じですか？人が揃っている 11/6 にやるほうが良い感じはしてます。

貸し出せるノートPCがあるかどうか確認してみます。

**Comment by Uemmra3** [comment]
6日にハンズオン、両日ともブース展示を申し込むつもりです。

とりあえずブース展示の申し込みはできました。ただ長机1台分なので、ここでのハンズオンはスペース的に厳しそうです（1～2人が限度？）。

別室(というかフロアも別の模様)にて60分単位のコミュニティ向けスペース貸出があり、こちらにも申し込もうと思います。これはスペース貸出であり、告知や設営、現状復帰は出展者側で行う必要があります。

ただしいずれかか1日のみ利用可能なので、人の多い6日に申込むつもりです。その際に、60分だと短くて途中で終わるのを懸念して（githubアカウント取得に手間取る場合など）、連続で2コマとかで確保できないのか、主催者に問い合わせ中です。

2016年9月21日(水) 1:24 N. Shimizu <notifications@github.com>:

**Comment by himorin** [comment]
わたしは両日とも会場にいるはずだと思うので、適当に声かけてくださいませ。
とはいえ最近のMDNのUIはあまりわかってませんが、、、

**Comment by Uemmra3** [comment]
OSC shimaneとかあって返信できてませんでした。。

11/6(日)にコミュニティ企画として申し込みました(30人 or 50人部屋)。
詳細決まりましたらDoorKeeper立てますー。

**Comment by Uemmra3** [comment]
最新メンバーです。
11/5 展示のみ 清水さん、ひもりん、上村
11/6 ハンズオン+展示 めこさん、清水さん、(濱崎さん)、potappoさん(翻訳MLより)、ひもりん、上村

**Comment by chikoski** [comment]
https://docs.google.com/spreadsheets/d/1qVONKGTQVljvh1i6_85QvKoSmuUhksS-_6qaCwJMPFk/edit#gid=1850746828 に [WiKi の用語集](https://github.com/mozilla-japan/translation/wiki/Mozilla-L10N-Glossary)をまとめておきましたー。
ご利用ください

**Comment by Uemmra3** [comment]
@chikoski ありがとうございます。
11/6の部屋が確定しましたのでご報告します。

http://www.ospn.jp/osc2016-fall/modules/article/article.php?articleid=4

時間が　13:00～14:45　で、15分前から入室できるようです。
基本的に場所の提供のみ(元に戻す必要がある)ので、それを踏まえてタイムテーブルやDoorKeeperを作っていきます。

**Comment by chikoski** [comment]
ありがとうございます。部屋の件、了解です。
PCですが、3台は用意できそうです。

あと所用により 11/5 は参加できなくなってしまいました…すみません。

**Comment by chikoski** [comment]
- [ ] 11/4  着で荷物を発送する

**Comment by hmatrjp** [comment]
今日(10/22) 開催された 表記ゆれ撲滅ハッカソン の Doorkeeper イベントページに
 mar さんが 冒頭の説明で使用した資料へのリンクなどが貼られています。
https://mozilla.doorkeeper.jp/events/52205

**Comment by chikoski** [comment]
@Uemmra3 さん：
ハンズオンの内容を具体的につめませんかー？
内容次第ですが、あと修正に向いているページをまとめておく、といった作業もした方がよいのかしら？

**Comment by chikoski** [comment]
@Uemmra3 
ハンズオン向けのPCを3台（Windows 2, Mac 1）を発送しました。
翻訳コミュニティ向けになっているので、受け取り後保管をお願いします。

PC以外に、
・MDN チラシ
・ネームプレート代わりの缶バッチ
・マジック
・チューター用のストラップ
・ガムテープ
などが入っています。

**Comment by Uemmra3** [comment]
@chikoski
荷物の件、了解ですー。
そして2つ前の投稿を完全に見逃してました(汗
明日、あさっては自分フリーなので、詰めましょう！

**Comment by chikoski** [comment]
105 分なので、

- イントロ (5 分)
- 更新の流れのデモ (15 分)
- ページを選んでステップバイステップで確認しながら更新（40 分)
- 自分でやってみよう (35分)
- まとめ (10 分)

みたいな感じでしょうか。

**Comment by chikoski** [comment]
編集するページは https://developer.mozilla.org/ja/docs/needs-review/editorial ここから選ぶと良さそうです

**Comment by Uemmra3** [comment]
ハッシュタグは #mdnja で良いでしょうかねー？

あと、adventarが出回っている季節なので、サクッと立ててしまって、当日に告知してしまいたい気がします。

**Comment by Uemmra3** [comment]
[adventar](http://www.adventar.org/calendars/1646) 立てました。
当日の最後のまとめあたりに告知しましょう。
みなさま申し込みの方もお願いします。

**Comment by chikoski** [comment]
個人的な振り返り：
* 事前準備に関して
  * diff の無いページを用意しておけばよかった：編集レビューが必要なページから選んだら、ほとんどが diff の反映が必要で詰まった
  * 電源タップを送っておけばよかった：会場に電源が潤沢で無いことが予想されるので、事前に用意しておくとよかった
* 当日に関して
  * URL のシェアの仕方や、今後継続的に参加するための入り口を整理しておくとよかった

**Comment by hmatrjp** [comment]
私も振り返り：
- PCのプロジェクターへの接続は、開始前に確認しておくべきだった。
 結果的には、@chikoski さんと説明を分担することになり、私としてはその分、楽になって 参加者の方を見回る余裕もできた。
- 電源タップは OSC事務局に8本余裕があったようで、事なきを得た
- スタイルガイドについては、今回は冒頭の説明より割愛し、まとめの時に参加者から出た質問に答える形で紹介。
- 参加者のPCで、MDNのページ内容が一部読み込めないケースが発現（ウィルス対策ソフトの副作用？）。ブースでの展示で使用できることからも、Mozilla Japan から借り出したPCの存在はありがたい。（セーフモード起動の必要がある機体など、ブース要因間で特性の引き継ぎが必要）
- Persona 終了の過渡期で、MDNユーザー登録の中の github アカウントとの結び付けができない症状が発現。同じメールアドレスを使うことで、自動検出→Recovery ボタンの出現→回復。（一度英語ページに切り替えたのが良かったのか？）

**Comment by chikoski** [comment]
だいたい振り返りも終わったということで、closeします
