### ISSUE TITLE
Firefox 49 fixes sites designed with WebKit in mind, and more

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#171]
* -webkit プレフィックスがついたものを処理できるようになったよ、という記事
* https://hacks.mozilla.org/2016/09/firefox-49-fixes-sites-designed-with-webkit-in-mind-and-more/

**Comment by chikoski** [comment]
https://www.mozilla.jp/blog/entry/10559/ で公開

**Comment by hmatrjp** [comment]
Q&A の2番めは、原文では
以前の表示が壊れていた、ではなく、「この変更で、私のサイトの表示がおかしくなるのでしょうか？」という疑問に見えます。それで、表示が改悪されたらバグレポートが欲しい、という流れではないでしょうか。
