### ISSUE TITLE
CSSMatrix

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#172]
CSSMatrix
https://developer.mozilla.org/ja/docs/Web/API/CSSMatrix

上記を翻訳します

**Comment by gurezo** [comment]
翻訳を完了したので、記事内容・技術レビューお願い致します。

**Comment by momdo** [comment]
レビューしてみます。

**Comment by momdo** [comment]
おおむね https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline に沿ってあれやこれやと編集上のもの、訳出そのものに手を入れました（がまだMDNの慣習から外れているところがあるかもしれません）。

2点ほど仕様周りの呼称で疑問なところが出たので記しておきます。

- working draftは「作業ドラフト」とされていましたが、とりあえず「ワーキングドラフト」としました。もし漢字表現なら「作業草案」となるはずです。あるいは原語ママでもいいと思いますが、これは何かきまりがあったかどうかは記憶にないです…
- 「CSS Transitions モジュールレベル 3」についても、「CSS Transitions Module Level 3」という文書の名前なので迷うところです。

**Comment by gurezo** [comment]
@momdo さん、レビュー有難うございます。
> おおむね https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline に沿ってあれやこれやと
> 編集上のもの、訳出そのものに手を入れました（がまだMDNの慣習から外れているところがあるかもしれません）。

上記のガイドライン知らなかったので、今後は参考にさせて頂きます。
また、[ L10N ガイドライン ](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline) も確認するようにします。

レビューをして頂いたので、closeとさせて頂きます。
