### ISSUE TITLE
MDNを「てにをは」から修正するハンズオンをOSC福岡で開催

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#173]
日程：2016年11月19日(土) 10:00～18:00 （展示は16:00まで）

会場：福岡ソフトリサーチパーク センタービル 2F 　
　　　[アクセスマップ]

体力の続く限り行く。
課題は東京から遠いので、スタッフ/チューターが集まるのか？

**Comment by Uemmra3** [comment]
@himorin

**Comment by albatrosary** [comment]
@himorin とMDNは関係があるのでしょうか？もしなければ身内ネタなのでここに記載するのはふさわしくないと思います。

**Comment by Uemmra3** [comment]
新参者なので昔のことは（もじら組とか）よく知らないのですが、卒業生という扱いかな？と思います。

どちらにせよハンズオン会場の確保ができないので閉じますね。

**Comment by marsf** [comment]
閉じた後からすみません。
@albatrosary: @himorin は MDC 日本語版 (現 MDN) の初代リーダーです。本人が言わないので内緒です。

**Comment by albatrosary** [comment]
つまり身内ネタ
