### ISSUE TITLE
[MDN] Tools/Responsive_Design_View → Tools/Responsive_Design_Mode

### ISSUE THREAD

**Issue by unarist** [mozilla-japan/translation#176]
https://developer.mozilla.org/ja/docs/Tools/Responsive_Design_View

上記ページに対応する英語版記事は現在 Tools/Responsive_Design_**Mode** にURLが変更されているようです。 https://developer.mozilla.org/ja/docs/Tools からのリンクも新しいURLになっていますし、ページの移動をお願いできないでしょうか。

**Comment by hmatrjp** [comment]
@unarist さん:
移動しました。
タイトルも変更しておきました。

**Comment by unarist** [comment]
確認しました。ありがとうございます。
