### ISSUE TITLE
MDN/Contribute/Structures のサブページが和訳されているのに一覧に出ていない

### ISSUE THREAD

**Issue by unarist** [mozilla-japan/translation#177]
https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures

> （訳注：下位の各ページを和訳すると、ここに表示されます）

とあるように、マクロを使ってサブ記事が表示されるようになっているようなのですが、和訳が存在する以下の記事が前述の一覧に表示されていません。

- [Compatibility tables](https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures/Compatibility_tables)
- [Content blocks](https://developer.mozilla.org/ja/docs/MDN/Contribute/Content/CSS_style_guide) （英語版でも Contribute/Content/CSS_style_guide にリダイレクトされているようです）
- [Live samples](https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures/Live_samples)
- [Quicklinks](https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures/Quicklinks)

憶測ですが・・・これらのページは LANGUAGES → Add a translation から作成されていて、この場合サブ記事として設定されない、なんてことだったりするのでしょうか。

**Comment by hmatrjp** [comment]
おそらくは、Landing page の再生成がなされていなかったのだと思います。

（参考）
https://developer.mozilla.org/ja/docs/MDN/Contribute/Tools/Page_regeneration

「ログインした状態で」 Shift + リロード を行うと、↑のページに説明がある "force refresh" が
働き、新たに追加された階層化のページの追加などが行われます。

（force refresh をしなくても、）ある一定の周期で再生成が行われるらしいのですが、
訳ページの新規追加など、すぐに編集結果を確認したいときには force refresh を使ってください。

濱崎


2016年10月20日 15:51 unarist <notifications@github.com>:

**Comment by unarist** [comment]
なるほど・・・Quicklinksなんて作成から3か月は経っているようですが、どんなスケジュールなんでしょうね。。

**Comment by hmatrjp** [comment]
生成の周期については、管理者に訊いてみないとわからないかもしれません。
[上のコメント](#issuecomment-255085137)にある Page_regeneration のページには 性能上の理由、とあるので、何かの都合で管理者がチューニングしている可能性もあります。

件のページでは必要ないかもしれませんが、周期の設定が必要な際には、原文側で設定してみてください。やり方は、同じページに訳出しておきました。
