### ISSUE TITLE
MDN マクロの中の埋め込み文字列修正(長音など)

### ISSUE THREAD

**Issue by hmatrjp** [mozilla-japan/translation#178]
MDNにログインしただけでは修正できない部分が存在するので、見つけた方はお知らせください。

**Comment by YuichiNukiyama** [comment]
{{SeeCompatTable}} マクロの「ブラウザ」に長音が入っていません。

**Comment by dskmori** [comment]
[テンプレート一覧](https://developer.mozilla.org/en-US/docs/templates) から見つけられた範囲で列挙します (ので抜け漏れあると思います)。
私は編集権限もってないので丸投げすみません。

- [ ] [{{deprecatedGeneric}}](https://developer.mozilla.org/en-US/docs/Template:deprecatedGeneric)
- [ ] [{{DeviceProximityEventProperties}}](https://developer.mozilla.org/en-US/docs/Template:DeviceProximityEventProperties)
- [ ] [{{DevNewsMeta}}](https://developer.mozilla.org/en-US/docs/Template:DevNewsMeta)
- [ ] [{{DOM_Whitespace_note}}](https://developer.mozilla.org/en-US/docs/Template:DOM_Whitespace_note)
- [ ] [{{GameTechBox}}](https://developer.mozilla.org/en-US/docs/Template:GameTechBox)
- [ ] [{{Harmony}}](https://developer.mozilla.org/en-US/docs/Template:Harmony)
- [ ] [{{HTML:Element_Navigation}}](https://developer.mozilla.org/en-US/docs/Template:HTML:Element_Navigation)
- [ ] [{{JsSidebar}}](https://developer.mozilla.org/en-US/docs/Template:JsSidebar)
- [ ] [{{L10n:Common}}](https://developer.mozilla.org/en-US/docs/Template:L10n:Common)
- [ ] [{{L10n:CompatTable}}](https://developer.mozilla.org/en-US/docs/Template:L10n:CompatTable)
- [ ] [{{L10n:CSS}}](https://developer.mozilla.org/en-US/docs/Template:L10n:CSS)
- [ ] [{{L10n:HTML}}](https://developer.mozilla.org/en-US/docs/Template:L10n:HTML)
- [ ] [{{L10n:SVG}}](https://developer.mozilla.org/en-US/docs/Template:L10n:SVG)
- [ ] [{{non-standardGeneric}}](https://developer.mozilla.org/en-US/docs/Template:non-standardGeneric)
- [ ] [{{obsoleteGeneric}}](https://developer.mozilla.org/en-US/docs/Template:obsoleteGeneric)
- [ ] [{{PopStateEventProperties}}](https://developer.mozilla.org/en-US/docs/Template:PopStateEventProperties)

あと、このテンプレートでは、プロパテ**イ** -> プロパテ**ィ** の誤字があったので修正お願いします。
- [ ] [{{js_property_attributes}}](https://developer.mozilla.org/en-US/docs/Template:js_property_attributes)

**Comment by hmatrjp** [comment]
@dskmori さん、お知らせありがとうございます。
まず最後の誤字だけ直しました。
続きは来週になるかもしれません。（11/6 のOSC Tokyo でやろうかな？）

**Comment by hmatrjp** [comment]
@dskmori さん、お待たせしました。
挙げてもらった一覧の、{{deprecatedGeneric}}　から　{{PopStateEventProperties}} も更新しました。

**Comment by dskmori** [comment]
@hmatrjp 対応ありがとうございます。一点だけ、[{{deprecatedGeneric}}](https://developer.mozilla.org/en-US/docs/Template:deprecatedGeneric) に **Web** が残っているのは意図的でしょうか？
> Web 標準
> Web アプリ

**Comment by hmatrjp** [comment]
確認漏れだと思います。

**Comment by hmatrjp** [comment]
あれれ、1年半前のコメントですね @dskmori  長らくの放置ですみません。
お知らせありがとうございました @Uemmra3 
github の方では既に直っているので、閉じていいと思います。
https://github.com/mdn/kumascript/blob/master/macros/deprecatedGeneric.ejs

**Comment by hmatrjp** [comment]
自分で開いた Issue だったんですね。閉じます。
