### ISSUE TITLE
Control mechanisms in JavaScript games

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#183]
- https://hacks.mozilla.org/2016/10/control-mechanisms-in-javascript-games/
- タッチ、キーボード、マウス、ゲームパッド、リモコンでの入力の取り方について紹介

**Comment by keisuketsushima** [comment]
翻訳してみました。
https://dev.mozilla.jp/2017/02/control-mechanisms-in-javascript-games/

**Comment by chikoski** [comment]
ありがとうございます！こなれててステキな訳だとおもいました。
