### ISSUE TITLE
OSC東京の「てにをは」ハンズオンでの、当日用タスク

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#185]
#167 から分離

前半の60分で概要を説明して、後半は各自に好きなページを編集してもらう。

> - イントロ (5 分)
> - 更新の流れのデモ (15 分)
> - ページを選んでステップバイステップで確認しながら更新（40 分)
> - 自分でやってみよう (35分)
> - まとめ (10 分)

**Comment by Uemmra3** [comment]
デモ用の候補

- [Zones](https://developer.mozilla.org/en-US/docs/Zones)
- [](url)
- [](url)
- [](url)

**Comment by Uemmra3** [comment]
(ドキュメントステータス)[https://developer.mozilla.org/ja/docs/MDN/Doc_status] ページから、分野で選んでもらうのもありかも?

**Comment by Uemmra3** [comment]
参照すると便利なページ:

- (ALCの辞書)[http://eow.alc.co.jp/]

**Comment by chikoski** [comment]
終わりました。お疲れ様でした。
