### ISSUE TITLE
「アドオン」の校正

### ISSUE THREAD

**Issue by bendyaming** [mozilla-japan/translation#188]
*　https://developer.mozilla.org/ja/Add-ons

**Comment by hmatrjp** [comment]
@bendyaming さん、
もしも、
A) 「見終わったが訂正の必要なし」、ということでしたら、
 1.その旨 github の Issue (ここ)でコメントしていただけますか？
 2. 編集レビュー フラグをおろしてください。(MDN の該当ページの編集モード、下の部分でチェックボックスを外す)
 3. 同じくMDN のリビジョンコメント欄で、「編集レビュー終わりました」と一言いただけますでしょうか。
B) 「見ること自体を中断した（再開の予定がない）」場合は、
 1. github の Issue (ここ)でコメントしていただけますか？

いずれのアクションもない場合、第三者が見た時に A) なのか B) なのか、それとも他の状態なのか、判別がつきません。操作方法がわからなければ、遠慮なく訊いてください。
