### ISSUE TITLE
「等価性の比較とその使いどころ」の校正

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#193]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Equality_comparisons_and_when_to_use_them

**Comment by kenji-yamasaki** [comment]
=== による厳格な等価性の直前まで編集レビューを行なった。

**Comment by kenji-yamasaki** [comment]
Strict equality using ===まで編集レビューを行なった。

**Comment by hmatrjp** [comment]
@kenji-yamasaki さん、レビューありがとうございます。

11/6 に参加していなかった人から見ると、Issue の履歴が不思議な状態になっているので、補足しておきます。
編集レビュー待ち一覧から1つタイトルをピックアップし、この Issue を作成した後、対象とするページを開いたら差分（日本語版と英語版の更新時期が離れているとまま起こること）が大きすぎたため、レビュー開始前に対象ページを変えています。

**Comment by kenji-yamasaki** [comment]
== による寛容な等価性まで編集レビューを行なった。

**Comment by chikoski** [comment]
ありがとうございます。closeします。
