### ISSUE TITLE
「CHIRIMEN」の編集

### ISSUE THREAD

**Issue by integra** [mozilla-japan/translation#194]
https://developer.mozilla.org/ja/docs/Mozilla/B2G_OS/Board_guide/CHIRIMEN

**Comment by integra** [comment]
編集レビュー行いました。

**Comment by hmatrjp** [comment]
@integra さん、レビューありがとうございました。

最近、和訳についての表記規則の改訂が行われ、Web は ウェブ とカタカナ表記することになりました。（WebAPI、WebGPIO など、固有名詞になっているところを除く）
→詳細は　http://mozilla.l10n.jp/~mar/pdf/MozillaL10nHackathon-20161022.pdf
（11/6 のハンズオンでは、紹介するのが最後になってしまいました）

お手数ですが、Web 技術　など、該当する部分を編集していただくことは可能でしょうか？
