### ISSUE TITLE
「Event属性」の校正

### ISSUE THREAD

**Issue by yamaguchi-takayuki** [mozilla-japan/translation#195]
https://developer.mozilla.org/ja/docs/Web/Guide/HTML/Event_attributes

**Comment by yamaguchi-takayuki** [comment]
「Event属性」編集レビュー終了

**Comment by dskmori** [comment]
close された issue へのコメントで恐縮です。
一点だけ気になったので。

原文
> This is an example of how not to do things, using one of these attributes.

に対し、現在の訳文では
> これは、こうするなという例ではなく、これらの属性の使い方の例です。

と二重否定のようになっていますが、文法的にも記事の文脈的にも
**これは、これらの属性の 1 つを使用する例であり、するべきではない方法です。**
のように単純な否定ではないでしょうか。

**Comment by hmatrjp** [comment]
@yamaguchi-takayuki さん、
@dskmori さんの書かれたように、単純な否定だと思います。後の方で、Instead （和訳では　代わりに） で受けていることからも。
レビュー前に入り込んでいた間違いだと思いますが、もしお時間あるようでしたら、反映していただけませんか？

**Comment by yamaguchi-takayuki** [comment]
反映してみました。
訳文の修正が入ったので、編集レビューを再チェックしました。
レビューをお願いします。

**Comment by dskmori** [comment]
ありがとうございます。レビューして、フラグも外しておきました。
