### ISSUE TITLE
担当者待ち：「SIMD.%type%.lessThanOrEqual()」の校正

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#198]
* https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/SIMD/lessThanOrEqual

**Comment by YuichiNukiyama** [comment]
確認しました。英数字前後の半角スペースの調整などを行って、レビュー済みにしておきました。

**Comment by chikoski** [comment]
ありがとうございます！closeしておきます
