### ISSUE TITLE
担当者待ち「数値と日付」の校正

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#200]
* https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Numbers_and_dates
* 校正をしてくれる方をお待ちしています

**Comment by yamaguchi-takayuki** [comment]
やります。

**Comment by yamaguchi-takayuki** [comment]
訳されている部分については、修正点はありません。
ただ、最後のExampleが訳されていないので、翻訳が必要だと思います。

**Comment by marsf** [comment]
Example のセクションを追加翻訳しました。

**Comment by chikoski** [comment]
ありがとうございます。編集レビューフラグを取っておきました。
