### ISSUE TITLE
「ページの移動」の校正

### ISSUE THREAD

**Issue by ghost** [mozilla-japan/translation#201]
https://developer.mozilla.org/ja/docs/MDN/Contribute/Tools/Page_moving

**Comment by tecPanda** [comment]
翻訳されていない部分が、複数行ございます。
どなたか、翻訳の程宜しくお願い致します。

**Comment by tecPanda** [comment]
大変申し訳ありません。
英語が苦手で、英語の翻訳に詰まっております。

どなたか、翻訳をお願いできないでしょうか？
お力になれず、大変申し訳ありません。

**Comment by Uemmra3** [comment]
まだ出先ですが、やってみますー。

2016年11月28日(月) 20:16 tecPanda <notifications@github.com>:

**Comment by tecPanda** [comment]
申し訳ありません。
ありがとうございます。

宜しくお願い致します。

**Comment by Uemmra3** [comment]
とりいそぎ翻訳してみましたー。

ただし私はページ移動権限を持っておらず、実際のページを確認できないので、文言がずれているかもしれません。
もともと訳してらした @hamatrip さんあたりの追加確認が必要な気がしますね。

**Comment by tecPanda** [comment]
Uemmra3様
お忙しい所、ありがとうございます。

"ページ移動権限" というものを、存じておりませんが
私の端末からは、文言ずれ等なく表示されておりました。

流石です。
大変勉強になりました。ありがとうございます。
申し訳ありません、お手数おかけしましました。

@hamatrip 様
申し訳ありません。
お手数ですが、ご確認の程宜しくお願い致します。

**Comment by Uemmra3** [comment]
少し補足します。

MDNのURLの最後の部分をスラグ（slug）と言います。
例えば当該ページ
https://developer.mozilla.org/ja/docs/MDN/Contribute/Tools/Page_moving
では
Page_moving
がスラグになります。
文書を読んでいけば分かると思いますが、「ページ移動権限」とは、このスラグを変える権限で、このページ末尾にあるように、日本のMDNユーザーではこの3人くらいしか持ってないんです。

で私が「文言ずれ」と言ったのは、MDNのページ移動画面のUIが私には確認できないので、MDNの画面で使われているのと同じ言葉がドキュメントで使われてない事を意図してます。
ややこしくてすみません。

2016年11月28日(月) 23:31 tecPanda <notifications@github.com>:

**Comment by tecPanda** [comment]
@Uemmra3 様

夜分遅くに、ご教授頂きありがとうございます。

おっしゃっている事、理解しました。
申し訳ありません、私の理解力が足らず。。。

ありがとうございます。

**Comment by hmatrjp** [comment]
@tecPanda さん、@Uemmra3 さん、ありがとうございました。
編集レビューを済ませました。
また、これを期に画像2枚を日本語ページで取り直しましたので、このページについては、移動権限を持っていない方にも文言ずれの確認をしていただくことができます。

長期間の放置になってしまい、すみませんでした。
なお、私の github ユーザー名(とMDN登録のメールアドレス)の @ の前で、 h と m の間に a は入りません。苗字からすると紛らわしくて申し訳ないですが、経緯があることでして、ご容赦ください。

**Comment by Uemmra3** [comment]
とりあえず作業は完了してるようなので閉じます。
@hmatrjp ユーザー名の件、失礼しましたm(_ _)m
