### ISSUE TITLE
担当者待ち：「キー付きコレクション」の校正

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#202]
* https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Keyed_collections
* 校正を担当いただける方をおまちしております。

**Comment by tecPanda** [comment]
担当致します。

**Comment by kenji-yamasaki** [comment]
担当します。
よろしくお願いします。

**Comment by kenji-yamasaki** [comment]
WeakMap objectの途中まで編集レビュー済
残りも作業中

**Comment by kenji-yamasaki** [comment]
Set objectまで編集レビュー済
残りも作業中

**Comment by kenji-yamasaki** [comment]
Array and Set comparedまで編集レビュー済
残りも作業中

**Comment by kenji-yamasaki** [comment]
全ての編集レビュー済

**Comment by kenji-yamasaki** [comment]
この後のIssueのクローズがどのように行われるか不明にしておりますので、ご教示ください。

**Comment by chikoski** [comment]
おわったら、close いただいて結構です！今回は close しておきます

**Comment by kenji-yamasaki** [comment]
close はどのように行えばいいのでしょうか。
Issueのどこかにボタンがあるかと思いましたが、見当たらず・・・。
初歩的な質問で申し訳ありません。

**Comment by hmatrjp** [comment]
Issue を Open した人には、Comment の隣に Close のためのボタンが出ます。

当人以外ですと、Label 付加・変更と同じで、権限がないとできないと思います。
（私も他の人が Openした Issue は close できません）

**Comment by kenji-yamasaki** [comment]
では校正が終わってクローズできないものはOpenされた方にクローズの依頼をするのでしょうか？
それとも放っておいてOpenされた方に閉じてもらうのに任すのでしょうか。
今後ご迷惑なく校正作業をする上で基本的なことなので、しっかり教えていただけますでしょうか。

**Comment by hmatrjp** [comment]
自分で Close できない Issue の場合は、作業が完了したことをコメントすれば、それで一段落です。（「完了しました」など。）
Open した人には、そのコメントもGithub からメッセージとして飛んでいくので、確認した上で閉じるはず、というのが基本的な考え方です。

以下、余談ですが：
一般的なチケットのライフサイクルと同様に、
Open した人と実際に作業者との間で、「完了した状態」について認識のずれがあった場合には、そこから追加の作業依頼や修正の依頼が入るので、必ずしも作業者が完了報告をすること　＝　Close にはなりません。

**Comment by kenji-yamasaki** [comment]
@hmatrjp さん

考え方を説明していただいたことで、不安なく作業に携われます。
本当にありがとうございました！
