### ISSUE TITLE
担当者待ち「Symbol」の校正

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#203]
* https://developer.mozilla.org/ja/docs/Glossary/Symbol
* 日本語を校正いただける方をおまちしております

**Comment by kenji-yamasaki** [comment]
校正を担当します。

**Comment by kenji-yamasaki** [comment]
校正を完了しました。

**Comment by hmatrjp** [comment]
@kenji-yamasaki さん:
一番下の　より詳しく知るには　にあるリンク2つについて、修正をお願いできないでしょうか。

1番め
・Wikipedia には、日本語の「シンボル」があり、「Symbol」のエントリーはありません。
2番め
・リンク先のタイトルは、日本語になっています。

**Comment by kenji-yamasaki** [comment]
1番めで、リンク先のSymbol(Programming)の日本語Wikipediaの記事は存在しませんでした。
この場合の対処方法が不明のため、ご教示いただけますでしょうか。
2番めは対応しました。

**Comment by hmatrjp** [comment]
@kenji-yamasaki さん、ありがとうございます。
1番めについては、
https://ja.wikipedia.org/wiki/%E3%82%B7%E3%83%B3%E3%83%9C%E3%83%AB#.E3.82.B3.E3.83.B3.E3.83.94.E3.83.A5.E3.83.BC.E3.82.BF.E7.A7.91.E5.AD.A6.E9.96.A2.E9.80.A3.E5.88.86.E9.87.8E.E3.81.AB.E3.81.8A.E3.81.91.E3.82.8B.E3.80.8C.E3.82.B7.E3.83.B3.E3.83.9C.E3.83.AB.E3.80.8D
に向けておくのが良いと思います。厳密には同等ではないですが、意味が近いかと。

**Comment by kenji-yamasaki** [comment]
@hmatrjp さん、ありがとうございました。
1番めですが、ページ「シンボル」へのInterwikiリンクは可能なのですが、アンカー「コンピュータ科学関連分野における「シンボル」」へのリンクの記述方法が不明です。ご教示いただけますでしょうか。
シンボルページへのリンクには変更済です。

**Comment by hmatrjp** [comment]
@kenji-yamasaki さん
ありがとうございます。
あ、なるほど。InterWiki マクロではアンカー指定ができないんですね。
私は、InterWiki マクロを使わず、直接 a href で、リンクを記述する方法を想定していました。

既にご存知かもしれませんが、チェーン型のアイコンを使うか、ソース編集モードで直接リンク先URLを指定できます。

**Comment by kenji-yamasaki** [comment]
@hmatrjp さん
ありがとうございます。
ソース編集モードでアンカー指定のリンクに修正しました。

**Comment by kenji-yamasaki** [comment]
校正が完了しているのでcloseをお願いします。

**Comment by hmatrjp** [comment]
@kenji-yamasaki さん
いろいろお手数かけました。ありがとうございました。
