### ISSUE TITLE
担当者待ち：「スクリーンキャスト」の校正

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#204]
* https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%AD%E3%83%A3%E3%82%B9%E3%83%88
* 日本語の校正を行なっていただける方をおまちしております。

**Comment by YuichiNukiyama** [comment]
変更なしです。チェックだけ外しました。

**Comment by Uemmra3** [comment]
なくなった？閉じます
