### ISSUE TITLE
GlobalFetchの翻訳 

### ISSUE THREAD

**Issue by aliceinwire** [mozilla-japan/translation#206]
https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch

**Comment by Uemmra3** [comment]
進捗どうですかー？

**Comment by lv7777** [comment]
翻訳完了しました。
編集レビューもしたつもりです。(boldの適用、表記ゆれ　...etc

**Comment by lv7777** [comment]
google翻訳に投げるのはいいんですが、引数のオプションなども翻訳してしまうのでかなり意味が変わるときがあります。
投げた後は確認しましょう。

**Comment by aliceinwire** [comment]
編集レビューありがとうございます。

**Comment by Uemmra3** [comment]
お二人ともありがとうございました。

ちょっとフォローしておくと、 @aliceinwire さんは留学生のため、翻訳はハードかもしれませんね。

あと、ざっとレビューしたのですが、原文(en-US)の差分を反映できていない箇所が見当たりました。
特にSyntaxが違ってたのは致命的なので、ざっと直しました。

MDNの編集画面の上の方に原文の差分が載っているので、かならず日本語ドキュメントにも反映するようにしてください。
(時間のない場合は、英語のままコピー&ペーストとかでも良いでしょう)
