### ISSUE TITLE
「Web Workers が使用できる関数とクラス」の校正

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#207]
* https://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers
* 校正いただける方をお待ちしております

**Comment by kenji-yamasaki** [comment]
校正を担当します。

**Comment by kenji-yamasaki** [comment]
Channel_Messaging_APIまで校正済。
引き続き作業中。

**Comment by kenji-yamasaki** [comment]
DOMRequest、DOMCursorまで校正済。
引き続き作業中。

**Comment by Uemmra3** [comment]
横画面 1920 pixelのモニターで校正したけど、それ以上のワイドモニター(またはデュアルモニター)でやるべきかもしれない。。。

**Comment by Uemmra3** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1437289

**Comment by hmatrjp** [comment]
英語ページの方を別ウィンドウに表示して上下に並べることで見比べられることに気づいたので、編集レビューします。
原文の方に少し変更も入っている様子。

**Comment by hmatrjp** [comment]
作業終了しましたので、閉じます。何かあったら、また開いてください。

原文の方に編集レビューフラグ、技術レビューフラグが立ったままなので、また変更が入る可能性はありますが、現状に追随できたと思います。
