### ISSUE TITLE
OSC 福岡 2016 への出展準備

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#209]
[OSC 福岡 2016](http://www.ospn.jp/osc2016-fukuoka/) へもブース出展されるようなので、その準備についてここで議論しましょう。

**Comment by chikoski** [comment]
@Uemmra3 さん
荷物を発送に関して、

* 発送先
* 締め切り

この二つについて情報をシェアしてくださいー。よろしくお願いします。
あと私物以外に何か送って欲しいものがあれば、おしらせください。

**Comment by chikoski** [comment]
発送先情報を手に入れました。
PCは2台程度お送りする予定です。

**Comment by Uemmra3** [comment]
メールにて送っていますが、
モニターを持ち込むのは難しいですか？

ノートPCを来た人に画面が見えるようにしながら操作するのは難しいもので。。。

**Comment by Uemmra3** [comment]
なんだか入り口付近のいい席になっている(ので人が多く来る)気もしています。

![osc-fukuoka](https://cloud.githubusercontent.com/assets/5329876/20259930/b08cc912-aa9a-11e6-9611-274874ac44b7.png)

アシュラマンになりたい。。

**Comment by chikoski** [comment]
ディスプレーも送れるようになりました。PC、私物などとまとめて発送しました。
