### ISSUE TITLE
word-wrap/overflow-wrap CSSプロパティについて

### ISSUE THREAD

**Issue by momdo** [mozilla-japan/translation#213]
日本語版：
https://developer.mozilla.org/ja/docs/Web/CSS/word-wrap
英語版：
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

についてですが、英語版と日本語版で異なるURLにリダイレクトがかかるようになっているようです。
（こういうものはGoogle Groupの方が好ましいでしょうか？）

**Comment by Uemmra3** [comment]
あれ、反応がありませんね…。
どなたか権限のある方のレスがほしいところですが。

**Comment by chikoski** [comment]
すみません。問題がよくわかってないので、確認させてください。
# ちなみに権限はありません…

https://developer.mozilla.org/docs/Web/CSS/overflow-wrap へアクセスした際に、
日本語は https://developer.mozilla.org/ja/docs/Web/CSS/word-wrap に、
英語は https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap へ
それぞれリダイレクトされるのは正しい振る舞いのように思うのですが、
どうなると良いのでしょう？？

**Comment by momdo** [comment]
ええと日英ともにリダイレクトの振る舞い自体は正しいのですが、
日本語版のリダイレクト先を、英語版のリダイレクト先のURLにあわせた方がいい（つまり、overflow-wrapに統一した方がいい）のではないか、という提案です。

根拠は、<a href="https://drafts.csswg.org/css-text-3/#overflow-wrap-property">仕様</a>にもある
> For legacy reasons, UAs must treat word-wrap as an alternate name for the overflow-wrap property, as if it were a shorthand of overflow-wrap. 

に依ります。

**Comment by marsf** [comment]
一般ユーザーの権限がどこまでか分かりませんが、記事タイトルの変更もできませんか？

**Comment by momdo** [comment]
@marsf 
今試してみましたが、記事のタイトルの変更はできたようです。

**Comment by marsf** [comment]
@momdo あとは移動すればいいだけですね。

**Comment by dynamis** [comment]
page moved:
https://developer.mozilla.org/ja/docs/Web/CSS/overflow-wrap

**Comment by momdo** [comment]
対応ありがとうございました。
