### ISSUE TITLE
Gamepad APIの翻訳

### ISSUE THREAD

**Issue by ukehito** [mozilla-japan/translation#216]
Gamepad API関連の翻訳をAdvent Calendar用に翻訳中です
頑張って全部一人で直してやろうかという意気込みです
(元気が続く限り)

**Comment by Uemmra3** [comment]
https://developer.mozilla.org/ja/docs/Web/API/Gamepad_API

**Comment by hmatrjp** [comment]
実験的な機能ではなく本流に昇格した様子。
原文で書式などタグが大量に変わったため、初心者には手を出しづらいかも。
内容はわかりませんが、タグ回りだけでも整えてみます。

**Comment by potappo** [comment]
ほぼ最新版と変わりないようなので、レビューと最新版の差分を反映次第クローズします。ぱっと見、「コントローラ」と「コントローラー」のぶれがあるので、「コントローラー」に統一します。

**Comment by potappo** [comment]
英語版が更新されていたのを反映し、Gamepad API 関連の「コントローラ」を「コントローラー」に、「ゲームパット」を「ゲームパッド」に表記を統一しました。クローズします。
