### ISSUE TITLE
Visualizations with Web Audio API

### ISSUE THREAD

**Issue by aokashi** [mozilla-japan/translation#217]
https://developer.mozilla.org/ja/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API

Web Audioに関する記事です。なかなかWeb Audio触れる機会が少ないので翻訳してみたい方いかがですか。

音声ファイルをグラフで表示できて、実際みて面白そうです。

**Comment by fnwiya** [comment]
翻訳してみました

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
棒グラフのところ、グラフを上から下げる(つららみたいな形)のではなく、下から生やす(木みたいな形)のを言いたかったんだと思います。もう少し通じるように直してみました。
