### ISSUE TITLE
Iteration/Itarator/Iterable/etc.はどう訳す？

### ISSUE THREAD

**Issue by unarist** [mozilla-japan/translation#223]
[Guide/Iterators_and_Generators](https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Iterators_and_Generators)や[Reference/Iteration_protocols](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Iteration_protocols)をざっと読んだ感じでは、現在は次のように訳されているようです。

- Iteration 反復・反復処理
- Iterator イテレーター
- Iterable 反復可能（Iterable object で反復可能オブジェクト）

この中で反復可能、に違和感を覚えました。例えば[Guide/Iterators_and_Generatorsの一節](https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Iterators_and_Generators#Iterables)では次のように書かれています。

> ...、反復処理の挙動が定義されているオブジェクトのことを反復可能 (iterable)（イテラブル）と呼びます。...
>
> 反復可能にするには、そのオブジェクトに `@@iterator` メソッドを実装しなければなりません。

日本語の文章としてみると、反復可能というのは物の性質ですから、「～オブジェクトのことを反復可能と呼ぶ」のは違和感があります。「～オブジェクトは反復可能である」ならよいでしょう。オブジェクトの性質としてのIterableではなく、Iterableプロトコルを実装したオブジェクトということなら、むしろ「反復可能オブジェクト」「Iterableオブジェクト」とした方がいいかもしれません。

また英語表記だと Iteration - Iterator - Iterable が深く関係する要素であるとわかりやすいのですが、現在の訳ではイテレーターと反復（可能）の間にちょっと距離があるような気がしました。読み手がきちんと理解していれば特に問題ないとも思いますが…。

**Comment by momdo** [comment]
リンク先で引用箇所がどこなのかよく分からなかったのですが、少なくとも <a href="https://github.com/mozilla-japan/translation/wiki/L10N-Guideline#%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A%E8%AA%9E%E3%81%A8%E9%95%B7%E9%9F%B3">l10n ガイドライン</a>によれば、Iterator をカタカナ表記するならイタレーターになると思います。

**Comment by unarist** [comment]
@momdo すみません、引用個所はここです。https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Iterators_and_Generators#Iterables

Iteratorのカタカナ表記に関しては長音の有無の話であればご指摘の通りかと思います。最初のコメントで伸ばしていないのは単に私の表記ミスですが、リンク先でも混在しているので統一するといいですね。

**Comment by momdo** [comment]
ああ、1つ目のリンクしか見てなかったようです。すみません。

>An object is iterable if it defines its iteration behavior, such as what values are looped over in a for..of construct. 
for..of のループ構造内で内部の値をループ処理できるような、反復処理の挙動が定義されているオブジェクトのことを反復可能 (iterable)（イテラブル）と呼びます。

>In order to be iterable, an object must implement the @@iterator method,
反復可能にするには、そのオブジェクトに @@iterator メソッドを実装しなければなりません。

英日比較するとこうでしょうか。

>「～オブジェクトのことを反復可能と呼ぶ」のは違和感があります。「～オブジェクトは反復可能である」

後者の方が素直な感じはしますね。現行訳で
> 反復可能 (iterable)（イテラブル）

と同じことを3回繰り返すのは冗長だと思います。

> また英語表記だと Iteration - Iterator - Iterable が深く関係する要素であるとわかりやすいのですが、現在の訳ではイテレーターと反復（可能）の間にちょっと距離があるような気がしました。

どう訳語統一するのかは訳者次第という感じはしますが、たとえば訳語をいじらず文中で

イテレーター (Iterator)
反復 (Iteration)

のように原語も若干くどいですが必要なところで併記するのはありかもしれませんね。

**Comment by hmatrjp** [comment]
話題になっている Iterable については、形容詞扱いになる場合と名詞扱いになる場合があるので、注意が必要です。...と書き始めたのですが、、、読み直してみると、このページ
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators
に出てくる Iterator については、すべて名詞扱いで問題ありません。

特に、セクションタイトルで s（複数形） がついて Iterables となっている部分を「反復可能」という、形容詞で訳すのは、厳密には誤りです。

「反復可能オブジェクト」または「イテラブルオブジェクト」という名詞の形に統一するのが無難なように思います。

**Comment by unarist** [comment]
大変遅くなりましたが、頂いたご意見を参考に
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Iterators_and_Generators を更新しました。ありがとうございます。
