### ISSUE TITLE
[MDN] ディスカッションの場所をフォーラムに変更する

### ISSUE THREAD

**Issue by yyss** [mozilla-japan/translation#227]
Janet Swisher さんから依頼がありました。
MDNコミュニティでディスカッションを行う場所が、メーリングリストからDiscourse 
forum (https://discourse.mozilla-community.org/c/mdn) に替わりました。
このためメーリングリストが記載されているページを、フォーラムを案内するように
更新してほしいそうです（英語版は更新済み）。

- [x] https://developer.mozilla.org/ja/docs/MDN/Feedback -- Update
- [x] https://developer.mozilla.org/ja/docs/MDN/Community/Conversations -- Update
- [x] https://developer.mozilla.org/ja/docs/MDN/Community/Roles/Localization_driver_role -- Update and complete translation
- [x] https://developer.mozilla.org/ja/docs/MDN/Community/Working_in_community -- Update and complete translation
- [x] https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures/Compatibility_tables -- Update
- [x] https://developer.mozilla.org/ja/docs/Web/API/Fetch_API/Basic_concepts -- Update
- [x] https://developer.mozilla.org/ja/docs/Archive/Meta_docs/MDN_content_on_WebPlatform.org -- Update ML link

**Comment by dynamis** [comment]
@yyss 対象ページリストを箇条書きからチェックリストに書き換えました

そうかー、Discourse メインになるのかー。時代だなー。

**Comment by Uemmra3** [comment]
一通りDiscourseに変わっているようなので閉じます
