### ISSUE TITLE
HTML 概論

### ISSUE THREAD

**Issue by im-cuttlefish** [mozilla-japan/translation#230]
https://developer.mozilla.org/ja/docs/Web/HTML/Introduction
編集レビューします

**Comment by ukehito** [comment]
このページは英語のページが移動し、元の場所にあったページと移動したページの両方に翻訳が行われてしまっている。

**Comment by hmatrjp** [comment]
Teoli さん（MDN管理メンバーの一人）に、古い日本語版→英語版のリンクをカットしてもらうようリクエストのメールを投げました。

**Comment by hmatrjp** [comment]
Teoli さんから反応がなく、mdn-admins@... に投げたところ、バグをオープンすることになりました。
https://bugzilla.mozilla.org/show_bug.cgi?id=1416376

**Comment by hmatrjp** [comment]
トリアージでP1（優先度 最高）が付きました。
他の言語のページも巻き込まれる話で、しばらく見守るしかなさそうです。

**Comment by hmatrjp** [comment]
言語間のリンク異常については、かなり前に解決していました。現在は
https://developer.mozilla.org/ja/docs/Web/HTML/Introduction
は
https://developer.mozilla.org/ja/docs/Learn/HTML/Introduction_to_HTML
にリダイレクトされています。

一段落つきましたので、このバグを閉じます。
