### ISSUE TITLE
CSSの transform プロパティ

### ISSUE THREAD

**Issue by im-cuttlefish** [mozilla-japan/translation#234]
https://developer.mozilla.org/en-US/docs/User:wbamberg/Examples_on_top/transform
新規翻訳します

**Comment by im-cuttlefish** [comment]
最初の方とh3のみ翻訳しました

**Comment by marsf** [comment]
URL 見たら個人作業用のページを翻訳してしまってますね。 翻訳すべきページはこっちです。
https://developer.mozilla.org/en-US/docs/Web/CSS/transform
日本語版は更新されてません。
https://developer.mozilla.org/ja/docs/Web/CSS/transform

**Comment by marsf** [comment]
更新しました。
