### ISSUE TITLE
スタック文脈

### ISSUE THREAD

**Issue by hinatami** [mozilla-japan/translation#235]
https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context

編集レビューします。

**Comment by hinatami** [comment]
編集レビューでひと通り読んで、半角スペースの追加/削除を中心に修正しました。
まだ完全ではないので、編集レビューフラグは残しています。

**Comment by potappo** [comment]
編集レビューします。

**Comment by potappo** [comment]
レビュー完了しました。
