### ISSUE TITLE
日本語ページに、日本語以外(ポーランド語？)のページが紛れている

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#241]
https://developer.mozilla.org/ja/docs/Learn/Tools_and_testing/Cross_browser_testing

**Comment by Uemmra3** [comment]
@rurumi66 さんが間違ってポーランド語に訳した？？

**Comment by hmatrjp** [comment]
こんなこともあるんですね。。。

日本語で上書きして構いません。ポーランド語の方は、後からでも履歴より参照可能なので。
[add a translation](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing$locales) から、ポーランド語のページを追加し、訳されている部分をそっくりそのままコピペしておくと親切だと思います。その時のコメントに、間違って ja locale にあったものを持ってきたよと触れておくのが良いかと。
Google Translation で冒頭の段落をポーランド語→英語にしてみたところ、ほぼ同じなので、ポーランド語訳としては正しいのだと思います。

[日本語版の履歴](https://developer.mozilla.org/ja/docs/Learn/Tools_and_testing/Cross_browser_testing$history)を見てみると
@rurumi66 さんは、タグを外すだけで本文には触っていない様子です。

さらに[英語版の履歴](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing$history)を見てみると、このポーランド語訳は
@prograamer さんが英語ページを誤って（？）ポーランド語に訳し revert された版を、再び日本語ページでポーランド語に翻訳したもののようです。

**Comment by Uemmra3** [comment]
ポーランド語のページを作って、日本語への翻訳を開始しています。
