### ISSUE TITLE
MDNのタグ付け

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#244]
なかなか大作なので、協力者を募集してみる。
https://developer.mozilla.org/ja/docs/MDN/Contribute/Howto/Tag

**Comment by hmatrjp** [comment]
確かに大きいですね。。。少しだけ訳しました。

**Comment by Uemmra3** [comment]
一通り完了した。

この方と作業がかぶってないと信じたい。
https://developer.mozilla.org/ja/profiles/mfuji09
