### ISSUE TITLE
Accessibility/XUL Accessibility Reference

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#245]
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/XUL_accessibility_reference
上記翻訳に着手します。

**Comment by Uemmra3** [comment]
なんかこれって英語側のテーブルがスクロールできないような。。
とりまバグ登録してみました。
https://bugzilla.mozilla.org/show_bug.cgi?id=1437289

**Comment by marsf** [comment]
記事をレビュー＆修正しました。
"read" は、スクリーンリーダーなので「読み取り」ではなく「読み上げ」です。

テーブルの問題は、<table class="fullwidth-table"> の class が削除で解決したようです。
