### ISSUE TITLE
HTMLを始めよう(Getting started with HTML)の翻訳

### ISSUE THREAD

**Issue by haruo-wakakusa** [mozilla-japan/translation#250]
https://developer.mozilla.org/ja/docs/Learn/HTML/Introduction_to_HTML/Getting_started
この記事の翻訳は途中で止まっているのかと思いますが、haruo_wakakusaの方で進めてもよろしかったでしょうか？

**Comment by haruo-wakakusa** [comment]
「属性」 - 「実習：要素に属性を追加する」の箇所を翻訳しました。

**Comment by haruo-wakakusa** [comment]
原文の「Boolean Attributes」の説明が、実際とは異なるので、訳文では実際の方に合わせることにいたします。
https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html
https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.3.4.2

**Comment by haruo-wakakusa** [comment]
w3c(HTML 5.2)だと、ここに属性値のクォーテーションマークを省略してもよいかどうかが書いてあるようです。
https://www.w3.org/TR/2017/REC-html52-20171214/introduction.html#a-quick-introduction-to-html

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
Boolean Attributes について、「実際とは異なる」というのはどこでしょう？
二つのリンク先を読んでみましたが、[原文](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started)と異なる記述をしてはいないように思います。

[後者](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.3.4.2)の方で最後に
"Authors should be aware that many user agents only recognize the minimized form of boolean attributes and not the full form."　とある部分のことでしょうか？

**Comment by haruo-wakakusa** [comment]
wikipediaでも属性の引用符(クォーテーションマーク)について、「ダブルクォート」、「シングルクォート」という言葉を使っているので、この記事でもこれらの言葉を使うようにしています。

https://ja.wikipedia.org/wiki/%E5%BC%95%E7%94%A8%E7%AC%A6

**Comment by haruo-wakakusa** [comment]
hmatrjp様
Boolean attributesの所について、原文が実際と異なると私が思ったのは、
「These are called boolean attributes, and they can only have one value, which is generally the same as the attribute name.」
「これらはブール型属性と呼ばれ、1つの値しか持つことができません。通常は属性名と同じです。」(Google翻訳)
の所です。論理属性は属性名があるかないか、が重要なのであって、inputのdisabled属性の項でも「"disabled"という値を割り当ててください」、とは書いてないはずです。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input#attr-disabled
w3cの説明の中にも属性値が属性名と同じ、というような記述は無かったので、訳文ではそこの部分を強調しています。

**Comment by haruo-wakakusa** [comment]
節「Single or double quotes?」の「use HTML entities」のリンクをクリックしても「Entity references: Including special characters in HTML」の項目にジャンプしてくれなかったので、訳文ではとりあえずリンクを貼らずにしておきました。ちなみに私はWindows 10(x64)のChromeとFirefoxで確認しています。

**Comment by haruo-wakakusa** [comment]
節「Single or double quotes?」の「HTML entities」は、日本語で「HTMLエンティティ」と言いますが、これは「実体参照」、「文字実体参照」、「文字参照」とも言うようです。しかもHTMLとXMLでは用語の使い方が違っていて、ここは初心者が非常に混乱するところだと思います。これらについては「Entity references: Including special characters in HTML」の節の訳出時に検討したいと思います。
http://perldoc.jp/docs/modules/HTML-Entities-3.55/Entities.pod
https://ja.wikipedia.org/wiki/%E6%96%87%E5%AD%97%E5%8F%82%E7%85%A7

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
Boolean attributesのお話の続きです：
後半にある which is generally the same as the attribute name.　によれば、
この場合の  （disabled という名前の）属性について、あてはまる値は "disabled" (または "DISABLED" など大文字小文字を無視すれば等価になるその他の文字列)になります。

リンクを張られていた[後者](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.3.4.2)には 3行目に、

> Boolean attributes may legally take a single value: the name of the attribute itself (e.g., selected="selected").


[前者](https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html)の3.2.2 Boolean attributes 節には2段落目に

> If the attribute is present, its value must either be the empty string or a value that is a case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

とありますので、[原文](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#Boolean_attributes)と言っていることは変わらないのでは？
これは、disabled 属性に限らず、すべての論理属性に当てはまる話として書かれています。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/input#attr-disabled
は、disabled 属性についての各論なので、ここに書かれていないのは自然だと思います。
いかかでしょう？

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
use HTML entities のリンクについて。確かに飛ばないですね。
これは、<a href= ... の # 以降と、飛び先の id= .. が少しだけ違うためです。
原文の著者としては、Entity_references_Including_special_characters_in_HTML とするのが本来の意図だったと思います。

可能であれば、原文のページの方もリンクを修正してください。
難しいようでしたら言ってください。やります。

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
HTML entities の訳語について、いくつか対応方法が考えられます。（他の人からも意見が出そうな気もする。）
いろいろな言い方が流通してしまっているケース として、訳注を入れるというのも1つの方法です。

翻訳コミュニティでは、ある程度訳語を統一するために
このリポジトリの Wiki から飛べる[用語集](https://github.com/mozilla-japan/translation/wiki/Mozilla-L10N-Glossary)を用意しています。
ここでも、実体参照　に対応する述語はわかるのですが、HTML entities に直接対応するものとしては結び付けられていません。

ご参考になれば幸いです。

**Comment by haruo-wakakusa** [comment]
@hmatrjp さん
論理属性の件、ご指摘ありがとうございます。<input type="text" disabled="foo bar baz">という書き方で、ブラウザが動作してしまうのですが、文法的にはNGということですね。HTMLチェッカーで確認させて頂きました。
https://gist.github.com/haruo-wakakusa/3fe6763dc5c5235d466af3c7392733ab

**Comment by haruo-wakakusa** [comment]
@hmatrjp さん
「Boolean attributes」の箇所、「論理属性に論理値を設定する場合は論理名と同じでなければならない」ということは重要なことなので、訳文では原文よりも強調した書き方をさせて頂きました。ご確認いただければと思います。

**Comment by haruo-wakakusa** [comment]
@hmatrjp さん
「use HTML entities」のリンクについてですが、HTMLのソースを確認することはできるのですが、編集画面上でどのように修正すればよいのかが分からないので、よろしければ今回はhmatripさんの方でご対応頂けますでしょうか。編集画面の使用方法も近いうちに勉強させて頂きますのでよろしくお願いいたします。

**Comment by haruo-wakakusa** [comment]
@hmatrjp さん
「HTML entities の訳語」については、ちょっと私の方では保留させて頂きます。もう少し周りの翻訳を進めてから考えるといった感じです。とりあえず、「HTML エンティティを使用」から「実体参照: HTML に特殊文字を含める」のほうにジャンプされていれば問題ないと思います。「HTMLエンティティ」とは「HTMLにおける実体参照」のことだと思うのですが、そこはもう少し考えさせてください。

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
[和訳の「Boolean attributes」の箇所](https://developer.mozilla.org/ja/docs/Learn/HTML/Introduction_to_HTML/Getting_started#Boolean_attributes)見ました。ありがとうございました。

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
「use HTML entities」のリンク:
原文、訳文ともに手を入れて修正したので、今は飛ぶようになっています。
訳文側のリビジョンコメントに書きましたが、思っていたより手直し箇所が多くなりました。

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
HTML entities の訳語 については、確かに、周りと合わせての文脈の中で考えた方が答えが出しやすいかもしれません。
周りの意見や助言が欲しくなったら、また書き込んでください。

**Comment by haruo-wakakusa** [comment]
@hmatrjp さん
ほえ～。リンク修正の件、お忙しい中直していただきましてありがとうございます。結構大掛かりでしたね。私がやっていたらドツボにはまって２，３日寝込んでたかもしれません... その他諸々のアドバイスありがとうございます。ちょっとMDNの翻訳作業、敵１万に対して100人くらいで戦っているような気がしますが、まあ一騎当千と、人事を尽くして天命を待つ感じで頑張っていきましょう（って私が言っていいのだろうか...）。

**Comment by haruo-wakakusa** [comment]
節「Anatomy of a HTML document」の中、
1. <!DOCTYPE html>: The doctype. In the mists of time, when HTML was young (about 1991/2), doctypes were meant to act as links to a set of rules that the HTML page had to follow to be considered good HTML, which could mean automatic error checking and other useful things. They used to look something like this:

原文の方も結構アバウトですよね。doctypeなんて言葉、オックスフォードの辞書にも載ってないし普通の人は使わない。the type of this document. あたりだと思います。about 1991/2って何？って話でしょう？1991/2ってw3cの標準なの？それとも1991年2月あたりと言いたいの？こんな文章、初心者に読ませたら初心者は怒ると思います。

**Comment by marsf** [comment]
> The doctype.

"the type of document" ではなく、"Document type declaration" ([文書型宣言](https://ja.wikipedia.org/wiki/%E6%96%87%E6%9B%B8%E5%9E%8B%E5%AE%A3%E8%A8%80)) です。
「いわゆる DOCTYPE です。」程度の書き方かと。今では形骸化しているので、それ以上説明する必要が無いというか、初心者に言われても困るんですけどね。

**Comment by haruo-wakakusa** [comment]
@marsf さん
コメントありがとうございます。節「Anatomy of a HTML document」のところで、DTDという言葉は使いませんでしたが、宣言という言葉は使い、宣言という言葉の意味も脚注に追加しました。このシリーズの次の記事以降は把握していないので、日本人にとって必要な情報も追加しておきました。

**Comment by hmatrjp** [comment]
DOCTYPE について：
HTML 初心者が初めてソースを覗いてみた時に、先頭に DOCTYPE があった、さてなんだこれは。・・・という場面を想像しながら書くとよいのではないでしょうか。
Anatomy ですから、DOCTYPE を知らない人も参照しに来る文書ということで。

**Comment by haruo-wakakusa** [comment]
うわ〜、私の説明だとXMLとHTML5以前を知っている人はちょっと不満かもしれないですね。でもHTMLがXMLから乖離しまくってるので、HTML以外をやりたい人は、別のやつで勉強してね、ってことですね。

**Comment by haruo-wakakusa** [comment]
<!DOCTYPE html>
なんかこの記述もうさんくさいんだよなー
HTML6になったら<meta version="6.0">とか書いてそう。

**Comment by haruo-wakakusa** [comment]
&lt;!DOCTYPE html&gt;
なんかこの記述もうさんくさいんだよなー
HTML6になったら&lt;meta version="6.0"&gt;とか書いてそう。
(まさかGitHibの投稿でも実体参照を書かされるとは…)

**Comment by haruo-wakakusa** [comment]
「Active learning: Adding some features to an HTML document」の中の「You'll get bonus points if you manage to link to a different image (either locally on your computer, or somewhere else on the web.)」ってもはや意味が分からない～。このインタラクティブ画面(Input, Output)はそこまでの採点機能を実装していないでしょう～。最終目標のモックも示されていないし...

**Comment by haruo-wakakusa** [comment]
「Active learning: Adding some features to an HTML document」の所で、例えばWindowsの場合は、ファイルの種類を「*.txt」ではなく「*.*」で保存することや、フォルダ(ディレクトリ)はデスクトップ等分かりやすい場所に保存する等(デフォルトではドキュメントというフォルダに保存されること)は説明しませんでした。そういったことはHTML入門ではなく「Web入門」の「ファイルを扱う」の部分でみっちり教えるべき（かあえてスルーするかすべき）ことかと思います。

**Comment by haruo-wakakusa** [comment]
「Active learning: Adding some features to an HTML document」のrenderは「レンダリング」と訳しました。分かってる人・スルー出来る人は気にしないでしょうし、気になる人は検索しますが、トップにwikiでレンダリングの解説が書いてあるので、レンダリングの説明をする必要はないと判断しました。

**Comment by haruo-wakakusa** [comment]
初心者の中でもうるさい人は、refresh the browserのことを「更新 (または再読み込み)」と言っただけでは分からなくて、各ブラウザ(Edge, Chrome, Firefox, Safari, ...)のどのアイコンを押すか画像で示せ、とか、Edgeには「最新の情報に更新」と書いてあるじゃないか、Chromeには「このページを再読み込みします」と書いてあるじゃないか、とかいう人もいるので...　もうそういう人達は切り捨ててもいいとは思うんですけどね。または、セミナーやパソコン教室に通うとかしてもらうとかで。

**Comment by haruo-wakakusa** [comment]
Androidのブラウザ(Google)では、記事が全て展開されない状態になっていますが、その一部を展開して、同じページの他の場所にリンクで飛ぼうとしても、その箇所が展開されてないと飛んでくれないみたいです。恐らく仕様なのでしょう。

**Comment by haruo-wakakusa** [comment]
そうでした。MDNの記事改善のために、日本語の質問フォーラムを（多分あると思うんですけど）作ればいいのかなとは思いました。しかしラーニングエリアの翻訳記事がそこまで充実していないorz...

**Comment by haruo-wakakusa** [comment]
「Whitespace in HTML」の節ですが、全角スペース「　」(U+3000)はHTMLの空白としてみなされず、そのまま表示される、と私の方では認識していますので、そのように注記しておきます。
https://www.w3.org/TR/2017/REC-html52-20171214/infrastructure.html#space-separated-tokens

**Comment by haruo-wakakusa** [comment]
親切のつもりで追記しまくってしまったが、HTMLチェッカーで分かることは外してしまったほうがいいのだろうか。

**Comment by hmatrjp** [comment]
@haruo-wakakusa 
Whitespace in HTML の節の中にある 3回目の 「吾輩は猫である。名前は・・・」は 1行になってしまっていますが、 これは意図通りでしょうか？
直前の説明　日本語の段落を記述する際には次のように〜　と合っていないように思います。

それから、解決済みのようですが、Learn 以下のページには、冒頭に 前提条件: が提示されています。
ファイルの保存時の拡張子設定については、ファイル取扱い に含まれるでしょうから、敢えて触れる必要はないという判断ができます。
訳注をどの程度入れるかも、前提条件と目標に沿って決めればよいもので、訳者の裁量に任される部分だと思います。

**Comment by haruo-wakakusa** [comment]
まず、HTMLエンティティ(HTML entity)の訳し方についてですが、そのままで行きたいと思います。
https://developer.mozilla.org/en-US/docs/Glossary/Entity

entityは直訳すると「実体」であり、
&#x61;&#x62;&#x63;&#xFF21;&#xFF22;&#xFF23;&#x3042;&#x3044;&#x3046;
のことではなく、
abcＡＢＣあいう
のことを言っています。

しかし実際にentityと言ったときには、entity referenceの意味で使われるようです。従って、実体(entity)と実体参照(entity reference)は同じ意味であり、HTMLエンティティは、「HTMLの実体参照」と解釈してもよいと考えます。

**Comment by haruo-wakakusa** [comment]
次に、訳者が記事の原著作者の意図に大きく外れるような訳を書いてよいかということについては、やはりよろしくないと思いました。なので、できるだけ元の記事と同じ内容とし、どうしても注を付けたい場合はその分量を1/10に抑えるようにしたいと考えています。多分そうしないと「翻訳」ではなくなってしまうので。あくまで私の考えです。

**Comment by haruo-wakakusa** [comment]
私が訳した部分について修正をかけていますが、1347274の内容が反映されていないように思います。済みませんがご確認のほどをよろしくお願いいたします。

**Comment by Uemmra3** [comment]
長いページの翻訳お疲れ様ですー。

1347274、つまり若草さんの最後の編集が反映されていない件、
こちらでは強制再読み込み(Shift+Ctrl+R)を行って反映されているのを確認しました。
サーバー側のキャッシュの関係で差分が生じることがたまにありますね。
試してみてください。

**Comment by haruo-wakakusa** [comment]
Uemmra3 さん、アドバイスありがとうございます。きちんと表示されるようになりました。

**Comment by haruo-wakakusa** [comment]
翻訳の方、一通り完了いたしました。

**Comment by hmatrjp** [comment]
ありがとうございました。 @haruo-wakakusa 
Issue タイトルにあるページの翻訳完了というとで、1度この Issue を閉じます。
閉じた後もssue への書き込みはできますので、何かお気づきの点がある方は書き込んでください。

**Comment by Uemmra3** [comment]
@haruo-wakakusa 
かなり長いページの翻訳、お疲れ様でした！
エディターの一番下のへんにある翻訳中フラグが外れてなかったので、次回から外してもらえるとよいかと。
(今回はこちらで外しておきました)
