### ISSUE TITLE
「How CSS works」のリンク修正願い

### ISSUE THREAD

**Issue by haruo-wakakusa** [mozilla-japan/translation#251]
https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Getting_started/How_CSS_works
のMozillaブラウザというのはFirefoxのことだとおもうのですが、
節「実例 : DOM を解析する」の「DOM Inspector」のリンク先は、
https://developer.mozilla.org/ja/docs/Tools/Page_Inspector
だと思われます。ご確認の上、リンクの張り直しを宜しくお願いいたします。

**Comment by hmatrjp** [comment]
少し調べてみました。
結論から書くと、
https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Getting_started/How_CSS_works
は
https://developer.mozilla.org/ja/docs/Learn/CSS/Introduction_to_CSS/How_CSS_works
へのリダイレクトとするべきページです。

原文では既にそのようになっています。
https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/How_CSS_works$edit

**Comment by dskmori** [comment]
リダイレクト設定を行いました。
- [履歴](https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Getting_started/How_CSS_works$history)
- [リビジョン](https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Getting_started/How_CSS_works$revision/1344297)

リダイレクト先には DOM Inspector へのリンクはありません。本 Issue はクローズしていただいてよろしいでしょうか。

**Comment by haruo-wakakusa** [comment]
すいません。初心者視点からもう一つ。
[MDN web docs]のトップページ - [テクノロジー] - [CSS]
で、遷移するページには、「CSS入門」の矩形領域があり、そのなかに「イントロダクション」へのリンクがあります。リンク先のページは、
https://developer.mozilla.org/ja/docs/Web/CSS/Getting_started
です。このページの「チュートリアル第１章」の「3. どのように CSS は動作するのか」だけ
https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Getting_started/How_CSS_works
から
https://developer.mozilla.org/ja/docs/Learn/CSS/Introduction_to_CSS/How_CSS_works
へ変更されていますが、そうすると、「3. どのように CSS は動作するのか」の次のトピックである「4. 接続と継承」
https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Getting_started/Cascading_and_inheritance
へと遷移せず、
https://developer.mozilla.org/ja/docs/Learn/CSS/Introduction_to_CSS/Syntax
へ遷移してしまいます。細かいことを言ってしまって申し訳ございませんが、再検討のほどをよろしくお願いいたします。

**Comment by dskmori** [comment]
https://developer.mozilla.org/ja/docs/Web/CSS 内の **CSS 入門** 矩形領域の *イントロダクション* のリンク先が原文と差異があったため直しました。
* https://developer.mozilla.org/ja/docs/Learn/Getting_started_with_the_web/CSS_basics

ご指摘ごもっともなのですが、本題 (DOM Inspector のリンク先修正) はクリアになっているので、本 Issue はクローズお願いします。
>節「実例 : DOM を解析する」の「DOM Inspector」のリンク先は、
>https://developer.mozilla.org/ja/docs/Tools/Page_Inspector
>だと思われます。ご確認の上、リンクの張り直しを宜しくお願いいたします。

**Comment by haruo-wakakusa** [comment]
すみません。HTML入門の翻訳は担当させて頂いているのですが、MDNとしての全体像を把握したくてCSSのセクションも閲覧していた次第です。とりあえず、矛盾はないのでクローズさせて頂きます。
