### ISSUE TITLE
ブラウザ互換性のテーブル

### ISSUE THREAD

**Issue by zakki** [mozilla-japan/translation#252]
英語版ではマクロで生成している互換性情報が、日本語版では手書きの表になっていて最新情報に追従できていません。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
単純に`<p>{{Compat("javascript.builtins.WeakMap")}}</p>`のように書き換えて問題ないでしょうか？

**Comment by momdo** [comment]
@zakki 
当該箇所は英語版がそうなっているので、英語版からそのままコピペして良いと思います（少なくとも、私はそうしてます…）

**Comment by Uemmra3** [comment]
英語版で
リビジョン 926805 / 編集者: LPGhatguy / 編集日時: 2015年9月30日 14:17:45 -0700
リビジョン 1340670 / 編集者: utkarshbhatt12 / 編集日時: 2017年12月28日 3:20:40 -0800
の差分を見てみると、
互換性テーブルは 926805 では手書きだったのが、1340670 ではマクロに変わってますね。
英語版に追従するという意味でも、変更すべきではないでしょうか。

**Comment by zakki** [comment]
ありがとうございます。書き換えて、全体の構成を英語版に追従させました。
