### ISSUE TITLE
Editor's Draftの訳語に勧告改訂案があてがわれている

### ISSUE THREAD

**Issue by momdo** [mozilla-japan/translation#256]
例えば以下のリソースで。
https://developer.mozilla.org/en-US/docs/Web/CSS/text-combine-upright#Specification
https://developer.mozilla.org/ja/docs/Web/CSS/text-combine-upright#Specification

これは編集者草案が正しいでしょうか。

**Comment by hmatrjp** [comment]
はい、そのほうが良いと思います。

マクロを使ってテーブルから引いているようで、
該当する文字列は
https://github.com/mdn/kumascript/blob/master/macros/spec2.ejs
にありました。

**Comment by Uemmra3** [comment]
@momdo この Issue って閉じちゃって良いでしょうか？

**Comment by momdo** [comment]
@Uemmra3 
MDNには反映されていない？のか、例えばこんな感じで古いものが残っているようです。（まるで仕組みが分かっていませんが。）
https://developer.mozilla.org/ja/docs/Web/CSS/background-position-x
閉じるかどうかの判断はお任せします…

**Comment by momdo** [comment]
@Uemmra3 
あ、Ctrl＋F5で編集者草案になってましたね…お騒がせしました。
（ということで閉じておきます。）
