### ISSUE TITLE
L10N マクロ再確認 (was: 訳注などのマクロが削られている！

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#263]
ちょっと背景はわかりませんが、報告します。

https://developer.mozilla.org/ja/dashboards/revisions?locale=ja&user=SphinxKnight&topic=&start_date=&end_date=&preceding_period=&authors=0&page=1

なんだか、YakuchuとかGengoheikiとかのマクロが削除されつつあります。
リビジョンコメントに「rm obsolete macro」とあるのでマクロ自体をなくしていくのかもしれません。
文章は残してくれているのですが、マクロがなくなるとスタイリングとかがないので他の文との区別がつきません。

まずはご報告まで。

**Comment by Uemmra3** [comment]
聞いてみました。
https://twitter.com/Uemmra3/status/967998422203576320
どうもコードベースが大きいので削除したかった模様です。

とりあえずちょっとアグレッシブすぎたかも？とはおっしゃっていますが、フィードバックが欲しいようなので以後はdiscourseで議論することになりそうです。

**Comment by Uemmra3** [comment]
そのdiscourseスレッドはこちらです。
https://discourse.mozilla.org/t/mdn-rfc-002-localization-reducing-the-number-of-kumascript-macros/26017

**Comment by dynamis** [comment]
個人的にはフォーマットが揃えることに意味があるマクロだけ残せば良いと思います。
具体的には、訳注ですね

### [{{訳註}}](https://github.com/mdn/kumascript/blob/master/macros/%E8%A8%B3%E6%B3%A8.ejs)
```
<span style="color: darkgreen; background: #ef9;">【訳注: <%- Web.html($0) %>】</span>
```
これは2000年頃に翻訳を始めた頃から、私が訳注は緑色にして入れる習慣で勝手に訳していてそれがある程度広がったものじゃないかと思います。
実際統一カラー、記法で訳注を入れると言うことに意義があるのでこれは残して欲しい。

ちなみに訳注とか Aliase にしたくなる。ただ、これって特に日本語固有の事情じゃないと思うので TranslationComment とかの Aliase にして全原語で使ってもらう提案しましょうか。

### {{原語併記}}
```
<%- Web.html($0) %> (<span style="color: green;"><%- Web.html($1) %></span>)
```
かっこ付けで英語を入れるだけじゃなくて色も変えてるんですね。その挙動を残すならやはりこれは表現の統一性が大事なので残すべき。

個人的な趣味としては、原語の併記をするときには別に色まで変えなくて単に 日本語 (English) って核だけでも良いのかなという気はしていますが。

### [{{英語版章題}}](https://github.com/mdn/kumascript/blob/master/macros/%E8%8B%B1%E8%AA%9E%E7%89%88%E7%AB%A0%E9%A1%8C.ejs)
```
※このテンプレートは内容によって自動的に見出しの id/name 属性が書き換わる事により
英語版のアンカーがそのまま使用できなくなる問題を解決する為に作成されたものですが、
幾つかの解決不能な欠陥があり、用いるべきではありません。
```

実装中に断念した過去のものっぽいので削除、使われているページからも削除して欲しい

**Comment by potappo** [comment]
Google Group の方に歴史的説明を書きました。

https://groups.google.com/d/msg/mozilla-translations-ja/GZR2i75n93I/Q71nB94xBQAJ

私の意見としては、統一できるものは統一する（Aliaseという解決が一番楽そう）、最近の翻訳者が使っていない、よく見られているべーじでまったく見かけない過去の遺物的なものはいらないで良いと思います。

**Comment by himorin** [comment]
多言語間の連携状況がいまどうなってるか把握できていないので何とも言えませんが、訳注を書くというのはほかであまり聞いたことはなかった＠昔、な気もします。訳注を入れすぎるとあとで英語版が更新されたことに追随しての更新の際に面倒な面はあった気もしなくはないので、あまり入れすぎるのも考え物かもしれませんが。

あとはgoogle groupの方に返信しておくようにします。

**Comment by Uemmra3** [comment]
皆さま、ご説明ありがとうございました。思ったよりは影響少なさそうなので安心しました。

これまでのところをまとめると、このあたりになりそうでしょうか？

- 残したいもの
{{原語併記}} {{Gengoheiki}}
{{訳語}}
{{訳注}}　{{Yakuchu}}

- 不要(今後は使わなくて良い)
{{MDCProjectPagesTOCJa}}
{{英語版章題}}
{{翻訳中}}
{{移行予定}}
{{移行}}

「残したいもの」については理由を示してほしいと言われてますが、 @dynamis さんの理由で良さそうですね。

訳注を入れると、WYSIWYGエディターで英語と日本語がズレて辛いことはありますが、それはエディター側でもう少し工夫してほしい部分なので (https://bugzilla.mozilla.org/show_bug.cgi?id=1174520) 現状仕方ないかとは思っています。

**Comment by Uemmra3** [comment]
@hmatrjp ご連絡ありがとうございます。
しばらく放置してました。。

> - 残したいもの : to Keep
> {{原語併記}} {{Gengoheiki}}
> {{訳語}}
> {{訳注}}　{{Yakuchu}}
どうやらエイリアスに相当するものはなさそうです。
その上で、@dynamis さんの提案のように英語化するべきでは？と提案を受けました。

{{訳注}}　{{Yakuchu}} => {{TranslationNote}}
のような感じです。

あとの2つも同じように考えてみると
{{原語併記}} {{Gengoheiki}} => {{LocalizedWordWithOriginal}}
{{訳語}} => {{OriginalWordWithLocalized}}
とかになるでしょうか？
もっと良い名前があればコメントください(><)

どうしてもこれまでの日本語マクロ名が要る！とかいう意見がなければ、
英語化するのが順当かな？と思います。

**Comment by 7cc** [comment]
お知らせありがとうございます。（あるページでスクリプトエラーが出ていて、削除決定なのかと思い編集したので）

--------------------------

訳語はツールチップでなく、原語併記と同様に普通のテキストで表示してほしいです。ツールチップは気付きにくいし、選択（してからコピーや検索）もできないし使い勝手が良くないと思います。
（discourseのほうで既に出ていますが、）どちらもテキスト表示にした場合は、原語併記か訳語どちらか一方だけを残して、順序は好きなように使うのもありかと思います。

多言語併記は英語だとbilingual、例えば標識はbilingual signと呼ばれているようですが、非英語圏で使うことが前提なのでbilingualで意味が通じるのか分かりません。

あと、origは事実上Enなのでその方が短くなります。

**Comment by hmatrjp** [comment]
またまた時間が空いてしまいましたが、discourse へ持っていく提案として以下のようにまとめてみました。

- {{訳語}} は廃止、{{言語併記}} を残す → {{OrigAndLocal}} に改名。
　orig は en-US が圧倒的に多いですが、別の言語の言葉を 原語として扱う場面もありそうな気がするので、En とはしない名前を提案します。

- {{訳注}} {{Yakuchu}}  → {{TranslationNote}} に改名

**Comment by hmatrjp** [comment]
特に反対意見が出ないようなので、discourse に投稿してきました。
https://discourse.mozilla.org/t/mdn-rfc-002-localization-reducing-the-number-of-kumascript-macros/26017/15?u=hmatrjp

**Comment by hmatrjp** [comment]
KumaScript の今後、ということでこちらも関係ありそうです。今月頭の投稿。
https://discourse.mozilla.org/t/next-steps-for-kumascript/32227

**Comment by momdo** [comment]
この手のマクロに関して、現時点のステータス等があんまりわかっていないので質問したいのですが…

1. 「訳注」のマクロは現時点でどれを使うことが推奨されますか？（それとも、KumaScriptの展開が読めないので、むしろ地の文の方が推奨される？）
1.  現時点での日本語特有なマクロのまとめは、公式なページとしてはどこにありますか？（ここに挙げられたのが一番まとまっている？）

**Comment by Uemmra3** [comment]
@momdo 

私の見解ですが、
1.については「注意しながら使う」ということではないでしょうか？
少なくとも日本語ロケールにおいては有効ですし、TranslationNoteに改名すれば他の言語でも使ってもらえるのではないかと思います。
「意味のない/冗長な/テストのないマクロをなくす」のが趣旨なので、「意味のある/重複しない/テストのあるマクロ」に変えていけば残るのかなと。
2.ないのかな？と思います。

他の方の訂正、フォローなど歓迎します。

**Comment by hmatrjp** [comment]
@momdo  @Uemmra3 亀レスすみません。

1.「訳注」のマクロで現時点で使えるものは「訳注」だけだと思います。
TranslationNote はまだ存在せず、Yakuchu は削除されている様子。

2.現状有効なもの名前の列挙としては
https://github.com/mdn/kumascript/tree/master/macros
の末尾（今は4つ）が一番の源ではないかと思います。

https://developer.mozilla.org/en-US/dashboards/macros
にもリストがあるのですが、上のディレクトリにあるファイル名から機械的に拡張子を除いているだけの可能性あり。（例：GruopData はマクロで使われるデータで、マクロそのものではなさそう）

**Comment by hmatrjp** [comment]
MDN が Yari ベースに変わり、 #547 で一段落するものと思いますので、一度閉じます。
