### ISSUE TITLE
[bug]英語のidに合わせてnameをつけるのが動作不良

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#265]
例
https://developer.mozilla.org/ja/docs/Learn/HTML/Howto$compare?locale=ja&to=1366345&from=1148738

バージョン 0.3.4 のregressionな気がする

**Comment by unarist** [comment]
んー、原文にリセットして適用しなおしてみましたが、ちゃんと処理されているようです。新規翻訳ではない（既に日本語版のリビジョンが存在する）ページなので自動実行はされなかったと思いますが、そういうことではないですか？

**Comment by Uemmra3** [comment]
どうやらMDN本体のバグのような気もします(編集画面を開いてすぐに自動保存でidが日本語化されるため？)。

0.3.4 で少しここの正規表現をいじった
(&lt;h2 hogehoge='fuga' id ='poi'&gt;とかに対応していく)
のが悪影響したのかとも思いましたが、やり直すとうまくいきますね。
お騒がせしました。

MDN本体にバグレポできるかどうか(確実な再現が難しい)見極めてから閉じようと思います。

**Comment by unarist** [comment]
既にidが日本語化されていれば「以下の見出しは既にidが翻訳済みだったため〜」と通知するようにしていますが、タッチの差でなにかあるかもしれませんね…。

本当は既にidが変更されている場合でも原文を参照して適用できると便利そうなんですが、見出し構造が変わっている可能性もあるので難しいのが惜しい。
