### ISSUE TITLE
Inheritance in JavaScriptの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#268]
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Inheritance

**Comment by kenji-yamasaki** [comment]
翻訳を開始しました。
翻訳終わりましたら、レビュー依頼のためまた投稿します。

**Comment by Uemmra3** [comment]
要約のとこでSyntaxを「統語論」とされていましたが単に「文法」としました。

**Comment by Uemmra3** [comment]
あと
https://developer.mozilla.org/ja/docs/Learn/JavaScript/Objects/継承
と、slugを翻訳(Inheritance => 継承)されていますが、今後は英語のままにしてください。

他のページからの被リンクも日本語に直さねばならなくなり、リンク切れが多数発生しかねないので。。

**Comment by Uemmra3** [comment]
とりあえず一通りレビュー済みなので、翻訳中フラグも外してあります。
またIssueも閉じておきます。
(問題などあれば再度開くこともできますので)

**Comment by kenji-yamasaki** [comment]
@Uemmra3 さん
レビューありがとうございました。
ただ翻訳しましたが、文書として見直しを最後にしようとしてcloseとしておりませんでした。

docsでUemmra3さんの訂正された履歴を確認したいと思っております。やり方を不明としておりますので、
ご教示いただけますでしょうか。

よろしくお願いいたします。

**Comment by Uemmra3** [comment]
まずは長いページの翻訳お疲れ様でした！

履歴については、ログインした状態で、
「編集」ボタンの右にある「歯車」のメニューから「履歴」をクリックすれば確認できます。

他の方も分からない可能性がありますので、今後質問はSlackとかGoogle Groupsで聞いていただけると良いかも？

**Comment by hmatrjp** [comment]
みなさんもうお気づきかもしれませんが：
このリポジトリの Issue への投稿は、Slack の #translation に流れるように設定されてます。　@kenji-yamasaki の質問も @Uemmra3 の回答も流れてます。便利な機能ですね。(Thanks @dynamis )

slug は、ページ移動して修正しておきました。
https://developer.mozilla.org/ja/docs/Learn/JavaScript/Objects/Inheritance
