### ISSUE TITLE
Iterators and generatorsの翻訳（更新）

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#271]
作業を開始します。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Iterators_and_Generators$edit

**Comment by kenji-yamasaki** [comment]
作業が完了しました。

**Comment by Uemmra3** [comment]
レビューしました。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Iterators_and_Generators$compare?to=1375919&from=1375803
翻訳の中身は概ねあっていますが、Symbol.Iteratorのプロパティを述べている文は「関数」のことだと思います。

あとは差分に抜けがありました。これは一番上に英語版のdiffが出ているハズですので、それを見ながら更新すればよいかと思います。

**Comment by kenji-yamasaki** [comment]
Uemmra3 さん
指摘された内容は確認しましたので、次回より改善いたします。
ありがとうございました。
