### ISSUE TITLE
Document and website structureの翻訳

### ISSUE THREAD

**Issue by JPMUG-KK** [mozilla-japan/translation#279]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

翻訳を開始します :)

**Comment by Uemmra3** [comment]
手付かずのまましばらく間が空いているようなので、見出し+αを訳してみました。

**Comment by Uemmra3** [comment]
レビューしました。内容をご確認ください。
