### ISSUE TITLE
NATの和訳

### ISSUE THREAD

**Issue by m-yamamo0417** [mozilla-japan/translation#283]
https://developer.mozilla.org/ja/docs/Glossary/NAT

**Comment by m-yamamo0417** [comment]
翻訳しました。
「用語集」ページのリンクが赤色のままですが、水色にするにはどうすればいいのでしょうか。

**Comment by dskmori** [comment]
[ページ](https://developer.mozilla.org/ja/docs/Glossary) をスーパーリロード (`Ctrl` + `F5`) してください。

**Comment by m-yamamo0417** [comment]
ありがとうございます。試してみます。
今朝確認したら水色になっていました。クローズします。
