### ISSUE TITLE
TCPの和訳

### ISSUE THREAD

**Issue by m-yamamo0417** [mozilla-japan/translation#284]
https://developer.mozilla.org/ja/docs/Glossary/TCP
やりますー

**Comment by m-yamamo0417** [comment]
終わりましたー

**Comment by Uemmra3** [comment]
じゃんじゃんやっちゃってくださいー👍

**Comment by Uemmra3** [comment]
https://developer.mozilla.org/ja/docs/Glossary/TCP$compare?locale=ja&to=1384346&from=1383778

**Comment by Uemmra3** [comment]
ちょこっとレビューしてみましたー。

**Comment by m-yamamo0417** [comment]
レビューありがとうございます。
タグの属性を修正する方法を教えていただけますか？

**Comment by Uemmra3** [comment]
https://youtu.be/gRotn_mZtt4
05:40あたりをご覧ください。

2018年5月29日(火) 6:19 Manabu Yamamoto <notifications@github.com>:

**Comment by dskmori** [comment]
ドキュメントに対するタグ付けではなく、ドキュメントの HTML タグの属性を修正する方法を問うているのではないかと思います。

https://developer.mozilla.org/ja/docs/MDN/Contribute/Editor/Source_mode

**Comment by m-yamamo0417** [comment]
H3タグのid属性やname属性を編集する方法が知りたいことでした。
@dskmori さん、ありがとうございました。
@Uemmra3 さん、動画も勉強させていただきます。
