### ISSUE TITLE
Attribute selectorsの翻訳

### ISSUE THREAD

**Issue by m-yamamo0417** [mozilla-japan/translation#285]
開始します。
https://developer.mozilla.org/ja/docs/Learn/CSS/Introduction_to_CSS/Attribute_selectors

**Comment by m-yamamo0417** [comment]
開始します。
https://developer.mozilla.org/ja/docs/Learn/CSS/Introduction_to_CSS/Attribute_selectors

**Comment by dskmori** [comment]
see: https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures/Live_samples

**Comment by m-yamamo0417** [comment]
@dskmori 修正ありがとうございました。IDが日本語になっていたのが問題ですか？

**Comment by dskmori** [comment]
Live Sample マクロの引数と ID が一致していなかったのが問題です。
引数と ID が一致していれば、日本語でも問題ありません。
[Sandbox](https://developer.mozilla.org/ja/docs/Sandbox) で試してみました。

今回は、私の好みで英語に統一しました。

**Comment by m-yamamo0417** [comment]
了解です。ありがとうございます。

**Comment by m-yamamo0417** [comment]
ようやく翻訳終わりました。
レビューおねがいします。

**Comment by hmatrjp** [comment]
編集レビューしました。いくつか修正しました。
https://developer.mozilla.org/ja/docs/Learn/CSS/Introduction_to_CSS/Attribute_selectors$revision/1396243

**Comment by m-yamamo0417** [comment]
レビューありがとうございました。クローズします。
