### ISSUE TITLE
String.prototype.trimLeft()やtrimRight()からtrimStart()、trimEnd()へ改名(stage3)

### ISSUE THREAD

**Issue by segayuu** [mozilla-japan/translation#288]
1. Stage3のドキュメント(es-US)の差分を反映。
2. タイトル、URLの変更
3. 日本語への翻訳

- [x] https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/TrimLeft
- [x] https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/TrimRight

**Comment by potappo** [comment]
すでに他の方が途中まで翻訳してくれていますが、最終更新が1年以上経っているので、引き継ぎます。

**Comment by potappo** [comment]
ページ移動し、英語版の最新版を反映しました。クローズします。
