### ISSUE TITLE
A first splash into JavaScriptの翻訳（更新）

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#290]
https://developer.mozilla.org/ja/docs/Learn/JavaScript/First_steps/A_first_splash

**Comment by kenji-yamasaki** [comment]
翻訳完了。原文が複数形にするだけの更新だったため、翻訳に変更なし

**Comment by Uemmra3** [comment]
H2 とかのid属性は、英語のままにしてください。
(他のページからのリンクがアンカーになってて、すべてを連動して日本語になくす仕組みがないため)
あとname属性にidと同じ値を追加してください。
(エディターで日本語タイトルを入れるとid属性も勝手に日本語化されるのを防ぐため、のハズ…)

**Comment by Uemmra3** [comment]
あとは問題ないと思います。お疲れ様でした！
