### ISSUE TITLE
Functionsの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#291]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Functions

**Comment by kenji-yamasaki** [comment]
翻訳完了しましたので、レビューをお願いいたします。

**Comment by hmatrjp** [comment]
編集レビューが済んでいる様子です。( by dskmori )
その後、原文最新版への追随もなされた( by Uemmra3 )ようですので、
何か手を入れたいところが残っていなければ、1度このIssue を閉じてください。 @kenji-yamasaki
