### ISSUE TITLE
Indexed_collectionsの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#292]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Indexed_collections

**Comment by kenji-yamasaki** [comment]
翻訳完了しましたのでレビューをお願いいたします。

**Comment by hmatrjp** [comment]
レビュー始めます（7/21翻訳ミートアップ、リモート参加）

**Comment by hmatrjp** [comment]
セクション  配列のメソッド　の手前まで編集レビューしました。上から 5分の2 くらいです。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Indexed_collections$revision/1397734
今日はここまでです。
続きは来月になってしまいそうなので、それまでに手を付けられる方いたらお願いします。

**Comment by hmatrjp** [comment]
編集レビューを終えました。
@kenji-yamasaki 
何箇所か日本語の気になった箇所など変更していますので、確認してください。
良ければ Close してください。 疑問点があったらコメントお願いします。

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
本来の意味に沿った日本語に訂正されたこと確認しました。
ありがとうございました。
