### ISSUE TITLE
Object-oriented JavaScript for beginnersの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#295]
https://developer.mozilla.org/ja/docs/Learn/JavaScript/Objects/Object-oriented_JS

**Comment by Uemmra3** [comment]
確認しました。

**Comment by hmatrjp** [comment]
もともと誤字、脱字等が紛れ込んでいたようですので、見つけたところを修正しました。
https://developer.mozilla.org/ja/docs/Learn/JavaScript/Objects/Object-oriented_JS$compare?locale=ja&to=1400935&from=1400631
