### ISSUE TITLE
HTTPの翻訳

### ISSUE THREAD

**Issue by oasis-forever** [mozilla-japan/translation#296]
【原文URL】
https://developer.mozilla.org/ja/docs/Web/HTTP

**Comment by oasis-forever** [comment]
翻訳完了したのでレビューをお願い致します。

**Comment by Uemmra3** [comment]
やりまーす

**Comment by Uemmra3** [comment]
一番上の「Summary」のところですが、英語版にはない具体的な説明が追加されていますねー。

例) UDP => 音声や動画のストリーミング等で使用される UDP

初学者にとってはわかりやすくて良いですが、ベテランの方には少しまどろっこしい面もあるかも。。
少し悩ましいですね。

あとは変更が頻繁にあるページの場合(HTTP はそうでもなさそうですが…)、英語の原文の修正に追従しにくかったりします。
とりあえずそのままにしておきます。

**Comment by potappo** [comment]
ここで議論されている該当箇所は、他の方の更新によって無くなっていました。
最新版にも追随しており、特に問題はありませんでしたので、本 issueをクローズします。
