### ISSUE TITLE
WebDAVの翻訳

### ISSUE THREAD

**Issue by k636174** [mozilla-japan/translation#297]
原文ページ：https://developer.mozilla.org/en-US/docs/Glossary/WebDAV
日本語ページ：https://developer.mozilla.org/ja/docs/Glossary/WebDAV

**Comment by k636174** [comment]
翻訳完了しましたので、レビューをお願いいたします。
* WebDAVで出来る事リストが原文自体もザックリだったので、翻訳も原文準拠としました。

**Comment by Uemmra3** [comment]
レビューしました。
https://developer.mozilla.org/ja/docs/Glossary/WebDAV$compare?locale=ja&to=1397953&from=1397748
差分を見てみてください。

**Comment by k636174** [comment]
ありがとうございます。
手が空き次第確認致します。
