### ISSUE TITLE
RSSの翻訳

### ISSUE THREAD

**Issue by bakunyo** [mozilla-japan/translation#298]
原文ページ
https://developer.mozilla.org/en-US/docs/Glossary/RSS

**Comment by bakunyo** [comment]
翻訳しました。レビューをお願いいたします :bow:
https://developer.mozilla.org/ja/docs/Glossary/RSS

**Comment by hmatrjp** [comment]
Uemmra3 によるレビューが済んでいる様子です。
他に手を入れたいところがなければ、この Issue を閉じてください。 @bakunyo

**Comment by bakunyo** [comment]
@hmatrjp  ありがとうございます！
すみません、気付きませんでした…
内容確認しましたので、Closeします。
