### ISSUE TITLE
Firefox Developer Toolsの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#299]
https://developer.mozilla.org/ja/docs/Tools

**Comment by kenji-yamasaki** [comment]
更新翻訳が終わりましたので、レビューをお願いいたします。

**Comment by kenji-yamasaki** [comment]
編集レビューフラグを降ろしまして追加分の翻訳を行うこととします。
またレビュー依頼しますのでよろしくお願いいたします。
@hmatrjp

**Comment by kenji-yamasaki** [comment]
冒頭の未翻訳部分の翻訳を行いましたのでレビューをお願いいたします。

**Comment by hmatrjp** [comment]
可能であれば、レビューの前に2点お願いします。 @kenji-yamasaki 
- English (en-US) へのリンクになっている部分を、日本語訳 ja へのリンクに直す。
この時、日本語訳ページはまだ存在していなくても構いません。（リンクをクリックすると翻訳へのお誘いが出ます。）
- ウェブ に訳せる Web が残っているので、ウェブ に。

冒頭の {{ToolsSideBar}} が抜けていたので入れておきました。

**Comment by kenji-yamasaki** [comment]
レビュー依頼の前の対応、畏まりました。@hmatrjp 
翻訳に関する文書を確認したのですが、以下の資料ですとjaに直すまでの記載がなく、「「en-US/」の部分を削除します。」となっていますので、これを機に記載を追記すると良いのではないかと思いました。

冒頭の追記、ありがとうございました。

ご確認よろしくお願いいたします。

**Comment by hmatrjp** [comment]
@kenji-yamasaki 
> 以下の資料ですとjaに直すまでの記載がなく、「「en-US/」の部分を削除します。」

どの資料のことでしょうか？ 直しておきたいです。
ときたま、en-US/ を消して対応しているページを見かけるので不思議に思っていました。

なお、両者の違いは次のとおりです。
1. ロケール指定部分( en-US/ とか ja/ など) を消す →ブラウザとMDNサーバーでコンテンツネゴシエーションが行われた結果決まった言語のページが表示される。
2. ja/ を明示する → 日本語指定になる。

上の1. で不都合が出るのは、普段日本語以外の言語でブラウザを使っている人が日本語ページを辿りたい場合です。具体例としては、MDN のシステム側で不具合が起き、一連の日本語関連ページを（英語圏の）Admin が見に来る場合です。

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
肝心なURLを添付忘れておりました。
http://fxos.org/hacks/mdn_doc_fest/

Mozillaドキュメント翻訳の始め方-作業上のヒント-リンク修正に該当の記載がありました。

よろしくお願いいたします。

**Comment by kenji-yamasaki** [comment]
hmatrjp 指摘への対処を行いました。
レビューをお願いいたします。

**Comment by hmatrjp** [comment]
@kenji-yamasaki 
URL ありがとうございます。
確かに削除って書かれてますね。。。

fxos.org の文書は私では直せないので、筆者の catch さんにお願いの
メールを出しました。

レビューについては、今 #292 を進めていまして
私がやる場合はその後になります。
いける方、いますか？

**Comment by marsf** [comment]
@hmatrjp 翻訳の始め方の件、別 issue にしました。よろしくお願いします。

**Comment by Uemmra3** [comment]
このIssueの本題である、レビューのほう完了しました。
l10n:priority
のついている重要なページの更新、お疲れ様でした！
