### ISSUE TITLE
B2G OS のアドオンを開発する

### ISSUE THREAD

**Issue by Suuzuukii** [mozilla-japan/translation#300]

**Comment by Suuzuukii** [comment]
こちらはすでに翻訳されているということで、レヴュー用ということでしょうか。

**Comment by hmatrjp** [comment]
https://developer.mozilla.org/ja/docs/Archive/B2G_OS/Add-ons/Developing_B2G_OS_add-ons
そうですね。取り上げるとすると主にレビュー対象として、だと思います。

一般論ですが、原文が更新されている場合は、差分を反映するという作業が発生することもあります。
このページは、 Archive 入りしている　（docs/Archive/ の下にある）ため、今後、原文が更新されることは基本的にありません。

**Comment by Suuzuukii** [comment]
今後ご訂正いただいたように、タイトル名も記載いたします。

**Comment by Uemmra3** [comment]
Issue整理のため閉じます。
