### ISSUE TITLE
PDFの翻訳

### ISSUE THREAD

**Issue by asuktakahashi** [mozilla-japan/translation#301]
https://developer.mozilla.org/en-US/docs/Glossary/PDF$translate?tolocale=ja

**Comment by asuktakahashi** [comment]
用語集のPDFを翻訳しました。
レビューをお願いいたします。

**Comment by Uemmra3** [comment]
dskmoriさんで対応済

**Comment by hmatrjp** [comment]
日本語訳へのリンクも置いておきます。
https://developer.mozilla.org/ja/docs/Glossary/PDF
[最初のコメントのリンク](https://github.com/mozilla-japan/translation/issues/301#issue-343301330)は、常に編集画面を開こうとするため。（ログインしてない人が読めない）

**Comment by asuktakahashi** [comment]
ありがとうございます、まだ慣れておらず勉強になります。
