### ISSUE TITLE
How to write an article to help people learn about the Web の翻訳

### ISSUE THREAD

**Issue by bakunyo** [mozilla-japan/translation#302]
原文
https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_article_to_help_learn_about_the_Web

**Comment by bakunyo** [comment]
途中までやったので一旦公開しました。
https://developer.mozilla.org/ja/docs/MDN/Contribute/Howto/Write_an_article_to_help_learn_about_the_Web

残りはどこかで時間見つけて、近日中にやろうと思います。

**Comment by bakunyo** [comment]
翻訳を最後まで終えました！
どなたか、レビューをお願いいたします。

**Comment by Uemmra3** [comment]
お疲れ様でした。
レビューしてみますね。

**Comment by bakunyo** [comment]
ありがとうございます！よろしくお願いいたします :bow:

**Comment by Uemmra3** [comment]
何度か出てきている"straightforward"という単語ですが、
「単純に」と訳されているのを「単刀直入に」としようかと思います。
要は「回りくどくないように書く」ということかと思っています。。

**Comment by bakunyo** [comment]
そうですね… 💦 改めて見ると "simple" も「単純に」になっていて、イマイチ区別できていなかったですね。。
ありがとうございます！

**Comment by Uemmra3** [comment]
あともしかしたら #148 も参考になるかもしれません。

この学習エリアは新記事がバンバン出てきていて翻訳が後手に回っているので、翻訳していただいてありがたいです！

**Comment by Uemmra3** [comment]
一通りレビューしました。差分をご確認ください。
https://developer.mozilla.org/ja/docs/MDN/Contribute/Howto/Write_an_article_to_help_learn_about_the_Web$compare?locale=ja&to=1401683&from=1401629

注意点として、H2とかの文を日本語化する前に、id属性に合わせたname属性をつけてください。
(ソースモードでないとうまく編集できない)

それが面倒な場合は…お役立ちツールの導入を検討してみてください。
https://github.com/mozilla-japan/translation/tree/master/MDN

**Comment by bakunyo** [comment]
@Uemmra3 レビュー＆編集ありがとうございました。
なるほど、ソースの中身にも注意して進める必要があるのですね…
次にやる時には、教えて頂いたツールを使ってみることにします！
