### ISSUE TITLE
line-break の翻訳

### ISSUE THREAD

**Issue by rigani** [mozilla-japan/translation#303]
原文ページ
https://developer.mozilla.org/en-US/docs/Web/CSS/line-break

**Comment by rigani** [comment]
翻訳 Done です。レビューお願いします！🚀
https://developer.mozilla.org/ja/docs/Web/CSS/line-break

**Comment by Uemmra3** [comment]
レビューしました。差分をご確認ください。
https://developer.mozilla.org/ja/docs/Web/CSS/line-break$compare?locale=ja&to=1397955&from=1397736

Breakは直接的な表現として「改行する」と訳しました。影響ある場合は教えてください。
