### ISSUE TITLE
Unicodeの翻訳

### ISSUE THREAD

**Issue by asuktakahashi** [mozilla-japan/translation#304]
https://developer.mozilla.org/ja/docs/Glossary/Unicode
用語集 Unicodeの翻訳が終わりました。
レビューをお願いいたします。

**Comment by Uemmra3** [comment]
完了しました。 気をつける点は #310 とほぼ同じかと。

翻訳についても配置を入れ替えたりしたのでご確認ください。
https://developer.mozilla.org/ja/docs/Glossary/Unicode$compare?locale=ja&to=1397793&from=1397738

**Comment by asuktakahashi** [comment]
ありがとうございました。
確認いたします。
