### ISSUE TITLE
Entityの翻訳

### ISSUE THREAD

**Issue by asuktakahashi** [mozilla-japan/translation#308]
https://developer.mozilla.org/ja/docs/Glossary/Entity
用語集 Entityの翻訳が終わりました。
レビューをお願いいたします。

**Comment by hmatrjp** [comment]
編集レビューが済んでいるようです。
他に手を入れたいところが残っていなければ、この Issue を閉じてください。 @asuktakahashi

**Comment by asuktakahashi** [comment]
クローズにします。
