### ISSUE TITLE
hanging-punctuation の翻訳

### ISSUE THREAD

**Issue by rigani** [mozilla-japan/translation#309]
📄原文
https://developer.mozilla.org/en-US/docs/Web/CSS/hanging-punctuation

**Comment by rigani** [comment]
翻訳しました。レビューいただけると嬉しいです。
https://developer.mozilla.org/ja/docs/Web/CSS/hanging-punctuation

しかし、 `force-end` が期待通りに動作しませんでした。🙄
私の解釈違いであればよいのですが。少し心配です。

|allow-end|force-end|
|:-:|:-:|
|<img width="353" alt="2018-07-21 16 54 28" src="https://user-images.githubusercontent.com/8327205/43033530-d0ea3712-8d06-11e8-913d-131d99cd7909.png">|<img width="371" alt="2018-07-21 16 54 16" src="https://user-images.githubusercontent.com/8327205/43033533-d90262f8-8d06-11e8-865e-b53369806a05.png">|

**Comment by hmatrjp** [comment]
force-end と allow-end の意図するところについては、
https://www.w3.org/TR/css-text-3/#hanging-punctuation-property にある EXAMPLE22 にわかりやすい図入りの解説があるのを見つけました。

ところで、半角英文字でやってみると、結果が変わったりするんでしょうか？

**Comment by Uemmra3** [comment]
とりあえず、翻訳はできているので閉じます。
