### ISSUE TITLE
Dynamic typingの翻訳

### ISSUE THREAD

**Issue by asuktakahashi** [mozilla-japan/translation#310]
https://developer.mozilla.org/ja/docs/Glossary/Dynamic_typing
用語集 Dynamic typing の翻訳が終わりました。
レビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューしますね

**Comment by Uemmra3** [comment]
個々の翻訳が終わったらMDNエディターの下にある「翻訳途中 - まだ翻訳が完了していない」のチェックを外してください。

**Comment by Uemmra3** [comment]
https://mozillajp.slack.com/archives/C5N6SFQMP/p1532156345000048
に書いたのですが、タグづけもお願いします。

**Comment by Uemmra3** [comment]
MDNのマクロ、つまり{{ }}で囲まれているところは少し注意が必要です。
https://developer.mozilla.org/ja/docs/Glossary/Dynamic_typing$compare?locale=ja&to=1397788&from=811715

{{glossary}}の第1引数は英語のままで、実際に表示するものを第2引数にすればよいですね。
{{interwiki}}はwikipediaの日本語版と英語版で項目名が違う(和訳されている)ので、それを注意していただければ！

少しテクニック的な落とし穴が多いページでしたが、この調子でお願いします！
