### ISSUE TITLE
「Mozillaドキュメント翻訳の始め方」を fxos.org から wiki に移す

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/translation#312]
fxos.org においてある [Mozillaドキュメント翻訳の始め方](http://fxos.org/hacks/mdn_doc_fest/) をこの Github の Wiki ページに転記したい。
別サイトにあると気軽に更新できないので不便です。

(issue https://github.com/mozilla-japan/translation/issues/299#issuecomment-410557056 より)

**Comment by marsf** [comment]
とりあえずコピペしました。

[Mozilla ドキュメント翻訳の始め方](https://github.com/mozilla-japan/translation/wiki/Mozilla-%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E7%BF%BB%E8%A8%B3%E3%81%AE%E5%A7%8B%E3%82%81%E6%96%B9)

**Comment by potappo** [comment]
#321 に別 issue を立てて、各所から Github の Wiki ページへのリンクを追加しましたので、もし URL を変える場合は、そちらにも反映してください。
Wiki ページの方で、古い記載（Personaとか、リダイレクトされますがProjectページへのリンクがあったので）を更新しました。

**Comment by potappo** [comment]
#321 でのURLとしたページ名は以下です。今日変わったばっかりで、ここにあるコメントからだとリンクされていないのでメモ。
[Get-started-with-translation-of-Mozilla-documentations](https://github.com/mozilla-japan/translation/wiki/Get-started-with-translation-of-Mozilla-documentations)

**Comment by marsf** [comment]
@potappo さんありがとうございます。
この issue は閉じます。
