### ISSUE TITLE
Navigator.registerProtocolHandler の翻訳

### ISSUE THREAD

**Issue by unarist** [mozilla-japan/translation#313]
https://developer.mozilla.org/ja/docs/Web/API/Navigator/registerProtocolHandler

古くなっていた訳を更新（ほぼ書き直し）しましたのでレビューをお願いします。

特に長い文は意訳が強くなってしまった気もするので、そのあたりも見ていただければと思います。

**Comment by unarist** [comment]
@hmatrjp ありがとうございます、日本語版の記事名を反映しました。

**Comment by hmatrjp** [comment]
編集レビューします。（翻訳ミートアップ 8/25）

**Comment by hmatrjp** [comment]
編集レビューしました。
日本語を一部変えているので、確認して大丈夫なら Close してください。 @unarist

**Comment by unarist** [comment]
@hmatrjp レビューありがとうございます。

> 〜、あるいはハンドラーの URL が HTTPS である、といった場合にこの例外が発生します。

これは逆で、（ブラウザによっては）HTTPの場合に例外が発生する可能性があります。なので原文でも、

> ... or if the browser requires that this function be called from a secure context, or that the handler's URL be an HTTPS one.

として安全なコンテキストのくだりと並べて書かれています。というわけで

> またはブラウザーがこの関数を安全なコンテキストから呼び出すことを要求している、あるいはハンドラーの URL が HTTPS である、といった場合にこの例外が発生します。

と直してみましたがどうでしょうか。

**Comment by hmatrjp** [comment]
@unarist 良いと思います。
該当部分は requires に that節 が二つぶら下がっている形ですね。見落としていました。
