### ISSUE TITLE
user-selectの翻訳

### ISSUE THREAD

**Issue by sutara79** [mozilla-japan/translation#318]
https://developer.mozilla.org/ja/docs/Web/CSS/user-select
ほぼ未訳だったので翻訳しました。
レビューをお願いします。

下記の訳に自信がありません。

- - -
### chrome
- This doesn't have any effect on content loaded as **chrome**, except in textboxes.
- これは、テキストボックスを除いて、chrome として読み込まれたコンテンツには何の影響も与えません。

ブラウザのchromeのことでしょうか?

- - -
### &lt;html&gt; container
- Doesn't work in Safari; use only "none" or "text", or else it will allow typing in the **&lt;html&gt; container**
- これは Safari では動きません。"none" または "text" を使ってください。そうしなければ、&lt;html&gt; コンテナで入力可能になってしまいます。

htmlコンテナが何のことか分かりません。
Windows機ばかりでSafariを持っていないので、試すこともできません...。

- - -
### HTML editor
- In an **HTML editor**, if a double-click or context-click occurred in sub-elements, the highest ancestor with this value will be selected.
- HTML 要素でダブルクリックや右クリックを行うと、この値が付けられている最も上位の先祖要素が範囲選択されます。

HTMLエディタとは &lt;textarea&gt; や &lt;input&gt; のことなのだろうかと思い、CodePenでサンプルを作って調べてみました。
https://codepen.io/sutara79/pen/NLqJRb

しかし、&lt;textarea&gt; や &lt;input&gt; では `user-select` の効果がありません。
それで、「HTMLエディタ」ではなく「HTML要素」と訳しました。

**Comment by hmatrjp** [comment]
@sutara79 疑問点3点について、思い当たるところを。

**chrome** おそらくこちらの chrome です。
https://developer.mozilla.org/ja/docs/Mozilla/Chrome_Registration

**&lt;html&gt; container** `<html>〜</html>`のタグの組みのことですね。
`<html>`と`</html>`で挟まれる内容を入れる、容れものとしての表現です。

**HTML editor** XUL の頃の editor のことだと思います。
https://developer.mozilla.org/ja/docs/Mozilla/Tech/XUL/editor
Firefox の場合 Quantum 以降では関係ないんですが、Thunderbird にはまだ含まれています。

**Comment by sutara79** [comment]
@hmatrjp ありがとうございます。
<html> コンテナはそのままにして、chrome と HTML editor にはリンクを追加することにしました。
その旨を隠し要素でメモしています。
https://developer.mozilla.org/ja/docs/preview-wiki-content

- - -
![001](https://user-images.githubusercontent.com/187350/44611089-573d3a00-a83a-11e8-9db0-4a400e9cb9e9.png)

![002](https://user-images.githubusercontent.com/187350/44611177-b9963a80-a83a-11e8-8bb6-396024247efd.png)

**Comment by hmatrjp** [comment]
これから編集レビューします。

**Comment by hmatrjp** [comment]
編集レビューを終えました。他に変更なければ Close してください。 @sutara79

**Comment by sutara79** [comment]
@hmatrjp レビューありがとうございました。
これで Close します。
