### ISSUE TITLE
Building up a basic demo with Three.js の英和翻訳

### ISSUE THREAD

**Issue by irimame256** [mozilla-japan/translation#319]
https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_on_the_web/Building_up_a_basic_demo_with_Three.js

**Comment by hmatrjp** [comment]
レビューを始めています。(9月29日のMDN翻訳ミートアップ)

**Comment by hmatrjp** [comment]
編集レビューを済ませました。
意訳かな？と思ったところにも、何箇所か手を入れています。
確認して、OKなら閉じてください。 @irimame256

**Comment by irimame256** [comment]
確認しました。レビューありがとうございます。closeします.
