### ISSUE TITLE
MDN日本語版翻訳ガイドの整理

### ISSUE THREAD

**Issue by potappo** [mozilla-japan/translation#321]
時代とともに移り変わっている MDN日本語版翻訳ガイドページの整理。
[GiutHub Wiki にあるガイドページ「MDN Web Docs ドキュメント翻訳の始め方」](https://github.com/mozilla-japan/translation/wiki/Get-started-with-translation-of-Mozilla-documentations)を最新として、他のページを更新ないし、GiutHub Wiki ガイドページへ誘導させます。

対象ページ：
- [x] [MDN グローバルページの翻訳である「Translating MDN pages」](https://developer.mozilla.org/ja/docs/MDN/Contribute/Localize/Translating_pages) 内容の最新化と GitHub WIki ガイドへの誘導
- [x] [MDN 日本語版独自の「MDN 技術ドキュメントの翻訳について」](https://developer.mozilla.org/ja/docs/Project:Translation)  GitHub WIki ガイドへ誘導して、このページはもうリタイアさせたい →「平成最後の夏」という最近のバズワードっぽい言葉を注意書きに入れてリタイア
- [x] [modestの MDN 日本語版](https://dev.mozilla.jp/project/mdnja/) MDN 日本語版独自のガイドページから GitHub Wiki ガイドページへの誘導に更新
- [x] GiutHub Wiki ガイドページの内容の最新化

**Comment by potappo** [comment]
整理作業を終えたのでクローズします。

**Comment by hmatrjp** [comment]
整理ありがとうございます。
[Github Wiki にあるガイド](https://github.com/mozilla-japan/translation/wiki/Get-started-with-translation-of-Mozilla-documentations)を少しだけ編集しました。
