### ISSUE TITLE
Styling boxes（ボックスの装飾）の翻訳

### ISSUE THREAD

**Issue by FumiyaShibusawa** [mozilla-japan/translation#325]
# 概要
以下の未翻訳の記事を翻訳します。
https://developer.mozilla.org/ja/docs/Learn/CSS/Styling_boxes

**Comment by FumiyaShibusawa** [comment]
https://developer.mozilla.org/ja/docs/Learn/CSS/Styling_boxes
翻訳が完了しました。お手数ですがレビューをお願い致します。

### 特にレビューしてほしいところ
1. `create your own files` の部分は直訳すると「ファイルを作成する」だと思うんですが、文脈を考慮して「コードを書く」くらいに意訳してみました。ちょっと意訳しすぎかもしれません。

原文:
> Note: If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as JSBin or Thimble.

翻訳:
> 注: 自身のPC/タブレット/その他のデバイスにコードを書く環境がない場合は、JSBin や Thimble などでサンプルコードを試すことも可能です。

--- 

2. 以下の部分の訳が難しかったです。いかにも英語から翻訳したんだなってのが丸分かりの日本語訳になってしまいました。他に良い翻訳案があればコメントお願い致します…。

原文:
> ## Assessments
> The following assessments will test your understanding of the box styling techniques covered in the guides above.
> 
> ## Creating fancy letterheaded paper
> If you want to make the right impression, writing a letter on nice letterheaded paper can be a really good start. In this assessment we'll challenge you to create an online template to achieve such a look.
> ## A cool looking box
> Here you'll get some more practice in creating cool-looking boxes, by trying to create an eyecatching box.

翻訳:
> ## 課題
> 以下の課題で、このガイドで網羅したボックスの装飾についての理解度をテストします。
>
> ### レターヘッド付きの文書の作成
> レターヘッド付きの手紙を書くのが相手に良い印象を与える出発点といえるでしょう。この課題では、そのような見た目を実現するためにオンラインテンプレートを作ってもらいます。
> 
> ### クールな見た目のボックス
> 上の課題に引き続き、人目につくようなクールなボックスを作ってみましょう。

**Comment by Uemmra3** [comment]
ここのレビュープロセスがキッチリしていてスゴい！
私からは、リード部分に不要なHTMLタグが混ざっていたのを除去しました。

あと、MDNページのタグ(日本語 のタグ)が全くつけられていなかったので追加しています。
新規翻訳時に、まずは英語版のタグをそのままつけておいてください。

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
snakadaさんにより大きく変更されていましたが、レビューを完了しました。Issueを閉じます。
