### ISSUE TITLE
Localization and Internationalization の翻訳

### ISSUE THREAD

**Issue by Suuzuukii** [mozilla-japan/translation#326]
https://developer.mozilla.org/ja/docs/Web/Localization

**Comment by Suuzuukii** [comment]
こちら、一通り和訳ができたのでレヴューをお願いいたします。

**Comment by FumiyaShibusawa** [comment]
レビューします！

**Comment by FumiyaShibusawa** [comment]
原文: 
> {{Glossary("Localization")}} (often abbreviated to L10n) is the process and concept of ensuring that a website, web application, or any other form of content can easily be adapted to suit a specific culture.

翻訳:
> ウェブサイト、ウェブアプリケーションまたは、その他の形式が容易に各文化圏に合わせるこことを確実にする過程・概念です。

「ウェブサイト、ウェブアプリケーション、またはその他の形式のコンテンツを各文化圏に合わせて個別に適応させる工程、またはその概念を指します。」はいかがでしょうか？easilyやensureも訳に組み込んでもいいと思いますが、組み込まない方が音読してみて自然だなと思いました。

**Comment by FumiyaShibusawa** [comment]
原文:
> {{Glossary("Internationalization")}} (often abbreviated to I18n) is the practice of ensuring that a site or app is designed in a way that makes localization possible.

翻訳: 
> {{Glossary("Internationalization")}} (略称：I18n) サイトやアプリが、ローカリゼーションを可能にする一つの方法で、デザインされることを確実にするプラクティスです。

「ウェブサイト、ウェブアプリケーションをローカリゼーションが可能な形で設計する手法を指します」はどうでしょうか。こちらに関しては、原文自体が曖昧な気がします。 `a site` とか `app` とか使うくらいなら、前の文に合わせて `a website` とか `web application` と明示的に書いた方が良いような…。

**Comment by Suuzuukii** [comment]
@FumiyaShibusawa さん 
　続けてご修正メッセージをいただき、ありがとうございました。

＞easilyやensureも訳に組み込んでもいいと思いますが、組み込まない方が音読してみて自然だなと思いました。
こういったご指摘は、自分でも気づきにくいので、特にありがたいです。

＞原文自体が曖昧な気がします。
原文作成の方たちも、自発的に作られているようなので、
大いにありますね。

＞前の文に合わせて …
これは、その典型かもしれませんね。そうします。

いただいた訂正文を考慮して修正いたします。
引き続き何かあれば、ご指摘お願いいたします。

**Comment by FumiyaShibusawa** [comment]
原文:
> Guides and tutorials to help you learn how to ensure that your apps are i18n ready, and how to localize them once they are.

翻訳:
> ガイド・チュートリアル：どのようにアプリが i18n仕様とされているか、どのようにローカリゼーションするのかということを確実にするためのヘルプ

「i18n対応、またそれに続くローカリゼーションを実装する方法について学習できるガイドやチュートリアルです。」とかはいかがでしょうか…？ここは見出しの後に続くリード文っぽいので、日本語の場合は体言止めより述語終わりの方が読んでいて自然かなと思いました。

**Comment by FumiyaShibusawa** [comment]
> Introduction to localization
An introductory guide to what's involved in localizing a web site or app, from identifying the factors that need to be reviewed and potentially changed to actually applying the needed changes.

この部分の訳が抜けている…かもしれません！

**Comment by FumiyaShibusawa** [comment]
原文:
> An overview of what internationalization (i18n) is and what features and technologies available to web developers can be used to make sure your content is ready to be localized.

翻訳:
> i18nとは何かということや、ウェブ開発者がコンテンツがローカリゼーション準備できることを確実にするために利用可能な側面や技術に関する概要

「国際化（i18n）とはなにか、またコンテンツをローカライズするためにウェブ開発者に提供されている機能や技術についての概要です。」だと変ですかね…。主語が大きいので訳しにくいですね。

**Comment by Suuzuukii** [comment]
＞ここは見出しの後に続くリード文っぽいので、日本語の場合は体言止めより述語終わりの方が読んでいて自然かなと思いました

リード文に続くため、文体にするということは、おっしゃる通りですね。
「見出し」という点につきまして、その後の小見出しごとを各括りとすると、
文章として分けていて自然な気がします（新聞や雑誌と同様で）。それが「見出し」の役割である
という印象ですが、どうでしょうか。

訳抜けがあり、失礼いたしました。そちらを追加いたしました。

＞i18nとは何かということや、ウェブ開発者がコンテンツがローカリゼーション準備できることを確実にするために利用可能な側面や技術に関する概要

こちらの方が自然ですね。

**Comment by FumiyaShibusawa** [comment]
原文:
> The Unicode Bidirectional Algorithm is the standard algorithm used to determine the rendering order of Unicode text, and is used by web browsers while rendering content. This overview will give you a general understanding of the BiDi algorithm and how it affects your internationalization efforts.

翻訳: 
> Unicode仕様双方向テキストアルゴリズムは、Unicodeテキストのレンダリングオーダーの決定に使用される、標準アルゴリズムであり、レンダリングコンンテンツの一方のウェブブラウザによって、使用されます。この概要は、BiDiアルゴリズム および、インターナショナライザゼーションへのと取り組みが、どのように影響するのかということに関する、一般的な理解を提供します。

「Unicode双方向アルゴリズムとは、Unicodeのテキストの表示順を決定するための標準アルゴリズムのことで、ウェブブラウザでコンテンツをレンダリングする際に使われています。この概要を読むことで、そのBiDi（訳注: 本アルゴリズムの略語でバイダイと読む[ [リンク] ](https://ja.wikipedia.org/wiki/%E5%8F%8C%E6%96%B9%E5%90%91%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88)）やそれが国際化（i18n）の取り組みにどう影響するかについての基本的（or 一般的な）な理解が得られます。」などはどうでしょうか。

`レンダリングオーダー` は表示順と訳してしまって良いと思います。また、Internationalizationは日本語で国際化と一般的に呼ばれているので、 `インターナショナライザゼーション` も `国際化` と訳して問題ないと思います。

**Comment by Suuzuukii** [comment]
はい、レンダリングオーダー・インターナショナライザゼーションの両方とも、
技術的にそのように用語化されているのであれば、そのようにいたします。

**Comment by FumiyaShibusawa** [comment]
原文:
> HTML elements used for i18n and l10n
A reference to the elements provided by HTML that can be used to create content that's ready to localize.

翻訳:
> i18n・l10nに使用されるHTMLエレメント
　ローカリゼーション仕様のコンテンツを作成するために使用される 　HTMLによって提供されるエレメント

「i18nやl10nに使用されるHTML要素
　ローカリゼーション可能なコンテンツを作成するためにHTMLで提供されている要素のリファレンス」はどうでしょうか。

`HTML element` は一般的に `HTML要素` と日本語で使われているので、 `エレメント` ではなく `要素` と訳して問題ないです。

**Comment by FumiyaShibusawa** [comment]
原文:
> A reference of the CSS properties that are especially important when producing l10n-ready content.

翻訳:
> 110仕様のコンテンツを制作する際に特に重要なCSSプロパティに関する参照

こちらは、l10nの訳が110となっているので修正お願いします！

**Comment by FumiyaShibusawa** [comment]
いったんレビューは以上です！色々とコメントしてしまってすみませんが、ご確認のほどよろしくおねがいします。

**Comment by Uemmra3** [comment]
ここのレビュープロセスがキッチリしていてスゴい！
私からは、リード部分に不要なHTMLタグが混ざっていたのを除去しました。

あと、MDNページのタグ(日本語 のタグ)が全くつけられていなかったので追加しています。
新規翻訳時に、まずは英語版のタグをそのままつけておいてください。

**Comment by Uemmra3** [comment]
完了していますので、閉じます。

**Comment by marsf** [comment]
レビューされた内容がページに反映されていません。修正してから issue を閉じてください。

**Comment by Uemmra3** [comment]
おおっと、失礼しました。
@Suuzuukii 確認のほう、いかがでしょうか？

**Comment by Suuzuukii** [comment]
@Uemmra3 
対応遅れております。
修正してから、閉じます。

**Comment by Uemmra3** [comment]
確認ありがとうございます。
こちらでも見てみたところ、元の英語ページが削除されていて編集できないですね。。

https://wiki.developer.mozilla.org/ja/dashboards/revisions?user=PushpitaPikuDey
↑の方が'18/8/25に編集したページのようですが。。

**Comment by hmatrjp** [comment]
確かに、編集しようとするとエラーになります。 en-US の原文がないためでしょうか。
何か手がかりを知らないかと PushpitaPikuDey に問い合わせ中です。 (ユーザープロファイルにあったTwitter の DM 宛)
週明けまで待って反応なければ、bugzilla に報告しようと思います。

**Comment by hmatrjp** [comment]
Twitter の DM には反応なし。
https://bugzilla.mozilla.org/show_bug.cgi?id=1610289
に報告しておきました。

**Comment by hmatrjp** [comment]
原文(en-US)は、削除されているとのこと。 
Archive もリダイレクトもされずにただ消されるというケースは珍しい（私は他に知らない）ので、そのへん含めて理由を尋ねています。
参照 https://bugzilla.mozilla.org/show_bug.cgi?id=1610289 （上にあるのと同じです）

**Comment by hmatrjp** [comment]
答えが返ってきています。
削除した人は、原文の方を復活させるつもりはなさそうで、日本語の方はせめて削除ではなく Archive エリアへの移動にしたいと思い、その旨回答しています。関心のある方は、上記の bugzilla 参照のこと。

また同 bugzilla に画像つきで出てますが、人によっては en-USのページ
https://wiki.developer.mozilla.org/en-US/docs/Web/Localization
を見ようとしたときに、'Not Found' ではなく、削除された旨のメッセージページが見えるそうです。
Permission による　らしいんですが、どなたか後者が見える方いますか？

**Comment by Uemmra3** [comment]
@hmatrjp "Not Found"でしたー。

**Comment by hmatrjp** [comment]
日本のボランティアに1人くらい staff ユーザーがいても良いように思うので、例の bugzilla でその話を降っています。

件のページはとりあえず、
https://wiki.developer.mozilla.org/ja/docs/Archive/Web/Localization
に移しました。
今のところ、編集できないことに変わりはありませんので、将来、誰かが似た内容を書きたくなった場合に参考にするページとしての扱いです。

**Comment by hmatrjp** [comment]
ページそのものがなくなっているので、一度閉じます。
もとの翻訳対象ページで触れられていたかもしれない内容としては、今
https://developer.mozilla.org/ja/docs/Glossary/Localization
https://developer.mozilla.org/ja/docs/MDN/Community/Contributing/Translated_content
があります。
