### ISSUE TITLE
POP3の翻訳

### ISSUE THREAD

**Issue by MasayoshiFujiwara** [mozilla-japan/translation#327]
https://developer.mozilla.org/ja/docs/Glossary/POP

**Comment by MasayoshiFujiwara** [comment]
翻訳完了いたしました。
レビューをお願いいたします。

**Comment by dskmori** [comment]
レビューしました。
常体と敬体が混在するなど、基本的なミスがあったので、今後は気を付けてみてください。

**Comment by MasayoshiFujiwara** [comment]
dskmori様
レビューありがとうございました。
私は根本的に文章を書く能力が低いです。
気をつけて、直していくように致しますので、今後ともよろしくお願い致します。

**Comment by Uemmra3** [comment]
完了しているようなので閉じますね。
@MasayoshiFujiwara 
翻訳や文章の練習に、「用語集」のページはピッタリだと思います。
これからもチャレンジしてみてください。
