### ISSUE TITLE
Cross-Origin Resource Sharing (CORS)の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#329]
https://developer.mozilla.org/ja/docs/Web/HTTP/HTTP_access_control

**Comment by kenji-yamasaki** [comment]
軽微な変更の翻訳を行いました。
レビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
と思ったけど @kenji-yamasaki さんの修正が反映されてなくないですか？
こちらで強制読み込みしてみても出てきませんでした。
確認お願いします。

**Comment by kenji-yamasaki** [comment]
失礼しました。
反映されていませんね。この記事だけ何度か公開の更新を試したのですが、うまく行かず・・・
通信環境、時間を変えて再度作業して、また依頼します。
@Uemmra3

**Comment by kenji-yamasaki** [comment]
作業が完了しましたので、レビューをお願いいたします。
@Uemmra3

**Comment by Uemmra3** [comment]
不要な<code>が混じっていたので消しておきました。あと @kenji-yamasaki さんが変えたわけではないと思いますがl10n:priorityタグが消えていたので追加しました。

https://developer.mozilla.org/ja/docs/Web/HTTP/HTTP_access_control$compare?locale=ja&to=1421674&from=1421602
