### ISSUE TITLE
[MDN] Web Components

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#33]
- https://developer.mozilla.org/en-US/Apps/Tools_and_frameworks/Web_components
- Web アプリを作る上で、Web Components を知っておくと効率がよくなりますし、これから大事な技術化と思います。

**Comment by storywriter** [comment]
2016年2月6日 羽山 翻訳いたします。

**Comment by Uemmra3** [comment]
archive行きになってるので閉じますね
