### ISSUE TITLE
翻訳：OPERA BROWSER 

### ISSUE THREAD

**Issue by Suuzuukii** [mozilla-japan/translation#331]
https://developer.mozilla.org/ja/docs/Glossary/Opera_Browser

**Comment by Suuzuukii** [comment]
こちらの和訳につきまして、できる方はレヴューをお願いいたします。

**Comment by dskmori** [comment]
レビューしました。ご確認ください。

**Comment by Uemmra3** [comment]
良いでしょう。閉じます。
