### ISSUE TITLE
How the Web worksの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#333]
https://developer.mozilla.org/ja/docs/Learn/Getting_started_with_the_web/How_the_Web_works

**Comment by kenji-yamasaki** [comment]
更新翻訳を完了したのでレビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューしました。
今回の修正は問題なく、その他の細かいところを修正しました。
https://developer.mozilla.org/ja/docs/Learn/Getting_started_with_the_web/How_the_Web_works$compare?to=1426454&from=1425215
