### ISSUE TITLE
Error の翻訳

### ISSUE THREAD

**Issue by segayuu** [mozilla-japan/translation#334]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Error
英語版の内容に結構な変更を確認したため、追記いたしました。

レビューお願いします。

**Comment by hmatrjp** [comment]
core error type が7つありますが
文中には6とあります。
今、手元で直せないので、
取り急ぎ、お知らせのみで。

-- 
濱崎

**Comment by segayuu** [comment]
ありがとうございます。気づいてすぐに修正しました。

**Comment by Uemmra3** [comment]
ざっと確認して問題なさそうなので、閉じます。
