### ISSUE TITLE
Expressions and operatorsの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#337]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Expressions_and_Operators

**Comment by kenji-yamasaki** [comment]
翻訳が完了しましたので、レビューをお願いいたします。

**Comment by Uemmra3** [comment]
やってみます

**Comment by Uemmra3** [comment]
いったん途中まで確認(どなたか別の方にレビューしてもらってもOKです)

**Comment by Uemmra3** [comment]
ひととおりレビューしました。
