### ISSUE TITLE
Geeksphone

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#34]
* https://developer.mozilla.org/ja/Firefox_OS/Developer_phone_guide/Geeksphone
* 購入されている方々は英語を苦にしないのかもしれませんが、Firefox OS に関する日本語ドキュメントも揃っているということを示すためにも翻訳されると良いと思っています。

**Comment by dynamis** [comment]
未訳部分もあるけど役割は終えたかと思うので閉じますね。
