### ISSUE TITLE
Keyed collectionsの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#340]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Keyed_collections

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
指摘箇所は修正しました。

**Comment by hmatrjp** [comment]
修正ありがとうございました。 @kenji-yamasaki 
見る範囲を広げてみたら、他にも直したい箇所が出てきたので、11/17のミートアップで一度触るつもりです。

**Comment by hmatrjp** [comment]
思ったよりも編集箇所が多くなりました。
編集レビューフラグは降ろしてありますが、もう一度見てもらえると安心です。 @kenji-yamasaki 
問題なければ、Close してください。

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
編集内容全て確認し、問題はありませんでした。
