### ISSUE TITLE
Date.prototype.getMilliseconds() の翻訳

### ISSUE THREAD

**Issue by segayuu** [mozilla-japan/translation#345]
1.  [x] 現在の英語版の反映
2.  [x] 追加部分の翻訳
3.  [x] レビュー

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/getMilliseconds

**Comment by segayuu** [comment]
反映終わりましたのでレビューお願いします。

**Comment by Uemmra3** [comment]
はーい

**Comment by Uemmra3** [comment]
よさげでした

**Comment by segayuu** [comment]
@Uemmra3 ありがとうございます！
