### ISSUE TITLE
Function.arity の更新

### ISSUE THREAD

**Issue by segayuu** [mozilla-japan/translation#346]
1. [x] 現在の英語版の反映
2. [x] 追加個所の翻訳
3. [x] レビュー

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Function/arity

**Comment by segayuu** [comment]
反映終わりましたのでレビューお願いします。

**Comment by Uemmra3** [comment]
はーい

**Comment by Uemmra3** [comment]
よさげです

**Comment by segayuu** [comment]
@Uemmra3 ありがとうございます！

**Comment by Uemmra3** [comment]
Advent Calendar、どっかの枠を埋めてみませんか？

https://adventar.org/calendars/3078

blogでも、作業ページでもOKですー。

**Comment by segayuu** [comment]
入れるかどうかは怪しいですが、のんびり翻訳してるページがあるので、隙間があったらやってみますー
