### ISSUE TITLE
Function.caller の更新

### ISSUE THREAD

**Issue by segayuu** [mozilla-japan/translation#347]
1. [x] 英語版の反映
2. [x] 追加箇所の翻訳
3. [x] レビュー

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Function/caller

**Comment by segayuu** [comment]
反映終わりましたのでレビューお願いします。

**Comment by Uemmra3** [comment]
はーい

**Comment by Uemmra3** [comment]
よさげです。
本筋ではないですが、hiddenのところは訳さなくてもよいかも？

**Comment by segayuu** [comment]
@Uemmra3 ありがとうございます！
