### ISSUE TITLE
Recursionの翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#348]
https://developer.mozilla.org/ja/docs/Glossary/Recursion を翻訳します

**Comment by takaneichinose** [comment]
翻訳終わりました。レビューお願いします。

**Comment by Uemmra3** [comment]
レビューしましたが、内容が少し難しいなぁ。。

**Comment by Uemmra3** [comment]
タグが抜けていたので、基本的に英語版と揃えるようおねがいします。

**Comment by hmatrjp** [comment]
recursion の訳を帰納とされていますが
プログラミング関連では　再帰　がほぼ定訳だと思います。

数学が絡むと　帰納　の可能性も出てきますが、ここでは当てはまらないと思います。

2018-12-06 12:49 GMT+09:00, Takane Ichinose <notifications@github.com>:
> 了解です。レビューありがとうございます。
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla-japan/translation/issues/348#issuecomment-444739186


-- 
濱崎

**Comment by takaneichinose** [comment]
ご指摘ありがとうございます。
翻訳を訂正します。

**Comment by takaneichinose** [comment]
翻訳を修正しました。
ご確認お願いします。

**Comment by Uemmra3** [comment]
編集レビューしました。
https://developer.mozilla.org/ja/docs/Glossary/Recursion$compare?locale=ja&to=1446571&from=1444527

「技術レビュー」フラグがOnになっていましたが、これは新APIの動作とかコードの動作確認になります。翻訳処理やその結果の文書については「編集レビュー」フラグだけOnにしてもらえばいいですよ。
他の方が直されている部分もあわせて見てみてください。
