### ISSUE TITLE
Raster Image の翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#351]
https://developer.mozilla.org/ja/docs/Glossary/Raster_image を翻訳します。

**Comment by takaneichinose** [comment]
翻訳終わりました、レビューお願いします。

**Comment by Uemmra3** [comment]
dskmoriさんが少し変更されてますが、やりきっちゃいますね

**Comment by Uemmra3** [comment]
レビュー完了ですが、オリジナルの英語版で技術レビューフラグがついているので、@takaneichinose さんのほうで英語版の変更をウォッチしていただけると助かります。(歯車アイコンからできるはず)

**Comment by takaneichinose** [comment]
レビューありがとうございます。
英語版の変更をウオッチしました。
