### ISSUE TITLE
Source_Code_Submissionの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#354]
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/Source_Code_Submission

**Comment by kenji-yamasaki** [comment]
翻訳作業を終えましたのでレビューをお願いいたします。

**Comment by Uemmra3** [comment]
はーい。
あとAdvent Calendarいかがですか？
https://adventar.org/calendars/3078

**Comment by Uemmra3** [comment]
これ私が少し訳しただけで置いてたやつですねw
拾っていただいてありがとうごさいます。
けっこうこまめに保存されていますが、あとでご自分で見たときにも分かりにくいと思いますので、
「～〇〇の前まで」とかでいいので履歴コメント書かれると良いかも？

**Comment by kenji-yamasaki** [comment]
@Uemmra3 
履歴コメントの残し方、次回からそのようにします。
Advent Calendar、入れてみました！
