### ISSUE TITLE
NaN の翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#355]
https://developer.mozilla.org/ja/docs/Glossary/NaN を翻訳します

**Comment by takaneichinose** [comment]
翻訳は完了しました。レビューお願いします。

**Comment by hmatrjp** [comment]
3段落め、原文と前後関係が入れ替わっているところがあるようです。

たとえば、未定義なのは、
NaNそのもので引数ではありません。


2018-12-02 21:22 GMT+09:00, T. Uemura <notifications@github.com>:
> Reopened #355.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla-japan/translation/issues/355#event-1999932023


-- 
濱崎

**Comment by hmatrjp** [comment]
原文の意味に沿うように、3段落目を修正しました。
