### ISSUE TITLE
Shadow tree の翻訳

### ISSUE THREAD

**Issue by dummy11022** [mozilla-japan/translation#356]
https://developer.mozilla.org/ja/docs/Glossary/Shadow_tree

**Comment by Uemmra3** [comment]
はーい

**Comment by Uemmra3** [comment]
しょうじきこの分野詳しくないけど、シャドーツリーでなくShadow treeで良いのか？

**Comment by hmatrjp** [comment]
足掛け3年になっていますが、年初の MDN 翻訳ミートアップをきっかけに見ました。
少しだけ訳文に触っています。
閉じます。
