### ISSUE TITLE
Debuggingの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#359]
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/%E3%83%87%E3%83%90%E3%83%83%E3%82%B0$edit

**Comment by kenji-yamasaki** [comment]
翻訳を終えましたので、レビューをお願いいたします。

**Comment by hmatrjp** [comment]
編集レビューしようと思ったら、原文が大幅に変更されていました。
バックグラウンドスクリプトをデバッグする の節までは、原文に追随しました。

**Comment by Uemmra3** [comment]
以降の文は原文をコピペしました。
…が未翻訳のままとなっています。あしからず。

**Comment by Uemmra3** [comment]
とりあえず一通り翻訳しました。同じような表現があちこちにあるのと、Console=>コンソールとかの、UI項目の訳が不十分な気もしていますが。。

**Comment by hmatrjp** [comment]
一度手を付けたこともあるご縁で、レビューします。(3/20翻訳ミートアップにて)

**Comment by hmatrjp** [comment]
途中まで編集レビューしました。コンテンツスクリプトをデバッグする　の手前まで。
続きは来月になるかもしれませんので、先にできる方いましたら、どうぞ。

**Comment by hmatrjp** [comment]
4/25のMDN翻訳ミートアップで、編集レビューの続きにかかります。

**Comment by hmatrjp** [comment]
編集レビュー一通り終わりました。長いベージで大変だったと思います。@kenji-yamasaki 
訳文に手を入れたところがあります。
訳し残しの訳、コピペの修正漏れ直しなど、気づいたところを直しましたので、一度変更箇所の確認をお願いします。 よければ close してください。

**Comment by hmatrjp** [comment]
@kenji-yamasaki 今日のMDN翻訳ミートアップのどこかで手が空くようでしたら、一度確認お願いします。

**Comment by kenji-yamasaki** [comment]
只今確認を行なっており、少し修正が入る予定です。

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
全文を確認し、いくつか修正をしました。

**Comment by hmatrjp** [comment]
修正点見ました。ありがとうございます。 @kenji-yamasaki 
Close しておきますね。
