### ISSUE TITLE
開発端末：ZTE Open

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#36]
* https://developer.mozilla.org/ja/Firefox_OS/Developer_phone_guide/ZTE_OPEN
* 購入された方は英語を苦にされないかもしれませんが、翻訳されていたほうが、日本語資料が揃っている感じがしてよいかと思います。

**Comment by dynamis** [comment]
Potappo, harry, Uemmra3 さんが翻訳してくださってますね。
