### ISSUE TITLE
 CSP: base-uriの翻訳

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#361]
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri
こちらを翻訳します

**Comment by gurezo** [comment]
翻訳してみたので、どなたかお時間有る時にレビューお願いいたします。

**Comment by hmatrjp** [comment]
構文のセクションの下に未訳が残ってますが
それ以外は良いように思います。

未訳部分は引き続き訳しますか？

-- 
濱崎

**Comment by gurezo** [comment]
https://github.com/mozilla-japan/translation/issues/361#issuecomment-450794130
@hmatrjp レビュー有難うございます。

構文セクション：
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri#Sources
{{page("Web/HTTP/Headers/Content-Security-Policy/default-src", "Sources")}}

これは、同じissueで作業するんでしたっけ？
おなじissue作業であれば、未訳作業をします。

**Comment by hmatrjp** [comment]
おっと、別のページからマクロで引用して表示しているんですね。
レンダリングされた表示だけ見ていたので気づきませんでした。

余力があれば、ということでお願いします。 @gurezo 
（同じIssueで、と決めつけてよいものではなさそう。）

**Comment by gurezo** [comment]
@hmatrjp @Uemmra3 
どなたかが下記部位をやってくださったようなので、レビューして問題なければ、closeをお願いします。

> {{page("Web/HTTP/Headers/Content-Security-Policy/default-src", "Sources")}}

**Comment by hmatrjp** [comment]
ありがとうございます。反応遅れてしまいましたが、
別ベージになっている部分、見ました。微修正したけど、大勢に影響なしです。
Close します。
