### ISSUE TITLE
Sideloading_add-onsの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#362]
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Distribution_options/Sideloading_add-ons

**Comment by kenji-yamasaki** [comment]
翻訳が完了しましたので、レビューをお願いいたします。

**Comment by hmatrjp** [comment]
冒頭を含めて2箇所、
ユーザーがアドオンを送信するのでなく、ユーザーにアドオンを送信する
という意図の所があります。

2018-12-19 21:52 GMT+09:00, kenji-yamasaki <notifications@github.com>:
> 翻訳が完了しましたので、レビューをお願いいたします。
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla-japan/translation/issues/362#issuecomment-448585962


-- 
濱崎

**Comment by kenji-yamasaki** [comment]
ご指摘の箇所と他少々訂正しました。引き続きレビューをお願いいたします。

**Comment by hmatrjp** [comment]
一通り見終わりました。
何箇所か手を入れましたが、修正箇所が少なかったため、このまま Close します。
