### ISSUE TITLE
Native manifestsの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#363]
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Native_manifests

**Comment by kenji-yamasaki** [comment]
翻訳が完了しましたので、レビューをお願いいたします。
「Use whichever is appropriate for your application.」という原文が意図がつかめず、うまく翻訳できていません。

**Comment by hmatrjp** [comment]
@kenji-yamasaki whichever 〜 の意図は、
32bit でも native でも、application にふさわしいレジストリを使ってください、ということでしょう。次の段落との対比で見ると、そうだと思います。

ついでに質問箇所周辺の誤訳の指摘も。
・原文ではFirefox 64以降と 63以前を分けて書いています。
・32-bit registry viewが先で、native registry view が後です。

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
ご指摘の内容で修正を行いました。

引き続きレビューをお願いいたします。

**Comment by hmatrjp** [comment]
@kenji-yamasaki 一通り見終わりました。
訳の方になかった正規表現を入れたり、消し残し？のところを削ったりしています。
もしかすると、意図に反する変更を入れている可能性もあるので、念の為見直しをお願いします。
OKだったら Close してください。

**Comment by kenji-yamasaki** [comment]
確認してOKだったので、Closeいたします。
