### ISSUE TITLE
HTML guidelinesの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#366]
https://developer.mozilla.org/ja/docs/MDN/Contribute/Guidelines/Code_guidelines/HTML$edit

**Comment by kenji-yamasaki** [comment]
新規翻訳を完了しましたので、レビューをお願いいたします。
neaterを「綺麗」と漢字で訳しています。
用語集には見当たりませんでしたが、平仮名が望ましいと意見が分かれるところかなと気になりました。

**Comment by hmatrjp** [comment]
・改行で差分が出ていたので、ソースレベルで修正しておきました。
・文書の言語　節の例、　html lang="ja" にしておきました。　原文では en-US でしたが、日本語読者にはこちらの方が良いかと。
・綺麗は、とりあえずそのままにしました。
・記述で何箇所か気になったところ（解釈が原文と異なりそうなところ含む）を変更しました。
https://wiki.developer.mozilla.org/ja/docs/MDN/Contribute/Guidelines/Code_guidelines/HTML$compare?locale=ja&to=1591972&from=1473927

良ければ Close してください。

**Comment by Uemmra3** [comment]
一部訂正しました。
大きくは問題なさそうなので閉じておきます。
