### ISSUE TITLE
TypedArray.from() 訳の修正

### ISSUE THREAD

**Issue by mandel59** [mozilla-japan/translation#367]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from
の訳を修正します。

**Comment by mandel59** [comment]
修正が終わりました。レビューをお願いします。

**Comment by Uemmra3** [comment]
レビューしてみます

**Comment by hmatrjp** [comment]
@Uemmra3 がレビューを済ませたかはわからないのですが、2月2日に別の人が手を入れて、今レビューフラグが降りているので、一段落したものとみなして一度閉じます。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from$history
