### ISSUE TITLE
Prototypeの翻訳

### ISSUE THREAD

**Issue by yuki26s** [mozilla-japan/translation#368]
https://developer.mozilla.org/ja/docs/Glossary/Prototype

**Comment by yuki26s** [comment]
https://developer.mozilla.org/ja/docs/Glossary/Prototype

**Comment by yuki26s** [comment]
翻訳が完了しましたので、レビューをお願いします。

**Comment by Uemmra3** [comment]
dskmoriさんの方で終わってますね。
あとでOKですので、差分をご確認ください。
タグは記事の検索をするためのものですので、とりま英語版にあわせてつけてみてください。

https://developer.mozilla.org/ja/docs/Glossary/Prototype$compare?locale=ja&to=1454730&from=1454707
