### ISSUE TITLE
Alignment Containerの翻訳

### ISSUE THREAD

**Issue by applejam9029** [mozilla-japan/translation#373]
https://developer.mozilla.org/ja/docs/Glossary/Alignment_Container
翻訳しましたので、レビューをお願いします。

**Comment by Uemmra3** [comment]
レビューしてみました。CSS周りの用語に自身がないですが。。

差分を確認ください。
https://developer.mozilla.org/ja/docs/Glossary/Alignment_Container$compare?locale=ja&to=1563818&from=1454794

あとタグはとりあえず英語版と同じにしておいてください。

**Comment by applejam9029** [comment]
レビューしていただき、どうもありがとうございます。

> タグはとりあえず英語版と同じに

とのことですが、ひとまずこの記事は現行の状態でよいという理解で合っていますでしょうか？

今までタグに気が回っていませんでしたので、以後注意いたします。

**Comment by hmatrjp** [comment]
> ひとまずこの記事は現行の状態でよいという理解で合っていますでしょうか？
はい。良さそうですよ。

**Comment by Uemmra3** [comment]
ひとまずは良いです。
今後、もっと本格的な翻訳をされて自信がないときとかには、
CSS 周りに明るいレビューアーをSlackやMLとかで募集してもよいかも？
