### ISSUE TITLE
日本語版でメタ変数が表現できない

### ISSUE THREAD

**Issue by mandel59** [mozilla-japan/translation#376]
MDNの日本語版ではイタリック体が反映されないため、メタ変数が表現できません。これはJavaScriptの記事を訳す場合に問題になります。

ここでいうメタ変数とは、コードの断片を表す変数のことで、そのような変数は、コード自体に現れる変数と区別するためにメタ変数と呼ばれています。
具体的には、 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from の _TypedArray_ という表記がそうです。具体的な _Int8Array_ や _Uint8Array_ などを代表して _TypedArray_ というメタ変数が使われています。

**Comment by dskmori** [comment]
ここらへんですね。

- [Bug 1522385](https://bugzilla.mozilla.org/show_bug.cgi?id=1522385)
- [Bug 999335](https://bugzilla.mozilla.org/show_bug.cgi?id=999335)

**Comment by mandel59** [comment]
`var` 要素に関してはイタリック体を適用してもらえるようCSSを変更すれば解決しそうです

**Comment by mandel59** [comment]
とりあえず、原文でemでマークアップされている箇所に関しても、varを使ったマークアップに修正して作業を続けておきます。

**Comment by hmatrjp** [comment]
Bug 1522385 の vote に、賛同の投票をしてきました。

**Comment by hmatrjp** [comment]
2014年頃に斜体を無効にする変更が入っていますね。当時の事情を知っていそうなkohei さん = [Bug 973171](https://bugzilla.mozilla.org/show_bug.cgi?id=973171) の担当 にも、質問中です。（slack の メッセージで）

**Comment by hmatrjp** [comment]
kuma のソースコード内で該当するCSS の場所は、
https://github.com/mozilla/kuma/tree/master/kuma/static/styles/locales
の ja.sccs だと思います。

**Comment by hmatrjp** [comment]
syntaxbox の中では、em または var で斜体が有効になりました。
外でも有効になるかな？　引き続き
https://bugzilla.mozilla.org/show_bug.cgi?id=1522385
でやりとり進行中です。

**Comment by hmatrjp** [comment]
しばらくこちらを放置して kuma のリポジトリでやりとりしていました。
経緯があって github の kuma の PR 5219 を 5236 に変更しています。
 [Pull Request 5236](https://github.com/mozilla/kuma/pull/5236) がマージされたので、英語ページと同様に、斜体が有効になるはずです。 確認できたら、この Issue を閉じてください。 @mandel59 

bugzilla の 1522385 には、これから報告に行きます。

**Comment by mandel59** [comment]
確認しました。closeします。
