### ISSUE TITLE
SpeechRecognitionAPIのonsoundstartの翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#378]
https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognition/onsoundstart を翻訳します。

**Comment by takaneichinose** [comment]
翻訳は完了しました。ご確認をお願いします。

**Comment by Uemmra3** [comment]
レビューします

**Comment by Uemmra3** [comment]
いいですねー。
見出し部の修正は少し意味をわかりやすくしたつもりです。

あと、タグづけもあわせてお願いします。

**Comment by takaneichinose** [comment]
ありがとうございました。
承知いたしました。
