### ISSUE TITLE
SpeechRecognitionAPIのonsoundendの翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#379]
https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognition/onsoundend を翻訳します。

**Comment by takaneichinose** [comment]
翻訳は完了しました。ご確認をお願いします。

**Comment by Uemmra3** [comment]
レビューします

**Comment by Uemmra3** [comment]
細かいですが、
インターフェイス
が
インターフェス
になってたのも直しました。

https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognition/onsoundend$compare?locale=ja&to=1454752&from=1454748

**Comment by takaneichinose** [comment]
ありがとうございました。
