### ISSUE TITLE
Game Development と配下のドキュメント

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#38]
最近 Web ゲーム開発者向けのドキュメントの拡充が続いています。まだ書きかけだったり技術レビューがされていないドキュメントもあったりして、すべて訳す必要性は全然無いと思いますが、イントロ的な所はあった方が良いかも知れません:

https://developer.mozilla.org/ja/docs/Games
https://developer.mozilla.org/ja/docs/Games/Introduction
https://developer.mozilla.org/ja/docs/Games/Tools

**Comment by Uemmra3** [comment]
おもむろに、Introductionを訳し初めます。

**Comment by dynamis** [comment]
皆さんのおかげで日本語でかなり読めるようになってきました。
ざっくりカテゴリ指定したこの Issue はひとまず close します (今後不足分で重要なモノがあれば個別の記事毎に Issue 立てていきましょう)
