### ISSUE TITLE
 CSS Box Alignmentの翻訳

### ISSUE THREAD

**Issue by applejam9029** [mozilla-japan/translation#383]
https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Box_Alignment

**Comment by applejam9029** [comment]
翻訳完了しました。
Fallback alignment周辺の説明があまり理解できなかったので、レビューの際はその辺りを主に見ていただければと思います。
よろしくお願いします。

**Comment by applejam9029** [comment]
mfuji09 さんという方にレビューとレビュー済み設定をしていただいた形跡があるのですが、こちらに音沙汰がなく心配しています。
この Issue は Close しても問題ないのでしょうか？

**Comment by hmatrjp** [comment]
レビューされた時の修正内容（あれば）を、applejam9029 さんが確認し、問題なければ閉じてください。

翻訳ミートアップで使用する（Google Docsで共有されている） github issue リストを見ずに、MDNのレビュー待ちリストから記事を選んでレビューする方もいます。
Google Docsのリストから、作業終了の方へ移動しておいてくださると助かります。

**Comment by applejam9029** [comment]
丁寧に説明してくださり、ありがとうございます。わかりました。
Google Docs のほうも作業しておきました。
