### ISSUE TITLE
document environmentの翻訳

### ISSUE THREAD

**Issue by mopinfish** [mozilla-japan/translation#385]
https://developer.mozilla.org/ja/docs/Glossary/document_environment を翻訳します。

**Comment by mopinfish** [comment]
翻訳完了いたしました。
XXX Environmentを「XXX環境」と訳すことに若干の違和感がありますので他に良い訳し方があればご指摘いただけたらと思います。
よろしくお願いいたします。

**Comment by Uemmra3** [comment]
レビューしていました。
ドキュメント環境以外の訳語はちょっとすぐには思いつきませんね。。

差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/document_environment$compare?locale=ja&to=1560004&from=1462096
