### ISSUE TITLE
Certifiedの翻訳

### ISSUE THREAD

**Issue by moriyafuto** [mozilla-japan/translation#386]
https://developer.mozilla.org/en-US/docs/Glossary/Certified$translate?tolocale=ja #

**Comment by moriyafuto** [comment]
翻訳が終わったのでレビューお願いします。

**Comment by Uemmra3** [comment]
dskmoriさんがレビュー済みでした。

差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Certified$compare?locale=ja&to=1595714&from=1462119
