### ISSUE TITLE
Netscape Navigator の翻訳

### ISSUE THREAD

**Issue by noriyasu39** [mozilla-japan/translation#388]
https://developer.mozilla.org/ja/docs/Glossary/Netscape_Navigator

**Comment by noriyasu39** [comment]
ご確認の程お願いいたします。

**Comment by hmatrjp** [comment]
Meetup 用の Google Docs に、この Issue の番号も書いておいてください。

**Comment by hmatrjp** [comment]
Google Docs に書かれたこと、確認しました。ありがとうございます。

**Comment by noriyasu39** [comment]
slackも見逃しており、Issueの番号の記入が遅れてしましました。。
お手数をおかけして申し訳ございません。どうぞよろしくお願いいたします。

**Comment by hmatrjp** [comment]
ざっと見ました。直してほしいところが、大きく分けて2種類あります。
・半角と全角の境目（外国人名の前後など）は、半角のスペースをいれてください。
・原文で、{{glossary ... }} マクロを使っているところは、そのままコピーしてください。ページの表示時に、用語集から引いて自動的に翻訳されます。

**Comment by noriyasu39** [comment]
２種類の修正をいたしました。
こちらでいかがでしょうか？
ご確認の程お願いいたします。

**Comment by hmatrjp** [comment]
修正ありがとうございます。
{[glossary }}マクロについては、そのままコピーすると英語になってしまうのですね。。。。表記を日本語に変換する方法がありました。こちらを参考にしてください。
https://developer.mozilla.org/ja/docs/MDN/Contribute/Structures/Macros/Commonly-used_macros

**Comment by hmatrjp** [comment]
dskmori さんが{[glossary }}マクロと、ヘッダタグのidも修正してくださったようです。
Close します。
