### ISSUE TITLE
Digest の翻訳

### ISSUE THREAD

**Issue by mopinfish** [mozilla-japan/translation#389]
https://developer.mozilla.org/ja/docs/Glossary/Digest

**Comment by mopinfish** [comment]
翻訳完了しました。
カタカナ表記の適切さあたりを中心に、内容をレビューいただけたらと思います。
よろしくお願いいたします。

**Comment by Uemmra3** [comment]
レビューしました。
差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Digest$compare?locale=ja&to=1589774&from=1462125

**Comment by Uemmra3** [comment]
閉じておきます。
