### ISSUE TITLE
 transitionendの翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#390]
https://developer.mozilla.org/ja/docs/Web/Events/transitionend を翻訳します。

**Comment by takaneichinose** [comment]
翻訳完了しました。ご確認をお願いします。

**Comment by Uemmra3** [comment]
原文でSumaryが追加されたりしていますが、レビューまで完了しました。
差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Continuous_Media$compare?locale=ja&to=1589768&from=1462150
