### ISSUE TITLE
Continuous_Mediaの翻訳

### ISSUE THREAD

**Issue by moriyafuto** [mozilla-japan/translation#392]
https://developer.mozilla.org/en-US/docs/Glossary/Continuous_Media$translate?tolocale=ja

**Comment by moriyafuto** [comment]
翻訳が終わったのでレビューお願いします。

**Comment by Uemmra3** [comment]
レビュー済みでした。差分をご確認ください。

**Comment by Uemmra3** [comment]
https://wiki.developer.mozilla.org/ja/docs/Glossary/Continuous_Media$compare?locale=ja&to=1589768&from=1462150
