### ISSUE TITLE
How do I use GitHub Pages? の翻訳 

### ISSUE THREAD

**Issue by Suuzuukii** [mozilla-japan/translation#396]
https://developer.mozilla.org/ja/docs/Learn/Common_questions/Using_Github_pages を翻訳します。

**Comment by Suuzuukii** [comment]
こちらの和訳のレヴューをお願いいたします。

**Comment by hmatrjp** [comment]
原文が 3/24 に更新されています。
編集レビューをしようとして編集画面に移行したときに気づきました。
差分を見ると、ほとんどが改行や空白の追加です。追随できそうでしょうか？　@Suuzuukii

**Comment by Uemmra3** [comment]
レビューしました。
差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Learn/Common_questions/Using_Github_pages$compare?locale=ja&to=1589754&from=1462164

**Comment by Uemmra3** [comment]
@hmatrjp が確認されてた空白や改行については、内部のコードの話しなので無視しています、あしからず。

**Comment by hmatrjp** [comment]
空白と改行を、ソースレベルで確認しました。ほとんど追随されてましたが、3箇所くらい手を入れました。
ついでに、誤訳を訂正しました。
しばらく反応がないようですので、close してしまいましょう。何かあったら Reopen してください。
