### ISSUE TITLE
CIA の翻訳

### ISSUE THREAD

**Issue by mopinfish** [mozilla-japan/translation#398]
https://developer.mozilla.org/ja/docs/Glossary/CIA

**Comment by mopinfish** [comment]
翻訳しました。内容のご確認をよろしくお願いいたします。

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
レビューしました。
差分をご確認ください。
https://developer.mozilla.org/ja/docs/Glossary/CIA$compare?locale=ja&to=1562994&from=1462146

**Comment by Uemmra3** [comment]
整理のため、閉じます。

**Comment by hmatrjp** [comment]
一般知識 の節にある Wikipedia へのリンクを、日本語版に合わせて書き換えました。
