### ISSUE TITLE
 Alignment subject の翻訳

### ISSUE THREAD

**Issue by applejam9029** [mozilla-japan/translation#400]
https://developer.mozilla.org/ja/docs/Glossary/Alignment_Subject
翻訳しましたので、レビューをお願いします。

**Comment by Uemmra3** [comment]
レビューしました。
差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Alignment_Subject$compare?locale=ja&to=1595695&from=1454713
