### ISSUE TITLE
 ガターの誤字と思われる箇所を訂正

### ISSUE THREAD

**Issue by applejam9029** [mozilla-japan/translation#401]
https://developer.mozilla.org/ja/docs/Glossary/Gutters
翻訳済み記事ですが、誤字と思われる箇所を訂正しました。ご意見伺いたいです。よろしくお願いします。

**Comment by shuuji3** [comment]
applejam9029 さん、はじめまして。

編集を確認させていただきましたが、適切な編集だと思います。

**Comment by applejam9029** [comment]
shuuji3 さん、初めまして。

確認くださり、ありがとうございます。

作業手順がよくわからずにいるのですが、これでレビューをいただいたものとしてこの issue をクローズして作業終了としてよいのでしょうか？

**Comment by shuuji3** [comment]
はい、ドキュメントの方ではレビュー済に設定したので、クローズしていただいて良いと思います。
