### ISSUE TITLE
 SpeechRecognition.abort()の翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#402]
https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognition/abort を翻訳します

**Comment by takaneichinose** [comment]
翻訳は完了しました。ご確認をお願いします

**Comment by hmatrjp** [comment]
返却という単語を使われている2箇所について。
return の訳は、プログラミング関係では定訳に近いものがあるので、合わせると良いと思います。

・の返却をしません。　→　を返しません。
・構文　の中の　返却　になっている見出し　→　返り値

**Comment by takaneichinose** [comment]
承知しました。
ご確認ありがとうございました。
コメントのように、修正します。

**Comment by hmatrjp** [comment]
return の訳の修正を確認しました。ありがとうございました。
改めて原文と比較したのですが、
from listening to incoming audio の部分がまるまる抜けていませんか？

**Comment by takaneichinose** [comment]
ありがとうございました。
確かに抜けていますね。
それを確認し、新しい文章を考えてみます。

**Comment by takaneichinose** [comment]
文章を修正しました。
ご確認をお願いします。

**Comment by hmatrjp** [comment]
抜けていたところの追加、ありがとうございます。
原文に付いているタグを、日本語版にも追加してください。編集画面では、下の方にあります。

私からは以上ですので、タグ付けが終わったら編集レビューフラグを外して、このIssue も close してもらって構いません。

**Comment by takaneichinose** [comment]
承知しました。
ありがとうございました。

**Comment by hmatrjp** [comment]
タグも付けられているので、閉じます。
