### ISSUE TITLE
 First contentful paintの翻訳

### ISSUE THREAD

**Issue by EriIke** [mozilla-japan/translation#403]
https://developer.mozilla.org/ja/docs/Glossary/First_contentful_paint を翻訳します

**Comment by EriIke** [comment]
翻訳を完了しました。レビューをお願いいたします。

**Comment by Uemmra3** [comment]
今更ですが、レビューしました。
(英文も変わっていましたが…)

差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/First_contentful_paint$compare?locale=ja&to=1595694&from=1485981
