### ISSUE TITLE
 FTU の翻訳

### ISSUE THREAD

**Issue by EriIke** [mozilla-japan/translation#406]
https://developer.mozilla.org/ja/docs/Glossary/FTU を翻訳します。

**Comment by EriIke** [comment]
翻訳を完了しました。レビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
レビューしました。
内容をご確認ください。
https://developer.mozilla.org/ja/docs/Glossary/FTU$compare?locale=ja&to=1562989&from=1485991
