### ISSUE TITLE
Web media technologies の英訳

### ISSUE THREAD

**Issue by Suuzuukii** [mozilla-japan/translation#412]
https://developer.mozilla.org/ja/docs/Web/Media を翻訳します。

**Comment by Suuzuukii** [comment]
英訳完了しました。お手すきの方は、レヴューをお願いいたしいます。

**Comment by Uemmra3** [comment]
レビューしました。
差分をご確認ください。
https://developer.mozilla.org/ja/docs/Web/Media$compare?locale=ja&to=1562992&from=1486054
