### ISSUE TITLE
 SpeechRecognition.serviceURI の翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#414]
https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognition/serviceURI を翻訳します

**Comment by takaneichinose** [comment]
翻訳は完了しました。ご確認お願いします

**Comment by Uemmra3** [comment]
やります

**Comment by Uemmra3** [comment]
レビューしました。
大きく問題なかったです。
https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognition/serviceURI$compare?locale=ja&to=1565065&from=1486029
