### ISSUE TITLE
 SpeechRecognitionResult.isFinal の翻訳

### ISSUE THREAD

**Issue by takaneichinose** [mozilla-japan/translation#415]
https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognitionResult/isFinal を翻訳します

**Comment by takaneichinose** [comment]
翻訳は完了しました。ご確認お願いします

**Comment by Uemmra3** [comment]
やります。

**Comment by Uemmra3** [comment]
レビューしました。差分をご確認ください。
https://developer.mozilla.org/ja/docs/Web/API/SpeechRecognitionResult/isFinal$compare?locale=ja&to=1565069&from=1529177
