### ISSUE TITLE
JavaScript ガイド > 正規表現 の翻訳の更新

### ISSUE THREAD

**Issue by segayuu** [mozilla-japan/translation#416]
割と大規模に渡って変更箇所があるため、本格的な翻訳まで手が回りませんでした。
一応英語版で追記された箇所はそのまま、変更箇所のみ翻訳しております。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by hmatrjp** [comment]
原文の 1535522 の修正を反映 したのと、
特殊文字の使い方 の節の \b と \B の訳に手を入れました。

**Comment by segayuu** [comment]
英語版側が、がっつりと特殊文字リストを別ページに移しました。
対応できるだけ対応。

**Comment by Uemmra3** [comment]
特殊文字のテーブルがトップページに戻ってきてるようですね。
とりあえず英語のまま戻しています。

developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by potappo** [comment]
特殊文字のテーブルは太字じゃなくなっていたりしますが、過去の翻訳を概ねそのまま持って来れそうなので、作業します。アドベントカレンダーのやつなので、本日中完了予定。

**Comment by potappo** [comment]
テーブルがそこそこ手強いので、明日も引き続き作業します。

**Comment by potappo** [comment]
メインページにあった英語部分は日本語に変えました。個別ページは英語版で例が追加されていたりしているので、また続きをやります（今週の空きを埋めました）。

**Comment by potappo** [comment]
個別ページを最新化しましたが、メインページも再び更新する必要があるので、メインページを再更新したら終わりにします。

**Comment by potappo** [comment]
メインページも最新の英語版を反映して更新しましたので、クローズします。なお、境界は言明に統合されましたので、境界の個別ページは言明へリダイレクトされます。
