### ISSUE TITLE
 Explaining basic 3D theoryの翻訳

### ISSUE THREAD

**Issue by smellman** [mozilla-japan/translation#418]
タイトル: 基本の 3D理論の説明

en-US: https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_on_the_web/Basic_theory

**Comment by smellman** [comment]
翻訳終わりました。レビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューしますー

**Comment by Uemmra3** [comment]
レビューしました。
ポイントを点に、
output mergingを出力統合にしてみました。

差分は以下の通り。
https://developer.mozilla.org/ja/docs/Games/Techniques/3D_on_the_web/Basic_theory$compare?locale=ja&to=1565040&from=1555955
