### ISSUE TITLE
font-familyの翻訳

### ISSUE THREAD

**Issue by mzmjp** [mozilla-japan/translation#419]
翻訳します。
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-family$translate?tolocale=ja

**Comment by mzmjp** [comment]
翻訳終わりました。レビューをお願いいたします。

**Comment by Uemmra3** [comment]
やります

**Comment by Uemmra3** [comment]
レビューしました。
Browser Compatibility はブラウザー実装状況で良いかと。
https://developer.mozilla.org/ja/docs/Web/CSS/@font-face/font-family$compare?locale=ja&to=1565064&from=1555887

**Comment by mzmjp** [comment]
レビュー、ありがとうございました！
