### ISSUE TITLE
 WebGL by exampleの翻訳

### ISSUE THREAD

**Issue by naotaro0123** [mozilla-japan/translation#421]
翻訳します
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example

**Comment by naotaro0123** [comment]
翻訳が終わりましたので、レビューお願いします
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example$translate?tolocale=ja

**Comment by Uemmra3** [comment]
やります

**Comment by Uemmra3** [comment]
レビューしました。
差分を見ていただければわかりますが、MDN内のリンクを"en-US"から"ja"に変更お願いします。
単純作業なので、ユーザースクリプトもあります。
https://developer.mozilla.org/ja/docs/Web/API/WebGL_API/By_example$compare?locale=ja&to=1565050&from=1555944
