### ISSUE TITLE
inputmodeの翻訳

### ISSUE THREAD

**Issue by daichan5891** [mozilla-japan/translation#423]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
翻訳します。

**Comment by daichan5891** [comment]
翻訳が終了しました。

**Comment by hmatrjp** [comment]
編集画面の下部にある 日本語のタグ　に、原文からのタグをすべて入れてください。
それができたら、翻訳中 フラグは降ろしてもらって構いません。

文に少し手を入れています。
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/inputmode$history

**Comment by daichan5891** [comment]
遅くなり、申し訳ありません。
タグを追加しました。

https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/inputmode

**Comment by hmatrjp** [comment]
ありがとうございます。 @daichan5891 
編集レビューを済ませました。
何箇所か手を入れてますので、問題なければこのIssue を Close してください。
https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/inputmode$history

なぜ変更したのかの疑問点などあれば、お知らせください。

**Comment by daichan5891** [comment]
確認いたしました。
特に問題ありません。
ありがとうございます！
