### ISSUE TITLE
TTLの翻訳

### ISSUE THREAD

**Issue by takeokunn** [mozilla-japan/translation#424]
翻訳します
https://developer.mozilla.org/ja/docs/Glossary/TTL

**Comment by takeokunn** [comment]
翻訳が終わりましたので、レビューお願いします!!!
https://developer.mozilla.org/ja/docs/Glossary/TTL

**Comment by Uemmra3** [comment]
レビューしました。
roamはローミングではなく、行き来する、くらいの意味だと思います。
https://eow.alc.co.jp/search?q=roam&ref=wl

ほか、差分を確認いただき、問題なければこのIssueを閉じちゃってください。
https://developer.mozilla.org/ja/docs/Glossary/TTL$compare?locale=ja&to=1560008&from=1555941

**Comment by hmatrjp** [comment]
言い回しに気になるところがあったので、一部の順番の入れ替えなどしました。

**Comment by potappo** [comment]
詳細情報の on の翻訳が統一されてなかったので、「～の」で統一するように修正しました。
https://wiki.developer.mozilla.org/ja/docs/Glossary/TTL$compare?locale=ja&to=1649057&from=1560521
他、問題ありませんでしたので、クローズします。
