### ISSUE TITLE
Robots.txtの翻訳

### ISSUE THREAD

**Issue by yoko0827** [mozilla-japan/translation#425]
翻訳します。
https://developer.mozilla.org/ja/docs/Glossary/Robots.txt$translate

**Comment by yoko0827** [comment]
翻訳が終わりましたので、レビューお願いします!
https://developer.mozilla.org/ja/docs/Glossary/Robots.txt$translate

**Comment by hmatrjp** [comment]
レビューしました。
よければこのIssueを Close してください。
文の順序を入れ替えた部分があります。
https://developer.mozilla.org/ja/docs/Glossary/Robots.txt$history

**Comment by Uemmra3** [comment]
多少文言を変えたのと、英語版の更新を反映してます。
@yoko0827 ご確認ください。

**Comment by yoko0827** [comment]
確認いただきありがとうございます。このIssueをCloseします。
