### ISSUE TITLE
VoIP の翻訳

### ISSUE THREAD

**Issue by fuekuma** [mozilla-japan/translation#426]
https://developer.mozilla.org/en-US/docs/Glossary/VoIP を翻訳します。

**Comment by fuekuma** [comment]
翻訳は完了しました。ご確認をお願いします。

**Comment by Uemmra3** [comment]
レビューします

**Comment by Uemmra3** [comment]
多少本文を整理しました。差分をご確認ください。
https://developer.mozilla.org/ja/docs/Glossary/VoIP$compare?locale=ja&to=1562986&from=1555932
