### ISSUE TITLE
Anatomy of an extensionの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#427]
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension

**Comment by kenji-yamasaki** [comment]
翻訳を完了しましたので、レビューをお願いいたします。

**Comment by Uemmra3** [comment]
少しずつレビューしています。なんか重複部分があって削りました。
TranslationHelperの↑↓スクロール機能が便利ですよ。(少しアピってみた)

**Comment by Uemmra3** [comment]
レビューの続きをします。

**Comment by Uemmra3** [comment]
とりあえず山崎さんの修正部分は確認できました。
