### ISSUE TITLE
max-heightの翻訳

### ISSUE THREAD

**Issue by mzmjp** [mozilla-japan/translation#428]
翻訳します。
https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/max-height

**Comment by mzmjp** [comment]
翻訳終わりました。レビューをお願いいたします。

**Comment by Uemmra3** [comment]
やります。

**Comment by Uemmra3** [comment]
レビューしました。
基本的なことですが、タグはとりあえず英語と同じものをつけておいてください。

差分も見ておいてください。
https://developer.mozilla.org/ja/docs/Web/CSS/@viewport/max-height$compare?locale=ja&to=1565044&from=1555933

**Comment by mzmjp** [comment]
レビュー、ありがとうございました！
タグの件、失礼いたしました。気をつけるようにいたします。
