### ISSUE TITLE
What HTML features promote accessibility?の翻訳

### ISSUE THREAD

**Issue by mzmjp** [mozilla-japan/translation#429]
翻訳します。
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/HTML_features_for_accessibility

**Comment by mzmjp** [comment]
翻訳終わりました。レビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューします

**Comment by Uemmra3** [comment]
ざっとレビューしました。
・可能ならタイトルも翻訳してみてください
・タグが最下部にあるんですが、とりあえず英語のものと同じものをつけてみてください
詳細は差分をご覧ください。
https://developer.mozilla.org/ja/docs/Learn/Common_questions/HTML_features_for_accessibility$compare?locale=ja&to=1562984&from=1555956

**Comment by mzmjp** [comment]
@Uemmra3 
レビューおよびご修正、ありがとうございました！
