### ISSUE TITLE
[2014年末ぐらい] FirefoxOSアプリ開発に必要なドキュメント整備

### ISSUE THREAD

**Issue by mantaroh** [mozilla-japan/translation#43]
* 12月末あたりから、FirefoxOS開発者向けに必要と思われるApps以下のドキュメントの参照が増えると思われます。
* DocFest 2014 Win で以下のドキュメントの翻訳を進めていきたいと思います。

### MDNの以下で翻訳が必要と思われるドキュメント
* https://docs.google.com/spreadsheets/d/1eLxr_YVWFDQtF4fl32ZDEsGkJjDrF7606KS-sjF27qo/edit?usp=sharing

**Comment by dynamis** [comment]
古くなってるので close
