### ISSUE TITLE
Browser_compatibility_for_manifest.jsonの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#430]
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json

**Comment by kenji-yamasaki** [comment]
翻訳を終えましたのでレビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューします

**Comment by Uemmra3** [comment]
OKでしょう。
