### ISSUE TITLE
WebSocketの翻訳

### ISSUE THREAD

**Issue by takeokunn** [mozilla-japan/translation#432]
翻訳します
https://developer.mozilla.org/en-US/docs/Glossary/WebSockets

**Comment by takeokunn** [comment]
レビューお願いします!!
https://developer.mozilla.org/ja/docs/Glossary/WebSockets

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
dskmoriさんがされてました。差分を確認してみてください。

https://developer.mozilla.org/ja/docs/Glossary/WebSockets$compare?locale=ja&to=1560006&from=1555948
