### ISSUE TITLE
Intrinsic Size の翻訳

### ISSUE THREAD

**Issue by dummy11022** [mozilla-japan/translation#434]
https://developer.mozilla.org/ja/docs/Glossary/Intrinsic_Size を翻訳します。

**Comment by dummy11022** [comment]
翻訳を完了したのでレビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューします

**Comment by Uemmra3** [comment]
細かい言い回しを変えました。
差分をご確認ください。
https://developer.mozilla.org/ja/docs/Glossary/Intrinsic_Size$compare?locale=ja&to=1565062&from=1565052
