### ISSUE TITLE
JavaScriptの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#435]
https://developer.mozilla.org/ja/docs/Web/JavaScript

**Comment by hmatrjp** [comment]
JavaScript の階層のトップですね。
もし続けて下位のページにも手を出す場合には、 #336 に登録がある可能性があるので、一度見てみてください。

**Comment by kenji-yamasaki** [comment]
改装トップの翻訳は完了しました。レビューをお願いいたします。
引き続いては、下位ページから作業対象を探すことにします。

**Comment by hmatrjp** [comment]
階層トップ、これから見ます。

**Comment by hmatrjp** [comment]
レビューしました。
いくつか、文言をところがあります。
https://developer.mozilla.org/ja/docs/Web/JavaScript$compare?locale=ja&to=1565036&from=1565033

文と宣言　の節は、原文と中身の順序を合わせました。
問題なければ、 Close してください。

**Comment by hmatrjp** [comment]
追加： 先頭の方に Wikipedia へのリンクが1つあって、もしかすると日本語版にも同じ解説があるかもしれないので、確認してみてください。

**Comment by kenji-yamasaki** [comment]
日本語版に同じ解説を見つけたのでその点を修正しました。
他は問題ありません。

**Comment by hmatrjp** [comment]
ありがとうございます。これで良いと思いますので、閉じておきます。
