### ISSUE TITLE
Using Promisesの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#436]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Using_promises

**Comment by kenji-yamasaki** [comment]
翻訳を完了したのでレビューをお願いいたします。

**Comment by Uemmra3** [comment]
レビューしてみます。

**Comment by Uemmra3** [comment]
レビュー完了。差分はMDN Translation Helperが直した(推奨レベル)ものばかりで、基本的にはコード1行の修正なので問題ないです。
