### ISSUE TITLE
SMTPの翻訳

### ISSUE THREAD

**Issue by succi0303** [mozilla-japan/translation#438]
https://developer.mozilla.org/ja/docs/Glossary/SMTP

**Comment by succi0303** [comment]
翻訳終わりました。レビューをお願いします。

気になった点を以下に記載します。

1. POP3、NNTPのMDN内リンクは日本語ページが存在しないため、英語ページへのリンクのままにしています。また、原文のリンク先が誤っており(/POP3が正しいところ、en/POP3になっている）、訳文では正しい英語ページへリンクさせました。
2. 外部(Wikipedia)へのリンクは英語版Wikipediaへのリンクのままにしています。NTLMは日本語版ページが存在するのでリンク先を変更するか迷いました。
3. 「(例、サーバがあるメカニズムを〜）」が原文の意味を正しく理解できているか自信がありません。

初翻訳で表記、文体等も怪しいかと思います。お手数ですがよろしくお願いします。

**Comment by Uemmra3** [comment]
長そう？だけどレビューしてみます。

**Comment by Uemmra3** [comment]
https://docs.google.com/document/d/16cKB9t8Deiv0emx01jvy1TJPIFQrqd-EUxZMRUvhlj0/edit#
↑これにも記入してもらえますか？

**Comment by succi0303** [comment]
記入しました。長くないです！

**Comment by Uemmra3** [comment]
1. 原文のリンクも直しておきました。(英語ロケールもen-USとかのハズ)
2. NTLMは日本語にした方が親切かもしれませんが、とりあえず英語のままでも良いでしょう
3. 少し整理しました。claimは要求するという動詞かと思います。
https://eow.alc.co.jp/search?q=claim

**Comment by Uemmra3** [comment]
差分もご確認ください。
https://developer.mozilla.org/ja/docs/Glossary/SMTP$compare?locale=ja&to=1565074&from=1565068
ステートマシンの方が一般的に通りやすいです。

**Comment by hmatrjp** [comment]
上の2.NTLM  は、せっかく日本語版があるので、日本語版に向けておきました。

**Comment by succi0303** [comment]
承知しました。ありがとうございます。
