### ISSUE TITLE
NNTPの翻訳

### ISSUE THREAD

**Issue by succi0303** [mozilla-japan/translation#439]
https://developer.mozilla.org/ja/docs/Glossary/NNTP

**Comment by succi0303** [comment]
翻訳終わりました。レビューお願いします。
非常に小さい、1文の訳です。

**Comment by Uemmra3** [comment]
やってみます

**Comment by Uemmra3** [comment]
確認しました。レガシーでよく知りませんが。。

あと、こまめに保存されていますが、
自動保存されていますのでそんなに心配しなくてもいいかも。
流儀なんで強制ではないですが、保存時にリビジョンコメントを入れると後で理解しやすいです。
https://developer.mozilla.org/ja/docs/Glossary/NNTP$history

**Comment by succi0303** [comment]
レビューありがとうございます。
自動保存されるんですね。公開ページでプレビューする目的で都度保存していました。編集画面のリッチテキストの見た目のまま公開される感じがわかったので次から無闇に保存しないかなと思います。
リビジョンコメント了解しました。
