### ISSUE TITLE
CSS Object Model (CSSOM)の翻訳

### ISSUE THREAD

**Issue by succi0303** [mozilla-japan/translation#442]
https://developer.mozilla.org/en-US/docs/Glossary/CSSOM を翻訳します。

**Comment by succi0303** [comment]
翻訳終わりました。
1文目のmapはなんとなく意訳しました。CSSOM APIの2文目 "It is much like the DOM, but for the CSS rather than the HTML. "の訳が正しいのか自信がありません。

**Comment by Uemmra3** [comment]
レビューしました。
中身はいいと思います。

差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/CSSOM$compare?locale=ja&to=1595713&from=1587469
