### ISSUE TITLE
WebKitの翻訳

### ISSUE THREAD

**Issue by liveasnotes** [mozilla-japan/translation#443]
https://developer.mozilla.org/ja/docs/Glossary/WebKit

**Comment by liveasnotes** [comment]
翻訳を公開しました。
表記方法などこれで大丈夫でしょうか？レビューお願いします。

**Comment by Uemmra3** [comment]
dskmoriさんがレビューされていました。
https://wiki.developer.mozilla.org/ja/docs/Glossary/WebKit$compare?locale=ja&to=1587516&from=1587453
差分をご確認の上、Issueを閉じてください。
