### ISSUE TITLE
A basic ray-casterの翻訳

### ISSUE THREAD

**Issue by horitaku1124** [mozilla-japan/translation#444]

**Comment by horitaku1124** [comment]
翻訳できました。
https://wiki.developer.mozilla.org/ja/docs/Web/API/Canvas_API/A_basic_ray-caster

**Comment by Uemmra3** [comment]
レビューしてみます。

**Comment by Uemmra3** [comment]
ざっとレビューしました。差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Web/API/Canvas_API/A_basic_ray-caster$compare?locale=ja&to=1588259&from=1587468

**Comment by horitaku1124** [comment]
レビューありがとうございます。
