### ISSUE TITLE
CSS pixelの翻訳

### ISSUE THREAD

**Issue by liveasnotes** [mozilla-japan/translation#445]
翻訳を始めます。
https://developer.mozilla.org/ja/docs/Glossary/CSS_pixel

**Comment by liveasnotes** [comment]
翻訳を公開しました

- `strain, but is otherwise as small as possible` は「but is 」のニュアンスが分からなかったので省いています。
- `located an arm's length away from the viewer's eyes.` は「locate」の位置を特定するという意味をベースに訳しました。
- `desktop` は具体的に何を指しているのか分からなかったので「デスクトップ」のままにしました。
- `the goal is to try to have the distance` は、「値が得られる」という方向で意訳しました。
- 見出し `Learn more` を「もっと学ぶ」と直訳してみました（ビギナー向けにはこの表記が適しているように感じます）。
- 見出し `Learn about it` は、見出し「Technical reference」の品詞：名詞に揃え、「関連知識」と意訳しました。

**Comment by Uemmra3** [comment]
レビューします

**Comment by Uemmra3** [comment]
- `strain, but is otherwise as small as possible` の前後は日本語としてわかりやすい表現に変更しました
- `desktop` は `desktop computer` の省略かと思います(https://eow.alc.co.jp/search?q=desktop)。
- 見出しに関しては、とりいそぎ他の記事で採用している定訳に合わせました。…が議論の余地ある気がします。
- `and an element is placed on the screen with a width of 96px` これもifの中に入る内容です。

**Comment by Uemmra3** [comment]
差分をご覧ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/CSS_pixel$compare?locale=ja&to=1588618&from=1587466

原文を見てみましたが、「技術レビュー」「編集レビュー」要になっていましたね。
分かりやすくない文章なので、原文が改良されてから見直してみるとわかるかもしれません。
