### ISSUE TITLE
Parseの翻訳

### ISSUE THREAD

**Issue by succi0303** [mozilla-japan/translation#446]
https://wiki.developer.mozilla.org/ja/docs/Glossary/Parse を翻訳します。

**Comment by succi0303** [comment]
翻訳を完了しました。レビューをお願いします。

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
編集レビューしました。差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Parse$compare?locale=ja&to=1588257&from=1587463
特に最終段については、かんじんな解析(Parse)のとこが抜けてしまっていたように思いますので追加しました。
問題なければIssueを閉じていただければと思います。

**Comment by succi0303** [comment]
確認しました。内容了解です。ありがとうございました。
