### ISSUE TITLE
Drawing shapes with canvasのサンプルコードの修正

### ISSUE THREAD

**Issue by horitaku1124** [mozilla-japan/translation#449]
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes

**Comment by horitaku1124** [comment]
サンプルコードの修正と一部表記の修正を行いました。

**Comment by hmatrjp** [comment]
円弧の節の途中までレビューしました。一部、訳文の修正をしました。

**Comment by hmatrjp** [comment]
翌月への持ち越しとなりましたが、続けて作業します(3/20のMDN翻訳ミートアップにて)

**Comment by hmatrjp** [comment]
レビュー終わりました。少しだけ訳文を編集しています。
確認していただき、良くないところは戻すなりして、 Close してください。 @horitaku1124

**Comment by horitaku1124** [comment]
レビューありがとうございます。
