### ISSUE TITLE
Media (CSS) の翻訳

### ISSUE THREAD

**Issue by liveasnotes** [mozilla-japan/translation#450]
https://developer.mozilla.org/ja/docs/Glossary/Media/CSS

**Comment by liveasnotes** [comment]
公開しました
- `term media refers to the destination to which the document is to be drawn`...「destination」を「出力先」として翻訳しました。
- 「レンダリングエンジン」へのリンクはあの表記で良いでしょうか？
- `CSS supports a variety of ~ or other values.` の木構造の解釈は合っているでしょうか？
- `test the window against a media query`はよく分からなかったので、直訳しました。

**Comment by hmatrjp** [comment]
編集レビュー。Learn more の訳だけ変更、あとはよいと思います。
3点目の　木構造の解釈　がどこに該当するのかわからなかったです。

**Comment by liveasnotes** [comment]
> 3点目の　木構造の解釈　がどこに該当するのかわからなかったです。

前回のものなのでうろ覚えですが、たぶん書いた「文章そのもの」の木構造を指していたんだと思います。
内容には問題がないようなので close しておきます
