### ISSUE TITLE
 Populating the page: how browsers workの翻訳

### ISSUE THREAD

**Issue by succi0303** [mozilla-japan/translation#451]
https://wiki.developer.mozilla.org/en-US/docs/Learn/Performance/Populating_the_page:_how_browsers_work#Navigation

**Comment by Uemmra3** [comment]
長い記事ですが、もう少し頑張ってみてください。

**Comment by succi0303** [comment]
翻訳終わりました！レビューをお願いします。

**Comment by hmatrjp** [comment]
長文の翻訳お疲れ様でした。あと一息！
1) タイトルも日本語にしましょう。
　編集画面上部の　翻訳についての説明　の中にあります。
2) 1) ができたら、同画面下部にある翻訳作業中フラグ（　翻訳途中 - まだ翻訳が完了していない　のチェックボックス）は降ろしてください。

**Comment by succi0303** [comment]
タイトルの日本語化と翻訳作業中フラグOFFしました:-)

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
レビューしました。長いページの翻訳お疲れ様でした！

差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Web/Performance/How_browsers_work$compare?locale=ja&to=1625223&from=1620528

冒頭の「読み込みが速い」「スムーズにインタラクションできる」は「contents」にかかっていると思いますのでそのように修正しました。
元々の解釈の「読み込みが速いコンテンツ」と「スムーズにインタラクションできる」「ウェブ体験」ならば、形容詞のsmoothではなくて名詞のsmoothnessとかになるのではないでしょうか？
あと dskmori さんが直してらっしゃるようですが、MDN内の日本語リンクはja-JPでなくjaなのでご注意下さい。
細かいですが、14kbはキロビットのように見えるので14kBにしました。

内容に問題なければIssue閉じちゃってくださいね。

**Comment by succi0303** [comment]
差分確認しました。文章の変更部分について了解です🙌
書き方の面では、数字は英単語と同じで半角で前後にスペース入れるのですね。H3などヘッダタグのid属性は特に意識していなかったですが、おそらくWYSYWIGで編集すると見た目の文字がそのままid属性に設定されるイメージでしょうか。次回からソースコード表示で属性値を確認します。

長文のレビューありがとうございました😊
