### ISSUE TITLE
WebAssembly.Global の翻訳

### ISSUE THREAD

**Issue by horitaku1124** [mozilla-japan/translation#452]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Global

**Comment by horitaku1124** [comment]
翻訳終わりました。レビューお願いします。

**Comment by Uemmra3** [comment]
レビューしました。差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Global$compare?locale=ja&to=1591450&from=1589015

**Comment by horitaku1124** [comment]
ありがとうございます。差分確認いたしました。

**Comment by Uemmra3** [comment]
閉じます
