### ISSUE TITLE
CSS selectors （CSS セレクター）

### ISSUE THREAD

**Issue by snakada** [mozilla-japan/translation#453]
en-US: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors
ja: https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/Selectors
（ゆっくりやる予定です）

**Comment by snakada** [comment]
おわりました。原文が直訳しちゃうとやや理解しづらい内容になりそうだったので、割と意訳する結果となりました。おおむね内容は問題ないと思うのですが、もし、おかしなところあればご指摘いただけますと幸いです。翻訳途中フラグは外しました。数日くらい立ったら、この issue はクローズしようかと思ってます。

**Comment by hmatrjp** [comment]
翻訳ありがとうございます。
タグについてお願いです。原文のタグを一部、落とされています（Learn → 学習 など）が、訳前のタグも付けておいてください。
タグはページ下部でリンクになるため、関連ページが漏れないよう（日本語ページでは）原文にあるタグはすべてコピーする運用としています。Learn と 学習 が両方付くのはOKです。

訳文自体はほとんど問題ないと思いました。少しだけ手を入れました。
（編集レビューフラグを残したのは、上のタグの件です。）

**Comment by snakada** [comment]
おっと失礼しました。うっかりしておりました汗
ひとまずすべて en-US 版に揃えるかたちで修正しました。
TranslationHelper 便利！😃

念の為に、これから私が過去に翻訳したものもどうかチェックしてきます〜。
ご指摘に感謝します、今後も微力を尽くしてまいります。

**Comment by hmatrjp** [comment]
ありがとうございました。
・タグが修正されていることを確認しました。
・編集レビューフラグを降ろしました。
このIssue も Close しておきますので、必要でしたら ReOpen してください。
