### ISSUE TITLE
Pseudo-element の翻訳

### ISSUE THREAD

**Issue by liveasnotes** [mozilla-japan/translation#455]
https://developer.mozilla.org/ja/docs/Glossary/Pseudo-element

**Comment by hmatrjp** [comment]
Incomplete フラグが立っていますが、ひととおり訳し終わっているようですのでレビューします。

**Comment by hmatrjp** [comment]
少しだけ修正し、分類用のタグを補いました。 Close します。
何かあれば Reopen してください。

**Comment by hmatrjp** [comment]
ヘッダタグ h2, h3 内の id属性を英語に戻しました。このため、name 属性も追加しました。
