### ISSUE TITLE
Firefox developer release notes の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#456]
https://wiki.developer.mozilla.org/ja/docs/Mozilla/Firefox/Releases

**Comment by kenji-yamasaki** [comment]
軽微な修正作業を行いました。レビューをお願いいたします。

**Comment by hmatrjp** [comment]
id をオリジナルに最修正。

idタグの内容を、英語に直す、という編集意図だったと思います。
name タグを合わせて指定しないと、id タグの内容が、<h2>の内容の日本語に引きずられます。
（山﨑さんの保存したリビジョンと最新を比較してみてください @kenji-yamasaki ）

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
内容確認いたしました。Closeしていただければと思います。

**Comment by hmatrjp** [comment]
確認ありがとうございます。閉じます。
