### ISSUE TITLE
-moz-stack-sizing の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#459]
https://wiki.developer.mozilla.org/ja/docs/Web/CSS/-moz-stack-sizing

**Comment by kenji-yamasaki** [comment]
翻訳を終えましたので、レビューをお願いいたします。

**Comment by hmatrjp** [comment]
翻訳ありがとうございます。
・文中、2箇所手を入れました。
・原文にある CSS 〜 XUL の6つのタグを、日本語訳にもそのままコピーしてください。編集レビューフラグを降ろしていないのはそのためです。

**Comment by kenji-yamasaki** [comment]
レビュー指摘の反映と小修正を行いましたので、ご確認お願いいたします。

**Comment by hmatrjp** [comment]
ありがとうございます。
変更箇所を確認しました。
編集レビューフラグを降ろしました。
この Issue を Close しておきます。何かあったら、Reopen してください。
