### ISSUE TITLE
 Slotable

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#461]
https://wiki.developer.mozilla.org/ja/docs/Web/API/Slotable
こちらを翻訳します

**Comment by gurezo** [comment]
本チケットのページのレビューをお願いします。

**Comment by Uemmra3** [comment]
はーい

**Comment by Uemmra3** [comment]
ほぼほぼいいと思いますが、タグがなかったです。

TranslationHelperというTampermonkey用スクリプトで自動でつけられるので、使ってみてください。
https://github.com/mozilla-japan/translation/tree/master/MDN

差分はこちらです。確認したらIssue閉じてください。
https://wiki.developer.mozilla.org/ja/docs/Web/API/Slotable$compare?locale=ja&to=1596715&from=1596706

**Comment by gurezo** [comment]
確認したので、close
