### ISSUE TITLE
スタイルガイドを更新して最新版を mozilla-l10n/styleguides に反映させる

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/translation#463]
Pontoon の [スタイルガイド](https://mozilla-l10n.github.io/styleguides/ja/) からリンクされている表記ガイドラインと L10n ガイドラインを更新したい。

mozilla-l10n 日本語スタイルガイドのリポジトリー
https://github.com/mozilla-l10n/styleguides/tree/master/docs/ja

↓これを↑へ
- [表記ガイドライン](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline)
- [L10n ガイドライン](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline)

**Comment by marsf** [comment]
とりあえず、自分のところにフォークした。
https://github.com/marsf/styleguides

**Comment by marsf** [comment]
表記ガイドラインには、現時点で検討事項が 3 個ある。

* ダッシュ記号 の使い分けにも注意が必要。
    使い分けについて、**現状統一ルールがないので今後改善が必要**。
* 「こと」「もの」「とき」「ところ」「まえ」「あと」「なか」について、特定の時刻や場所など、実質的な事柄は漢字にする。
    例文: (TBD)　**←例文を追加する必要あり**
* 読みづらい漢字は適宜ひらがなにする。
    ただし、**現状統一ルールがないので今後改善が必要** (「記者ハンドブック」準拠で良いか？)。

**Comment by marsf** [comment]
> * ダッシュ記号 の使い分けにも注意が必要。
>   使い分けについて、**現状統一ルールがないので今後改善が必要**。

『共同通信 記者ハンドブック 第13版』から調べてみました。

P.119【その他の符号】より
> ２ 「―」は、説明や間をもたせるときや追い込み箇条書きの切れ目、「AからBまで」「A対B」、一問一答の問いの代わりに用いる。

この「追い込み箇条書き」の詳しい内容　P.498【箇条書き】より
> 文中に箇条書きのある場合は①②…を使って追い込みにし、最後は「―」（長棒）で受ける。
> 〔例〕〇〇首相は〇日、当面の政治課題について①景気の本格回復②金融システムの信頼回復③日米関係の再構築―を挙げた。


P.119【その他の符号】より
> ５「～」は数字の範囲を表すのに用いる。

P.544　２(1)より（一部省略）
> 数字の範囲を表すには「～」を使う。「１」と紛らわしいので「―（長棒）」は使わない。
> 〔注〕数字を含まない「月―土曜」などは「―（長棒）」。

**Comment by marsf** [comment]
「A対B」は、試合の得点で使われています。
[楽3―4西（18日）　西武が逆転勝ち｜共同通信](https://this.kiji.is/657134555188266081)

この「―（長棒）」は U+2015 (HORIZONTAL BAR) でした。

**Comment by marsf** [comment]
Microsoft の日本語スタイルガイド (February, 2019) では、

P.24 "3.1.12 Punctuation" より
> #### Em dash
> 
> The em dash should only be used to emphasize an isolated element or introduce an element that’s not essential to the meaning conveyed by the sentence.
> 
> In Japanese, don’t use it unless necessary.
> 
> #### Wave dash
> 
> It’s known that full-width wave dash (～) often causes build errors in software localization. The symbol may be used when referring to numeric range except for copyright notice, but it must be replaced with a word “から” or half-width hyphen in this case.

**Comment by marsf** [comment]
『JTF日本語標準スタイルガイド 第3.0版』では、

> 3.2.9 ダッシュ（―）
> 原則として和文ではダッシュ（―）を使用しません。

**Comment by marsf** [comment]
どちらも必要でない限り使わない方針らしい。

使わないのも勿体ないし、日本語の文章で制限する必然性もないので、記者ハンドブックからいくつか採用したい。

- ダッシュは「―」(U+2015 長棒) と「～」 (U+FF5E 全角チルダ) を使用する。
  - 「―」は説明や間をもたせるときや追い込み箇条書きの切れ目に用いる。
  - 「～」は数字の範囲を表すのに用いる。 
  - 「—」(U+2014 EM DASH) は原文の表記に合わせて使用してもよい。
  - 「〜」(U+301C 波ダッシュ) は使用しない。

という感じでいかがでしょうか。

**Comment by marsf** [comment]
全角チルダ問題 @tsuda_ahr LTDD#5 2014/7/5 2014/7/7 改訂2版 
https://www.slideshare.net/tsudaa/ss-36658329
> 25. ところで 全角チルダのコードですが、 U+FF5E って、やけに後ろのほうだと思いません？
> 26. こういうわけです。
> 27. 半角形／全角形 • 互換用の領域。 • 互換文字とは、既存の文字コードとの互換性と往復変換のためだけに 収録された文字 • ユニコードコンソーシアムは、互換文字は使わないことを推奨 つまり、この領域の文字は使わないほうがよいです。 （極力使わないでください）

**Comment by marsf** [comment]
ついでに、このスライドからリンクされてたページ。

日本語における長音符の起源
https://www.shochian.com/cho'onpu.htm
> 　（3） はっきりと、長音の意味で「ー」を使ったと認められる最初の人は、新井白石で、イタリア人宣教師のシドッチを取り調 べて まと めた「西洋紀聞」（1715年頃）に登場する。「シローテ」（シドッチのこと）、「ローマン」などで使われている。
> 
> 　（3）は右の直筆の画像を見てもらえばわ かる が、現在のように行の真 ん中ではなく、やや右よりに書かれていることに注目すべきである。実は、白石は別の文献（ヨハンバツテイスタ物語）では「アリツテメ引テイカ」（算術）、 「レト引リ カ」（修辞学）といった風に「引」の漢字を長音記号とした表記を使っている。（原文縦書き）　この「引」の字は、上記の古事記などでの「音引」という注釈 の「音」の字が省略されたものらしい。さらにその「引」の字の篇（へん）を省略して、旁（つくり）の部分だけ にしたのが 長音符だ、ということらしい。日本語のカタカナは漢字の篇や旁の一部を取ってきて作られたものが多い。（例：伊→イ）長音符もこれと同じで、成立起 源から見るとカタカナの一種であると言える。

**Comment by marsf** [comment]
波ダッシュ・全角チルダ記号のまとめ。
※現在は解決している Unicode での字形の違いは取り上げません。

- Shift JIS の全角文字コード 8160 に定義されている「〜」は「波ダッシュ」。
  - JIS X 0208:1997 附属書 4 表 2 より
  > 区点1-33　～　波ダッシュ WAVE DASH
  - JIS X 0213:2000 附属書 7 (参考) 面区点位置詳説より
  > 1.3.2 ダイアクリティカルマーク a) 1-2-18 ~ TILDE, チルド
  この図形文字は，この規格の国際規格との整合性を高めるため，ISO/IEC 646 IRV の TILDE に対応するものとして，追加している。JIS X 0208は，この図形文字に類似した，〜 (1-3-33，WAVE DASH，波ダッシュ) を規定し，また，この規格では，ダイアクリティカルマーク (合成可能) で，別に ...中略... を規定しているので，これらの図形文字の区別に注意する必要がある。
  - Unicode では「〜」(U+301C、波ダッシュ) に相当する。
- 日本語で、数字などの範囲を示す用途には「波ダッシュ」を使う。（文字コードではなく、波ダッシュと呼ばれる文字）
  - そもそも、日本語には「全角チルダ」を使う用途が存在しない？


- Windows の MS-IME では、日本語キーボードの Shift + ^ で、波ダッシュと同じ字形の「～」 (U+FF5E、全角チルダ) が入力されてしまう。
  - ATOK、Google 日本語入力など、Windows 用のほとんどの IME でも「～」 (U+FF5E、全角チルダ) が入力される？（要確認）
  - 単純に、半角チルダに対応する全角文字として、全角チルダが入力されていると取ることもできる。
- macOS では、日本語キーボードの Shift + ^ で波ダッシュが入力される。
- 「から」の読みで変換すると、MS-IME の場合、「～ [全]」全角チルダと「〜 [環境依存]」波ダッシュの二つの候補が表示される。

**Comment by marsf** [comment]
ガイドラインの参考にしている共同通信社の場合、
- 『共同通信 記者ハンドブック』は印刷物なので、どちらの文字コードを使用しているかは不明。
- 共同通信社のウェブサイトでは、「～」 (U+FF5E、全角チルダ) が使われている。
https://this.kiji.is/664736330252076129
  > 7月には21～25年度の復興費を ...

**Comment by marsf** [comment]
またまたついでに、JIS X 0213:2000 附属書 7 の続きに書いてあった。

> 1.3.13 この規格で追加したけい線素片
> この規格では，JIS X 0208で規定した罫線素片に，**歯科用記号**を典拠とする15種類の罫線素片を追加している。これらのけい線素片は，歯科医療の分野で歯種や歯式図を表記するために、 ...

全角文字の罫線って歯科用記号だったんだ。

**Comment by marsf** [comment]
JIS X 0213:2000 で定義されている "DASH" 記号は以下の 3 文字だけ。
— (1-1-29, EM DASH)、〜 (1-1-33, WAVE DASH)、– (1-3-92, EN DASH)

他に、罫線素片の ─ (1-8-1BOX DRAWINGS LIGHT HORIZONTAL), ━ (1-8-12 BOX DRAWINGS HEAVY HORIZONTAL) はあるが、― (HORIZONTAL BAR) は定義されていない。

**Comment by marsf** [comment]
二分ダーシ - JAGAT https://www.jagat.or.jp/past_archives/content/view/3554.html
> JIS X 0213では、“–”の日本語名称として“二分ダーシ”と“ダッシュ（二分）”を掲げている。英語名称は“en dash”なので、二分ダッシュ（半角ダッシュ）などとも呼ばれている。
> 二分ダーシの代表的な用例は、年号やページ数などの範囲を示す場合である。23–36ページや1998–2012年のようになる。 

二分ダーシのハイフンとの混用
> JIS X 0208の文字集合に二分ダーシが含まれていなかったので、ハイフンに比べると二分ダーシの入力は簡単ではなかった（JIS X 0213では、その文字集合に追加された）。
> 
> そのため、ハイフンと二分ダーシは混用され、市販の本でも二分ダーシの使用が望ましい箇所にハイフンを用いた例をよく目にした。

二分ダーシの用法
>  なお、縦組で漢数字を用い、範囲をダーシで示す場合は、全角ダーシを用いる。
> 
> 二分ダーシは、固有名詞などの単語の結合にも用いる。例えば、“Boyle–Charle's law”のように、科学の法則では人名をつないで示す例があり、この場合はハイフンではなく、二分ダーシでつなぐ。片仮名で示す場合も同様に“ボイル–シャルルの法則”のように2人の人名を二分ダーシでつなぐ。
> 
> ハイフンは、複合語のつなぎ符号として、および分綴するときに使用する。しかし、単語と単語をつなぐ場合は、複合語とは異なる。二分ダーシを用いれば、複合語との差異を示すことができる。
> 
> こうした用法は、慣習である。読者は、一般に慣習に慣れ親しんでいるので、記号の使い方は慣習にしたがった使用方法にするのが望ましい。

**Comment by marsf** [comment]
以上、Shift JIS からのアプローチで、提案を以下のように変更します。

- ダッシュ記号は以下の文字を用いる。
  - 「—」(U+2014 全角ダッシュ) は説明や間をもたせるときや追い込み箇条書きの切れ目に用いる。
  - 「–」(U+2013 二分ダッシュ) または「〜」(U+301C 波ダッシュ) は数字の範囲等を表すのに用いる。 
  - 「―」(U+2015 水平線) と「～」 (U+FF5E 全角チルダ) は用いない。
    - Windows のキーボードから「～」を入力すると、通常は U+FF5E 全角チルダが入力されてしまうので注意すること。

※「—」(U+2014 EM DASH) は、2 倍ダッシュにする場合は文字間を分離できません。JIS X 4051で「分離禁止文字」に指定されています。

全角ダッシュは、MS-IME の場合、数字で 2014 と入力し、続けて F5 キーで文字コード変換すると入力できます。

**Comment by xfq** [comment]
ここでも関連情報があります：http://densyodamasii.com/?p=3913

**Comment by marsf** [comment]
@xfq 情報ありがとうございます。
JIS を基準にするのは間違いではなさそうですね。

Unicode に ⸺ (U+2E3A 'TWO-EM DASH') や ⸻ (U+2E3B 'THREE-EM DASH') があるのは知りませんでした。これらはウェブページであまり使われていないと思うので、スタイルガイドに含めて制限することはしません。

**Comment by marsf** [comment]
特に異論がなければ、今週末にダッシュ記号の項目をスタイルガイドに反映させたいと思います。
https://github.com/mozilla-japan/translation/issues/463#issuecomment-670934834

**Comment by marsf** [comment]
> 特に異論がなければ、今週末にダッシュ記号の項目をスタイルガイドに反映させたいと思います。

反映させました。

**Comment by marsf** [comment]
> -「こと」「もの」「とき」「ところ」「まえ」「あと」「なか」について、特定の時刻や場所など、実質的な事柄は漢字にする。
例文: (TBD)　←例文を追加する必要あり

実例に見る実用文のスタイル
https://takeda25.hatenablog.jp/entry/20120905/1346936852
> 区別するポイントは、「もの」を「物体」のような言葉に置き換えて意味が通じるかどうか。

14.　形式名詞 | niwa saburoo の日本語文法概説
https://niwasaburoo.amebaownd.com/posts/5733468
> 形式名詞の中で、「こと」と「もの」がいちばん抽象的です。

**Comment by marsf** [comment]
いわゆる形式名詞を分類してみました。
- 「名詞」の抽象化 → 「もの」「ところ」「はず」「わけ」
- 「動詞」（〜する）の抽象名詞化 → 「こと」
- 「副詞」（〜に）の抽象名詞化 → 「とき」「まえ」「あと」「なか」「うえ」「ため」「ころ」「ほか」
- 「形容詞」の抽象化？ → 「よう」「まま」「とおり」

**Comment by marsf** [comment]
前回の [c-bou さんのコメント](https://github.com/mozilla-japan/translation/issues/260#issuecomment-428159366) も関係あり。
> 「時」は、いろいろな使われかたがあります。
> 
> ・文頭で「時には、このような…」
> ・漢字の後ろについて「発生時に」
> ・「●×する時に」
> 
> 組み合わせやこれも上の読み方などと絡むことがあり、揺れやすいです。

それと、[前回の考察](https://github.com/mozilla-japan/translation/issues/260#issuecomment-450489515) から。
> 翻訳の場合は使い分けがはっきりしていますから、迷うことはほとんど無いかと思います。
> 迷っても、同じドキュメント内では統一する、というのは文章を書く上で当然のこととして、暗黙の了解でよろしいのではないでしょうか。

「特定の時刻や場所など、実質的な事柄は漢字にする。」をもっと分かりやすく具体化したい。

**Comment by marsf** [comment]
形式名詞の分類を整理しました。
英語の Abstruct noun とは違うので「抽象名詞化」を「抽象化名詞」に訂正しました。

- 「名詞」の抽象化 → 「もの」「ところ」「わけ」「ほか」「ほう」
- 「動詞」（〜する）の抽象化名詞 → 「こと」「はず」「ため」「せい」
- 「副詞」（〜に）の抽象化名詞 → 「とき」「まえ」「あと」「なか」「うえ」
- 「形容詞」の抽象化名詞 → 「よう」「まま」「とおり」

参考:
- [sptt やまとことばじてん: ＜みやび＞と＜ひなび＞について](https://spttyamatokotoba.blogspot.com/2015/03/blog-post_22.html)
- [会話中の『省略』部分を『元に戻す』技術を覚えると疲れにくくなる - はり・灸・あん摩マッサージの平穏堂 三郷早稲田鍼灸治療院](https://www.heion-do.com/2014/10/22/%E4%BC%9A%E8%A9%B1%E4%B8%AD%E3%81%AE-%E7%9C%81%E7%95%A5-%E9%83%A8%E5%88%86%E3%82%92-%E5%85%83%E3%81%AB%E6%88%BB%E3%81%99-%E6%8A%80%E8%A1%93%E3%82%92%E8%A6%9A%E3%81%88%E3%82%8B%E3%81%A8%E7%96%B2%E3%82%8C%E3%81%AB%E3%81%8F%E3%81%8F%E3%81%AA%E3%82%8B/)

**Comment by marsf** [comment]
以下、提案です。

- 形式名詞はひらがなで表記する。
- ただし、以下の形式名詞について、特定の場所、時刻、状態など、各品詞の具体的な言葉を指し示す場合は漢字で表記する。
  - 名詞:「もの」「ところ」「わけ」「ほか」「ほう」
  - 動詞:「こと」「はず」「ため」「せい」
  - 副詞:「とき」「まえ」「あと」「なか」「うえ」
  - 形容詞:「よう」「まま」「とおり」

**Comment by marsf** [comment]
この提案にした場合の @c-bou386 さんへの回答です。

・文頭で「時には、このような…」
　→「ときには、このような」
　　副詞的な使い方で具体的な時刻と置き換えられないのでひらがな。

・漢字の後ろについて「発生時に」
　→「発生時に」
　　発生した瞬間、具体的な時刻を指すので漢字。

・「●×する時に」
　→「●×するときに」
　　条件を表し、具体的な時刻が定まらないのでひらがな。
　　「した時」の場合は時刻が定まるので漢字。

**Comment by marsf** [comment]
形式名詞の項目に反映させました。
https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline/_compare/8fad603a15ea07a0041ee7ae295f0aabcad0802d...76b77c0419fee1fdbd65e71f9d37165b86d60997

**Comment by marsf** [comment]
https://github.com/mozilla-l10n/styleguides/pull/196

**Comment by marsf** [comment]
マージされたので今回はこれで close します。
