### ISSUE TITLE
[MDN] Bootstrapの翻訳

### ISSUE THREAD

**Issue by blackpeach7** [mozilla-japan/translation#471]
https://wiki.developer.mozilla.org/ja/docs/Glossary/Bootstrap
翻訳します。

**Comment by blackpeach7** [comment]
翻訳完了しました。レビューお願いします。

**Comment by hmatrjp** [comment]
ありがとうございます。
・訳文を修正しました。
・編集ページの下部にある、タグが追加されれば、編集レビューも完了扱いでOKです。
　原文の下にあるタグを、翻訳せず、そのまま日本語訳側にコピーしてください。

・ソース内のヘッダタグ (h2, h3)の id 属性を英語に戻しました。合わせて name 属性も追加済み。

**Comment by blackpeach7** [comment]
ありがとうございます。
タグを追加したので、編集レビュー完了します。
