### ISSUE TITLE
Glossary> "Promise" 項の翻訳

### ISSUE THREAD

**Issue by h-subaru** [mozilla-japan/translation#475]
"Glossary" > "Promise" 項の翻訳に着手します。

<a href="https://wiki.developer.mozilla.org/en-US/docs/Glossary/Promise">Promise</a>

**Comment by h-subaru** [comment]
翻訳を完了しました。ただ、コメントのとおりPromiseにわたすコールバック関数の総称への訳語を決めかねため、未訳出としました。

技術レビュー、編集レビューをお願いします。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Promise

**Comment by Uemmra3** [comment]
編集レビューやります。
技術レビューはオリジナル(英語版)でフラグ立ってないので不要かと思います。

**Comment by Uemmra3** [comment]
レビューしました。
差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Promise$compare?locale=ja&to=1610080&from=1609689

resolution, fulfillment, completion
については、他のページとのかねあいもあり、とりあえず英語のままとしています。

**Comment by h-subaru** [comment]
<p>レビューありがとうございます！差分の内容に目を通して、私からも追加の変更はありません。</p>

<blockquote>resolution, fulfillment, completion については、他のページとのかねあいもあり、とりあえず英語のままとしています。</blockquote>

<p>上記の部分も検討いただき助かりました。</p>
