### ISSUE TITLE
AbortSignalの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#476]
https://wiki.developer.mozilla.org/ja/docs/Web/API/AbortSignal

**Comment by kenji-yamasaki** [comment]
翻訳を完了しましたのでレビューをお願いいたします。

翻訳で悩んだ単語を2つ記載します。
listen→アクセスに待機する
promise→保証、単語としての訳は迷わなかったが、非同期処理のPromiseオブジェクトとひょっとすると関連するのかと迷った

**Comment by marsf** [comment]
> promise→保証、単語としての訳は迷わなかったが、非同期処理のPromiseオブジェクトとひょっとすると関連するのかと迷った

`the fetch() promise rejects with an AbortError.`
Promise オブジェクトのことです。

https://wiki.developer.mozilla.org/ja/docs/Web/API/Fetch_API
> fetch() メソッドは必須の引数を1つ取り、取得したいリソースのパスを指定します。成功か失敗かに関わらず、リクエストに対する Response に解決できる Promise を返します。

**Comment by kenji-yamasaki** [comment]
@marsf 
アドバイスに従って、再翻訳しました。
Fetch を使う(https://developer.mozilla.org/ja/docs/Web/API/Fetch_API/Using_Fetch)を参考にすると、promiseは 「Promise」というオブジェクト名で表記するのと、コード中の「promise」そのままに表記するの2つがあり、今回は後者としました。

**Comment by vtomaixe** [comment]
編集レビューをします。

**Comment by kenji-yamasaki** [comment]
作業が終了しているため、closeとします。
