### ISSUE TITLE
Using the CSS Painting API の翻訳

### ISSUE THREAD

**Issue by koyhoge** [mozilla-japan/translation#480]
https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API/Guide
こちらの翻訳作業をします。

**Comment by koyhoge** [comment]
文中に「worklet」という単語が幾度も出てくる。
Worklet は現時点では新し目の Web 技術で、日本語での表記は確定していないぽい。
[Worklet](https://developer.mozilla.org/ja/docs/Web/API/Worklet)
検索してみたが、Web技術文脈で「ワークレット」というカタカナ表記は発見できなかったので、「Worklet」表記でいくことにした。

**Comment by koyhoge** [comment]
翻訳おわりましたー。レビューをお願いします。

**Comment by hmatrjp** [comment]
履歴によると dskmori さんが編集されていますが、編集レビューフラグが降りていないので、念の為もう一度見ます。

**Comment by hmatrjp** [comment]
確認の続きをします。(9月のMDN翻訳ミートアップにて)

**Comment by hmatrjp** [comment]
一通り確認終わりました。微細な修正点あり。
Close しますが、何かあれば ReOpenしてください。
