### ISSUE TITLE
Attr.prefix の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#481]
https://wiki.developer.mozilla.org/en-US/docs/Web/API/Attr/prefix$translate?tolocale=ja

**Comment by kenji-yamasaki** [comment]
翻訳が終わりましたので、レビューをお願いいたします。

**Comment by potappo** [comment]
レビューしました。細かいところだけだったのでこちらで直しました。
Syntaxは他のリファレンスページに合わせて「構文」と訳していただけたらと思います。

**Comment by kenji-yamasaki** [comment]
レビューありがとうございました。
