### ISSUE TITLE
CanvasCaptureMediaStreamTrack.requestFrame() の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#484]
https://wiki.developer.mozilla.org/en-US/docs/Web/API/CanvasCaptureMediaStreamTrack/requestFrame$translate?tolocale=ja

**Comment by kenji-yamasaki** [comment]
翻訳を終えましたので、レビューをお願いいたします。

**Comment by hmatrjp** [comment]
日本語訳のURLを入れておきます。
https://wiki.developer.mozilla.org/ja/docs/Web/API/CanvasCaptureMediaStreamTrack/requestFrame
これからレビューします。（5/23 翻訳ミートアップにて）

**Comment by hmatrjp** [comment]
編集レビューしました。
・原文と少しニュアンスがズレているところがあったので訳文を一部修正しました。
・TranslationHelper 内蔵の定訳に合わせて訳語を変えた部分もあります。
・タグに、原文から抜けていた Method を補いました。
・h2, h3 タグの id を英文に戻しました。　(*)

確認して Close をお願いします。

(*) 履歴に、一度英語に戻したというコメントがありましたが、　id 属性だけで日本語→英語に戻しても、保存時にまた日本語に戻ります。　要素の日本語に引きずられないようにするには、 合わせて（原文にはない） name 属性を指定する必要があります。これは、TranslationHelper を使って新規に訳を始めると、うまいこと面倒を見てくれたと思います。

**Comment by kenji-yamasaki** [comment]
確認を行ったのでcloseとします。
