### ISSUE TITLE
Intl.DisplayNames の翻訳

### ISSUE THREAD

**Issue by shisama** [mozilla-japan/translation#485]
表題のとおり [Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames) の翻訳を行いました。レビューしていただけると幸いです。

https://wiki.developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
と思ったら dskmori さんがレビューされていました。差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames$compare?locale=ja&to=1621249&from=1620029

新規翻訳時には最下部のタグの付加をお願いします。

あと私の方では原文の最新に追従しておきました。

内容確認できたらIssue閉じてもらってOKですー。

**Comment by shisama** [comment]
ありがとうございます。タグの付加は次回から気をつけます。
