### ISSUE TITLE
Intl.RelativeTimeFormat の翻訳

### ISSUE THREAD

**Issue by shisama** [mozilla-japan/translation#487]
こちらの翻訳をします。
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat

**Comment by shisama** [comment]
翻訳が完了したのでレビューをお願いいたします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビュー完了しました。
翻訳テキスト部分の修正はありません。
各見出しの id 属性の値を原文の英語にする（さらに name 属性で同じ値を付加）という日本語版固有の修正だけ入れています。
https://wiki.developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat$compare?locale=ja&to=1634365&from=1628405
[TranslationHelper](https://github.com/mozilla-japan/translation/tree/master/MDN) を使うと新規翻訳時に自動で処理してくれますので、ご利用ください。
