### ISSUE TITLE
IntersectionObserver.observe() の翻訳

### ISSUE THREAD

**Issue by Fudodi** [mozilla-japan/translation#488]
こちらの翻訳をします。
https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/observe

**Comment by Fudodi** [comment]
翻訳が終わりました！レビューをお願いいたします。
https://wiki.developer.mozilla.org/ja/docs/Web/API/IntersectionObserver/observe

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
レビューしました。わかりやすい文だったと思います。
引数のtargetElementのところは、日本語の「要素」に変えています。

差分をご確認いただき、問題なければIssueを閉じてください。
https://wiki.developer.mozilla.org/ja/docs/Web/API/IntersectionObserver/observe$compare?locale=ja&to=1625235&from=1625234
