### ISSUE TITLE
-moz-float-edgeの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#489]
https://wiki.developer.mozilla.org/ja/docs/Web/CSS/-moz-float-edge

**Comment by hmatrjp** [comment]
github の Issue に登録する時は、日本語訳へのURLを入れてください。
レビューの時に、和訳に直接跳べると楽なので。上のURLだと、原文に飛びます。

**Comment by kenji-yamasaki** [comment]
@hmatrjp 
承知しました。

**Comment by hmatrjp** [comment]
ありがとうございます。見ました。
