### ISSUE TITLE
[MDN]MDN User docs

### ISSUE THREAD

**Issue by mantaroh** [mozilla-japan/translation#49]
プライオリティはつけられていませんが、MDNを始める方が読むことになるMDN User Docsが未翻訳がおおいので、Issueとして登録します。

MDN を初めて翻訳・寄稿するかたに向けた翻訳に興味がある方はぜひ、翻訳にご参加ください。
https://developer.mozilla.org/ja/docs/MDN/Doc_status/MDN

**Comment by mfuji09** [comment]
プラットフォーム更新後、このページがなくなったようですので、この課題は閉じてよいのではないでしょうか。

**Comment by potappo** [comment]
クローズします。
