### ISSUE TITLE
用語集の「Internationalization」の翻訳をしてみます。

### ISSUE THREAD

**Issue by dukesan** [mozilla-japan/translation#490]
https://developer.mozilla.org/ja/docs/Glossary/Internationalization_and_localization

**Comment by dukesan** [comment]
翻訳をしましたのでレビューをお願いします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。以下、修正した点です。ご確認ください。
・Internationalization は、日本の OSS コミュニティだと、「国際化」と訳すことが一般的、また、すでに MDN 日本語版にあるページでも「国際化」と訳していますので、「国際化」に直しています。
・記事中の MDN内のリンクは en から ja に変更してください。
・See Also はページによってぶれがあるかもですが、「関連情報」と訳すことが多いです。
・リンクも翻訳可能なら翻訳してください。
・「文字の配列方向」から「文章の記述方向」に直しました。アラビア語は左方向とかのやつです。
差分をご確認いただき、問題なければIssueを閉じてください。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Internationalization_and_localization$compare?locale=ja&to=1625237&from=1625221

**Comment by dukesan** [comment]
potappoさん、レビューありがとうございました。Issueを閉じます。
