### ISSUE TITLE
Lazy load の翻訳

### ISSUE THREAD

**Issue by benibana2001** [mozilla-japan/translation#493]
こちらの翻訳をします。よろしくお願いします。
https://developer.mozilla.org/en-US/docs/Glossary/Lazy_load

**Comment by benibana2001** [comment]
こちらの記事の翻訳を完了しました。
https://wiki.developer.mozilla.org/ja/docs/Glossary/Lazy_load

レビューのほど、よろしくお願いいたします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。

https://wiki.developer.mozilla.org/ja/docs/Glossary/Lazy_load$compare?locale=ja&to=1629405&from=1629400

「あわせて参照」のところがなぜかリンクになっていたので削除したのと、リンクを en-US から ja にしています（リンク先の日本版版ページが存在しない場合は英語版が表示されます）。

差分を確認して問題なければ、この issue をクローズしてください。

**Comment by benibana2001** [comment]
potappoさん、レビュー、修正いただきありがとうございます！
クローズいたします。
