### ISSUE TITLE
PannerNode関連ページの翻訳

### ISSUE THREAD

**Issue by toyakun** [mozilla-japan/translation#495]
https://wiki.developer.mozilla.org/ja/docs/Web/API/PannerNode
こちらの直下のページを翻訳していきます。

未完成の以下3件を着手して、その後ほかのPannerNode関連ページを編集します。
https://wiki.developer.mozilla.org/ja/docs/Web/API/PannerNode
https://wiki.developer.mozilla.org/ja/docs/Web/API/PannerNode/orientationX
https://wiki.developer.mozilla.org/ja/docs/Web/API/PannerNode/coneInnerAngle

**Comment by toyakun** [comment]
上記3件の調整が完了しました。レビューをお願いします。

### https://wiki.developer.mozilla.org/ja/docs/Web/API/PannerNode について
以下のリンクを参考に、以前の翻訳に少し手を加えました。
https://webaudio.github.io/web-audio-api/#Spatialization-sound-cones

**Comment by Uemmra3** [comment]
レビューしました。概ねいいと思いますが、円錐を「コーン」で統一しています。
タグのつけ忘れがあったので、とりあえず英語版と同じものをつけておけば良いです。

それぞれ差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Web/API/PannerNode$compare?locale=ja&to=1629401&from=1629382
https://wiki.developer.mozilla.org/ja/docs/Web/API/PannerNode/orientationX$compare?locale=ja&to=1629406&from=1629403

**Comment by Uemmra3** [comment]
問題なければ、このIssueを閉じてください。
