### ISSUE TITLE
 WebRTC API の翻訳の続き

### ISSUE THREAD

**Issue by kaitas** [mozilla-japan/translation#496]
2020-06-20 「みんなで MDN を翻訳しよう！ 翻訳コミュニティ月例ミートアップ」にて
初心者です
こちらの後半の翻訳に着手してみます
https://wiki.developer.mozilla.org/ja/docs/Web/API/WebRTC_API

**Comment by kaitas** [comment]
とりあえず最後の他ドキュメントのインデックス以外はレビュー＆翻訳終わりました
レビューよろしくお願いいたします。
- ドメイン内ドキュメントへのハイパーリンクの張り方（ `/ja` ではなく `https://wiki.developer.mozilla.org/ja/...` といったフルパスで作業してましたが問題ないでしょうか？）

**Comment by hmatrjp** [comment]
MDN 内へのリンクは、 /ja/ ... から始まるリンクの方が良いです。公開した画面で比べるとわかりますが、https:// から書いた場合、外部へのリンクと同じマークが付きます。

**Comment by kaitas** [comment]
おお、なるほど…直さねばですね

確認なのですが、実際は `/ja` のドキュメントが存在するかどうか確認できていなくても `/ja` で書いたほうがいいということですかね？

**Comment by kaitas** [comment]
- `}}` マクロエラーへの対応（多分スタイルエディタでの貼り付けで混入）
- `https://wiki.developer.mozilla.org/en-US/` の `/ja/` への置き換え
を終わりました

一か所だけ、
> Represents an error associated with the identity provider (idP). This is usually for an {{DOMxRef("RTCPeerConnection")}}. Two events are sent with this type: {{event("idpassertionerror")}} and {{event("idpvalidationerror")}}.

これを以下の日本語訳に置き換えるとマクロエラーが取れません
> ID プロバイダ (idP) に関連するエラーを表します。これは通常、 {{DOMxRef("RTCPeerConnection")}} に対して行われます。このタイプでは、 {{event("idpassertionerror")}} と {{event("idpvalidationerror")}} の 2 つのイベントが送信されます。

その下の
`RTCCertificate` も dt要素なのにdd要素になっているように見えます…

何かが間違っているようなのですが、何が間違っているかわからない…。

**Comment by hmatrjp** [comment]
今見たところでは、マクロエラーは出ませんし、RTCCertificate もきちんと表示されているように見えます。

**Comment by hmatrjp** [comment]
今月に入ってから、原文に手が入ったようなので、差を確認します。（7/18 MDN翻訳ミートアップにて）

**Comment by hmatrjp** [comment]
一通り和訳への反映と修正が済みましたので、Closeします。何かあったら ReOpenしてください。
