### ISSUE TITLE
Cross-Origin Resource Policy の翻訳

### ISSUE THREAD

**Issue by shisama** [mozilla-japan/translation#498]
https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)

こちらの翻訳が不完全だったので翻訳します。

**Comment by shisama** [comment]
翻訳しました。お手数ですが、レビューをお願いいたします。
https://wiki.developer.mozilla.org/ja/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビュー完了しました。

https://wiki.developer.mozilla.org/ja/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)$compare?locale=ja&to=1634389&from=1634164

細かいところは上記リンク先で見ていただくとして、若干手直ししています。
- 「Web」は「ウェブ」としています（Mozilla 日本語ローカライズとしての統一）。
- resurrected はニュアンスが若干難しいですが、伝わること重視で単純に「再提案」としました。
- opt-in はハイフンありなしに関わらずオプトインで統一。

クローズしておきますが、何か質問あれば、再オープンしてください。
