### ISSUE TITLE
Caching_modulesの翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#499]
https://wiki.developer.mozilla.org/ja/docs/WebAssembly/Caching_modules

**Comment by kenji-yamasaki** [comment]
こちら軽微な作業かと思って進めたのですが、かなり混乱しました。
(混乱のため、翻訳した内容の破棄、復活をしたり分かりにくくなっています。ごめんなさい。)

今回の翻訳は
* リンクの削除(1箇所)
* コード部分の先頭の改行の削除(複数箇所)
が反映すべき内容だと思って作業を行なっていました。

しかし、英文の公開されている以下のページでは、
https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules
IndexedDBに削除したリンクが残っています。

Revision 1589327で英文版にこのリンクの削除が反映されているのを確認しました。
https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules$compare?locale=en-US&to=1589327&from=1491505

公開されている記事は最新のリビジョンを表示しているものではないのでしょうか、ご教示ください。

**Comment by potappo** [comment]
私の方では、英語版の最新版でリンクが消えています。
ブラウザのキャッシュが残ってしまっているのではないでしょうか？
スーパーリロード（Ctrl+F5）などしてみてください。

**Comment by kenji-yamasaki** [comment]
2019年が最終更新で、随分前の記事なのですが・・・
スーパーリロードしても「IndexedDB」リンクはありました。

**Comment by dskmori** [comment]
> IndexedDBに削除したリンクが残っています。
> 
> Revision 1589327で英文版にこのリンクの削除が反映されているのを確認しました。
> https://wiki.developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules$compare?locale=en-US&to=1589327&from=1491505

このリビジョン間での変更はIndexedDBのリンクではなく、[Setting up a caching library](https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules#Setting_up_a_caching_library) セクションの第 2 パラグラフにある wasm-utils.js のリンクだと思います。

![Caching compiled WebAssembly modules compareMDN-2](https://user-images.githubusercontent.com/13865683/87846299-de519a80-c909-11ea-9d9e-4860dbd8a07d.png)


変更が加えられた時期も半年以上前のようなので、キャッシュとかの問題でなく、何か勘違いなさっているのではないでしょうか。

**Comment by kenji-yamasaki** [comment]
勘違いでしたね。
ありがとうございました。

**Comment by kenji-yamasaki** [comment]
レビューをお願いいたします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
翻訳内容は修正なしです。見出しのidを英語化してname属性をつけました。クローズします。
