### ISSUE TITLE
DOMParserの翻訳

### ISSUE THREAD

**Issue by Shu-cpartner** [mozilla-japan/translation#500]
https://wiki.developer.mozilla.org/ja/docs/Web/API/DOMParser

**Comment by Shu-cpartner** [comment]
こちら翻訳完了しました。レビューお願いします！

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
英語版の更新を反映して英語になっていた部分を翻訳してくれたのだと思いますが、
それ以降、さらに英語版で更新が入っているようです。var を let になどの細かい修正なので、レビュー時に取り込みました。

https://wiki.developer.mozilla.org/ja/docs/Web/API/DOMParser$compare?locale=ja&to=1634395&from=1634385

翻訳時画面の左側に、現在の最新の英語版が表示されますので、今後、差異がないか見てみるようにしてください。

クローズしますが、何か質問あれば、再オープンください。
