### ISSUE TITLE
Basic animationsの翻訳

### ISSUE THREAD

**Issue by ycatch** [mozilla-japan/translation#506]
下記のページの翻訳に着手します。

Basic animations - 開発者ガイド | MDN
https://developer.mozilla.org/ja/docs/Web/Guide/HTML/Canvas_tutorial/Basic_animations

よろしくお願いします。

**Comment by potappo** [comment]
まだレビュー待ちにありましたので、レビューします。

**Comment by potappo** [comment]
レビューしました。1か所、メソッド名の後に半角空白を追加しただけです。クローズします。
