### ISSUE TITLE
SCMの翻訳

### ISSUE THREAD

**Issue by jinishiguro** [mozilla-japan/translation#507]
下記のページの翻訳に着手します。

https://developer.mozilla.org/ja/docs/Glossary/SCM

よろしくお願いします。

**Comment by Uemmra3** [comment]
@jinishiguro 

参考まで。
name属性を自動的に追加する、UserScriptがあります。
https://github.com/mozilla-japan/translation/tree/master/MDN
導入を検討してみてください。

**Comment by jinishiguro** [comment]
最終fix及び、色々と教えて頂きましてありがとうございました。
今回、大変参考にになりました。
また、スクリプトの導入も検討します。
