### ISSUE TITLE
FileReader.readAsBinaryString()の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#510]
https://wiki.developer.mozilla.org/ja/docs/Web/API/FileReader/readAsBinaryString$edit

**Comment by kenji-yamasaki** [comment]
翻訳を終えましたのでレビューをお願いいたします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。細かい修正のみです。差分は以下の通りです。

https://wiki.developer.mozilla.org/ja/docs/Web/API/FileReader/readAsBinaryString$compare?locale=ja&to=1645436&from=1645424

loadend イベントのリンクに関しては、英語版だと、Events/loadend から Web/Events/loadend にリダイレクトされ、さらに Web/API/XMLHttpRequest/loadend_event にリダイレクトされているのですが、日本語版では、Events/loadend も  Web/Events/loadend も存在しない（どちらもリダイレクトされるので日本語版ページを作成できませんでした）ため、Web/API/XMLHttpRequest/loadend_event  のリンクに修正した、という経緯です。

他に大きな問題はありませんでしたので、クローズします。何かあればリオープンください。
