### ISSUE TITLE
「レスポンシブタイポグラフィ」の現行日本語訳が誤訳かもしれない

### ISSUE THREAD

**Issue by matzryo** [mozilla-japan/translation#511]
### 該当箇所
「レスポンシブデザイン」ページの「レスポンシブタイポグラフィにビューポート単位を使用」の章です。
<https://developer.mozilla.org/ja/docs/Learn/CSS/CSS_layout/Responsive_Design#Responsive_typography>

### 英語原文

英語原文は以下のとおりです。

 > This means that we only need to specify the font size for the heading once, rather than set it up for mobile and redefine it in the media queries. The font then gradually increases as you increase the size of the viewport.

### 現行日本語訳

現行日本語訳は以下の通りです。

 > これは、一度だけ見出しのフォントサイズを指定するのではなく、モバイルのためにそれを設定し、メディアクエリーでそれを再定義する必要があることを意味します。 ビューポートのサイズを大きくすると、フォントは徐々に大きくなります。

### 私の解釈、および現行日本語訳が誤訳かもしれない、と思う理由

「レスポンシブタイポグラフィ」の項目全体の英語原文を拝読し、文脈は以下のとおりだと解釈しました。

画面サイズに応じたフォントサイズ変更は、メディアクエリーを用いてfont-size指定を再定義することで実現できる。別アプローチとして、vw使うとメディアクエリでの再定義不要で画面サイズに応じたフォントサイズ変更ができる。

この文脈ですと、上記の一文でいいたいのは、「再定義不要」ということだろうと推測する次第です。現行日本語訳は、「再定義する必要がある」としており、逆の意味になっているのではないか？と思っております。

### 翻訳案

> これは、見出しのフォントサイズを指定する必要があるのは一度だけで、モバイルのためにそれを設定し、メディアクエリーでそれを再定義せずともよいことを意味します。

上記案はドラフトになります。これから以下のガイドラインを拝見し、必要あれば修正いたします。

- [表記ガイドライン](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline)
- [L10Nガイドライン](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline)
- [日本語の文体](https://docs.google.com/spreadsheets/d/1y-hC-xMXawCgcYZwJDnvuSlAOTgMRLLyqXurpYkJbYE/edit#gid=0)

**Comment by hmatrjp** [comment]
現状が誤訳との解釈、賛成です。rather than 〜ですから。
翻訳案も、良いのではないでしょうか？

**Comment by matzryo** [comment]
[日本語の文体](https://github.com/mozilla-japan/translation/wiki/L10N-Guideline#%E6%96%87%E4%BD%93%E3%81%A8%E8%A1%A8%E8%A8%98%E8%A6%8F%E5%89%87) の
「言語差と意訳」の項目を拝読しました。それを踏まえ、issueに記載した翻訳案よりも、より日本語として自然な訳文に変更しました。

> これは、見出しのフォントサイズを指定する必要があるのは一度だけで、モバイル用にメディアクエリーで再定義せずともよいことを意味します。ビューポートのサイズを大きくするにつれて、フォントは徐々に大きくなります。

ページを編集しました。変更差分は以下の通りです。
https://wiki.developer.mozilla.org/ja/docs/Learn/CSS/CSS_layout/Responsive_Design$compare?locale=ja&to=1645433&from=1637423

**Comment by matzryo** [comment]
ページを編集いたしました。お手数ですがレビューをお願いいたします。

変更差分は以下の通りです。
<https://wiki.developer.mozilla.org/ja/docs/Learn/CSS/CSS_layout/Responsive_Design$compare?locale=ja&to=1645433&from=1637423>

すでに <https://github.com/mozilla-japan/translation/issues/511#issuecomment-699426528> にて一度レビュー頂いてますが、訳文を変更したため、念の為再度依頼いたします。

**Comment by hmatrjp** [comment]
編集レビューしました。特に変更していませんので、編集レビューフラグを降ろし、このまま Close します。
