### ISSUE TITLE
Animation.cancel() の翻訳

### ISSUE THREAD

**Issue by ycatch** [mozilla-japan/translation#512]
下記の翻訳に着手します。

API: Web Animations > Animation.cancel()
https://developer.mozilla.org/en-US/docs/Web/API/Animation/cancel

よろしくお願いします。

**Comment by ycatch** [comment]
翻訳終了です。

**Comment by hmatrjp** [comment]
せっかくですので、日本語版URLも書いておきます。
https://developer.mozilla.org/ja/docs/Web/API/Animation/cancel

関連情報 セクションの最下行も、日本語にしてもいいかも。

**Comment by ycatch** [comment]
レビューありがとうございました。修正しました。

**Comment by hmatrjp** [comment]
半角空白1つ追加しました。
