### ISSUE TITLE
ChildNode.remove()の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#513]
https://wiki.developer.mozilla.org/ja/docs/Web/API/ChildNode/remove$edit

**Comment by kenji-yamasaki** [comment]
翻訳が完了しましたので、レビューをお願いいたします。

**Comment by potappo** [comment]
レビューします

**Comment by potappo** [comment]
レビュー完了しました。レビューフラグをOFFにした以外の修正はありません。クローズします。
