### ISSUE TITLE
ChildNode.after() の翻訳

### ISSUE THREAD

**Issue by ShirasuGyoza** [mozilla-japan/translation#514]
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/after
を翻訳します。

**Comment by ShirasuGyoza** [comment]
翻訳しましたので、レビューをお願いします。
https://wiki.developer.mozilla.org/ja/docs/Web/API/ChildNode/after

**Comment by hmatrjp** [comment]
翻訳ありがとうございます。
訳すべきところが一通り終わっていたら、翻訳作業中 のチェックを外してください。
編集レビュー依頼のフラグは、そのままでいいです。

**Comment by ShirasuGyoza** [comment]
承知しました。翻訳作業中 のチェックを外しました。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。

https://wiki.developer.mozilla.org/ja/docs/Web/API/ChildNode/after$compare?locale=ja&to=1649055&from=1649050

最後の関連情報の「and」を「と」に直しただけです。他は問題ありませんでした。クローズします。
