### ISSUE TITLE
ChildNode.before() の翻訳

### ISSUE THREAD

**Issue by ShirasuGyoza** [mozilla-japan/translation#516]
https://developer.mozilla.org/ja/docs/Web/API/ChildNode/before
を翻訳します。

**Comment by ShirasuGyoza** [comment]
翻訳しましたのでレビューをお願いします。
https://wiki.developer.mozilla.org/ja/docs/Web/API/ChildNode/before

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
特に問題ありませんでしたので、編集レビューフラグをはずしただけです。クローズします。
