### ISSUE TITLE
ChildNode.replaceWith() の翻訳

### ISSUE THREAD

**Issue by ShirasuGyoza** [mozilla-japan/translation#517]
https://developer.mozilla.org/ja/docs/Web/API/ChildNode/replaceWith
を翻訳します。

**Comment by ShirasuGyoza** [comment]
https://developer.mozilla.org/ja/docs/Web/API/ChildNode/replaceWith
翻訳しましたのでレビューをお願いします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
特に問題ありませんでしたので、編集レビューフラグをはずしただけです。クローズします。
