### ISSUE TITLE
Document: scroll event の翻訳

### ISSUE THREAD

**Issue by ShirasuGyoza** [mozilla-japan/translation#518]
https://developer.mozilla.org/ja/docs/Web/API/Document/scroll_event
を翻訳します。

**Comment by ShirasuGyoza** [comment]
https://wiki.developer.mozilla.org/ja/docs/Web/API/Document/scroll_event
を翻訳しましたのでレビューをお願いします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
最初にある青い表のヘッダ部分を追加で翻訳しました。
https://wiki.developer.mozilla.org/ja/docs/Web/API/Document/scroll_event$compare?locale=ja&to=1649082&from=1649079
他は問題ありませんでしたので、クローズします。
