### ISSUE TITLE
囲み文字の使い方について

### ISSUE THREAD

**Issue by marsf** [mozilla-japan/translation#519]
#463 に追加の issue です。

10/17 の翻訳ミートアップで、囲み文字 (括弧、引用符) に関する質問があったので、スタイルガイドの追加対象にしたいと思います。

mimi さんの質問:
> 【質問】囲み文字についてなのですが、
> https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline#%E7%B4%84%E7%89%A9%E3%81%AE%E8%A1%A8%E8%A8%98
> を読んでもちょっと判別出来ず、ご教授いただければ幸いです。
> 例えば、"chunk"は 「塊」ではなく"塊" で行く感じでしょうか？

potappo さんの回答:

> だいたいは"塊”で良いと思います。「塊」の方が意味が通ると思ったときは「塊」ですね。

**Comment by marsf** [comment]
要は、英文で " " (U+0022) または “ ” (U+201C, U+201D) が使われている単語について、引用符をそのまま使うか、かぎ括弧にするか迷うという問題です。

例によって、他のスタイルガイドでの記載を調べました。

共同通信の記者ハンドブック第13版 (p.118):
> ### 【引用符】1
> 会話、語句の引用に「」『』〝〟を用いる。〝〟は、どうしても必要な場合に限って使い、濫用はしない。

記者ハンドブックはあまり参考にならず。一般的な和文での使い方のみ。

　
Microsoft の Japanese Style Guide (February, 2019):
> ### Left/right corner brackets
> In Japanese, full-width left/right corner brackets (「」) are used when referring to:
> • Help topics  _ヘルプトピック_
> • Topics or information on web site  _ウェブサイト上のトピックまたは情報_
> • Title of chapter/section/subsection/appendix in documents  _文書内の章、セクション等のタイトル_
> • Texts to enter  _入力する文字_
> • Texts in a file  _ファイル内のテキスト_

Microsoft の日本語スタイルガイドでは、タイトルや見出しの参照、入力する文字、検索語句などでかぎ括弧を使うようになっている。

　
JTF日本語標準スタイルガイド 第3.0版:
> ### 3.3.3 かぎかっこ「」
> 引用、参照先、入力する文字を示す場合、語句を強調する場合に使用します。
> 
> ### 3.3.5 二重引用符" "
> 引用や語句を強調する場合に使用します。和文では多用しません。

JTF スタイルガイドは Microsoft とほぼ同じ。タイトルやトピックを「参照先」としている。

**Comment by dskmori** [comment]
用法に準じることもさることながら、見た目も考慮したいです。
個人の感覚ですが、引用符 (U+0022, U+201C, U+201D) でひらがなやカタカナを囲うと濁点と混同するし、濁点のある文字で終わる語句を囲うと、濁点と引用符が並ぶので結構見づらいことがあります 。
ガイドラインとして引用符を禁じる必要はないと思いますが、第一選択肢としてはかぎかっこを推したいです。

**Comment by marsf** [comment]
> ### 約物の表記
> - カギ括弧以外は半角を用いて前後に半角スペースを挿入する。

上記項目を以下のように変更することを提案します。

- 句読点、カギ括弧などの日本語 [約物](http://ja.wikipedia.org/wiki/%E7%B4%84%E7%89%A9) と英数字が隣接する場合は半角スペースを挿入しない。　　 _←「英数字の表記」から移動_
- 引用符は、日本語の場合は濁点と引用符が連続して読みづらくなることがあるので「 」(U+300C, U+300D カギ括弧) および『 』(U+300E, U+300F 二重カギ括弧) を用いる。
  - 英数字では “ ” (U+201C, U+201D 二重引用符) および ‘ ’ (U+2018, U+2019 単引用符) を用いてもよい。
  - " " (U+0022 引用符) は、エスケープする必要を避けるためできるだけ用いない。

参考:
The Unicode® StandardVersion 9.0 – Core Specification
[Chapter 6. Writing Systems and Punctuation](https://www.unicode.org/versions/Unicode9.0.0/ch06.pdf) (PDF)

**Comment by marsf** [comment]
特にコメントが無ければ今週中にガイドラインに反映させたいと思います。

**Comment by marsf** [comment]
表記ガイドラインに反映しました。

https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline/_compare/95904de133c4c7eafe6d7ee7ca8bd773de10ecd9...8fad603a15ea07a0041ee7ae295f0aabcad0802d
