### ISSUE TITLE
NodeList.prototype.forEach()　の翻訳

### ISSUE THREAD

**Issue by ShirasuGyoza** [mozilla-japan/translation#520]
https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach
を翻訳します。

**Comment by hmatrjp** [comment]
一区切りついてからでもいいので、日本語版ページのURLもこちらの Issue に追記してください。（レビューを受けたい時など、日本語版に直接跳べると便利なので。）

**Comment by ShirasuGyoza** [comment]
翻訳しました。
日本語版ページのURLはこちらになります：
https://wiki.developer.mozilla.org/ja/docs/Web/API/NodeList/forEach

レビューをお願いします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。修正は細かな点のみです。
https://wiki.developer.mozilla.org/ja/docs/Web/API/NodeList/forEach$compare?locale=ja&to=1654611&from=1654597
