### ISSUE TITLE
Measuring performanceの翻訳

### ISSUE THREAD

**Issue by succi0303** [mozilla-japan/translation#521]
https://developer.mozilla.org/ja/docs/Learn/Performance/Measuring_performance

**Comment by succi0303** [comment]
翻訳を完了しました。レビューお願いします🙌

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。
Web をウェブに統一しています（リンク先タイトルが Web であっても）。
https://wiki.developer.mozilla.org/ja/docs/Learn/Performance/Measuring_performance$compare?locale=ja&to=1654630&from=1654614

**Comment by succi0303** [comment]
修正点確認しました。レビューありがとうございます。他の関連記事をウェブ→Webで揃え始めていたので「ウェブ」に統一するよう変更しますね。
