### ISSUE TITLE
Using Web Workersの翻訳

### ISSUE THREAD

**Issue by windchime-yk** [mozilla-japan/translation#522]
https://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by windchime-yk** [comment]
他の方が編集できないようにロックしたいのですが、方法がよくわからないです

**Comment by hmatrjp** [comment]
MDN では、編集のロックはできません。
衝突回避を考えてのことでしょうか？　今回のように集団で翻訳を行う時は、このように github の Issue を使って、宣言する方式で運用しています。なお、訳の途中で保存することも可能で、保存した版は、他の人が上書きしても、データベースに残っています。

**Comment by windchime-yk** [comment]
なるほど、失礼しました。
[MDN Web Docs ドキュメント翻訳の始め方](https://github.com/mozilla-japan/translation/wiki/Get-started-with-translation-of-Mozilla-documentations)に

> 始める前に、とりあえず保存すると、他の人が編集できないようにロックされる。

とあり、他の方が翻訳されている記事の冒頭に『この記事は翻訳作業中です。』とあったので、何かしら方法があるのかと勘違いしておりました。

コメントいただき、ありがとうございます。
このまま作業を続行いたします。

**Comment by potappo** [comment]
> なるほど、失礼しました。
> [MDN Web Docs ドキュメント翻訳の始め方](https://github.com/mozilla-japan/translation/wiki/Get-started-with-translation-of-Mozilla-documentations)に
> 
> > 始める前に、とりあえず保存すると、他の人が編集できないようにロックされる。
> 
> とあり、他の方が翻訳されている記事の冒頭に『この記事は翻訳作業中です。』とあったので、何かしら方法があるのかと勘違いしておりました。
> 
別の意図で書かれたものなのか、勘違いで書かれた記載なのかはわからないですが、誤解を招く記述だったので、取り消し線と追記を行いました。

**Comment by hmatrjp** [comment]
補足しておきますと、『この記事は翻訳作業中です。』が表示されるのは、編集ページの下の方にある　 翻訳途中 - まだ翻訳が完了していない　のチェックが入っている場合です。

**Comment by windchime-yk** [comment]
@potappo 
追記いただきありがとうございます！

@hmatrjp 
ありがとうございます！ 疑問が氷解いたしました。

**Comment by windchime-yk** [comment]
翻訳いたしました！
レビューをお願いします！

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。
https://wiki.developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Using_web_workers$compare?locale=ja&to=1654632&from=1654629
リンク先が英語版だったものを日本語版に直しています。
