### ISSUE TITLE
Set() constructorの翻訳

### ISSUE THREAD

**Issue by shigef** [mozilla-japan/translation#523]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/Set を翻訳します。

**Comment by shigef** [comment]
翻訳しました。
日本語ページのURLは以下です。
https://wiki.developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set/Set

レビューをお願いします。

**Comment by potappo** [comment]
レビューします。

**Comment by potappo** [comment]
レビューしました。
特に問題ありませんでしたので、更新はレビューフラグをはずしたのみです。
クローズします。
