### ISSUE TITLE
IntersectionObserver.IntersectionObserver()　の翻訳

### ISSUE THREAD

**Issue by ShirasuGyoza** [mozilla-japan/translation#524]
https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/IntersectionObserver
を翻訳します。

日本語版URL：
https://developer.mozilla.org/ja/docs/Web/API/IntersectionObserver/IntersectionObserver

**Comment by ShirasuGyoza** [comment]
翻訳しました。

https://developer.mozilla.org/ja/docs/Web/API/IntersectionObserver/IntersectionObserver

レビューをお願いできますと幸いです。

**Comment by hmatrjp** [comment]
レビューします。（1/23 ミートアップにて）

**Comment by hmatrjp** [comment]
いくつか気づいた点があります。
1. 冒頭の段落、訳で一文抜けています。　 if the threshold list is empty, it's set to the array [0.0].
2. crossed の訳語を　交差した　としていますが、しきい値に対してなので、越えた　の方が良さそうです。
3. root の2文め、　Any part of the target not visible in the visible area (of the root) は、（rootの）可視領域に見えていない部分はいずれも  で、文の意味が少し違ってきます。
4. threshold の冒頭：　1 つの数字　→　1 つの数値

**Comment by ShirasuGyoza** [comment]
レビューいただきありがとうございます。自分でも翻訳を直そうと思っていたところ、翻訳更新ができないと聞いて止まっていてしまいました。
後ほど頂いた指摘を反映した本文を、こちらにコメントに記載します。

**Comment by ShirasuGyoza** [comment]
下記に修正した本文を記載しました。
お手数ですが再度レビューおねがいできますでしょうか。
___

IntersectionObserver() コンストラクタは、新しい IntersectionObserver オブジェクトを生成します。 rootMargin は、指定されていた場合は構文が正しいかが確認され、閾値は、0.0 から 1.0 の間であるか確認され、閾値のリストは昇順に並べ替えられます。閾値のリストが空の場合、 [0.0] の配列に設定されます。

# 構文

```
var observer = new IntersectionObserver(callback[, options]);
```

## パラメーター

### callback
対象の要素の比率が、閾値を超えて表示されたときに実行します。コールバックは 2 つの引数を受け取ります。

 - entries
IntersectionObserverEntry オブジェクトの配列で、それぞれが閾値を超えたのか、閾値で指定したパーセンテージをどのくらい超えたのかまたは超えていないのかを表します。
- observer
コールバックが呼び出される IntersectionObserver です。

### options Optional
オブザーバをカスタマイズするためのオプションオブジェクトです。 もし options に何も指定されていない場合、オブザーバはルートとして、余白の無い、閾値 0% のドキュメントビューポートを使用します（つまり、1px でもドキュメントビューポート内に入ればコールバックが実行されます）。次のオプションから任意の組み合わせを利用できます。

- root
Element または Document オブジェクトは、対象の祖先要素であり、これらの矩形はビューポートとみなされます。ルートの可視領域に見えていない部分はいずれも、見えているとみなされません。
- rootMargin
交差状態を計算するときに root の bounding_box に適用されるオフセットのセットを指定する文字列で、計算のために root を効果的に縮小または拡大させます。構文は概ね CSS の margin プロパティのものと同じです。margin のしくみと構文について詳しくは The root element and root margin in Intersection Observer API を御覧ください。デフォルト値は "0px 0px 0px 0px" です。
- threshold
1 つの数値か、または 0.0 と 1.0 の間の数字の配列で指定し、監視対象の矩形の総面積に対する交差領域の比率を指定します。 0.0 に指定された場合、1px でも交差領域に入ったらその対象要素は表示されたとみなされます。threshold がどのように使われるかについては、 Thresholds in Intersection Observer API でより深く説明されています。 デフォルトの値は 0.0 です。

## 戻り値

新しい IntersectionObserver は、対象要素が指定された root 内で threshold の可視閾値を超えて表示されたかどうかを監視するために使用することができます。対象要素の表示の変更を監視し始めるには、 observe() メソッドを呼び出します。

### 例外

- SyntaxError
指定した rootMargin は無効な値です。
- RangeError
 threshold の値のうち 1 つまたは 1 つ以上の値が 0.0 から 1.0 の範囲に当てはまりません。

## 例

この例では、監視されている要素の可視範囲が 10% 以上になったときに毎回 myObserverCallback を呼び出すような新しい intersection observer を生成しています。

```
let observer = new IntersectionObserver(myObserverCallback,
                   {threshold: 0.1});
```

**Comment by hmatrjp** [comment]
指摘の部分、対応していただいてありがとうございました。原文との対応で精度が上がってきたと思います。

2. のところ、越えた　で「超」を使わなかったのは理由があります。　callback の entries の説明（原文）にあるのですが、しきい値を下から上に越えた場合も、上から下に越えた場合も、callbackが呼び出されるからです。　この部分の訳、上から下の部分があることも示唆するように変えられるでしょうか？

もう一点追加でお願いです。

5. 「observer」の訳は、オブザーバー　と伸ばしてください。
日本語としてはどちらでも通じるのですが、MDNの中で混在するのを避けるため、数年前に、元の単語の綴に従って区別するよう規則を作りました。詳しくは、
https://mozilla-l10n.github.io/styleguides/ja/editorialguideline.html
の　カタカナ語の表記　の部分を参照してください。

**Comment by ShirasuGyoza** [comment]
@hmatrjp 
再度レビュー頂きありがとうございます。漢字の選定などとても勉強になります。

> 上から下の部分があることも示唆するように変えられるでしょうか？

Callback の説明内で文章を修正しました。また「越える」に統一しました。

> 「observer」の訳は、オブザーバー　と伸ばしてください。

表記ルールに従いすべて長音を伸ばすように修正しました。


上記の修正を、[先のコメント中翻訳文](https://github.com/mozilla-japan/translation/issues/524#issuecomment-765907655)に反映しましたのでお手数ですがご確認いただけますと幸いです。

**Comment by hmatrjp** [comment]
entries のところが難しいですね。
各配列の要素が表すのは、しきい値　ですので、例えば

> An array of IntersectionObserverEntry objects, each representing one threshold which was crossed, either becoming more or less visible than the percentage specified by that threshold.

> IntersectionObserverEntry オブジェクトの配列で、それぞれの要素がしきい値となります。これは、見えている割合が下から上に、または上から下にその値を越える時に callback が呼ばれるよう指定するものです。

末尾に、原文にないところを補ってしまったので説明過剰の気もします。原文では ,（カンマ） での区切りですが、上の例では、　。　で区切ってしまっています。もっとすっきりするようなら適当に変えてください。

関連して、冒頭の
> 対象の要素の比率が

は　

> 対象の要素が見えている割合が

の方がわかりやすいでしょう。

他は修正していただいたままで問題ないと思います。

**Comment by ShirasuGyoza** [comment]
@hmatrjp 
ご確認頂きありがとうございます！
entriesの個所の翻訳が難しく悩んでいました、、、提案いただいたものを使わせていただきます。
callbackの冒頭も、わかりやすくなるように変更しました。
問題なさそうであれば、翻訳可能になり次第、アップしたいと思います。

[先のコメント中翻訳文](https://github.com/mozilla-japan/translation/issues/524#issuecomment-765907655)に反映しました

**Comment by hmatrjp** [comment]
冒頭の変更も見ました。良いと思います。お疲れ様でした。

**Comment by ShirasuGyoza** [comment]
こちらは翻訳完了、マージ済みのためクローズします。
