### ISSUE TITLE
BigInt.prototype.toString()の翻訳

### ISSUE THREAD

**Issue by shigef** [mozilla-japan/translation#525]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/toString
を翻訳します。

**Comment by shigef** [comment]
翻訳しました。
日本語ページのURLは以下です。
https://wiki.developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/BigInt/toString

原文のExample - Negative-zero BigIntで、意訳した１文があります。
> -0.0 is an IEEE floating-point concept that only appears in the JavaScript Number type.
原文のonlyが掛かっているのはappearsだと思いますが、訳文で「〜Number型に現れるのみ〜」とするより
「〜Number型にのみ現れる〜」とした方が日本語としてもJSとしても自然だったため、後者で訳しています。
問題があればコメントいただければ訳を考え直します。

レビューをお願いいたします。

**Comment by hmatrjp** [comment]
レビューします。（1/23翻訳ミートアップにて）

**Comment by hmatrjp** [comment]
文章は、特に直すところはないと思います。

訳文フリーズの影響か、一部マクロが機能していない様子で、原文と見かけが異なる部分がありますが、今は措きましょう。

**Comment by shigef** [comment]
レビューいただきありがとうございます！

> 訳文フリーズの影響か、一部マクロが機能していない様子で、原文と見かけが異なる部分がありますが、今は措きましょう。
パラメーターのセクションの Optional の見た目の部分でしょうか？
確かに見た目も、DOM要素に付いている class も原文と翻訳で異なっていますね・・・

一旦、この翻訳のissueとしてはクローズいたします。

**Comment by hmatrjp** [comment]
そうです。Optional のところです。
翻訳ありがとうございました。
