### ISSUE TITLE
[修正依頼] 「初めてのフォーム」のライブサンプルが表示されない

### ISSUE THREAD

**Issue by wlt** [mozilla-japan/translation#527]
「[初めてのフォーム - ウェブ開発を学ぶ | MDN](https://developer.mozilla.org/ja/docs/Learn/Forms/Your_first_HTML_form)」のページで、以下の画面キャプチャのようにライブサンプルが表示されない問題を見つけました。

----

![image](https://user-images.githubusercontent.com/543234/100745285-67352280-3422-11eb-95fe-42953f536625.png)

----

後述する理由から、この修正には、[「ページの移動」を行える権限](https://developer.mozilla.org/ja/docs/MDN/Tools/Page_moving) が必要のようなので、こちらでどなたかにお願いできればと思いイシュー起票しました。

### 表示されない原因
調べてみたところ、このライブサンプルのマクロで指定されているページスラグが、

```
EmbedLiveSample('A_simple_form', '100%', '240', '', 'Learn/Forms/Your_first_form/Example')
```

なのですが、対応する **日本語の** 該当ページの URL は現状、以下のように途中に「HTML」という文字列が含まれるもので、上記スラグに該当するページは存在しませんでした。

https://developer.mozilla.org/ja/docs/Learn/Forms/Your_first_HTML_form/Example

この不一致が表示されない原因です。

### 不一致の原因
以下のような流れで発生したようです:

1. もともとは「HTML」を含むスラグでした。
1. 英語版は[ページに対するこのあたりの変更](https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form$compare?locale=en-US&to=1598221&from=1597772) と[ライブサンプルのページのこの変更](https://wiki.developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form/Example$compare?to=1597775&from=1597718)で「HTML」がはずされました。（ページの移動（スラグの変更）と、`EmbedLiveSample` マクロの引数）
1. 日本語版は[ここで英語版の新しい版を反映され](https://wiki.developer.mozilla.org/ja/docs/Learn/Forms/Your_first_HTML_form$compare?to=1620497&from=1559019)、 `EmbedLiveSample` マクロの引数だけ修正されました。（ページの移動（ライブサンプルのページ含む）は行われていません。）

上記「3.」の時点で不一致が発生しました。

以上のように、発生の経緯からして、ライブサンプルのページの移動（「HTML」をはずしたスラグに変更）をすることで不一致が解消されると考えられます。（実際にはライブサンプルだけでなく上位の[本体ページ](https://developer.mozilla.org/ja/docs/Learn/Forms/Your_first_HTML_form)ごと移動するのが適切かと思われます。）

**Comment by hmatrjp** [comment]
ご報告ありがとうございます。
応急手当として、 @dskmori さんが EmbedLiveSample の引数を合わせてくれましたが、
根本的な対処として、 @wlt さん提案のとおり、文書の移動を行いました。

なお、移動権限持ちは日本に私含めて3人しかおらず、反応が遅れることがあります。
気長にお待ちいただけると幸いです。

**Comment by hmatrjp** [comment]
とりあえず、Closeします。この件に追加で何かあれば、ReOpenしてください。

**Comment by wlt** [comment]
さっそくご対応いただきありがとうございます！
むしろ反応もらえたらラッキーぐらいの気持ちでした（こういうのはアクティブな方がいたとしても見落とされたりとか色々ありますしね。）

応急手当もやっぱりやっておいた方が良いんだなと理解しました。（ページへの一般的な訪問者にとって）
今度同じような問題にあたったときは、まず処置してから、助けを仰ぎたいと思います。
