### ISSUE TITLE
General asynchronous programming conceptsの翻訳

### ISSUE THREAD

**Issue by shigef** [mozilla-japan/translation#528]
以下の記事を翻訳します。
https://developer.mozilla.org/ja/docs/Learn/JavaScript/Asynchronous/Concepts

**Comment by shigef** [comment]
日本語記事のURLは以下です。
https://developer.mozilla.org/ja/docs/Learn/JavaScript/Asynchronous/Concepts

レビューをよろしくお願いします。

**Comment by Uemmra3** [comment]
レビューします。

**Comment by Uemmra3** [comment]
レビューしました。大筋問題ないです。差分をご確認ください。
https://wiki.developer.mozilla.org/ja/docs/Learn/JavaScript/Asynchronous/Concepts$compare?locale=ja&to=1656452&from=1656371
問題なければIssueを閉じてください。
