### ISSUE TITLE
Application の翻訳

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#529]
https://developer.mozilla.org/en-US/docs/Tools/Application
を翻訳します。

**Comment by gurezo** [comment]
@hmatrjp @Uemmra3 

質問です。
MDN Web Docs になって、翻訳手順が変わりました？
いつもの翻訳ページを生成しようとしたら UI 違う？手順が違う？翻訳始められませんでした＞＜

`Add a Translation` ボタンを見つけられませんでした＞＜

**Comment by shigef** [comment]
横からすみません。
2020/12/14のMDNの新システム移行（Yari）に伴い、現在日本語への翻訳が出来なくなっている状態です。
翻訳が再度解禁されるまでは、残念ながら、しばらく待つ必要があります。

情報元は以下のHacksの記事です。
[An update on MDN Web Docs’ localization strategy](https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/) 

SlackのJapanese Mozilla community#translationチャンネルにもいくつかコメントがあります。

ご参考になれば幸いです。

**Comment by gurezo** [comment]
@shigef 

ご連絡ありがとうございます！
解禁まで待つことにします！

**Comment by gurezo** [comment]
対象が見つからない・分からなくなったので、 close します。
