### ISSUE TITLE
Localizing MDN & Localizing_with_Verbatim

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#53]
MDN の Localization 関連ドキュメントリンク集

肝心なページである /docs/MDN/Contribute/Localize/Translating_pages は既に日本語になってるからいいナビゲーションの都合で親である /docs/MDN/Contribute/Localize から日本語に一応しておいた方が良いかもなと思ってます。

https://developer.mozilla.org/ja/docs/MDN/Contribute/Localize
https://developer.mozilla.org/ja/docs/MDN/Contribute/Localize/Translating_pages

あと Verbatim の使い方の説明がこんなところにあったので訳しておきたいかも
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_with_Verbatim

**Comment by hmatrjp** [comment]
https://developer.mozilla.org/ja/docs/MDN/Contribute/Localize
の翻訳を開始します。
-- 
濱崎

**Comment by hmatrjp** [comment]
Verbatim については、今 手を付けられそうにありません。
他にできる方がいればお願いします。

**Comment by dynamis** [comment]
Verbatim は現在 Pontoon でそちらも日本語化されているので閉じます
https://developer.mozilla.org/ja/docs/Mozilla/Localization/Localizing_with_Pontoon
