### ISSUE TITLE
GlobalEventHandlers.onauxclick の翻訳

### ISSUE THREAD

**Issue by kenji-yamasaki** [mozilla-japan/translation#531]
MDNの翻訳ツールが利用できないため、翻訳内容をこのコメントに書き出します。

---

**Comment by kenji-yamasaki** [comment]
試験中
試験中の技術です。
商用で使用される前にブラウザー互換性テーブルをしっかりと確認してください。

GlobalEventHandlers ミックスインの onauxclick プロパティは auxclick イベントを処理するための EventHandler です。

auxclick イベントは入力を行っているデバイスで主要でないボタン (例えば、マウスの真ん中のボタン) を押した時に発生します。 mousedown と mouseup のイベントに続いて発生します。

注記: ブラウザーを提供するベンダーはボタンの振る舞いに関する互換性を改善する計画の中でこのプロパティの実装を進めています。具体的には、イベントの振る舞いを改め、click は主要なボタン (例えば、マウスの左ボタン) のクリックだけで発生し、auxclick は主要でないボタンのクリックで発生します。歴史的には、click は通常あらゆるデバイスの入力ボタンのクリックで発生するとなっており、ブラウザーの振る舞いとしては若干統一がされていませんでした。

文法
target.onauxclick = functionRef;

値
functionRef は関数の名前か関数式です。関数は単一の引数でマウスイベントを受け取ります。関数の内部では、this がイベントが引き起こされた要素です。1 つの auxclick ハンドラーがその時点でオブジェクトに割り当てられます。より柔軟であることから、 EventTarget.addEventListener() メソッドを代わりに使うとよいでしょう。

例
この例では onclick と onauxclick 、2 つのイベントハンドラーに対して関数を定義しています。前者はボタンの背景の色を変更します、一方で後者はボタンの前面の (テキストの) 色を変更します。複数のボタンのついたマウスでデモを試しに動かして ２ つの関数を確認してください。(GitHub で公開されている内容を参照したり、ソースコードを参照できます。)

注記: 3 つのボタンのマウスを使用している場合、onauxclick ハンドラーはマウスの左以外のボタンのどちらかをクリックした時に実行されることに注意してください。

**Comment by hmatrjp** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onauxclick こちらですね。
レビューします。（1/23 ミートアップにて）

なお、黄色い背景の Experimental の枠内はマクロで生成されているので、翻訳を反映する場合は本文とは別の場所からになります。

**Comment by hmatrjp** [comment]
気づいた点です。　値　セクションで、
1.　マウスイベント　は、（リンク先だけ ja に替えて）そのままの方が良さそうです。
2.　Only のニュアンスを出すため、例えば 1 つの auxclick ハンドラーが　→　1 度に 1 つの auxclick ハンドラーだけが

**Comment by kenji-yamasaki** [comment]
@hmatrjp の指摘を反映しました。

---

GlobalEventHandlers ミックスインの onauxclick プロパティは auxclick イベントを処理するための EventHandler です。

auxclick イベントは入力を行っているデバイスで主要でないボタン (例えば、マウスの真ん中のボタン) を押した時に発生します。 mousedown と mouseup のイベントに続いて発生します。

注記: ブラウザーを提供するベンダーはボタンの振る舞いに関する互換性を改善する計画の中でこのプロパティの実装を進めています。具体的には、イベントの振る舞いを改め、click は主要なボタン (例えば、マウスの左ボタン) のクリックだけで発生し、auxclick は主要でないボタンのクリックで発生します。歴史的には、click は通常あらゆるデバイスの入力ボタンのクリックで発生するとなっており、ブラウザーの振る舞いとしては若干統一がされていませんでした。

文法
target.onauxclick = functionRef;

値
functionRef は関数の名前か関数式です。関数は単一の引数で MouseEvent オブジェクトを受け取ります。関数の内部では、this がイベントが引き起こされた要素です。1 度に 1 つの auxclick ハンドラーだけがその時点でオブジェクトに割り当てられます。より柔軟であることから、 EventTarget.addEventListener() メソッドを代わりに使うとよいでしょう。

例
この例では onclick と onauxclick 、2 つのイベントハンドラーに対して関数を定義しています。前者はボタンの背景の色を変更します、一方で後者はボタンの前面の (テキストの) 色を変更します。複数のボタンのついたマウスでデモを試しに動かして ２ つの関数を確認してください。(GitHub で公開されている内容を参照したり、ソースコードを参照できます。)

注記: 3 つのボタンのマウスを使用している場合、onauxclick ハンドラーはマウスの左以外のボタンのどちらかをクリックした時に実行されることに注意してください。

**Comment by hmatrjp** [comment]
反映していただき、ありがとうございました。原文の意図をよりよく表す訳になったと思います。

**Comment by kenji-yamasaki** [comment]
合致する記事がないため、closeとします。
