### ISSUE TITLE
Worker.prototype.postMessage() の翻訳

### ISSUE THREAD

**Issue by shigef** [mozilla-japan/translation#532]
以下の記事を翻訳します。翻訳した内容はこの issue にコメントとして残します。
https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage
https://github.com/mdn/content/blob/main/files/en-us/web/api/worker/postmessage/index.html

**Comment by shigef** [comment]
---
title: Worker.prototype.postMessage()
slug: Web/API/Worker/postMessage
tags:
  - API
  - JavaScript
  - Method
  - Reference
  - Référence(2)
  - Web Workers
  - Worker
  - postMessage
---
<p>{{APIRef("Web Workers API")}}</p>

<p>{{domxref("Worker")}} インターフェースの <code><strong>postMessage()</strong></code> メソッドは、ワーカーの内部スコープにメッセージを送ります。このメソッドは引数を 1 つ受け取り、それがワーカーに送られるデータになります。このデータには、あらゆる値もしくは<a href="/ja/docs/Web/Guide/DOM/The_structured_clone_algorithm">構造化複製アルゴリズム</a>によって処理される循環参照を含んだ JavaScript オブジェクトを受け取ることが可能です。</p>

<p><code>Worker</code> は {{domxref("DedicatedWorkerGlobalScope.postMessage")}} メソッドによって生成元のスレッドへ情報を送り返すことができます。</p>

<h2 id="Syntax">構文</h2>

<pre class="brush: js notranslate">worker.postMessage(message, [transfer]);</pre>

<h3 id="Parameters">引数</h3>

<dl>
 <dt><em>message</em></dt>
 <dd>ワーカーへ渡されるオブジェクトであり、 これは {{domxref("DedicatedWorkerGlobalScope.onmessage")}} ハンドラーに渡されるイベントの <code>data</code> フィールドに収められます。このオブジェクトには、あらゆる値もしくは<a href="/ja/docs/Web/Guide/DOM/The_structured_clone_algorithm">構造化複製アルゴリズム</a>によって処理される循環参照を含んだ JavaScript オブジェクトを受け取ることが可能です。</dd>
 <dd><code>message</code> パラメーターが与えられ<em>なかった</em>場合、<code>TypeError</code> がスローされます。もしワーカーに渡すデータが重要でない場合は、<code>null</code> または <code>undefined</code> を明示的に渡すことが可能です。</dd>
 <dt><em>transfer</em> {{optional_inline}}</dt>
 <dd>所有権を渡す {{domxref("Transferable")}} オブジェクトの<a href="/ja/docs/Web/JavaScript/Reference/Global_Objects/Array">配列</a> (オプション)。もしオブジェクトの所有権が渡されると、そのオブジェクトは送信元のコンテキストからは利用できなくなり (<em>neutered</em>)、送信先のワーカーからのみ利用できるようになります。</dd>
 <dd>Transferable オブジェクトとは {{domxref("ArrayBuffer")}}、{{domxref("MessagePort")}}、{{domxref("ImageBitmap")}} のような転送可能なクラスのインスタンスのことです。<code>null</code> を <code>transfer</code> に渡すことはできません。</dd>
</dl>

<h3 id="Returns">返り値</h3>

<p>なし。</p>

<h2 id="Example">例</h2>

<p>次のコードの抜粋は {{domxref("Worker.Worker", "Worker()")}} コンストラクタを使用した {{domxref("Worker")}} オブジェクトの生成を示しています。2 つの入力フォーム (<code>first</code> と <code>second</code>) のどちらかの値が変わったとき、{{event("change")}} イベントが <code>postMessage()</code> を起動し、両方の入力値がワーカーに送られます。</p>

<pre class="brush: js notranslate">var myWorker = new Worker('worker.js');

first.onchange = function() {
  myWorker.postMessage([first.value,second.value]);
  console.log('Message posted to worker');
}

second.onchange = function() {
  myWorker.postMessage([first.value,second.value]);
  console.log('Message posted to worker');
}
</pre>

<p>例の全体は <a class="external external-icon" href="https://github.com/mdn/simple-web-worker">Basic dedicated worker example</a> (<a class="external external-icon" href="https://mdn.github.io/simple-web-worker/">run dedicated worker</a>) を参照してください。</p>

<div class="note">
<p><strong>注</strong>: <code>postMessage()</code> は一度に 1 つのオブジェクトしか送信できません。上記のように複数の値を渡したい場合は配列を送信してください。</p>
</div>

<h3 id="Transfer_Example">転送の例</h3>

<p>この例はメインスレッドから <code>ArrayBuffer</code> を <code>ChromeWorker</code> へ渡し、その後 <code>ChromeWorker</code> がメインスレッドへそれを戻す Firefox アドオンを示しています。</p>

<h4 id="Main_thread_code">メインスレッドのコード:</h4>

<pre class="brush: js notranslate">var myWorker = new ChromeWorker(self.path + 'myWorker.js');

function handleMessageFromWorker(msg) {
    console.log('incoming message from worker, msg:', msg);
    switch (msg.data.aTopic) {
        case 'do_sendMainArrBuff':
            sendMainArrBuff(msg.data.aBuf)
            break;
        default:
            throw 'no aTopic on incoming message to ChromeWorker';
    }
}

myWorker.addEventListener('message', handleMessageFromWorker);

// バッファーを生成して送信しましょう
var arrBuf = new ArrayBuffer(8);
console.info('arrBuf.byteLength pre transfer:', arrBuf.byteLength);

myWorker.postMessage(
    {
        aTopic: 'do_sendWorkerArrBuff',
        aBuf: arrBuf // 3 行下の transferable の部分に渡す配列バッファー
    },
    [
        arrBuf // 9 行上で生成した配列バッファー
    ]
);

console.info('arrBuf.byteLength post transfer:', arrBuf.byteLength);
</pre>

<h4 id="Worker_code">ワーカーのコード</h4>

<pre class="brush: js notranslate">self.onmessage = function (msg) {
    switch (msg.data.aTopic) {
        case 'do_sendWorkerArrBuff':
                sendWorkerArrBuff(msg.data.aBuf)
            break;
        default:
            throw 'no aTopic on incoming message to ChromeWorker';
    }
}

function sendWorkerArrBuff(aBuf) {
    console.info('from worker, PRE send back aBuf.byteLength:', aBuf.byteLength);

    self.postMessage({aTopic:'do_sendMainArrBuff', aBuf:aBuf}, [aBuf]);

    console.info('from worker, POST send back aBuf.byteLength:', aBuf.byteLength);
}
</pre>

<h4 id="Output_logged">ログ出力</h4>

<pre class="brush: bash notranslate">arrBuf.byteLength pre transfer: 8                              bootstrap.js:40
arrBuf.byteLength post transfer: 0                             bootstrap.js:42

from worker, PRE send back aBuf.byteLength: 8                  myWorker.js:5:2

incoming message from worker, msg: message { ... }             bootstrap.js:20
got back buf in main thread, aBuf.byteLength: 8                bootstrap.js:12

from worker, POST send back aBuf.byteLength: 0                 myWorker.js:7:2</pre>

<p><code>byteLength</code> は配列バッファーが転送されたときに 0 になっています。この Firefox アドオンのデモの全体はこちらを参照してください: <a href="https://github.com/Noitidart/ChromeWorker/tree/aca57d9cadc4e68af16201bdecbfb6f9a6f9ca6b">GitHub :: ChromeWorker - demo-transfer-arraybuffer</a></p>

**Comment by shigef** [comment]
Specification のセクション以下は省略してます。
Transferable オブジェクトが Worker に渡された際に、元のコンテキストから使用できなくなることを表した "neutered" のうまい訳語が分からなかったので、一旦そのままにしました。
訳語の事例や候補について、どなたかコメントを頂けるとありがたいです。

**Comment by hmatrjp** [comment]
まず、neutered のところ、考えてみたのですが、今以上の訳は思いつきませんでした。
続いて全体をレビューします。（2/20の翻訳ミートアップ中）

**Comment by hmatrjp** [comment]
見ました。ほぼ完成した訳だと思うのですが、2箇所だけ気になった点を挙げます。
1.　冒頭の2文め　　このデータには、   ・・・ 受け取ることが可能です
　　　主語と述語のミスマッチ？ 　例えば　データは・・・であることが可能です。　の方がすっきるするかと。
2. 　引数の message の説明にも、1.と似た原文からの訳で、同様のところがあります。

**Comment by shigef** [comment]
1年近くissueを放置してしまい申し訳ありません。
せっかくレビューをしていただいたのですが、既に他の方が記事を翻訳されたため、このissueはクローズします。
