### ISSUE TITLE
MDNのWiki編集ツールが一時的に使えなくなることへの対応

### ISSUE THREAD

**Issue by hmatrjp** [mozilla-japan/translation#533]
知るべきこと、やるべきこと、やったことを整理するために、Issue を1本立てます。

**（背景を把握する）**
MDNのシステム移行によるもの。　Kuma から Yari へ。

- [x] hacks ブログの記事
https://hacks.mozilla.org/2020/12/welcome-yari-mdn-web-docs-has-a-new-platform/
に現状、今後のことなど記事として書かれているが、翻訳については記述なし。（2020年12月14日付けの投稿）
さらに詳しいこと、新しいことは、チャット(Matrix)ルームへと誘導あり。　https://chat.mozilla.org/#/room/#mdn:mozilla.org

**（ミートアップ関係の文書を現状に合わせるか注記する）**
- [x] DoorKeeper のイベント説明、前日に流れるメッセージ　1/23開催用だと、 https://manage.doorkeeper.jp/groups/mozilla/events/114420/notifications
- [x] 参加者への説明　https://docs.google.com/presentation/d/1Q3seJxCUh0n5GQDvj3NPJXmUBOOzNfC-cOsawk8tVzM/

**Comment by hmatrjp** [comment]
日本語含むいくつかの言語について、早期 unfreeze の議論あり。 
**Uplift zh-CN, zh-TW, fr, ja**　https://github.com/mdn/yari/milestone/33
Due date は 2/26。

**Comment by hmatrjp** [comment]
2月11日付で hacks ブログに投稿あり。
https://hacks.mozilla.org/2021/02/mdn-localization-update-february-2021/

内容の抄訳をSlackに流れたまとめから引用：
【まとめ】

1. これまでローカライズされたページのSlug(/en-us/や/ja/以降のurl)は自由に編集できたため、ページの二重翻訳や、親ページののない迷子ページなどが多数存在してしまった。アップデート以降は、ローカライズされたページは/en-us/以下の元のページの子ページとして一律に扱う。
2. アクティブな翻訳コミュニティのいるtier1言語以外のローカライズ記事については、公開を停止する（多くの場合内容が古くてときに間違っているため）
3. 1.の二重翻訳、迷子を整理して英語の原文に対応づける作業が必要になる
4. 対応付けられないものは削除か移動を検討している。削除した場合もgitのヒストリーに残っているので復元は可能。
5. 3月はじめに Tier 1 locales について Unfrozen できたらいいな。Tier 1 locales は日本語、フランス語、中国語の繁体と簡体。

**Comment by fuzz139** [comment]
以下に、今回非公開対象となっているja記事を抜き出しました。
https://docs.google.com/spreadsheets/d/10YNykyNFvBKe8g3Tnx_A4mXXvZLDP3HW1sBn1yx0CMc/edit#gid=0

(元のリンク)
https://github.com/mdn/archived-content/

**Comment by himorin** [comment]
MDN以下はいわゆるmediawikiのProject:相当のものの扱いだった気がするのでどこかに保存しておいた方がいいのかもしれません、、？
そしてDevNews/懐かしい、、英語版はdevmoの別なカテゴリのところにあったはずなのでMDN wikiの中には対応する英語版は存在しないはずですね。もう歴史的位な意味しかないコンテンツではありますが。。

**Comment by potappo** [comment]
Slackで藤本さん(mfuji)さんが投稿されている情報をこちらにも書き留めておきます。
- 各言語の翻訳は、言語別コミュニティのレビュアー（CODEOWNERS）がプルリクエストを承認することで翻訳記事が本体にマージされる仕組みになる
- MDNのコンテンツリーダーのChris Mills氏曰く、レビュアーは2～3人がいい

今のところ、藤本さんと私がレビュアーを引き受ける予定になっていますが、他にやりたい、やる予定の方がいれば、こちらの issue にも書き込みお願いします。あと1人？なのか、もっと多くの人数がレビュアーになるかは、要相談ですが。

私のレビュー頻度をこれまでよりも上げるつもりではいますが、私が全然承認者として役に立てないと判断したときは、そのときにアクティブな貢献者に承認権限を委譲します。

日本語版は、以下のレビューの仕組みを考えています。次の 3/20 のイベント時に相談できればと思います。

※月一の翻訳イベントでレビューを行うだけでは遅くなるので、それ以外の時も考慮した仕組みを想定※

ここの既存の日本語版翻訳ガイドなどからリンクする等の形で、日本語版独自の翻訳プルリクエストガイドを用意したいと思っています。ローカルルールを明確化した方が良いと思うので。

- 承認する時間の目安の明示。実際始めてみて徐々に調整というのもあるかと思いますが、承認に24時間ないし48時間かかる（本家より早くするつもりはないので本家に合わせます）、それなりの長さがある新規翻訳文書は1週間かかることもあるなどは許容してもらうなど、承認には時間がかかることがあること、レビュー、承認を速くするためにプルリクエスト時のコメントをきちんと書いてもらうなどのルールを明示化したいです。

- 翻訳イベント時や翻訳予約をしたいときなど、今まで通りこちらにまず issue を立てて、出来たらプルリクエストする。ここでレビュー依頼してもOKだが、恐らく、プルリクエストした方が楽？
- プルリクエストにコメントするのに何か権限が必要とは思っていないですが、必要だったりする場合は従来通り、issueでレビュー運用することも考えます。

- プルリクエストを承認できる権限を持つユーザは、自身がそのリクエストを最初からレビューする、あるいは、（コメントできるならば）他ユーザの承認妥当と判断できるレビューOKコメントをもって承認を行う。レビューOKコメントをするのは承認者以外でもかまわないというルールにする。イベント時や承認者のその時々の許容量を超える量のリクエストに対応するため。

- 出来ればチェックツールを用意し、プルリクエスト前にチェックしてもらう、レビュアーはそれを用いてレビューにかかる時間を短縮させるなどの工夫を徐々にでも作る。

**Comment by hmatrjp** [comment]
> レビュアーは2～3人がいい

の根拠が気になるところですが、それ以外は全面的に @potappo さんのコメントに賛成です。

**Comment by hmatrjp** [comment]
肝腎なことを書いてなかった。**私もレビュアーを引き受けたいと思います**が、自分が可能な頻度を考えると、もっといた方が安心です。

**Comment by potappo** [comment]
> 承認を速くするためにプルリクエスト時のコメントをきちんと書いてもらう

mdn/translated-content のコミットを眺めていて気付きましたが、プルリクエストしたときにデフォルトコメントだと、GitHub Actions でエラーにしているようです。
https://github.com/mdn/content/issues/782
他にもテンプレートとかあるっぽいので、日本語版向け翻訳PRテンプレートとか作れるかもしれません。
https://github.com/mdn/content/pull/2906

レビュアー人数については、なるほどです。私も、将来的にはもっと人数がいた方が安心かと思います。

**Comment by hmatrjp** [comment]
@mfuji09 slack のダイレクトメッセージと一部重複しますが、ご容赦ください。
Chris Millsさんからの回答とも一致していて、藤本さんの解釈どおりであることがわかりました。　https://github.com/orgs/mdn/teams/yari-content-ja
私がレビュアー陣就任の声かけをしたいのは、（私から見て）MDN翻訳ミートアップで参加が多い方と、レビュー件数の多い方たちです。 取り急ぎ github のidが手元ですぐにわかる方のみ、列挙してしまいます。 @Uemmra3 @marsf @fuzz139 @dynamis @kenji-yamasaki もりさんのIDが見つからない。。。

一方で「3人」の根拠として挙がっている「早く始めた方がいい」というのにも賛成で、声掛けはするけど、次に進むのに返事を待つ必要はないという認識です。

**Comment by dynamis** [comment]
@hmatrjp お声掛けありがとうございます。折角ですので＆人数が多い方が良いという意図のお話のようですので、最近アクティブさが低いですが参加させて頂ければ幸いです。

> もりさんのIDが見つからない。。。
@dskmori ではないでしょうか。是非 @dskmori さんも。

**Comment by mfuji09** [comment]
@hmatrjp さん、皆さんに呼び掛けてくださり、ありがとうございます。確かに、普段の日本語コミュニティの活動量からすれば、3人でこなすのは大変そうですね。
後は翻訳が再開するのを待つばかりですね。リポジトリ周りの準備はおおむね整っているようなので、まもなく再開されるのではないかと思います。

**Comment by potappo** [comment]
現状、翻訳レポジトリの日本語版ページへの issue、pull request は、以下のラベルで追うことができます。

https://github.com/mdn/translated-content/labels/l10n-ja

翻訳レポジトリは全言語なので、reason:review-requested を優先的に見る、issue に対しては、上記ラベルで管理するしかなさそうです。fr の方が積極的にラベル付けしてくださっています。

**Comment by unarist** [comment]
ラベル付けもworkflowで自動化するとか、言語ごとのissueテンプレートをラベル指定付きで作ってもらうとかできるといいかもですね。

----

ところでmdn/translated-contentのissuesとmozilla-japan/translationのissuesの使い分けはどうなるんでしょう。現状mdn側のissuesは英語で書かれているものが多く、英語が基本になるのかな？という印象を受けたんですが、もし向こうに寄せていくのであれば日本語でも書ける（ことがわかりやすい）ようにしたいと思いました。

**Comment by potappo** [comment]
>ところでmdn/translated-contentのissuesとmozilla-japan/translationのissuesの使い分けはどうなるんでしょう。

言語ごとの issue テンプレートみたいなものが出来れば、mdn メインにしても良いかもしれないですが、毎月の翻訳イベントでの翻訳ページ宣言のようなローカル的なものは、今後もこちらを使うというような使い分けになるかと思います。

>日本語でも書ける（ことがわかりやすい）ようにしたい

これはそうしたいですね。

**Comment by potappo** [comment]
https://whatsdeployed.io/s/16d/mdn/translated-content
上記サイトで、マージされたコミットが実際にサイトに反映されたかどうかがわかります。自分が承認してマージした pull request が反映されているのを確認できました。Prodにチェックが付けばOKです。
上記サイトだと時間が経つと流れると思うので、実際に反映されたURLも記載しておきます。
https://developer.mozilla.org/ja/docs/MDN/Contribute/Where_is_everything

**Comment by hmatrjp** [comment]
@dynamis github のチーム https://github.com/orgs/mdn/teams/yari-content-ja への 招待は届いているでしょうか？
（Chris Mills さんから） 3日くらい前だと思います。見つからなければ、招待を再送してもらいます。

**Comment by hmatrjp** [comment]
このIssueのコメントに書かれているのは、
システム移行について知ったところから、新システムでの新しいレビュアーの決定、今後の進め方の入口まで、あたり。
次のステップに進むため、一度閉じます。目先のこととしては、案内文書の書き換えがあります。 #542

DoorKeeper のイベント案内文は、[4/17開催分](https://mozilla.doorkeeper.jp/events/119827)から書き換えてあります。
