### ISSUE TITLE
「<iframe>: インラインフレーム要素」の誤字

### ISSUE THREAD

**Issue by k08045kk** [mozilla-japan/translation#535]
https://developer.mozilla.org/ja/docs/Web/HTML/Element/iframe

> srcdoc
> 埋め込むインライン HTML で、 src 属性を上書きします。ブラウザーがブラウザーが srcdoc 属性に対応していない場合は、 src 属性の URL で代替されます。

↓

> srcdoc
> 埋め込むインライン HTML で、 src 属性を上書きします。ブラウザーが srcdoc 属性に対応していない場合は、 src 属性の URL で代替されます。

本リポジトリのWiki等を読みましたが新システムの誤字の報告・修正方法がわかりませんでした。なので、ここに報告します。

**Comment by hmatrjp** [comment]
ご報告ありがとうございます。
現在、システム改修の一貫としてMDNの翻訳ページの編集機能が凍結されており、すぐに反映できない状態です。
編集機能が復旧し次第、反映作業ができるよう目印としてこの Issue に Yari ラベルを付けました。
