### ISSUE TITLE
Web/JavaScript/Reference/Global_OBjects/Number 内のコードブロックが右寄せになっている

### ISSUE THREAD

**Issue by sarisia** [mozilla-japan/translation#539]
Number - JavaScript | MDN
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number#convert_numeric_strings_and_null_to_numbers 

上記ページの "数字や null を数値に変換する" 項のコードブロックが右寄せに設定されていますが,
原文では左寄せとなっています.

![image](https://user-images.githubusercontent.com/33576079/108590944-7c7a7700-73a9-11eb-8e76-80360dd81e5e.png)

**Comment by hmatrjp** [comment]
報告ありがとうございます。
ソースを覗いてみると、該当部分のブロック直前、`<pre>`ブロックの中に `dir="rtl"` という指示がありました。
現在、MDNのシステム移行（Kuma→Yari）に伴い翻訳の編集機能が一時的に凍結されていますが、凍結が解除されたら反映できるよう、Yari ラベルを付けておきます。

**Comment by mfuji09** [comment]
https://github.com/mdn/translated-content/pull/83 にて修正が完了していますので、ご確認ください。

**Comment by sarisia** [comment]
修正を確認しました。ありがとうございました！
