### ISSUE TITLE
翻訳レビュー担当ルールについて

### ISSUE THREAD

**Issue by potappo** [mozilla-japan/translation#544]
現レビュアー以外の方の意見もあれば聞きたいので、こちらに issue を立てます。

pull request (以下、PR) に割り当てられるレビュアーですが、現状、ja チームメンバーからランダムにアサインされるようで、変えることはできないとのこと。

※割り当てアルゴリズムは2種類存在する模様。
[GitHubのヘルプ](https://docs.github.com/ja/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team)

レビューを滞りなく行うために、以下のルールを設けようと思いますが、いかかがでしょうか。
※レビュアーはマージ権限まで持っていますので、他レビュアーが担当している PR もマージすることができるかと思います。

- 翻訳イベントで出された PR については、当日イベント参加しているレビュアーが優先的にレビューする
- レビューリクエスト、または、最後のレビュアーのコメントから7 日間経ったものについては他レビュアーがレビューすることを可能にする。7 日を超えてレビューを続行する意思がある場合は、PR にコメントする。
 
1 つ目は、なるべく、イベント当日のレビューを可能にするためです。
2 つ目は担当レビュアーがレビューする時間が取れない場合（GitHubで busy かどうかのステータスを変えれば、候補から除かれるのかと思いますが、それすらも出来ないことはあり得るので）への対応です。期間に関しては、7 日間という期間について、もっと長くする、もっと短くするはあって良いかと思います。

**Comment by mfuji09** [comment]
方針について、わたしは全面的に賛成です。
ここ数日やってきて、7日間はちょっと長いかなという気がしますので（未レビューのPRがたくさん溜まりそう）、3日間くらいのほうがいいかもしれないと思いました。

**Comment by hmatrjp** [comment]
方針案ありがとうございます。 @potappo 
3日間 @mfuji09 に賛成です。　投稿した方にとっても、7日間は長いかも。
https://github.com/mdn/translated-content#requirements-for-keeping-locales-up-to-date　は満足するんですけどね。

**Comment by potappo** [comment]
@mfuji09  @hmatrjp コメントありがとうございます。
7 日間はだいたいの最大値で提案したので、3 日間でも良いかと思います。それでやってみましょう。
レビュアー向けページをここの Wiki のどこかに作って、後で参照できるようにしてから、クローズします。

**Comment by potappo** [comment]
以下にページを作成しましたので、クローズします。
レビュー基準等は、レビュアーであれば、だいたいの共通認識があるもの、として記載していませんが、今後、認識のずれなどの問題が出てくれば、随時ルールを追加していく方向で良いかと思います。

https://github.com/mozilla-japan/translation/wiki/MDN_about_review
