### ISSUE TITLE
日本語版独自の KumaScript マクロの削除

### ISSUE THREAD

**Issue by mfuji09** [mozilla-japan/translation#547]
MDN では、英語版で使用されていない KumaScript のマクロを廃止したいとのことです。
（詳しい議論は https://github.com/mdn/yari/issues/3063 をご覧ください。）
日本語版でよく使われているマクロとしては、下記の物が該当します。

kumascript/macros/英語版章題.ejs 439
kumascript/macros/訳注.ejs 118
kumascript/macros/原語併記.ejs 88
kumascript/macros/訳語.ejs 6

これらのマクロの一括削除（マクロの実行結果での置き換え）も提案されていますが、これらのマクロは意味論的な使い方もされていますし、これらのマクロは古い記事に使われている傾向があるため、修正が二度手間になる可能性もあります。

そこで、集中してこれらのマクロを他の表記に置き換える（必要に応じて、その記事の翻訳を見直す）作業を行いませんか。

**Comment by mfuji09** [comment]
基本的な方向性としては、以下のようなものが良いのではないかと思いますが、文脈によって変わってくる可能性もあると思います。ご意見があれば議論をお願いします。

- 英語版章題
新プラットフォームではidの自動修正がなくなったので、役目を終えたと思います。削除し、見出しについているidを英語版記事の物に付け替えた方が良いと思います。
- 訳注
普通の注（Note）に置き換え、見出しを「訳注」とする。なお、本文内に収めるべき訳注は（訳注: ×××）のように表記する。
- 原語併記・訳語
日本語の語を基本に英語を括弧で併記する（例: 属性 (attribute)）。または、日本語の語に対して英語をルビで表現する。

**Comment by marsf** [comment]
原語併記は役立つのであれば残して良いよと言われてますね。
https://github.com/mdn/translated-content/pull/611#issuecomment-824180614

マクロに表記以外の処理がないので ( ) で置き換えてしまってよいと思います。ただし訳語をルビで表記するのは、ルビの使い方として読者が想定するものではない（ルビは補足や説明ではない）し混乱します。

**Comment by potappo** [comment]
いずれのテンプレートも MediaWiki 時代からあったものです。一応、歴史的説明を書いておきますが、mfuji さんの提示した方向性で置き換えてしまって良いと思います。

英語版章題は MediaWiki では必要だったので利用していましたが、それ以降のシステムでは上手く移植できずに使われなくなり、英語版の id を維持するためにわざわざ name 属性を追加する必要もなくなった今の Yari では、もう使いどころがないと思います。

訳注、原語併記、訳語は、意味論的に使われてきた側面もあるかと思いますが、使うためには知っていなければいけないというデメリットもあるので、置き換えて問題はないかと思います。特に、訳語に関しては、残っている使用数からも、知る人ぞ知るテンプレートになっているのかと思います。

>ただし訳語をルビで表記するのは、ルビの使い方として読者が想定するものではない（ルビは補足や説明ではない）し混乱します。

これに対しては同意します。MediaWiki テンプレートからのスタイルをそのまま継承しているだけなので、無理に再現にこだわる必要はないかと思います（今思えば、MediaWiki の次システムである DekiScript への移植時に直せば良かったかもですが、あまり使わないのもあり、そのまま移植してしまったのかもしれないです）。

**Comment by mfuji09** [comment]
皆さん、ありがとうございます。なるほど、私が想像していたよりずっと古いものだったんですね。
原文をルビではなく括弧表現のみにするというのは、私もそれでよいと思います。

ただ、機械的に置き換えると文脈に合わない箇所が出てくるかもしれませんし、そもそもこれらのマクロが使われている記事は古いものが多いので、これらのマクロを含む記事についてはマクロを置き換えつつ、翻訳を見直すように進めていきたいと思います。

**Comment by mfuji09** [comment]
すべての対応が完了したようなので、この Issue を閉じます。
