### ISSUE TITLE
Understanding client-side web development tools の翻訳

### ISSUE THREAD

**Issue by tmstar** [mozilla-japan/translation#554]
以下のベージの翻訳を行います。
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools

**Comment by hmatrjp** [comment]
公開されているので、閉じます。
https://developer.mozilla.org/ja/docs/Learn/Tools_and_testing/Understanding_client-side_tools

リポジトリではこちら：
https://github.com/mdn/translated-content/tree/main/files/ja/learn/tools_and_testing/understanding_client-side_tools
