### ISSUE TITLE
(orphaned) Bugzilla-ja/jp に関するページ

### ISSUE THREAD

**Issue by mfuji09** [mozilla-japan/translation#560]
https://github.com/mozilla-japan/translation/issues/548 および https://github.com/mdn/translated-content/issues/1832 関連

MDN の orphaned の中に Bugzilla-ja/jp に関するページがあります。
https://developer.mozilla.org/ja/docs/orphaned/Bugzilla-ja
https://developer.mozilla.org/ja/docs/orphaned/Bugzilla-jp

どちらも日本または日本語版独自の取り組みについて書いた文書のようですが、内容は古く、積極的に保守されていないように思えますので、このまま放置しても混乱のもとになってしまうのではないかと思います。

どこかに移動するか、それともそのまま削除するか、どちらかの対応が必要だと思いますが、どうしましょうか。

**Comment by potappo** [comment]
文書が保守されていないようなので、削除で良いと思います。
