### ISSUE TITLE
用語集  Static typing を翻訳します。

### ISSUE THREAD

**Issue by uidev1219** [mozilla-japan/translation#563]
以下ページの翻訳を行います。
https://developer.mozilla.org/en-US/docs/Glossary/Static_typing

**Comment by potappo** [comment]
レビューしてマージしましたが、1点だけ。
PR 時の issue 番号には、頭に mozilla-japan/translation を付けてください。PR ページは修正しておきました。

※後で気が付きましたが、既にマージ済の PR 番号だったので影響なし。

**Comment by uidev1219** [comment]
わかりました。ありがとうございました。
