### ISSUE TITLE
Element.scrollHeightの翻訳に「幅」という語が出てくる

### ISSUE THREAD

**Issue by ftnext** [mozilla-japan/translation#573]
翻訳ありがとうございます。日本語で読めてとても助かっています。

`Element.scrollHeight`の訳で気になる箇所を見つけたので報告です。
https://developer.mozilla.org/ja/docs/Web/API/Element/scrollHeight

## 1箇所目

英語
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight
>The Element.scrollHeight read-only property is a measurement of the height of an element's content, including content not visible on the screen due to overflow. 

日本語
>Element.scrollHeight は読み取り専用のプロパティで、あふれて画面上に表示されない部分を含めた、要素の中身の幅の寸法です。

「a measurement of the *height* of an element's content」の訳が「要素の中身の*幅*の寸法」となっているのが誤訳ではないかと思いました。
要素の中身の幅の寸法 → 要素の中身の**高さ**の寸法 が適切と考えます。

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollWidth の訳を元にした際に、幅→高さという置き換えが漏れてしまったのかもしれません。

## 2箇所目

英語
>It can also include the height of pseudo-elements such as ::before or ::after. 

日本語
>これには ::before または ::after のような擬似要素の幅を含むことがあります。

こちらも同様に、元の語がheightなので、幅→高さとなると考えます

**Comment by hmatrjp** [comment]
お知らせありがとうございます。
確かに、幅より、高さのほうが適切ですね。（scrollWidthから、訳を流用された可能性があります。）

こちらに、和訳が格納されているのですが、
https://github.com/mdn/translated-content/blob/main/files/ja/web/api/element/scrollheight/index.html
該当部分(14行目と、16行目でしょうか)を（右上のペンのアイコンから）直接編集して、Pull Request を出すことで、修正依頼をかけることができます。

**Comment by hmatrjp** [comment]
直接修正しました。　（12月のMDNミートアップにて）
https://github.com/mdn/translated-content/commit/529c7fd30ad22e5d4860e4374a45763bcc598c76#diff-7f6b9422647fb860c24fde224549f13a7870427d4333509c01afee8f1111f0c8

MDNサイトで表示される内容には、まだ反映されていないようです。

**Comment by hmatrjp** [comment]
MDNサイトに反映されました。

**Comment by ftnext** [comment]
修正いただき、ありがとうございました
