### ISSUE TITLE
Mozilla 翻訳フォーラムやMozilla 翻訳グループのアーカイブ化

### ISSUE THREAD

**Issue by Guest126** [mozilla-japan/translation#575]
[Mozilla 翻訳フォーラム](http://forums.firehacks.org/trans/)や[Mozilla 翻訳グループ](https://groups.google.com/g/mozilla-translations-ja)は現在ほとんど使われていないため、新規の投稿を停止し、こちらのGithubリポジトリ（またはSlack）に移行した旨を大々的に掲載した方が良いのではないでしょうか。

## Mozilla 翻訳フォーラム

活発だったのは2010年頃までで、昨年の投稿は[1件](https://forums.firehacks.org/trans/viewtopic.php?t=4107)のみでした。2016年にフォーラムが[部分的にロック](https://forums.firehacks.org/trans/viewtopic.php?t=8050)されていますが、ロックを免れたところで今年に入ってから[数十件のSPAM投稿](https://forums.firehacks.org/trans/viewforum.php?f=30)が続いており、管理が行き届いていないように思われます。

また、同じドメイン配下にある[Mozilla L10N フォーラム](https://forums.firehacks.org/l10n/)も昨年新規投稿がなかったことから、同様にロックして構わないように思います。

## Mozilla 翻訳グループ

活発だったのは2018年までで、2019年は4件、2020年は1件、2021年は5件と投稿が低調でした。各スレッドの閲覧回数も30回程度です。

Google グループのヘルプによると、[グループ メンバーによる投稿を停止する](https://support.google.com/groups/answer/2646833?hl=ja)ことができるようです。

一応ヘッダテキストからGithubへの誘導も行われているのですが、スクロールしないと見えない位置にあるため、親切ではないと感じています。

### メリット

* GithubやSlackにアカウントを持っていない（作れない・作りたくない）人でも投稿できる
* 使い慣れている人には古い方が使いやすいかもしれない

### デメリット

* 議論の場所が分散する
* 活動実態がないように思われてしまう
* SPAM削除など管理の手間が掛かる

もはやデメリットの方が大きいため、ライブで残しておく必要はないと考えています。

**Comment by hmatrjp** [comment]
ご提案ありがとうございます。

Mozilla 翻訳フォーラムは個人（私の記憶通りなら @dynamis ）の負担で保持しているドメイン上で動いているので、最終的な措置はその判断次第、という前提で：
・活動実態がないように思われてしまうからロックして github なりslack なりに誘導するべき、という論に賛成一票です。
・実は私も一部のモデレーター権限をいただいていますが、この数年ほとんど見ていません。

Mozilla 翻訳グループは、私もたまに投稿したくなることがあります。（昨年の5件のうち、1件は私でした。）
github、slack への登録者と違うユーザー層にも届くことを期待してのことです。（どれくらいユーザー層に違いがあるのか具体的に調べたことはありません）

フォーラム、グループをかつては活発に使っていた1ユーザーの意見です。他の方からもご意見いただければと思います。

**Comment by marsf** [comment]
firehacks.org の翻訳 / L10N フォーラムは mozillazine.jp と同じサーバーで動いているはずです (ただし firehacks ドメインは @dynamis さんの私物)。

今までコミュニティからの意思表示がなかったため、そのまま維持していました。
L10N に関しては一度 saneyuki さんから Github に一本化してはという意見があっただけですが、日本語版の作業用リポジトリーが trac → Google Code → Github と移行していく中で意見集約の場として継続的に役目を果たしたことは記しておきます。

> デメリット
>     議論の場所が分散する
>     活動実態がないように思われてしまう
>     SPAM削除など管理の手間が掛かる

少なくとも最近 10 年間で、フォーラムの利用を停止するかどうか検討するほどの、上記のようなデメリットはありませんでした。フォーラム admin としての感想です。



例えば 2 週間くらい期間をおいて、使いたいという要望がなければ、すべてロックさせていただきます。

**Comment by Cai0407** [comment]
一応 L10N フォーラムのモデレータ権限持ちです。
・翻訳フォーラムは、ここ 5 年以上にわたり実質的に動いていない。
・L10N フォーラムは、ここ数年は Google Code や Github へエスカレーションすることがほとんど。
という状況ですので、どちらも Github、Slack への誘導を確保したうえでロックすることに賛成します。

翻訳グループについては賛否を保留します。

**Comment by potappo** [comment]
翻訳フォーラムの MDN フォーラムを昔使っていましたが、今はもう使っていないので、他がロックされるなら、まとめてロックしてもらってかまいません。

翻訳グループに関しては、濱崎さんの意見のように、メールで情報が欲しいという需要がどれくらいあるかという感じですね。議論の場としての存在意義はもう薄いかと思います。

**Comment by Guest126** [comment]
デメリットの具体例を述べておきます。どうして私がこんなことを言い出したかというと、[MPL 2.0日本語訳にあたっての付記](https://note.com/note_s/n/nf17f5151c834)を書いた2020年7月当時、

>WebDINO Japanが引き継いだMozilla関連ドキュメント翻訳グループは今年に入ってから一度も投稿がなく、活動実態が見えないことから、自ら翻訳した方が早いと判断した。

ということがあったからです。私の調べ方が甘かったと言われればそうなのですが、当時は[Mozilla Japan コミュニティポータル](https://web.archive.org/web/20200721034230/https://www.mozilla.jp/)からも[Mozilla 翻訳＆ローカライズコミュニティ Wiki](https://github.com/mozilla-japan/translation/wiki)にはリンクが張られていなかったので、GoogleグループからGithubにごっそり移行したとは知る由もありませんでした。

その後、活動実態を調べるため Slack に登録して [Mozilla Public License Version 2.0の翻訳レビュー依頼](https://github.com/mozilla-japan/translation/issues/502)へバトンを繋げていただいたことで最終的にはコミュニティ訳の公開に漕ぎつけることが出来ましたが、私訳とコミュニティ訳の2度手間になってしまったことは否めませんし、私が面倒くさがって Slack への登録をしなければ今ここにいることはなかったと思います。

**Comment by marsf** [comment]
[L10N フォーラム](https://forums.firehacks.org/l10n/index.php)と[翻訳フォーラム](https://forums.firehacks.org/trans/)をロックしました。
L10N フォーラムは 2003年10月05日から、翻訳フォーラムは 2003年5月22日から運用されていました。

Mozilla 翻訳グループの現在のオーナーは dynamis, marsf, 井上さん（他にいなかったっけ？）になってます。どうするかは保留中。
ここで発言のあった @Cai0407 さん、@hmatrjp さん、@potappo さんをマネージャーに変更しておきました。

**Comment by dynamis** [comment]
今頃気付きました＆ロック対応ありがとうございます。

もういつか忘れてしまった遙か昔に、各フォーラムの立ち上げ・カスタマイズなどは行ったが何年も完全にお任せモードになっており、ほぼ何もお手伝いできない状態になっていたことは申し訳ない限りです。

github/slack 側に集約された方が (フォーラムのシステムメンテナンスが出来ていないので) 安心かつフィードバックも増えるだろうと思い何年か前に github repo の立ち上げやそちらへの誘導強化などはしたものの、使ってもらえる限りは維持しておく方が良いし、利用者が完全にゼロではなかった＆「存続していることによるデメリットはあまり感じていない」という管理者意見を mar さんから聞いていたことから AS IS で残していた状況でした。

外部からの流入も日々の活動も既にほぼ github/slack に集約されたし、安心してロックやアーカイブ化に進められる時期に入ったのだと思います＆ロック実施ありがとうございます。

今後当面はロックしたまま維持し、何処かで(過去の議論は参照可能にすべきなので)完全にアーカイブとしての出力を残しつつクローズするのが良いのだろうと思っております。

**Comment by dynamis** [comment]
修正したい誘導元の修正タスクリスト:

- [ ] https://github.com/mozilla-japan/translation
- [ ] https://github.com/mozilla-japan/translation/wiki
- [x] https://github.com/mozilla-japan/gecko-l10n はアーカイブ化済みとの記載に変更済み

**Comment by hmatrjp** [comment]
上の投稿にある項目の
 https://github.com/mozilla-japan/translation/wiki ページ、
本文末尾にある、フォーラムのところに、注記しました。（アーカイブ目的で、新たに投稿できないこと）

サイドバーからは消えているので、二番目のチェック入れておきます。

**Comment by dynamis** [comment]
https://github.com/mozilla-japan/translation はコミュニティのコミュニケーションチャネルとして、Slack に加えて (slack は 90 日でログが見られなくなる＆検索で出てこないよねという話があり) disussions の案内や月例ミートアップの案内などを追加した。

取りあえず主だったところからの誘導は無くなってると思うのでクローズ。
こちらに限らず wiki の細かなページの確認、更新はまた随時。
