### ISSUE TITLE
Yari時代の翻訳補助を考える

### ISSUE THREAD

**Issue by unarist** [mozilla-japan/translation#586]
Kuma 時代は以下のような機能を持ったUserScriptがありました。

* 見出しのidを英語のままにするためのname属性付与
* 自動翻訳もとい置換
  * 見出しや互換性表などのよくある語句
  * アルファベットと日本語の間に半角スペースを自動挿入
  * /en-US/docs/ → /ja/docs/
  * etc.
* 翻訳中フラグをオフに、編集レビューをオンに
* タグを元記事からコピー
* 編集コメントに元記事のリビジョン番号を自動入力

https://github.com/mozilla-japan/translation/tree/master/MDN

Yari / GitHub 運用になって不要になった機能もある一方で、今でも一部機能は便利そうです。

* 見出しのidを英語のままにするための `## hoge` → `<h2 id="hoge">hoge</h2>` 変換
* 定型文の自動翻訳（どこまでやるかは相変わらず迷う）
* いわゆる校正・スタイルガイド適用（表記揺れ、長音、スペース）
* タグの同期（まとめてコピペできるのでそれでもいいかも）

ので、なんか考えたいなというか、実験のメモとかの置き場としてissueを起こしてみました。

**Comment by unarist** [comment]
以下のような路線があるだろうか。

* cloneせずGitHub上で編集しちゃう人向け
* cloneする人向け
  * 外部エディタ（VSCodeとか）向け
    * textlint や prh みたいな既存のツールに乗っかれると楽かもしれない
    * 設定ファイルの置き場に悩むかもしれない
  * `yarn start` で生えるあれの組み込みエディタを魔改造？
    * 原文との比較とかもやれそうではある
  * エディタを作る？？

で、とりあえず prh のルールをやっつけで作ってみた。

* vscode-prh-extension を使ってみたが、ちょっと古くて動きが微妙
  * VSCodeのQuickFixから修正ができず、拡張が生やしたコマンドで一括修正しかできない？
* スペースの調整とかは textlint にルールがあるのでそっちでやるといい気がする
  * が、textlint-rule-prh を使うとHTMLタグを巻き込んだ置換とかできない気がする
  * タグ指定置換の代わりに完全一致 `/^hoge$/` とかでもいいかもしれない？

**Comment by mfuji09** [comment]
> 見出しのidを英語のままにするための ## hoge → <h2 id="hoge">hoge</h2> 変換

Markdown化以降、IDは各国語に翻訳することになったようです。
実際、EmbedLiveSample()などのマクロも、IDではなく文書構造で引用部分を決定するようになりましたし、Page()マクロも廃止が進んでいます。

**Comment by unarist** [comment]
おっと、そんなことになっていたんですね。手間が減っていい話。

[Wikiにもこの書き換えの話が残っていた](
https://github.com/mozilla-japan/translation/wiki/Get-started-with-translation-of-Mozilla-documentations#%E3%83%A9%E3%82%A4%E3%83%96%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%9E%E3%82%AF%E3%83%AD%E3%81%8C%E5%A4%B1%E6%95%97%E3%81%99%E3%82%8B)ので、折を見て修正するとよさそうですね。

**Comment by potappo** [comment]
> [Wikiにもこの書き換えの話が残っていた](https://github.com/mozilla-japan/translation/wiki/Get-started-with-translation-of-Mozilla-documentations#%E3%83%A9%E3%82%A4%E3%83%96%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%9E%E3%82%AF%E3%83%AD%E3%81%8C%E5%A4%B1%E6%95%97%E3%81%99%E3%82%8B)ので、折を見て修正するとよさそうですね。

ひとまず、改善されたという情報と、ここへのリンクだけ追加しておきました。来月以降に追加修正します。

**Comment by mongolyy** [comment]
@unarist 

> cloneする人向け

普段使っているのがVS Codeでないこともあって、ローカルでチェックできるツールをtextlint + prhで作ってみました（unaristさんも作っていればすみません 🙇 ）
prhのルールはunaristさん作のものを参考にさせていただきました。
https://github.com/mongolyy/mdn-textlint-ja/tree/main

meetupでhmatrjp（濱崎）さんらに、作ったものをどうすればいいか伺ったところ、お役立ちツールのところ（ https://github.com/mozilla-japan/translation/tree/master/MDN ）に移動させたらいいのでは？と、アドバイス頂いたのでそうしようと思っています。
「こうした方がいいよ！」みたいなご意見ありますか？
@hmatrjp

**Comment by hmatrjp** [comment]
参考のため mongolyyさんの投稿に補足しておくと、mongolyyさんには、Uemmra3 にお願いしてこのリポジトリ(mozilla-japan/translation)の権限を付与する予定です。

unaristさん作の TranslationHelper.user.js は、コードがリポジトリに入っていることと、Project も使ってますね。
https://github.com/mozilla-japan/translation/projects/1

それから、Issue にも、TranslationHelper 用のラベルが設定してあります。

**Comment by potappo** [comment]
レビューしていて、新規参加者の方だと空白が足りないなどの同じような指摘があるので、mongolyy さんのツールをちょっと動かしてみようと思ったら、インストールで警告が出たので、issue を立てました。

https://github.com/mongolyy/mdn-textlint-ja/issues/1

モジュールのバージョンアップとかで解決するのだと思うのですが、手元に本格的な node 開発環境がないのでひとまず現時点での調査結果を貼り付けています。

**Comment by potappo** [comment]
mongolyy さんのツールが使えるようになったので、以下、メモ書きです。翻訳ガイドか Wiki のどちらかに改めてまとめます。

- mdn-textlint-ja をチェックツールとして紹介する。textlintプラグインを複数含んでいるので、プラグインを個別に使っても良いかもしれません的なことを書く。空白チェックは textlint-rule-ja-space-between-half-and-full-width。
  -  textlint-rule-preset-ja-technical-writing のルールチェックで出る日本語表記関係のエラーに従うことは必ずしも必須ではない（よい文章とするために参考にはなるが、MDN 日本語版ではそこまで厳密にルール化していないものもある）ので、参考程度に、の但し書きが必要。

**Comment by unarist** [comment]
> prhのルールはunaristさん作のものを参考にさせていただきました。

@mongolyy 活用していただきありがとうございます！

多分あれHTMLタグがpatternに含まれているものは textlint-rule-prh だと動かない（タグを除去したあとのテキストに対して適用された気がする）…というか、今はHTMLほとんど登場しないと思うので、その辺は削るか直すかするとよいはず。。

**Comment by mongolyy** [comment]
@unarist 
アドバイスありがとうございました。

> 今はHTMLほとんど登場しないと思うので、その辺は削るか直すかするとよいはず

確かに動作しないことが確認されたので、パターンからHTMLタグは削除しました。
mongolyy/mdn-textlint-ja#6

**Comment by Uemmra3** [comment]
こんにちは、本件（新しい方の権限追加）まだ対応必要そうでしょうか？

2022年3月12日(土) 15:48 Takeshi HAMASAKI ***@***.***>:

**Comment by mongolyy** [comment]
@hmatrjp 
> こんにちは、本件（新しい方の権限追加）まだ対応必要そうでしょうか？

今のリポジトリ（[mongolyy/mdn-textlint-ja](https://github.com/mongolyy/mdn-textlint-ja)）から当初想定していたリポジトリ（mozilla-japan/translation）にツールを移動してもいいと思っています、いかがしましょうかね？

**Comment by hmatrjp** [comment]
[mozilla-japan/translation](https://github.com/mozilla-japan/translation) の下（TranslationHelper.user.js の入っている MDN と並列）に、一つディレクトリを作って、格納したら良いのではと思います。Readme.md は専用のものがあったほうが良いと思うので。

**Comment by hmatrjp** [comment]
このリポジトリに対して [Admin アクセスがある](https://github.com/orgs/mozilla-japan/people/mongolyy)ので、必要な操作はできると思いますが、なにかわからないことがあればまた随時どうぞ。 @mongolyy

**Comment by mongolyy** [comment]
@hmatrjp 
> [mozilla-japan/translation](https://github.com/mozilla-japan/translation) の下（TranslationHelper.user.js の入っている MDN と並列）に、一つディレクトリを作って、格納したら良いのではと思います。Readme.md は専用のものがあったほうが良いと思うので。

アドバイスありがとうございます。
週末にやってみようと思います 🙇 

> このリポジトリに対して [Admin アクセスがある](https://github.com/orgs/mozilla-japan/people/mongolyy)ので、必要な操作はできると思います

失礼いたしました 🙇

**Comment by mongolyy** [comment]
@hmatrjp
権限的には私でもマージできるように思いますが、念のためプルリクエストを作成いたしました。
お時間あるときで構わないのでレビューをお願いいたします 🙇 
https://github.com/mozilla-japan/translation/pull/673
@potappo

**Comment by hmatrjp** [comment]
#673 が閉じて、
https://github.com/mozilla-japan/translation/tree/master/MDN/textlint
に追加され、一段落しているようですので、こちらも一度閉じます。
必要でしたら再オープンしてください。
