### ISSUE TITLE
[MDN] 開発ツール - パフォーマンス

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#60]
[Firefox 40 でパフォーマンスツールが刷新された](https://hacks.mozilla.org/2015/06/new-performance-tools-in-firefox-developer-edition-40/) ので MDN の解説ページを更新したい:

https://developer.mozilla.org/ja/docs/Tools/Performance

**Comment by yyss** [comment]
更新しました。

**Comment by mantaroh** [comment]
最新に翻訳していただき、更新も追従確認。
