### ISSUE TITLE
MDN Web Docs の `Tools` 以下の移管または削除

### ISSUE THREAD

**Issue by mfuji09** [mozilla-japan/translation#609]
MDN Web Docs では Firefox の開発ツールの使い方を示した `Tools` ディレクトリ以下が https://firefox-source-docs.mozilla.org/devtools-user/ 以下に移管されました。
ただ、移管先のシステムには多国語対応機能がないため、現在登録されている日本語訳を受け入れることができません（多国語化の方針も、まだ決まっていないようです）。

また、英語版のドキュメントは既に削除されているため、日本語訳も削除が求められています。
https://github.com/mdn/translated-content/pull/4875

既に翻訳されている文書の分量も多いので、できれば、 mozilla-japan のリポジトリでこのディレクトリ以下を保持しておくことはできないでしょうか。

**Comment by potappo** [comment]
リポジトリを作成しました。

https://github.com/mozilla-japan/mdn-devtools-user

**Comment by mfuji09** [comment]
@potappo さん
ありがとうございました！
