### ISSUE TITLE
[MDN] writing-mode

### ISSUE THREAD

**Issue by makotokato** [mozilla-japan/translation#61]
英語のページが全く別物になったので、日本語のページも一から翻訳する必要があります。
https://developer.mozilla.org/ja/docs/Web/CSS/writing-mode

なお、Firefox 41でデフォルト有効になるので、そこまでにする必要があります。

**Comment by marsf** [comment]
{{cssbox("writing-mode")}} の内容が「\*Value 'initial-writing-mode' not found in DB\*」になっている部分について、
[Template:cssbox](https://developer.mozilla.org/en-US/docs/Template:cssbox) に書かれた各一覧ページ (このエラーメッセージでいう「DB」のページ) を更新する必要があります。
cssbox マクロに書かれた KumaScript では、既定値を以下のページから抜粋して表示しています。
```
var syntaxPageURL        = p + "Web/CSS/CSS_values_syntax";
var animatedPageURL      = p + "Web/CSS/CSS_animated_properties";
var serializationPageURL = p + "Web/CSS/CSS_values_serialization";
var percentagesPageURL   = p + "Web/CSS/CSS_percentage_values";
var specialPageURL       = "/en-US/docs/Web/CSS/CSS_special_properties"; // Need to look at the English page, here!
```

**Comment by marsf** [comment]
翻訳しました。

DB の一覧ページは、"Web/CSS/CSS_percentage_values" を除いて更新しました。
CSS_percentage_values は未訳なので他の CSS プロパティでも en-US が読み込まれます。

**Comment by makotokato** [comment]
ありがとうございます
