### ISSUE TITLE
Getting started with Svelte の翻訳

### ISSUE THREAD

**Issue by SuzukiKatsuma** [mozilla-japan/translation#612]
"Getting started with Svelte" を翻訳します。

### 当該ページ
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started

**Comment by dynamis** [comment]
Svelte! 楽しみ！ (意味の無いコメントスミマセンｗ)

**Comment by SuzukiKatsuma** [comment]
マージされたので閉じます。
