### ISSUE TITLE
CSS の where()

### ISSUE THREAD

**Issue by hmatrjp** [mozilla-japan/translation#613]
https://developer.mozilla.org/en-US/docs/Web/CSS/:where
について、slack に誤訳の報告が来ていました。　https://mozillajp.slack.com/archives/C5N6SFQMP/p1653826063280009
内容を確認して、必要な修正をします。　（MDN翻訳ミートアップにて）

**Comment by hmatrjp** [comment]
PR出しました。
https://github.com/mdn/translated-content/pull/6360
ついでに、未訳の部分も
https://github.com/mdn/translated-content/pull/6359
で翻訳しています。

**Comment by potappo** [comment]
レビューの上、マージしました。クローズします。
