### ISSUE TITLE
Web Componentsの誤字を修正する

### ISSUE THREAD

**Issue by Nkzn** [mozilla-japan/translation#614]
シャドウDOMの項に誤字がありましたので、修正が必要です
https://developer.mozilla.org/ja/docs/Web/Web_Components#%E3%82%B7%E3%83%A3%E3%83%89%E3%82%A6_dom

- 誤: このイベントがシャドウ DOM 境界を超えて標準 DOM にまで **電波** する場合は
- 正: このイベントがシャドウ DOM 境界を超えて標準 DOM にまで **伝播** する場合は

**Comment by hmatrjp** [comment]
ありがとうございます。修正が反映されているので、閉じますね。
