### ISSUE TITLE
ブログ記事(What to Look Forward to from Firefox)

### ISSUE THREAD

**Issue by mantaroh** [mozilla-japan/translation#62]
[Mozilla Future Release blog](https://blog.mozilla.org/futurereleases/)にて掲載された「What to Look Forward to from Firefox」の記事を翻訳協力して頂ける方を募集しています。

[What to Look Foward to from Firefox](https://blog.mozilla.org/futurereleases/2015/07/02/what-to-look-forward-to-from-firefox/)
この記事は、Firefox でこれからの戦略を記載されたものです。

翻訳したドキュメントの掲載場所は特に指定しませんので、ご自身の Github や ブログ等で構いません。
なお 翻訳して頂いた記事は、Mozilla Japan ブログにて翻訳者を明記のうえ、記載させていただきたいと考えてます。

**Comment by sakyou31** [comment]
英語初心者なのですが翻訳させていただきたいです。
締切等ありますでしょうか。。

**Comment by mantaroh** [comment]
ありがとうございます！
デッドラインは特に決めていませんが、今月中に翻訳頂けると嬉しいです。

**Comment by dynamis** [comment]
ブログポストよりも詳しい詳細版が ML で追加公開されました。元のブログでも良いですが、こちらの詳細版にしていただくのも歓迎です。いずれにしても翻訳の参考になるかと:

https://groups.google.com/forum/#!topic/firefox-dev/SdlSCH34uz4

**Comment by sakyou31** [comment]
ありがとうございます！
それでは詳細版をさせていただきます！

**Comment by dynamis** [comment]
ブログポストは Gigazine のニュースで採り上げられたようです。翻訳の参考になるかも知れません:

http://gigazine.net/news/20150708-firefox-big-change/

**Comment by sakyou31** [comment]
ありがとうございます！><

**Comment by sakyou31** [comment]
遅くなりましたが翻訳させていただきました。
宜しくお願い致します。
https://blog.mozilla.org/futurereleases/2015/07/02/what-to-look-forward-to-from-firefox/
<hr>
<div>
	<p>
		私たちは10年以上前に、オンラインに透明性と選択、コントロールを人々に与えることをミッションとしてFirefoxを創りました。以来、ブラウザはユーザーのWeb体験とオンライン生活の制御における重要な役割を進化させ続けています。
	</p>
	<p>
		We created Firefox more than a decade ago with a mission to give people transparency, choice and control online. Since then, the browser has continued to evolve its critical role in how users experience the Web and control their online lives.
	</p>
	<p>
		そのためMozillaは常に、Firefoxをどのように改善してユーザを楽しませ続けられるのかということに焦点を当ててきました。大部分の技術系企業とは異なりMozillaは取り組みをオープンにする組織ですから、私たちが戦略的に注力する3つの分野についての実験的な取り組みをご紹介します。
	</p>
	<p>
		That’s why at Mozilla we’re always focused on one question: how do we make Firefox even better and continue to delight users? Because we are different than most tech companies and work in the open, we are sharing some experiments centered around the three focus areas of our strategy.
	</p>
</div>
<div>
	<img src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/futurereleases/files/2015/07/Firefox_Pillars-600x372.png"/>
</div>
<div>
	<h2>妥協のない品質</h2>
	<p>
		第一に重視しているのは、品質やパフォーマンスの最も厳しい基準を満たし、妥協のないユーザーエクスペリエンスを提供することです。これを実現してきていることは、HTML5のビデオ再生やゲームのパフォーマンスといったWebで最もリッチな体験を進化させていることから明らかでしょう。また、FirefoxをiOSやWindows 10などの新しいプラットフォーム用にも、標準搭載ブラウザとは別の高性能な選択肢として提供します。
	</p>
	<p>
		The first focus area is delivering an uncompromised user experience that ensures Firefox meets the most rigorous of quality and performance standards. This commitment is evident in the strides we’re making to improve the richest Web experiences like HTML5 video playback and game performance.  We’ll also soon deliver Firefox to new platforms, such as Firefox for iOS and Windows 10, where we will provide an independent and high-performing alternative to the stock browser.
	</p>
</div>
<div>
	<h2>Webにおける最高の存在</h2>
	<p>
		Firefoxは「モダンブラウザ」の境界を押し広げるとともに、ユーザーにWeb体験の完全なコントロールを与えることでよく知られています。技術革新を伝え、Webで最高の体験をFirefoxで提供するため、私たちはいま世界中のより多くのパートナーや技術者と共に取り組んでいます。検索に関するFirefoxの新しい戦略では選択と革新を促進していくことを示しました。Telefonicaとの提携の元で開発した初のブラウザ内蔵WebRTCビデオチャットツールFirefox Helloなどのように、Web標準に基づく新しいオープンな技術を示してきています。私たちは、開発プラットフォームとしてWebを前進させるために、WebVR、WebGL、WebRTCを含めオープンスタンダードを開拓し続けています。
	</p>
	<p>
		Firefox is well known for giving users complete control over their Web experience while pushing the boundaries of the “modern browser.” Today, we’re working with more partners and developers around the world to highlight innovation and offer the best of the Web in Firefox. We showed this with our new search strategy for Firefox to promote choice and innovation and with new open technologies we build based on standards including Firefox Hello, the first WebRTC in-browser video chat tool made in partnership with Telefonica. We continue to pioneer open standards including WebVR, WebGL and WebRTC to advance the Web as the development platform.
	</p>
</div>
<div>
	<h2>Firefoxだけ</h2>
	<p>
		今年の初めにユーザーにFirefoxの何が他のブラウザと異なるかを調査した結果、パフォーマンス、信頼、品質といった私たちのミッションに沿った特徴でFirefoxを認識してもらうことが重要だと再確認しました。
	</p>
	<p>
		Earlier this year, we asked users to identify what’s different about Firefox and the results reaffirmed our view that it’s important for Firefox to be increasingly recognized for attributes such as performance, trust and quality that align with our mission.
	</p>
	<p>
		私たちはユーザが選択する権利と、ユーザのプライバシーを守る為、ユーザが私たちを信頼してくれていると考えています。これら3つの領域に焦点を当てたメジャーリリースでFirefoxユーザに提供しています。
	</p>
	<p>
		We value that our users trust us because we protect their choices and protect their privacy. That’s why we are experimenting with improvements to private browsing and other unique features for a major release focused on these three areas that we’ll share with Firefox users later this year.
	</p>
</div>

**Comment by lv7777** [comment]
横から失礼します。
真ん中の段の
＞検索に関するFirefoxの新しい戦略では選択と革新を促進していくことを示しました。
というのが気になりました。

それと 
＞FireFoxだけ
というのもちょっと気になりました。

僕も翻訳初心者ですので全く検討違いの事を言っていたらすみません。

**Comment by mantaroh** [comment]
遅くなってすみません。
ステキな翻訳ありがとうございます！

> We showed this with our new search strategy for Firefox to promote choice and innovation and with new open technologies we build based on standards including Firefox Hello, the first WebRTC in-browser video chat tool made in partnership with Telefonica.   

1 文前の「世界中のより多くのパートナーや技術者と共に取り組んでいる」ことを、以下の2つで示しましたという事を述べた文だと思います。
- Firefox の新しい検索戦略(選択と革新の推進)
- 新しいオープンテクノロジー(Mozilla が標準技術を用いて構築したもの。Telefonica と共同で作成した Web RTC を使った最初のブラウザ内ビデオチャットである Firefox Hello も含む)

そのために、現在2文に分かれている文が何に対する説明なのかを示したら、もっとわかりやすい文書になるかと思います。

**Comment by sakyou31** [comment]
皆さんご指摘ありがとうございます！
これを機にもっと英語の勉強頑張ります><。

**Comment by Uemmra3** [comment]
MJブログで公開すみなので、閉じますね。
