### ISSUE TITLE
リクエスト: Math.PI の更新

### ISSUE THREAD

**Issue by K0baU** [mozilla-japan/translation#626]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Math/PI

## 更新内容・備考・ヘルプ

 - 「**Math.SQRT2** プロパティは、円周と直径の比率、およそ 3.14159 を表します。」を「**Math.PI** プロパティは、円周と直径の比率、およそ 3.14159 を表します。」に修正する必要があります

**Comment by potappo** [comment]
ありがとうございます。修正したものを Pull Request しました。
