### ISSUE TITLE
ブログ記事(Mozilla Games Technology Roadmap)

### ISSUE THREAD

**Issue by mantaroh** [mozilla-japan/translation#63]
[Mozilla Future Release blog](https://blog.mozilla.org/futurereleases/)にて掲載された「Mozilla Games Technology Roadmap」の記事を翻訳協力して頂ける方を募集しています。

[Mozilla Games Technology Roadmap](https://blog.mozilla.org/futurereleases/2015/07/02/mozilla-games-technology-roadmap/)
この記事では、ゲーム開発に関する技術ロードマップを紹介したものです。

翻訳したドキュメントの掲載場所は特に指定しませんので、ご自身の Github や ブログ等で構いません。
なお 翻訳して頂いた記事は、Mozilla Japan ブログにて翻訳者を明記のうえ、記載させていただきたいと考えてます。

**Comment by Uemmra3** [comment]
興味ありますけど、マイルストーンはどれくらいでしょうか？
〜7/7くらいまでならできそうです。

2015年7月3日(金) 13:30 Mantaroh <notifications@github.com>:

**Comment by mantaroh** [comment]
ありがとうございます！！
マイルストーンは明確に決めてないので、7月7日でも大丈夫です。

**Comment by Uemmra3** [comment]
アルゼンチン時間ですが、とりあえず翻訳しました！
誤訳や表現のご指摘お待ちしております！

http://d.hatena.ne.jp/Uemmra3/20150707

**Comment by hmatrjp** [comment]
ロードマップの中の ブラウザストレージの節の中で：

周波数のようなアカウント要因を考慮に入れるため、
→Frecency のような要因を考慮に入れるため、

Frecency は、頻度(frequency) だけでなく recency も計算に入れるための要素です。
MDN では日本語ページの解説でもそのまま使われているところもありました。
https://developer.mozilla.org/ja/docs/The_Places_frecency_algorithm

また、ここの account は、take into account というひと続きの熟語として使われているのだと思います。

**Comment by Uemmra3** [comment]
おお、ありがとうございます！

2015年7月10日 7:54 hmatrjp <notifications@github.com>:

**Comment by mantaroh** [comment]
ご連絡遅くなって、すみません。
翻訳、ありがとうございました！

後日、ブログに掲載させていただきますね。

**Comment by mantaroh** [comment]
公開：http://www.mozilla.jp/blog/entry/10494/
ありがとうございましたー！！

**Comment by Uemmra3** [comment]
MJブログで公開すみなので、閉じますね。
