### ISSUE TITLE
クリップボードとのやりとり の更新

### ISSUE THREAD

**Issue by mather** [mozilla-japan/translation#635]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

## 更新内容・備考・ヘルプ

英文では `execCommand` が deprecated であることが一行目から明記されており `navigator.clipboard` を先に紹介しています。
日本語訳ではこの内容を追従できていないため、再翻訳をするべきだと思います。

英文ページ: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

「js クリップボード」などのキーワードで検索上位に出てくることが多いため、修正いただけるとありがたいです。

**Comment by debiru** [comment]
作業リクエストのトピックなので対応します。
