### ISSUE TITLE
ブログ記事(What to Look Forward to from Firefox OS)

### ISSUE THREAD

**Issue by mantaroh** [mozilla-japan/translation#64]
[前回](https://github.com/mozilla-japan/translation/issues/63)に続いて、[Mozilla Future Release Blog](https://blog.mozilla.org/futurereleases/)にて掲載された「[What to Look Forward to from Firefox OS](https://blog.mozilla.org/futurereleases/2015/07/17/what-to-look-forward-to-from-firefox-os/)」の記事を翻訳協力して頂ける方を募集しています。

[What to Look Forward to from Firefox OS](https://blog.mozilla.org/futurereleases/2015/07/17/what-to-look-forward-to-from-firefox-os/)
この記事では、これからの Firefox OS の戦略について書かれたものです。

翻訳したドキュメントの掲載場所は特に指定しませんので、ご自身の Github や ブログ等で構いません。
なお 協力して頂いた記事は、[Mozilla Japan ブログ](http://www.mozilla.jp/blog/)にて翻訳者を明記のうえ、記載させていただきたいと考えてます。

**Comment by ycatch** [comment]
やらせてください。
よろしくお願します。

**Comment by mantaroh** [comment]
宜しくお願いします！

**Comment by ycatch** [comment]
こんな感じで訳してみました。まだ、ドラフト版です。
皆さんのご意見など頂ければ助かります。

--------------------

Firefox OSに期待できること - What to Look Forward to from Firefox OS
=======================================================

https://blog.mozilla.org/futurereleases/2015/07/17/what-to-look-forward-to-from-firefox-os/

[Firefox OS](https://www.mozilla.org/firefox/os/2.0/)は、私たちのモバイル戦略にとって、[Firefox for Android](https://www.mozilla.org/firefox/android/)や他の構想と合わせて、重要な構成要素です。私たちにとって、オープンで、独占的な１ベンダーに依存しない他のプラットフォームを構築することは、健全なモバイルエコシステムの未来にとって重要だと信じています。そして、私たちのミッションの核は、オンラインライフのオープン性とイノベーションの機会を広めることにあります。

[Firefox OS](https://www.mozilla.org/firefox/os/2.0/) is an important part of our mobile strategy, in addition to [Firefox for Android](https://www.mozilla.org/firefox/android/) and other initiatives. We believe that building an open, independent alternative to proprietary, single-vendor platforms is critical to the future of a healthy mobile ecosystem. And it is core to [our mission](https://www.mozilla.org/mission/) to promote openness, innovation and opportunity in online life.

オープンソースプロジェクトとして、私たちは、他の技術系企業と異なり、私たちの仕事と計画をオープンに進めています。そこで、私たちの計画とFirefox OSの次の段階で試みようとしている最新情報を簡単に共有したいと思います。

As an open source project, we are different from other tech companies and do most of our work and planning in the open, so we want to share a brief update of what we're planning and what we'll be experimenting with for the next phase of Firefox OS.


構想の出発点 - Ignite Initiative
---------------------------------------

今年の初めに、私たちは、Firefox OSを次の段階に進めることを発表しました。そこでは、クリーンで現代的で簡単に使うことができるコア製品としてフォーカスし、拡張性と優れたデザイン、ユーザーが自分たちの体験を制御できる機能を強力に実現しようとしています。

Earlier this year, we shared that we were moving to the next phase of Firefox OS, where we would focus on the core product experience to ensure that it is clean, modern and easy-to-use, and yet powerful through its extensibility, clever design and features that put users in control of their experience.

私たちの目標は、次世代のFirefox OSを作り上げることです。それは、強力で、一層統合された製品体験を持ち、最高のWebのショーケースとして、私たちの価値の見本となる開発プラットフォームです。

Our aim is to build the next generation of Firefox OS with a stronger, more unified product experience and developer platform that exemplifies our values by showcasing the best of the Web.

これを成し遂げるため、私たちは、3つのキーアイデアと共に目指していきます。

To accomplish this, we are bringing three image key ideas together:

- ユーザーにフォーカス：私たちは、人々が愛することができる、ユーザーを中心としたデザインと調査、発展する製品による体験を提供していくことを保証します。
- Webプラットフォーム：私たちの製品の構築を通じて、Webテクノロジー以上のモジラとオープンWebの多くを人々にもたらします。
- コミュニティ：開発者とデザイナ、さらに未来の構築を手助けしてくれる人々による私たちのグローバルコミュニティに十分に力を与えます。

- User focus: Ensuring that we're delivering an experience that people love through user-centered design, research and product iteration
- Web platform: Bringing more of Mozilla and the Open Web to people than just the Web technologies upon which our products are built
- Community: Rallying and fully empowering our global community of developers, designers, and more to help build the future together

![three image key ideas](http://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/futurereleases/files/2015/07/ignite-image.png)

このビジョンを実現するため、私たちは、週ごとの開発スプリントをベースにした6ヶ月ごとのメジャーリリースにより、単一のFirefox OSのオープンソースコアに開発モデルを移行します。

To deliver upon this vision we are immediately moving to a development model where we will drive a single open source core of Firefox OS, with major releases every six months, based upon weekly sprints.

各メジャーリリースでは、重要なユーザーとプラットフォームの価値を提供し、Androidフォンに囲い込まれたくない人たちや、B2GDroid(AndroidでFirefox OSの画面を実現するアプリ)を使う人たちに最終的な体験を直接届けられるようにし、全てのプロジェクトで新しい機能のテストとフィードバックを手助けするよう努めていきます。私たちは、これらのメジャーリリースによるFirefox OSベースのデバイスを構築・供給するパートナー(例えば、OEM事業者や通信事業者)もサポートしていきます。

Each major release will strive to deliver significant user and platform value, and will be available directly to anyone who wants to flash an unlocked Android phone or run through B2GDroid (an app that allows you to experience Firefox OS on Android) to get the latest experience, help test new features and to contribute back to the overall project. We will also support our partners (i.e. OEMs and operators) who will build and ship Firefox OS-powered devices based upon these major releases.


Firefox OS 2.5
-------------------

Firefox OSの次のメジャーバージョンは、この11月に予定しています。ドラフト版のロードマップとプランを[こちら](https://wiki.mozilla.org/Firefox_OS/Releases/2.5)で見ることができます。

The next major version of Firefox OS is now scheduled for this November.  You can view the draft roadmap and plan [here](https://wiki.mozilla.org/Firefox_OS/Releases/2.5).

Firefox OS 2.5は、さらにカスタマイズ可能で安全になり、地域に密着して、Firefox OSによる体験で力を与えます。ローカルコンテンツ対応とパーソナライズ、プライバシー機能に加えて、FirefoxOSの[コンセプトビデオ](https://www.youtube.com/watch?v=kv2uJUKscu0&feature=youtu.be)をモバイル環境で実現するよう計画しています(注記：最終的な機能セットやデザインは、まだ開発中です)。そして、セキュリティモデルを刷新し、新しい[モバイルWeb APIs](https://developer.mozilla.org/en-US/docs/WebAPI)を提供すると共に、Firefoxライクな拡張メカニズムをユーザーインターフェースと電話機能に追加します。

Firefox OS 2.5 will be the most customizable, secure, locally relevant and empowering Firefox OS experience yet. In addition to local content, personalization and privacy features, we plan to enable the [mobile equivalent of "View Source"](https://youtu.be/kv2uJUKscu0) (note: we're still evaluating and designing the final feature set), revamp our security model to expose more of the new [mobile Web APIs](https://developer.mozilla.org/en-US/docs/WebAPI) to developers and enable a Firefox-like extension mechanism to add to the user interface and phone capabilities.


新しい製品の開発 - New Product Development
---------------------------------------------------------

私たちは、Firefox OSによる[スマート TV](https://blog.mozilla.org/blog/2015/05/14/first-panasonic-smart-tvs-powered-by-firefox-os-debut-worldwide/)や[フィーチャーフォンのスマート化](https://blog.mozilla.org/blog/2015/03/01/new-category-of-firefox-os-phones/)といった、これまで[発表](https://blog.mozilla.org/blog/2015/03/01/firefox-os-proves-flexibility-of-web-ecosystem/)してきた主要なパートナーとの新しい製品の開発を強化していきます。

We are also ramping up focused new product development efforts with key partners, building on recent [announcements](https://blog.mozilla.org/blog/2015/03/01/firefox-os-proves-flexibility-of-web-ecosystem/) about Firefox OS [Smart TVs](https://blog.mozilla.org/blog/2015/05/14/first-panasonic-smart-tvs-powered-by-firefox-os-debut-worldwide/) and [Smart Feature Phones](https://blog.mozilla.org/blog/2015/03/01/new-category-of-firefox-os-phones/), and active explorations into the Internet of Things and other connected device opportunities.

続報に期待してください。

Stay tuned for more.


--------------------------------------------------------------------------------------------------
From Mozilla Future Release Blog

Creative Commons Attribution Share-Alike License v3.0 or any later version.

Japanese transration by catch.

**Comment by mantaroh** [comment]
Firefox の製品名ですが、
Firefox for Android → 「Android 版 Firefox」ですー。

素敵な翻訳ありがとうございます！

**Comment by ycatch** [comment]
mantarohさん、ご指摘ありがとうございました。
先の投稿を直接修正しました。

**Comment by Uemmra3** [comment]
we are bringing three image key ideas together.
の"together"の所ですが、3つのアイデアを「いっぺんに」or「一緒に」目指す、という事になると思います。
# 図でもそうなってるので
私の主観ですが ycatchさんが訳された「共に」だと、Mozillaが誰かと「共に」目指すように見えます。

**Comment by Uemmra3** [comment]
「Webプラットフォーム」のところ、「モジラ」とカタカナにされていますが、「Firefox の製品名」と同じ理由で「Mozilla」の方がよいかと。

私は下記の用語集(Mozilla全般とFirefox OSの2つがありますが)を参考にしています。
https://github.com/mozilla-japan/translation/wiki#%E7%BF%BB%E8%A8%B3%E6%99%82%E3%81%AE%E7%94%A8%E8%AA%9E

**Comment by ycatch** [comment]
Uemmra3さん、フィードバックを、ありがとうございました。

  we are bringing three image key ideas together.

なるほどというところもあると同時に、「成し遂げるために、3つのアイデアと共に目指す」の"目指す"がヘンだなと思いまして、こんなふうにしました。

  これを成し遂げるため、私たちは、イメージとなる3つのキーアイデアを採用します。

**Comment by Uemmra3** [comment]
さみだれでスミマセン(酔っぱらいです)
Firefox OS 2.5 〜 yet.
のyetは「まだまだ」「さらに」あたりでどうでしょうか？

**Comment by ycatch** [comment]
Uemmra3さん、ありがとうございます。

> Firefox OS 2.5 will be the most customizable, secure, locally relevant and empowering Firefox OS experience yet.
Before
> Firefox OS 2.5は、さらにカスタマイズ可能で安全になり、地域に密着して、Firefox OSによる体験を強化していきます。
After
> Firefox OS 2.5は、さらにカスタマイズ可能で安全になり、地域に密着して、Firefox OSによる体験を一層強化していきます。

「一層強化していきます」としました。
「まだまだ強化して」は、ちょっと座りが悪く、「さらに」は、その直前で使っているので。

**Comment by Uemmra3** [comment]
MJブログで公開すみなので、閉じますね。
