### ISSUE TITLE
用語集 - Table Wrapper Box と Table Grid Box の翻訳

### ISSUE THREAD

**Issue by hskwakr** [mozilla-japan/translation#642]
## 翻訳対象ページ (原文 URL)

https://developer.mozilla.org/en-US/docs/Glossary/Table_Wrapper_Box
https://developer.mozilla.org/en-US/docs/Glossary/Table_Grid_Box

## 備考・ヘルプ

(特になし)

**Comment by hmatrjp** [comment]
2点めの方を先に。おそらくそれで合っています。absolutely 云々は、absolute でないなら異なる場合もある、ということを示唆していると思います。
（参考）[包含ブロックの識別](https://developer.mozilla.org/ja/docs/Web/CSS/Containing_block#%E5%8C%85%E5%90%AB%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%AE%E8%AD%98%E5%88%A5)

2つの Box の説明から読み取れるのは、
・1つのtable に対して 1つの Table Wrapper Box は1つしか存在しない
・1つの Table Wrapper box 内に、複数の Table Grid Boxが存在し得る
・Table Wrapper Box は table のキャプションを含む
の3つで、1点めの質問に添えていただいた図は、少なくとも最初と最後の2つの点で異なっています。

**Comment by hskwakr** [comment]
自分が間違えてる部分を発見できました。詰まってた部分を抜け出すことできそうです。
助けていただいてありがとうございます。

**Comment by hskwakr** [comment]
該当のプルリクエストが承認、マージされたのでクローズします。
