### ISSUE TITLE
[MDN] Firefox OS Add-ons

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#65]
アドオンが Firefox OS にやってくる〜ってことでそのドキュメントが日本語で読みたい人がいっぱいいるはず！

https://developer.mozilla.org/Firefox_OS/Add-ons

**Comment by mantaroh** [comment]
アドオンに関連する Spark / DeveloperMode についての記事も！
https://developer.mozilla.org/en-US/Firefox_OS/Spark
https://developer.mozilla.org/en-US/Firefox_OS/Developer_Mode

**Comment by kechol** [comment]
Firefox OS アドオン、他のOSにはない面白い機能ですね。時間があったのでとりあえずひと通り訳しました。

https://developer.mozilla.org/ja/Firefox_OS/%E3%82%A2%E3%83%89%E3%82%AA%E3%83%B3

レビューをお願いできれば幸いです。

特に気になった点としては、原文のFilterに関する記述で、

> A regular expression that is matched against the names of the apps you want to affect with the add-on. In this example, the add-on targets all apps.

のようにアプリ名に対してマッチする、とある部分と

> Filters are RegEx expressions that are matched against the URL of the page being loaded to determine whether or not that app is targeted by the add-on. The following are examples of possible filters:

URLに対してマッチする、とある部分があり、それぞれそのまま訳しているつもりです。URLに対してマッチする、というのが正しいような気がしますが、前者の文意を取り違えているようなことがあればご教示頂ければ幸いです。

**Comment by dynamis** [comment]
パッケージ型アプリの app://fm.gaiamobile.org みたいな URL だとアプリ名な感じがするし、ホスト型アプリの https://m.facebook.com みたいな URL だとページ (サイト) な感じがしますが、どちらも両方含んだ形での filter になるのでどちらも間違いとまでは言わない説明のぶれなんだと思います。
URL じゃなくてドメイン名 (もしくはアプリ ID) だけのマッチングだろ！と思いますけどね。

ということで翻訳は問題ないと思います。
