### ISSUE TITLE
PointerEvent.getCoalescedEvents() の更新

### ISSUE THREAD

**Issue by SuzukiKatsuma** [mozilla-japan/translation#652]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/API/PointerEvent/getCoalescedEvents

## 更新内容・備考・ヘルプ

原文が新しくなっていたため更新をします。

**Comment by hmatrjp** [comment]
レビューします。

**Comment by hmatrjp** [comment]
PR の Related Issues に書く Issue 番号の前に、 Fixed と入れておくと、Merge されたときに自動的にこちらが Close されます。
9438 の PR を Edit してから Merge して、確認しました。
