### ISSUE TITLE
Background Fetch API の翻訳

### ISSUE THREAD

**Issue by neko-kawaii-nyan** [mozilla-japan/translation#658]
## 翻訳対象ページ (原文 URL)
https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API

**Comment by neko-kawaii-nyan** [comment]
翻訳完了しましたのでレビューお願いいたします。

**Comment by neko-kawaii-nyan** [comment]
関連ページの翻訳もこのissueで管理してよろしいでしょうか？それとも別立てすべきでしょうか。

いま着手したい関連ページは以下です。
- https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchManager
- https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchManager/fetch
- https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchManager/get
- https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchManager/getIds

**Comment by debiru** [comment]
> 関連ページの翻訳もこのissueで管理してよろしいでしょうか？それとも別立てすべきでしょうか。

issue については、少なくとも mozilla-japan リポジトリ上では厳密なルールはなく、何なら issue を立てることすら必須ではないので、自由に issue を使っていただくのが良いかと思います。つまり、別立てすべき理由は特にありません。今回の場合であれば、1つの issue でまとめて作業を管理した方が分かりやすいように（個人的には）思います。

issue を立てるのは、主に他人との作業が重複しないようにする目的のためのようです。 issue を立てることすら必須ではないと書きましたが、作業記録を残すという意味では、常に mozilla-japan リポジトリ上で issue を立てるのが良いかとは思います。

また、PR (Pull-Req) についても、1つの PR で複数ページを扱うこともしばしば行われています。

ただし、レビューが困難になるようなページ数（数百ページ以上など）の場合は、レビューがしやすい分量に PR を分割して作業するように工夫されているようです。

**Comment by neko-kawaii-nyan** [comment]
ご回答ありがとうございます！
今回はページ数がさほど多くないので、このissueで作業することにします。

**Comment by neko-kawaii-nyan** [comment]
BackgroundFetchManager, BackgroundFetchEventを翻訳しました。
レビューお願いいたします。

**Comment by neko-kawaii-nyan** [comment]
翻訳を二点追加しました。
ご確認よろしくお願いいたします。

**Comment by neko-kawaii-nyan** [comment]
完了したので閉じます。
