### ISSUE TITLE
[MDN] About MDN is not found

### ISSUE THREAD

**Issue by makotokato** [mozilla-japan/translation#66]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1194626

Now, this is 404 page.  We should translate https://developer.mozilla.org/ja/docs/MDN/About to Japanese.

**Comment by hmatrjp** [comment]
About MDN のページを訳しました。MDC 時代に書かれていたライセンスについての記述も流用しています。

Bugzilla の方は resolved になっていたので何もしていません。

**Comment by dynamis** [comment]
完了しているようなので close します。
