### ISSUE TITLE
[SUMO] Tracking Protection in Private Browsing

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#67]
Fx42 からの Tracking Protection に関する記事は UI からもリンクされているので重要。誰か訳してくれる人プリーズ。

https://support.mozilla.org/ja/kb/tracking-protection-pbm

**Comment by hashedhyphen** [comment]
始めまして。 hashedhyphen と申します。
これから翻訳します。

**Comment by hashedhyphen** [comment]
翻訳が終了しました。
どなたかレビューをお願い致します…。

**Comment by hashedhyphen** [comment]
dskmori さんにレビューしていただきました。
ありがとうございます！

**Comment by dynamis** [comment]
ありがとうございました！

実際の UI ラベルは製品自体の日本語化が進んだ時点でまた更新できれば良い感じですね:
https://dxr.mozilla.org/mozilla-central/source/browser/locales/en-US/chrome/browser/aboutPrivateBrowsing.dtd
https://github.com/mozilla-japan/gecko-l10n/blob/master/ja/browser/chrome/browser/aboutPrivateBrowsing.dtd
などで UI ラベルは定義されている様子
