### ISSUE TITLE
リクエスト:ARIA ライブリージョン の更新

### ISSUE THREAD

**Issue by hiroya-uga** [mozilla-japan/translation#670]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

## 更新内容・備考・ヘルプ

原文が新しくなっているため、更新をお願いします。
この違いはReactなどのCSRページ開発者を混乱させる恐れがあります。

### 日本語版

> メモ: 支援技術はライブリージョンへのコンテンツの動的な変更を通知します。ライブリージョンはブラウザーと支援技術が認識できるように最初から（かつ空で）存在しなければなりません。続いて後に起こる変更は通知されます。
>
> 単に読み込まれた最初のマークアップに aria-live 属性もしくは 特化したライブリージョン role （例えば role="alert" など）を含めても何も効果はありません。
> 
> aria-live 属性もしくは特化した role をドキュメントへ動的に追加しても支援技術による通知は発生しません (その時点で支援技術はまだライブリージョンを認識していないので、変更を監視することができません)。
> 
> 常にライブリージョンが最初からドキュメントに存在することを確認して動的なコンテンツの追加／変更をしてください。

### 原文

> Note: Assistive technologies will announce dynamic changes in the content of a live region. Including an aria-live attribute or a specialized live region role (such as [role="alert"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role)) on the element you want to announce changes to works as long as you add the attribute before the changes occur — either in the original markup, or dynamically using JavaScript.

**Comment by hmatrjp** [comment]
対応遅くなりましたが、今から確認します。（ 12月の MDN翻訳ミートアップにて）

**Comment by hmatrjp** [comment]
高度なライブリージョン のセクションから確認を続けます（4/22 翻訳ミートアップにて）

**Comment by hmatrjp** [comment]
PR が Merge されましたので、 Close します。
MDN のサイトへの反映は、おそらく明日か明後日です。
その前に反映後どのようになるかを確認したい場合は、  [PR content#12896](/mdn/translated-content/pull/12896) の Preview URL から見えます。
