### ISSUE TITLE
リクエスト: 正規表現 - アサーション の更新

### ISSUE THREAD

**Issue by miyahkun** [mozilla-japan/translation#672]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions

## 更新内容・備考・ヘルプ

"境界型のアサーション" セクション、 `\B` の説明中にある正規表現リテラルが誤っているので修正して頂きたいです。

誤

> 例えば、 /onBon/ は "at noon" の "on" に、

正

> 例えば、 /\Bon/ は "at noon" の "on" に、

原文

> For example, /\Bon/ matches "on" in "at noon",

**Comment by hmatrjp** [comment]
修正のための PR がマージされましたので close します。ご報告ありがとうございました。
