### ISSUE TITLE
[MDN] TV and Connected devices

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#68]
これから徐々に TV 系開発者向けのドキュメントが必要になってくるのであると嬉しい。

https://developer.mozilla.org/ja/Firefox_OS/TVs_connected_devices

**Comment by Uemmra3** [comment]
本文はだいたい訳しました(MDNリンク先のタイトル以外)。
翻訳者のリクルーティングの期待をこめて放置中ですー。

**Comment by dynamis** [comment]
ちょっとだけ英語が挿入されてる状態になってるので補完してくれる人まってます (Good First Translation)

**Comment by kenichisak** [comment]
2015/2/6

**Comment by dynamis** [comment]
一段落しているので close します
