### ISSUE TITLE
yari に PRを出した時の merge するまでフロー

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#681]
### 前提条件

- GPG署名が必要
- ref. https://github.com/mdn/yari/pull/6757#issuecomment-1194079148
- [mdn / yari の新しいルールのメモ](https://lifewood.hatenablog.com/entry/2022/08/24/223159)

### 現在のフロー
- yari のPRを作成
  - 対象の翻訳記事を merge されるまでマージされない
  - PRをドラフトに戻された場合もあった
- 対象の翻訳記事 のPRを作成
- 対象の翻訳記事を merge
- yari のPRを merge
  - 対象の翻訳記事を merge されて初めて、review, approve, merged される
  - 上記条件が達成されないと保留

### 課題／改善したいこと
- GPG署名が必要 => yari だけ？
  - GPG署名を不要にしたい
- yari のPRの merge までのフロー
  - 合意の上、自動的にマージできる仕組みを作りたい

### 事例

- https://github.com/mozilla-japan/translation/issues/651
- https://github.com/mozilla-japan/translation/issues/637
- https://github.com/mozilla-japan/translation/issues/623
- https://github.com/mozilla-japan/translation/issues/615
- https://github.com/mozilla-japan/translation/issues/610
- https://github.com/mozilla-japan/translation/issues/607
- https://github.com/mozilla-japan/translation/issues/599
- https://github.com/mozilla-japan/translation/issues/595

### next action ?
- MDN の discord で、聞いてみる？
  - https://discourse.mozilla.org/t/join-the-mdn-web-docs-discord/110177
- mozilla discourse で、聞いてみる？
  - https://discourse.mozilla.org/c/mdn/236

**Comment by potappo** [comment]
ディスカッションのページも紹介しておきます。
https://github.com/mdn/mdn-community/discussions
discord で直接聞けるなら、そちらの方が良いのかもしれませんが、ディスカッションだと、他の言語チームからの意見も含めて議論できるかもというメリットはあるかと思います。

**Comment by gurezo** [comment]
最新の yari が翻訳ページのタイトルを取り込む方式になったようなので、一旦close
