### ISSUE TITLE
リクエスト: HTTP Cookie の使用 の更新

### ISSUE THREAD

**Issue by netmarkjp** [mozilla-japan/translation#684]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/HTTP/Cookies

## 更新内容・備考・ヘルプ

`Cookie の接頭辞とブラウザー対応の現在の状態については、 [Set-Cookie リファレンス記事の接頭辞の節](/ja/docs/Web/HTTP/Headers/Set-Cookie# Cookie の接頭辞)を参照してください。`

の箇所について

- Markdownの記法が意図せずレンダリングされているように思います
- リンク先は `/ja/docs/Web/HTTP/Headers/Set-Cookie#クッキーの接頭辞` が適切に思います（`#`の後ろの部分）

**Comment by debiru** [comment]
報告ありがとうございます。

修正PRを作成し、マージされました。

**Comment by debiru** [comment]
反映されていることを確認したので、Issue をクローズしておきます。
