### ISSUE TITLE
import の動的インポートの更新

### ISSUE THREAD

**Issue by tamuratak** [mozilla-japan/translation#685]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import#%E5%8B%95%E7%9A%84%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88

## 更新内容・備考・ヘルプ

import の動的インポートの節の以下の訳は間違っています。

- 静的にインポートすると、コードの読み込みが大幅に遅くなり、インポートするコードが必要になる可能性が低くなるか、後で必要になる可能性が低くなります。
- 静的にインポートすると、プログラムのメモリー使用量が大幅に増加し、インポートするコードが必要になる可能性が低くなります。

原文は

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#description

The following are some reasons why you might need to use dynamic import:

- When importing statically significantly slows the loading of your code and there is a low likelihood that you will need the code you are importing, or you will not need it until a later time.
- When importing statically significantly increases your program's memory usage and there is a low likelihood that you will need the code you are importing.

なので「(リストの各項で説明していることがあてはまる)ときに dynamic import を使うべき」と解釈しないといけないです。

**Comment by igrep** [comment]
実際のところ、[import *statement* についての原文](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/import)には問題の動的インポートを解説する節がなく、挙げていらっしゃる [import() についての原文](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)に移動してしまっているようです。

で、移動先である [import() についての日本語版のページ](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/import)では、次のとおり正しく訳せているようです。

> import宣言の構文（`import something from "somewhere"`）は静的で、常にモジュールが 読み込まれた時点で評価される結果となります。ダイナミックインポートを使用すると、import宣言の構文の硬直性を回避し、条件付きまたはオンデマンドでモジュールを読み込むことができます。以下のような理由で、動的インポートが使用することがあります。

> - 静的にインポートするとコードの読み込みが著しく遅くなる場合で、インポートしているコードが必要になる可能性が低い、または後日必要になる可能性がある場合。
> - 静的にインポートすると、プログラムのメモリー使用量が大幅に増える場合で、インポートするコードが必要になる可能性が低い場合。
> - 読み込むモジュールが読み込む時点で存在しない場合。
> - インポート指定子文字列を動的に構築する必要がある場合。（静的インポートでは静的指定のみ対応しています。）
> - インポートされるモジュールに副作用があり、ある条件を満たさない限りその副作用を望まない場合。 （モジュールに副作用を持たないことを推奨しますが、モジュールの依存関係でこれを制御できないこともあります）。
> - モジュール以外の環境（例: `eval` やスクリプトファイル）にいるとき。

なので、[import *statement* についての日本語版](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import)から動的インポートの節を削除することで対応します。

**Comment by igrep** [comment]
訂正します。「[import *statement* についての日本語版](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import)から動的インポートの節を削除する」だけで済むかと思いきや、構成や本文が所々変わっているみたいなので、そちらも併せて対応します。

**Comment by hmatrjp** [comment]
PRがマージされ、一段落しているようですので閉じます。何かあったらまた開いてください。
(翻訳ミートアップにて開いているIssue点検中)
