### ISSUE TITLE
CSS セレクター (CSS selectors) の更新

### ISSUE THREAD

**Issue by OTaku10** [mozilla-japan/translation#687]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/Selectors

### 質問 1/2

この記事の最後の2つの章：

- セレクターのリファレンス表
- このモジュール

は英語版では削除されています。削除するべきですか？　ちなみに2つ目の章（「このモジュール」）は日本語翻訳記事の Learn 配下のほぼすべての記事に存在します。

### 質問 2/2

- 英語記事で W3C draft 状態の Selectors Level 4 の外部リンクが追加され、 mature specification と表現されています（Selectors Level 3 同様の扱い）。

> The majority of selectors that you will come across are defined in the Level 3 Selectors specification and Level 4 Selectors specification, which are both mature specifications, therefore you will find excellent browser support for these selectors.

今のところ英語記事の表現通りに記述するつもりですが、この表現は妥当か、詳しい方にも確認していただけると嬉しいです。

### 備考

MDNの翻訳に参加するのは初めてです。

以下の内容の更新を行う予定です。

- 現行の英語記事の反映
- 誤訳の修正（特に CSS Rules, Whitespace）
- URL・マークダウン文法エラーの修正
- その他の修正（表記ゆれ、冗長な表現）

**Comment by debiru** [comment]
> 質問 1

英語版に存在しないのが意図的（合理的）であれば、日本語版からも同様に削除すべきだと考えます。一方で、削除前の方がドキュメントとして有益だと判断できるのであれば、日本語訳には残しておいてもよいかなと考えます。

より適切な判断を下すには、英語版から当該セクションが削除された理由を探る必要がありそうです。

> 質問 2

（私は「詳しい方」とは言い切れませんがコメントしてみます）

現時点で妥当かどうか判断できていませんが、私なら英語版の通りに翻訳してしまいそうです。

内容の妥当性を調査・判断することも非常に有意義ですが、それができない場合には「とりあえず英語版に合わせておく」という方針も良いかと考えているためです。
