### ISSUE TITLE
[MDN] Firefox OS for TV UX Overview

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#69]
TV Gaia の UX に関する記事群 (Firefox_OS_TV_UX とその配下のページ)。こちらはアプリを作る人達の参考にしてもらいたいので訳されていると有り難い記事になります。

https://developer.mozilla.org/en-US/Apps/Design/Firefox_OS_TV_UX

**Comment by mitsuruog** [comment]
@mitsuruog 2016/2/6 やりまーす :rocket:

**Comment by mitsuruog** [comment]
翻訳完了しました。

> TVの画面には特別なユースケースや課題がつきまといます。（The television’s display comes with its challenges and specific use cases）

の部分は解釈が迷っているのでアドバイスしただけると嬉しいです。

**Comment by Uemmra3** [comment]
レビュー着手しました。気にされている部分はとりあえずよいかと。
まだ途中ですが、大きな部分ではタグがありませんでしたのでつけています。

**Comment by dynamis** [comment]
多少更新が必要になってますがひとまず翻訳完了しているので issue は close します。
ありがとうございましたっ！
