### ISSUE TITLE
UI Events の翻訳

### ISSUE THREAD

**Issue by aokashi** [mozilla-japan/translation#691]
## 翻訳対象ページ (原文 URL)
- https://developer.mozilla.org/en-US/docs/Web/API/UI_Events

## 備考・ヘルプ
- 特になし

**Comment by aokashi** [comment]
https://github.com/mdn/translated-content/pull/16952 で翻訳済みの模様。 Close しても良さそう。

**Comment by hmatrjp** [comment]
close してしまってよいと思います。
または、原文の更新が入っていたら、続けて更新することを宣言する手もあります。

**Comment by aokashi** [comment]
翻訳のプルリクエスト以降、原文の更新がないようなので、特に再度更新する必要はないみたいです。
ですので Close します！
