### ISSUE TITLE
リクエスト: fetch() - WebAPI の更新

### ISSUE THREAD

**Issue by orisano** [mozilla-japan/translation#694]
## 更新対象ページ (日本語 URL)
https://developer.mozilla.org/ja/docs/Web/API/fetch

## 更新内容・備考・ヘルプ
構文では options と記載されていて引数では init と記載されているのでどちらかに統一してほしいです
英語版では構文も引数も options　になっています
spec では引数は init なので構文も init でもいいのかなと思います

**Comment by hmatrjp** [comment]
原文では、
https://github.com/mdn/content/discussions/17941
で init から option への変更が提案され、反映されたようです。

**Comment by hmatrjp** [comment]
変更が Merge されましたので、Close します。この件で追加で何かあれば ReOpen してください。
