### ISSUE TITLE
リクエスト:論理積 (&&) の更新

### ISSUE THREAD

**Issue by nkn-ms** [mozilla-japan/translation#700]
## 更新対象ページ (日本語 URL)
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_AND#%E6%BC%94%E7%AE%97%E5%AD%90%E3%81%AE%E5%84%AA%E5%85%88%E9%A0%86%E4%BD%8D

## 更新内容・備考・ヘルプ
-演算子の優先順位

> 以下の式は同じであるように見えるかもしれませんが、異なります。 && 演算子は || 演算子よりも先に実行されるからです（[演算子の優先順位](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Operator_precedence)を参照）。

上記の文は
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_OR#%E6%BC%94%E7%AE%97%E5%AD%90%E3%81%AE%E5%84%AA%E5%85%88%E9%A0%86%E4%BD%8D
論理和 (||)の-演算子の優先順位のコピペとなっており
原文に
> 以下の式は同じであるように見えるかもしれませんが、異なります。

に当たる箇所はないです
原文
>The AND operator has a higher precedence than the OR operator, meaning the && operator is executed before the || operator (see [operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence)).

上記をchatgptに丸投げ↓
AND（&&）演算子はOR（||）演算子よりも優先度が高いため、&&演算子が||演算子よりも先に評価されます（詳細は[演算子の優先順位](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence)を参照してください）。

**Comment by debiru** [comment]
補足情報です。

- 英語版で当該部分が書き換えられたコミット
    - https://github.com/mdn/content/pull/10846/files#diff-449bff15e4a780aa35cac39fdd989ae197be07f99fce564b39557dd839e7f909L77
- 日本語版の編集履歴
    - https://github.com/mdn/translated-content/commits/main/files/ja/web/javascript/reference/operators/logical_and/index.md

**Comment by hmatrjp** [comment]
9/16のミートアップで対応します。確かに、原文にない文が入っていますね。
