### ISSUE TITLE
 HTML: アクセシビリティの基礎 の更新

### ISSUE THREAD

**Issue by nakaakist** [mozilla-japan/translation#701]
## 更新対象ページ (日本語 URL)
https://developer.mozilla.org/ja/docs/Learn/Accessibility/HTML

## 更新内容・備考・ヘルプ
- [UIコントロール セクション](https://developer.mozilla.org/ja/docs/Learn/Accessibility/HTML#ui_%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%AB)の下記2点
  - 「形式コントロール」->「フォームコントロール」に修正
  - 「形式入力」-> 「フォーム入力」に修正

- 詳細
   - [原文](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#ui_controls)では、該当箇所がそれぞれform control, form inputとなっています。「形式xx」という用語はあまり一般的ではない気がするので、「フォームxx」と訳す方がわかりやすく感じます。

**Comment by hmatrjp** [comment]
MDNミートアップ(9/16)で対応します。

> 「形式xx」という用語はあまり一般的ではない

賛成します。さらに、フォーム・コントロールと形式入力が混在していますね。

なお、微小な修正は、ページ下部にある Edit this page on Github からも修正できますので、気が向いたらご利用ください。
参考画像：
![image](https://github.com/mozilla-japan/translation/assets/2672068/81fd3193-ff2e-44ba-b24c-96f06803fe6a)

**Comment by nakaakist** [comment]
ありがとうございます！

> なお、微小な修正は、ページ下部にある Edit this page on Github からも修正できますので、気が向いたらご利用ください。

承知しました。活用させていただきます。
