### ISSUE TITLE
<length> - CSS の更新

### ISSUE THREAD

**Issue by aokashi** [mozilla-japan/translation#705]
## 更新対象ページ (日本語 URL)
   - https://developer.mozilla.org/ja/docs/Web/CSS/length

## 更新内容・備考・ヘルプ
   - 原文では新しい単位（例えば iOS 用に追加された `svh` など) が追加されているので、その箇所の翻訳をします。
       - https://developer.mozilla.org/en-US/docs/Web/CSS/length

**Comment by aokashi** [comment]
現在の日本語版と英語版で異なる箇所

- 「構文」の見出し構造のネストが浅くなっている
  - 構文 → 単位 → 相対的な長さの単位 → フォントの相対長 と結構深いところまで見出しを作成していた
  - 英語原文ではそうではなく、 構文 → フォントの相対長 で済んでいる
- 「ビューポートのパーセント値による寸法」に大まかな分類が追加されている
  - Small, Large, Dynamic, Default
- 各単位に詳しい解説が追加されている
  - `vh` や `vw` では、ブラウザーの高さが `300px` だとした場合、 `70vh` は `210px` と同じ値であると追記されている
- 各単位の順番が若干違う

**Comment by aokashi** [comment]
https://github.com/mdn/translated-content/pull/20267 で翻訳済みの模様。 Close しても良さそう。

**Comment by hmatrjp** [comment]
open したときに気になっていた差異が解消されているようでしたら、closeしてしまってください。

**Comment by aokashi** [comment]
> 現在の日本語版と英語版で異なる箇所
> 
>     * 「構文」の見出し構造のネストが浅くなっている
>       
>       * 構文 → 単位 → 相対的な長さの単位 → フォントの相対長 と結構深いところまで見出しを作成していた
>       * 英語原文ではそうではなく、 構文 → フォントの相対長 で済んでいる
> 
>     * 「ビューポートのパーセント値による寸法」に大まかな分類が追加されている
>       
>       * Small, Large, Dynamic, Default
> 
>     * 各単位に詳しい解説が追加されている
>       
>       * `vh` や `vw` では、ブラウザーの高さが `300px` だとした場合、 `70vh` は `210px` と同じ値であると追記されている
> 
>     * 各単位の順番が若干違う

上記異なる箇所が概ね解消されていることを確認できたので、この Issue は Close します！
