### ISSUE TITLE
Fuzzing 講演資料の翻訳

### ISSUE THREAD

**Issue by chikoski** [mozilla-japan/translation#71]
9/8 のGecko Insideで使用される講演資料の翻訳者を募集します：

* [資料](http://nth10sd.github.io/2015-Fuzzing-and-Mozilla/?full=&lang=en-US#cover)
* [資料のGitHubレポジトリ](https://github.com/nth10sd/2015-Fuzzing-and-Mozilla)

**Comment by dynamis** [comment]
myakura さん登場感謝:
https://twitter.com/myakura/status/639598532588998656

**Comment by myakura** [comment]
あい。
https://github.com/nth10sd/2015-Fuzzing-and-Mozilla/pull/1

**Comment by Uemmra3** [comment]
基本的にはいいと思いますです \(^o^)/ が、ちょっと訳モレっぽいとことかあるので直しときました。
https://github.com/nth10sd/2015-Fuzzing-and-Mozilla/pull/2

**Comment by myakura** [comment]
@Uemmra3 ありがとうございます。reductionとbisectionは訳漏れというか適切な用語を思いつかなかったのですよね。

「(続き)」については、日本語のスライドではcont'd使う例をあまり見ないので違和感があるため省き、
「翻訳者」「開発者」については、謝辞は訳さない方針＆こちらも訳すと違和感があるため訳さない
という意図的な方針がありますが、特にこだわりはないため作成者に任せます。

**Comment by nth10sd** [comment]
Thank you everybody for the translation and the improvements!

FYI between your translations I have added a quote from :arai, a Mozilla community contributor who works on the SpiderMonkey engine. The quote is originally in Japanese and English, so it should already be translated. [1]

[1] http://nth10sd.github.io/2015-Fuzzing-and-Mozilla/?full=&lang=ja-JP#araiquote

**Comment by Uemmra3** [comment]
@myakura おーっっ、とくにcont'dやTranslatorやDeveloperについてはそういう意図だったという事ですよね…。
まず私自身がGit操作が怪しいのでアレ(なんとかPR送れた程度)ですが、今回myakuraさんのrepoをforkして、そちらにPR送れば良かった気もしてます。
今後ともよろしくお願いします！

**Comment by dynamis** [comment]
close しておきますねー
