### ISSUE TITLE
リクエスト: Element: mouseover event の更新

### ISSUE THREAD

**Issue by sizumita** [mozilla-japan/translation#715]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/API/Element/mouseover_event

## 更新内容・備考・ヘルプ

\#構文 セクションのサンプルコードの、`addEventListener`の第一引数が`"mouseover"`ではなく`"mouseout"`になっています。`"mouseover"`に修正をお願いいたします。

**Comment by hmatrjp** [comment]
MDNミートアップ(9/16)で対応します。
なお、微小な修正は、ページ下部にある Edit this page on Github からも修正できますので、気が向いたらご利用ください。
参考画像：
![image](https://github.com/mozilla-japan/translation/assets/2672068/de98410c-678a-4936-9d40-3fe898aefc91)
