### ISSUE TITLE
document.execCommand

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#73]
Flash なしでクリップボードを動かす https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/ ために必要とされている document.execCommand は Flash 引退して貰うための説明として必要とされるドキュメントなので更新したい…

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by marsf** [comment]
更新しました。
https://developer.mozilla.org/ja/docs/Web/API/Document/execCommand

**Comment by dynamis** [comment]
ありがとうございますっ！
