### ISSUE TITLE
リクエスト: SVG 要素リファレンス > g の誤字修正

### ISSUE THREAD

**Issue by ashphy** [mozilla-japan/translation#734]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/SVG/Element/g

## 更新内容・備考・ヘルプ

「多数のオブジェクトを グループかしておくと後に」を「多数のオブジェクトを グループ**化**しておくと後に」

**Comment by debiru** [comment]
@ashphy レポートありがとうございました。

修正内容がマージされ、本番環境に反映されたようです。

反映されたのでこの Issue はクローズしておきます。

**Comment by ashphy** [comment]
素早いご対応ありがとうございました。
