### ISSUE TITLE
HTTPメッセージ の更新

### ISSUE THREAD

**Issue by yui-Kitamura** [mozilla-japan/translation#738]
## 更新対象ページ 
https://developer.mozilla.org/ja/docs/Web/HTTP/Messages

## 更新内容・備考・ヘルプ
RFC定義に沿った用語修正（原文issue https://github.com/mdn/content/issues/28249 ）  
- start-line (開始行) ::= request-line (リクエスト行) | status-line (ステータス行)
- 原文の修正プルリク( https://github.com/mdn/content/pull/28319 )がApproveからMergedに更新されたら反映させる

差し支えなければセルフassignで翻訳に初参画したいです

**Comment by potappo** [comment]
ありがとうございます。assign に関してのルールは特にありませんので、セルフ assign で問題ありません。

**Comment by yui-Kitamura** [comment]
対応しました。成果物(diff)は以下の通りです:
https://github.com/yui-Kitamura/translated-content/commit/b94a7f3fceb1364e752c2edbde4d1bd5907378d9  

「メモ」書きの記法は https://developer.mozilla.org/ja/docs/Games#ウェブゲーム開発 を参照しました

**Comment by yui-Kitamura** [comment]
プルリク開きました。お手すきの際にご確認よろしくおねがいします
