### ISSUE TITLE
[hacks] Firebug & DevTools Integration

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#74]
Firebug が好きな人 (好きだった人) には役立つ Hacks 記事。Firebug 3 の最終リリース時にも多分別途記事が出るでしょうが、Fx44 Develoepr Edition などで開発ツールが話題の今こちらも役があると喜ばれるかも。

https://hacks.mozilla.org/2015/10/firebug-devtools-integration/

**Comment by kishikawakatsumi** [comment]
@dynamis 
[翻訳アドベントカレンダー](http://www.adventar.org/calendars/1026)の私の分として、翻訳してレビュー待ちのステータスにしました。初めての翻訳なので、やり方なども含めておかしなところをご指摘ください。

https://dev.mozilla.jp/2015/12/firebug-devtools-integration/

**Comment by mantaroh** [comment]
こんばんは。吉永です。

少し古いですが、ガイドラインがあります。
https://dev.mozilla.jp/2009/10/guide/

今回の内容では、「英数字と日本語との間には半角空白を入れることを原則とする。」を入れていただければ分かりやすくなるかと思います。

**Comment by kishikawakatsumi** [comment]
@mantaroh ありがとうございます。とても良いガイドラインですね。見つけられていませんでした。ガイドラインを参考にして、全体的に直します。

**Comment by kishikawakatsumi** [comment]
@mantaroh 「英数字と日本語との間には半角空白を入れることを原則とする。」直していただいてありがとうございました。
@dynamis 公開しました。

**Comment by chikoski** [comment]
公開済みということで、closeします。
