### ISSUE TITLE
用語集 - Second-level_Domain の更新

### ISSUE THREAD

**Issue by yukapacos** [mozilla-japan/translation#749]
## 更新対象ページ (日本語 URL)
英語ページ https://developer.mozilla.org/en-US/docs/Glossary/SLD の日本語翻訳 https://developer.mozilla.org/ja/docs/Glossary/SLD は、実質英語ページ https://developer.mozilla.org/en-US/docs/Glossary/Second-level_Domain の翻訳となっているので、日本語翻訳のディレクトリを SLD -> Second-level_Domain に変更したいです。

## 更新内容・備考・ヘルプ
(特になし)

**Comment by yukapacos** [comment]
Second-level_Domain とは別に、SLD https://developer.mozilla.org/en-US/docs/Glossary/SLD というページも存在していて、現存している翻訳ページは SLD のものでした。クローズさせていただきます。

**Comment by yukapacos** [comment]
issueのdescriptionを更新しました。

**Comment by potappo** [comment]
マージしたのでクローズします。

**Comment by yukapacos** [comment]
ありがとうございます！
