### ISSUE TITLE
リクエスト: <source>: メディアまたは画像のソース要素 の更新

### ISSUE THREAD

**Issue by y-hiraoka** [mozilla-japan/translation#750]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/HTML/Element/source#media

## 更新内容・備考・ヘルプ

`media` 属性の説明が英語版と差異がありました。

>この `source` 要素の親が `<picture>` 要素である場合は指定可能ですが、`source` 要素の親が `<audio>` または `<video>` 要素の場合は指定できません。

と記載がありますが、MDN英語版では要素の制約について記載がありませんでした。

**Comment by hmatrjp** [comment]
長く放置状態となっているリクエストですが、今日の翻訳ミートアップで対応したいと思います。

原文では、[昨年のIssue](https://github.com/mdn/content/issues/27079)で制限部分が削除されたので、　
和訳でも該当部分を修正します。
