### ISSUE TITLE
[MDN] Firefox OS Phone Guide - Nexus 4/5

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#76]
Firefox OS Participation Hub でビルドが一般公開されそこからリンクされたので解説ページの需要が高くなりそうです

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Phone_guide/Nexus_4
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Phone_guide/Nexus_5

**Comment by dskmori** [comment]
done.

**Comment by dynamis** [comment]
archive に移されたので close
