### ISSUE TITLE
翻訳ハンズオンを企画したいです。

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#77]
先日のFirefox Developer Confferenceの懇親会で
マーケティング部の宮本さんとの雑談から、翻訳のハンズオンやろうという案がでました。

キグレ＠グンマーがその場でイベント参加打診をした方
- 矢倉さん
- 清水さん
- 可知さん
- 上村さん
※打診した順番
----
### 翻訳ハンズオンのイメージ
- プログラム：休日　午後半分
- ノルマ：１～ｎページをコミットする事
- チーム：２～４人くらい？
- ビギナーとベテランを組み合わせる？
- 翻訳対象：興味のあるもの、又は初心者向けのページを設定
~~~~
あくまでも雑談時でのイメージです。
~~~~
----
#### TODO
- アイディア出し
- 企画のミーティング

**Comment by gurezo** [comment]
濱崎さん

こんばんは。
昨日MDN翻訳企画ミーティングを行いました。
申し訳ありません、濱崎さんへの日程調整のご連絡が漏れていていました。
自分の手落ちでした、すみません。

議事録は下記の通りです。
何かありましたら、アドバイスをお願い致します。
日程・企画内容は下記の通りです。

## 詳細は下記URLをご覧ください
- [Mozilla 翻訳グループ ](
https://groups.google.com/forum/?hl=ja#!forum/mozilla-translations-ja)
- [MDN翻訳ハンズオン議事録](https://public.etherpad-mozilla.org/p/MDN-ja)

----

## 連絡方法
- 基本的に上記Mozilla 翻訳グループに投稿します。
- 漏れがあった場合は、個別対応します。




2015-11-19 6:25 GMT+09:00 hmatrjp <notifications@github.com>:

**Comment by hmatrjp** [comment]
こんばんは、濱崎です。

> 申し訳ありません、濱崎さんへの日程調整のご連絡が漏れていていました。 
> 自分の手落ちでした、すみません。

いえ、少なくとも濱崎への連絡について、グンマーさんの手落ちはありません。
github のこのリポジトリに投稿された記事は
Mozilla-japan translationグルーブ (Google グループ) に流れ、私もそのグループのメンバーですので、
連絡は届いています。
調整さんも見ていたのですが、出張続きで予定が立たず、記入を見送っていました。
議事録も、流れたその日か翌日には1度目を通したのですが、お返事遅くなってしまってすみません。

当日2/6 については、できる限り予定を空けて参加したいと考えています。
進め方も特に異存ありません。場所と、飲み物お菓子も手配ありとのこと、具体的に計画が
進んでいるのを見て、嬉しいです。

2つだけ提案です。
・ノルマについては、コミットだけでなく、作業している参加者への貢献もカウントする
　参加人数にもよりますが、多くなると、初心者からの問い合わせに対応するのに手いっぱいで
　自分の翻訳が進まない人、というのが出てきます。

・使うと便利だと思うツールの紹介時間を入れる(ただし、全員には聞くことを強制しない)
　私の場合は FireDictionary を想定しています。

**Comment by Uemmra3** [comment]
濱崎さん
お忙しいようですが、良ければ登録ください！
http://www.adventar.org/calendars/1026

2015年12月4日(金) 21:21 hmatrjp <notifications@github.com>:

**Comment by gurezo** [comment]
濱崎さん

アドバイス有難うございます。
早速議事録にオプションノルマ（必須ではない）として
6.2.，6.3.を加筆させて頂きました
