### ISSUE TITLE
ウェブフォームへのスタイル設定 の更新

### ISSUE THREAD

**Issue by hirokisuganuma** [mozilla-japan/translation#770]
## 更新対象ページ (日本語 URL)
https://developer.mozilla.org/ja/docs/Learn/Forms/Styling_web_forms

## 更新内容・備考・ヘルプ
初めまして。いつもこちらのwebサイトを利用させていただいております。
誤字と思われる記述を見つけましたので起票いたしました。

原文：部hラウザー

「ブラウザー」と思いましたのでご確認いただけますと幸いです。

**Comment by hmatrjp** [comment]
ご報告ありがとうございました。
こちらのコミットで修正されているようですので、閉じます。
https://github.com/mdn/translated-content/commit/ec62afecb92db9f9b91bde3207e244bd27fa36d5
