### ISSUE TITLE
[MDN] CSS - will-change

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#79]
面白い機能だが使い方が難しい機能でもあるのでちゃんと説明が読めるようになると良いかも
https://developer.mozilla.org/ja/docs/Web/CSS/will-change

日本語解説記事の例:
https://dev.opera.com/articles/ja/css-will-change-property/

**Comment by YuichiNukiyama** [comment]
新規に翻訳してみました。レビューをお願いします。
https://developer.mozilla.org/ja/docs/Web/CSS/will-change

**Comment by hmatrjp** [comment]
気になったところを修正しました。
・, given CSS properties ident:.... の given は、よく見る「与えられた」という意味のものとは少し異なります。（接続詞的用法というやつか）
・will-change: will-change は CSSスタイルシートでの書き方そのままです。

改訂履歴　に余計な文字が入ってしまいました。（最後の k）

**Comment by YuichiNukiyama** [comment]
@hmatrjp Thanks for your review.
