### ISSUE TITLE
論理積 (&&) の誤訳修正リクエスト

### ISSUE THREAD

**Issue by nkn-ms** [mozilla-japan/translation#791]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_AND

[演算子の優先順位](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_AND#%E6%BC%94%E7%AE%97%E5%AD%90%E3%81%AE%E5%84%AA%E5%85%88%E9%A0%86%E4%BD%8D)
の式文に誤りがあります。

```
false || (true && true); // true を返す　　　　　　←カッコがあるのが間違い
true && (false || false); // false を返す
2 == 3 || (4 < 0 && 1 == 1); // false を返す　　　　←　原文と異なる
```
↓原文
```
true || false && false; // true
true && (false || false); // false
(2 === 3) || (4 < 0) && (1 === 1); // false
```

原因はprettierしたコミットを取り込んだ時に発生したようです。
https://github.com/mdn/translated-content/commit/00f2c695715f3bb78efa0b740e9f953fe06095b8

他にも以下の誤りがあります。

[入れ子になった括弧の除去](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_AND#%E5%85%A5%E3%82%8C%E5%AD%90%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E6%8B%AC%E5%BC%A7%E3%81%AE%E9%99%A4%E5%8E%BB)

`bCondition1 || (Condition2 && bCondition3;`　　⇦はじまりのカッコだけある

原文は↓
`bCondition1 || bCondition2 && bCondition3`

**Comment by hmatrjp** [comment]
お知らせありがとうございます。
こちらも #792 と同じく、式自体は原文と同じにしないと意味が通らないところですね。

**Comment by hmatrjp** [comment]
10/19のMDN翻訳ミートアップで対応します。

**Comment by hmatrjp** [comment]
コミットがマージされれば解決の運びです。
prettier に邪魔させないポイントは、例文の開始 js を js-nolint にしておくことのようです。
