### ISSUE TITLE
リクエスト:<論理和 (||)> の更新

### ISSUE THREAD

**Issue by nkn-ms** [mozilla-japan/translation#792]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_OR

## 更新内容・備考・ヘルプ

こちらの件と同じく
https://github.com/mozilla-japan/translation/issues/791

prettierしたコミットを取り込んだ時に発生した誤訳について報告します。
https://github.com/mdn/translated-content/commit/00f2c695715f3bb78efa0b740e9f953fe06095b8

1. [演算子の優先順位](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_OR#%E6%BC%94%E7%AE%97%E5%AD%90%E3%81%AE%E5%84%AA%E5%85%88%E9%A0%86%E4%BD%8D)

の式文がおかしい
```
true || (false && false); // true を返す。 && が先に実行されるため      　　 ←原文にカッコはない
(true || false) && false; // false を返す。演算子の優先順位が適用されないため　←翻訳が変
```
原文↓
```
true || false && false; // returns true, because && is executed first
(true || false) && false; // returns false, because grouping has the highest precedence
```

原文は以下なので翻訳がずれているように思います
> because grouping has the highest precedence

copilot翻訳
> グループ化の優先順位が最も高いためです

「グループ化の優先順位が最も高いため」と訳すのが適切でしょうか

2. [入れ子になった括弧の除去](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_OR#%E5%85%A5%E3%82%8C%E5%AD%90%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E6%8B%AC%E5%BC%A7%E3%81%AE%E9%99%A4%E5%8E%BB)

の2番目の式文が原文と異なる

```
!(!bCondition1 || (!bCondition2 && !bCondition3));　　←かっこが多い
```

原文↓

```
!(!bCondition1 || !bCondition2 && !bCondition3)

```

**Comment by hmatrjp** [comment]
訳文、原文とも確認したところ、 @nkn-ms さんの書かれたとおりです。
修正自体は単純なので、以下を参考に挑戦してみてはいかがでしょうか。
[【MDN 翻訳コミュニティミートアップ 翻訳ガイド】　の軽微な修正を行いたい場合](https://mozilla-japan.github.io/mdn-translation-guide/misc/for-minor-change.html)
[【MDN 翻訳の流れ 動画版】](https://www.youtube.com/watch?v=KxMmm98emKw)

**Comment by nkn-ms** [comment]
@hmatrjp 
翻訳にお誘いいただきありがとうございます。
プルリクエストを作成しました。
https://github.com/mdn/translated-content/pull/24175

**Comment by hmatrjp** [comment]
さっそくプルリクエストを作っていただき、ありがとうございます。
すでに Merge されたのにこちらが Open のままということは、Fixes キーワードが効いていないようですね。
まだウェブサイトには修正が反映されていないので、ちょうどよいのかもしれません。
（github での変更から、 MDN サイトへの反映まで[最大 48時間かかる](https://github.com/mdn/content/blob/main/CONTRIBUTING.md#pull-request-etiquette)そうです ）

**Comment by nkn-ms** [comment]
@hmatrjp 
closeさせます
翻訳にお誘いいただきありがとうございます。
誤訳に気づいたら報告します。
翻訳は気が向いた時にチャレンジします。
ありがとうございました。
