### ISSUE TITLE
<IndexedDB の使用> の更新

### ISSUE THREAD

**Issue by mahito1594** [mozilla-japan/translation#794]
## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/API/IndexedDB_API/Using_IndexedDB

### 更新内容
[以下の記載](https://github.com/mdn/translated-content/blob/5e1b3bc168bd5352586a3af7718978dcf2556b93/files/ja/web/api/indexeddb_api/using_indexeddb/index.md?plain=1#L68) が英語版からは削除されているため、更新をお願いします。

> (Firefox のプライベートブラウジングモードや Chrome のシークレットモードのことですが、2021 年 5 月現在の Firefox ではこれが[未実装です](https://bugzilla.mozilla.org/show_bug.cgi?id=781982)ので、Firefox のプライベートブラウジングでは IndexedDB をまったく使用できません)

現在 Firefox はプライベートブラウジングでも IndexedDB を使用できるようです:

- 英語版記事で該当箇所が削除された Pull Request: https://github.com/mdn/content/pull/28652
- Bugzilla: [[meta] Support IndexedDB in Private Browsing Mode (with encrypted disk storage)](https://bugzilla.mozilla.org/show_bug.cgi?id=1639542)

**Comment by hmatrjp** [comment]
確かにご指摘の該当部分が原文から削除されていますね。ありがとうございます。

和訳を合わせるための編集自体は単純な削除なので、
以下を参考に挑戦してみてはいかがでしょうか。
[【MDN 翻訳コミュニティミートアップ 翻訳ガイド】　の軽微な修正を行いたい場合](https://mozilla-japan.github.io/mdn-translation-guide/misc/for-minor-change.html)
[【MDN 翻訳の流れ 動画版】](https://www.youtube.com/watch?v=KxMmm98emKw)

**Comment by mahito1594** [comment]
@hmatrjp 
ありがとうございます。
編集にチャレンジしてみます。

**Comment by mahito1594** [comment]
PR マージと Web サイトへの反映が確認できたためクローズします
