### ISSUE TITLE
[hacks]  Service Worker に関する記事の翻訳

### ISSUE THREAD

**Issue by mantaroh** [mozilla-japan/translation#80]
https://hacks.mozilla.org/2015/12/beyond-offline/

Service Worker に興味がある方は是非！
Mozilla Hack 記事なので、以下の Hacks ブログ翻訳に投稿していただけると助かりますー。
https://dev.mozilla.jp/project/hacksmozillaorg/

**Comment by lv7777** [comment]
翻訳開始します。

**Comment by lv7777** [comment]
一応終わりました。レビューしてほしい場合ってどうすればいいですかね？

**Comment by mantaroh** [comment]
ありがとうございます！
翻訳していただいた URL を教えていただければ確認いたしますー。

Mozilla Developer Street (Mozilla Hacks ブログ翻訳)に翻訳記事を書かれている場合は、
状態を「レビュー待ち」にしてレビューを依頼することもできます。

**Comment by lv7777** [comment]
お願いします。
https://dev.mozilla.jp/2016/01/%E3%82%AA%E3%83%95%E3%83%A9%E3%82%A4%E3%83%B3%E3%81%AE%E4%B8%96%E7%95%8C/

**Comment by hmatrjp** [comment]
翻訳ありがとうございます。

原文へのリンクを入れてください。入れ方は、過去の記事が参考になります。例えば
https://dev.mozilla.jp/2015/12/trainspotting-2015-%E5%B9%B4%E3%81%AE-firefox/

文が途切れているところもあるようですが、特にここがわからなかった、という箇所ありますか？
あれば、そこを優先して見ます。

**Comment by lv7777** [comment]
指摘ありがとうございます。
原文へのリンクなど入れておきました。文は移植するときにミスって変なとこで改行が入っていたようです。

ボロボロなのは自分でもわかっているので正直全部見た頂きたいですが、

* Service workers today（今日におけるServiceWorker）の後半部分
* API analytics(APIの解析)
* Implementing modern framework functionality（機能的な現代のフレームワークを実装する。）

などをreviewして頂けると嬉しいです。

http://lv7777.hatenablog.com/entry/2016/01/03/212550
ここに原文と翻訳が載っています。

**Comment by hmatrjp** [comment]
箇条書きされた3点について、hatenablog も読みながら書いています。
私の解釈も載せておくので、適宜取捨選択してください。意訳あり、必ずしも文対文で対応していないなど、英語の試験では満点が取れないような書き方をしている部分もあります。

まず1点目から。
・ふたつの concept（概念） の関係が読み取れないと、訳も混乱すると思います。
・ここでのintercept の後、リクエストは元の目的どおりネットワークへ向かうので、妨害でなく乗っ取りとしました。
・The best part? は動詞がありませんが、一文の扱いです。
・最後の文は、訳が見当たりません。


最初の取り組みは、ナビゲーションコントロールの概念を導入することになりました。これは後にService Worker の fetch functional event の概念へと成長しました。つまり、ネットワークへ向かうリクエストを乗っ取り、ネットワークまたはデータベースより得たデータ、もしくは手続きに従って生成されたデータを返すやり方です。良い点は？制御されているページは、乗っ取られていることを知る必要がないので（知らせを受け取ることは可能です）、サービスロジックは完全にアプリケーションロジックから切り離されています。完全な"中間者"です。

しかしハッカー（結局これもハッカーブログだからね！！）として、私たちが好むのは、そうすることが適切である問題に対しては「まっとうでない」解決策を作ることで、時として「まっとうでない」とはあるものの使い方がその本来の目的とは異なっていることを意味します。Mozilla では WADIと Firefox OS initiative が Service Worker の次に挙げるような、本来の用法とは異なる使い方を探っています。


2点目：
・最初の application はアプリのことではなく、応用。
・ここのleave の使い方が「残す」ではなく、「〜するままに放っておく」という意味合いです。


Man in the middle の直接的な応用から始めましょう、API の解析です。
あなたはAPIの使用回数の統計がほしい、そしてサーバーにアクセスできないと想定しましょう。
従来の解決方法ではクライアントコードに手を加え、HTTPリクエストを作成し適切なログをanalytics serviceに送信します。Service Workerは一枚上手で、それぞれのリクエストを捕まえて引数を抽出し、解析に備えてログを送信した上で、元の形のリクエストがネットワークに到達するようにできます。


3点目：
・framework の訳はフレームワークで統一しておいた方がプログラミング関係者には通りが良いと思います。
・render は、描画よりも広い意味で、「〜をこなした結果として〜を作り出す」
・後半は、原文では一文ですが、日本語では無理せず分けた方がわかりやすいと思います。


Service Worker はモダンなフレームワーク用の構成要素として、独自の位置づけを確保しています。
例として、template interpolationを考えてみます。 backbone.js や Angularのような現在のポピュラーなウェブアプリ用のフレームワークの多くは、テンプレートにプロパティを補間することで、モデルから動作するものを作り出しています。上で述べた New Gaia Architecture では、レンダーストアという概念を導入しています。これはオフラインキャッシュであり、データモデルを補間した結果を格納しておきます。再びクライアントが同じモデルをリクエストしたときにはレンダーストアから取り出すことで、補間にかかる時間を節約することができます。

**Comment by lv7777** [comment]
レビュー全部読ませて頂きました。
ありがとうございました。
modestの方も修正しました。

**Comment by chikoski** [comment]
公開、レビュー反映済みということでクローズします。
