### ISSUE TITLE
Symmetric-key cryptographyの誤植を修正

### ISSUE THREAD

**Issue by OHMORIYUSUKE** [mozilla-japan/translation#800]
誤植を修正しました。

誤：[対象か偽アルゴリズム](https://developer.mozilla.org/ja/docs/Glossary/Symmetric-key_cryptography)
正：共通鍵暗号

## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Web/API/SubtleCrypto/encrypt#%E5%AF%BE%E5%BF%9C%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0

## 更新内容・備考・ヘルプ

(特になし)

**Comment by OHMORIYUSUKE** [comment]
修正しました。
https://github.com/mdn/translated-content/pull/24782

**Comment by hmatrjp** [comment]
ありがとうございました。
こちらも PR 24909 の Fixes キーワードが効いていないようですね。
Merge されているので Close しておきます。
