### ISSUE TITLE
CSS入門のページを更新

### ISSUE THREAD

**Issue by OHMORIYUSUKE** [mozilla-japan/translation#801]
軽微な誤字を修正しました。

## 更新対象ページ (日本語 URL)

https://developer.mozilla.org/ja/docs/Learn/CSS/First_steps/Getting_started

## 更新内容・備考・ヘルプ

(特になし)

**Comment by OHMORIYUSUKE** [comment]
修正しました。
https://github.com/mdn/translated-content/pull/24783

**Comment by hmatrjp** [comment]
ありがとうございました。
PR 24783 の Fixes キーワードが効いていないようですね。
Merge されているので Close しておきます。
