### ISSUE TITLE
用語集Cloud の翻訳

### ISSUE THREAD

**Issue by ycatch** [mozilla-japan/translation#802]
## 翻訳対象ページ (原文 URL)
https://developer.mozilla.org/en-US/docs/Glossary/Cloud

## 備考・ヘルプ

リンク先ページの [Cloud computing](https://developer.mozilla.org/en-US/docs/Glossary/Cloud_computing) も未翻訳のため、いったん英語版にリンクします。

**Comment by hmatrjp** [comment]
リンク先が未訳でも、日本語版へのリンクとしてください。
和訳ページがない場合は、英語版にリダイレクトされます。

**Comment by hmatrjp** [comment]
和訳ありがとうございました。PRが Merge されていますので、閉じます。 @ycatch 
PRを作るときに、 Fixes キーワードを使用すると、 Mergeされた場合に自動的に閉じられます。
