### ISSUE TITLE
MDN 翻訳ハンズオン告知公開しました！

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#82]
MDN 翻訳の初のハンズオンです。
興味のある方は是非、参加してみて下さい！

チューターも絶賛募集中です！
宜しくお願いします。

みんなで、MDN 翻訳に貢献しつつ、英語力上げよう！おー！
https://firefox-os.doorkeeper.jp/events/37119

※プレビューが公開されてないと有りますが、公開済みです！

**Comment by dynamis** [comment]
イベント完了しているので close しておきます
