### ISSUE TITLE
MDN 翻訳ハンズオンの題材記事

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#83]
Mozilla 翻訳グループ各位

お疲れ様です。
お陰様で、イベント公開後に順調に応募して頂いております。

表題や議事録にありますようにハンズオンの記事を
選定しなくては、いけないと思います。

記事選定 [https://developer.mozilla.org/ja/docs/MDN/Doc_status/Overview](https://developer.mozilla.org/ja/docs/MDN/Doc_status/Overview)
・翻訳手直し
・更新系
・原文がしっかりしているもの
・MDNラーニング
・チュートリアル

議事録より抜粋
[https://public.etherpad-mozilla.org/p/MDN-ja](https://public.etherpad-mozilla.org/p/MDN-ja)

どのような段取りで、どこに情報を集約すれば良いか
アドバイス頂ければ幸いです

きぐれ＠ぐんまー

**Comment by hmatrjp** [comment]
情報は、議事録が公開されているEtherpad に集める、もしくは別にEtherpad を立てるということでいかがでしょうか。

JavaScript とか Firefox OS とか、特定のカテゴリを目標に参加する人には、
カテゴリの最優先記事があればそれを第一候補にしてもらい、
特に目的とする分野を持たない参加者には、MDN User Docs にある記事の原文最新への追随から
入ってもらうのが分かりやすいかなという気がします。
https://developer.mozilla.org/ja/docs/MDN/Doc_status/MDN

濱崎

**Comment by dynamis** [comment]
今回にとどまらずに長期的に関わってもらうという意図であればもしかしたらここの Issues で Good First Translation つけたものをある程度用意しておくと良いんじゃないかって勝手に思ってます。
https://github.com/mozilla-japan/translation/labels/Good%20First%20Translation

毎回流用しそうなイベント説明文とかも Wiki の下に Hands-on-Template 的なページを残しておくとあとで辿りやすいなーとか勝手に思ってみたり:
https://github.com/mozilla-japan/translation/wiki

**Comment by dynamis** [comment]
過去に (github 使用する前) に翻訳ワークショップをしたときの記録とかはこちら
https://old.etherpad-mozilla.org/translist
https://groups.google.com/forum/#!topic/mozilla-translations-ja/cIXKtfxAXp0

当時は便利な MDN doc status ページとかもなかったし MDN 以外も色々提案して他ので translist は etherpad 上で分量とか難易度とか含めてざっと書いたものを用意してたのですが、当日以降も残すとか翻訳したよって通知を受けるとかやっぱ欲しいのでこの GitHub 立てたという流れです。

当日参加者が担当する記事を簡単に表明できるといういみでは etherpad がアカウントも不要でいいのですが、維持管理や長期的なフォローアップ的には GitHub の方が良いというやつです。

**Comment by hmatrjp** [comment]
このGithub を立てたのは、そういう理由もあったんですね。
Etherpad の利用にこだわりはなく、Github 利用に賛成です。

**Comment by gurezo** [comment]
アドバイス有難うございます！
継続して行くのが大事だと思うので、github案が良いと思います。
記事のリストアップのやり方は別途またご相談させて下さいませ。

**Comment by gurezo** [comment]
各位
いよいよ、今週末ですが記事選定が全然出来ていませんでした。
選定できる方、いらっしゃればお願いしたいです。

もしいらっしゃらなければ、dynamisさんのアドバイスで
下記手順にしたいと思います。
・Priority Article から選んで各自 Isuue 立てて、ハンズオンを開始する。

何かアドバイスありましたら、宜しくお願い致します。

**Comment by dynamis** [comment]
参加者さんにとって自分で興味のあるものというのも大事ですから選択肢もそれなりに必要なので問題ないかと思います。直前にでも Priority Article の中で短めのモノとかさらっとリストできると良いかも、くらいです。

ちなみに私は今回に限らず常に初心者さんが参加しやすいように時々 #76 #85 #86 のように GoodFirstTranslation ラベルを付けた Issue を登録し続けていくつもりです。

**Comment by dynamis** [comment]
翻訳の始め方を書いているページへのリンクとかを Wiki に追記するとよいかも:
https://github.com/mozilla-japan/translation/wiki

**Comment by gurezo** [comment]
:+1:

**Comment by dynamis** [comment]
イベント完了しているので close しておきます。
