### ISSUE TITLE
[hacks]2015年のハイライト記事

### ISSUE THREAD

**Issue by mantaroh** [mozilla-japan/translation#84]
https://hacks.mozilla.org/2015/12/trainspotting-firefox-in-2015/
Mozilla Hacks にて Firefox 2015年 のハイライト記事が出ていますので、興味のある方はぜひ！

**Comment by hashedhyphen** [comment]
翻訳しました！ [Trainspotting: 2015 年の Firefox](https://dev.mozilla.jp/2015/12/trainspotting-firefox-in-2015/)

**Comment by hmatrjp** [comment]
hashed hyphen さん、翻訳ありがとうございます。さっそく読ませていただきました。
一点だけ used to の訳し方が気になったので。

> 今までよりも多くクリックされるようなインターフェイスへ改善されました。

→ かつてはより多くのクリックが必要だったインターフェイスが改善されました。

濱崎

**Comment by hashedhyphen** [comment]
濱崎さん、レビューしていただきありがとうございます！
指摘していただいた箇所について、訳文を修正しました。完全に誤訳でした…
[https://dev.mozilla.jp/2015/12/trainspotting-firefox-in-2015/](https://dev.mozilla.jp/2015/12/trainspotting-firefox-in-2015/)
