### ISSUE TITLE
[MDN] Push API

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/translation#85]
Firefox 44 でサポートされる注目機能ですので日本語訳の需要は高いかと思います。

https://developer.mozilla.org/ja/docs/Web/API/Push_API

**Comment by TETRA2000** [comment]
@tetra2000 2016/2/6

**Comment by TETRA2000** [comment]
作業完了(要レビュー)

**Comment by marsf** [comment]
レビュー完了。
配下のページは未訳。

**Comment by TETRA2000** [comment]
@marsf レビューありがとうございます！！

**Comment by Uemmra3** [comment]
閉じようかと思ったけど、配下のページで途中のものがあるので、区切りを付けたい気持ち

**Comment by potappo** [comment]
配下のページ、全般的に更新が少し必要ですので、今日のミートアップで作業します。
- [ ] PushManager
- [ ] PushSubscription
- [ ] PushEvent
- [ ] PushMessageData
- [ ] ServiceWorkerRegistration.pushManager
- [ ] ServiceWorkerGlobalScope.onpush
- [ ] ServiceWorkerGlobalScope.onpushsubscriptionchange
- [ ] push
- [ ] pushsubscriptionchange

**Comment by potappo** [comment]
以下のページ、英語版だと、Web/API/Push_API へのリダイレクトに変わっていますね。
https://developer.mozilla.org/ja/docs/Web/API/Push_API/Using_the_Push_API
仕様的に古い内容だから捨ててリダイレクトしたようです。

下記でリダイレクト前の履歴を確認できます。
https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API?redirect=no
https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API$history

日本語版も追随してリダイレクトしますが、日本語版、10日前に更新されてるので、1週間ぐらい
してから削除します。今日はリダイレクト警告だけ入れておきます。どこかにアーカイブすれば良いかなという気もしますが、古い仕様の状態でどこまで需要あるかは不明です。

**Comment by potappo** [comment]
配下の既存ページの編集レビューと更新完了、リダイレクトも設定しました。
私としては作業完了とみなしますので、クローズします。必要あれば、再オープンするか、別 isuue 立ててください。
