### ISSUE TITLE
DOMContentLoaded

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation#88]
02/06 ぐんまー
DOMContentLoaded
https://developer.mozilla.org/ja/docs/Web/Events/DOMContentLoaded

**Comment by hmatrjp** [comment]
技術レビューと編集レビューのフラグが立っていたものを仕上げました。
必要性を感じたところには既存の訳部分にも手を入れています。確認お願いできますか？ > @gurezo さん

**Comment by gurezo** [comment]
濱崎さん
確認しました！
レビュー＆フォロー有難うございました！
これにて、closeします！
