### ISSUE TITLE
[meta] Web security 配下

### ISSUE THREAD

**Issue by hashedhyphen** [mozilla-japan/translation#92]
Web security - https://developer.mozilla.org/ja/docs/Web/Security

まずは親ページから追随していきます ;-)

**Comment by hashedhyphen** [comment]
ディレクトリ構造が入り乱れているので、まずは子ページの追随・タグの修正をします。ディレクトリ構造の変更がどうしても必要だったら、Bugzilla に載せる or 権限を持っている方に直接声をかける。

**Comment by hashedhyphen** [comment]
状況

* [CSP (Content Security Policy)](https://developer.mozilla.org/ja/docs/Security/CSP_%28Content_Security_Policy%29)
* [HTTP Strict Transport Security](https://developer.mozilla.org/ja/docs/Security/HTTP_Strict_Transport_Security) => OK
* [Insecure passwords](https://developer.mozilla.org/ja/docs/Web/Security/Insecure_passwords) => OK
* [Public Key Pinning](https://developer.mozilla.org/ja/docs/Web/Security/Public_Key_Pinning) => @hashedhyphen
* [Same-origin policy](https://developer.mozilla.org/ja/docs/Web/JavaScript/Same_origin_policy_for_JavaScript)
* [Secure Contexts](https://developer.mozilla.org/ja/docs/Web/Security/Secure_Contexts)
* [Securing your site](https://developer.mozilla.org/ja/docs/Web/Security/Securing_your_site)
* [Site Identity Button](https://developer.mozilla.org/ja/docs/Web/Security/Site_Identity_Button)
* [Subresource Integrity](https://developer.mozilla.org/ja/docs/Web/Security/Subresource_Integrity) => @satakeh さん #94 
* [The Do Not Track Field Guide](https://developer.mozilla.org/ja/docs/The_Do_Not_Track_Field_Guide)
* [Transport Layer Security](https://developer.mozilla.org/ja/docs/Web/Security/Transport_Layer_Security)
* [Weak Signature Algorithm](https://developer.mozilla.org/ja/docs/Web/Security/Weak_Signature_Algorithm)

**Comment by satakeh** [comment]
2016-02-06 Securing your siteを @satakeh が翻訳し始めます

**Comment by hashedhyphen** [comment]
@satakeh よろしくお願いします！

**Comment by satakeh** [comment]
Securing your siteの翻訳終わりました！

**Comment by hashedhyphen** [comment]
@satakeh ありがとうございます！お疲れ様でした！ ;-)

**Comment by hmatrjp** [comment]
ディレクトリ構造について見始めたところ、CSP のページがほぼ（まったく？）同じ内容で3つあります。
https://developer.mozilla.org/ja/docs/Security/CSP_%28Content_Security_Policy%29
https://developer.mozilla.org/ja/docs/Web/Security/CSP
https://developer.mozilla.org/ja/docs/Web/Security/CSP_not_connected
3つめは、おそらく私の手違いによるものです。
残すべきは、言語間リンクがつながっている1番目のものです。

子ページとのつながりで、すぐには解決できない可能性がありますが、
試行錯誤も交えながらできるところからやりますので
可能なところは引き続き子ページの内容の翻訳をお願いします。

濱崎

**Comment by marsf** [comment]
1番目のオリジナルを /docs/web/ へ移動する前に、2番目のが作成されてしまったようですね。
親ページからは、2番目の記事にリンクしています。
https://developer.mozilla.org/ja/docs/Web/Security

1と2の文面は全く同じなので、2を削除して、1のURLを/docs/web/ へ移動する、でよいと思います。
子ページについては、濱崎さんがすでに移動してくれているようなので、文章内に書かれたアンカータグのリンク先を、順次 /docs/Web へ変更すればいいですね。

**Comment by marsf** [comment]
The Do Not Track Field Guide も /docs/Web/Security 下へ移動する必要がありますね。
https://developer.mozilla.org/ja/docs/The_Do_Not_Track_Field_Guide

**Comment by hashedhyphen** [comment]
@hmatrjp @marsf 
濱崎さん、mar さん、お忙しい中ありがとうございます。

新規ページ（[Site Identity Button](https://developer.mozilla.org/ja/docs/Web/Security/Site_Identity_Button) など）は無事に /docs/Web/Security 配下に作成されているので安心しています。

CSP の件ですが mar さんが書かれている通り、2・3 の削除、1 の URL を /docs/Web/Security/CSP が可能であれば非常に助かります。

加えて、現状 [同一オリジンポリシー](https://developer.mozilla.org/ja/docs/Web/JavaScript/Same_origin_policy_for_JavaScript) が /docs/Web/JavaScript/Same_origin_policy_for_JavaScript なのですが、英語版と同じく /docs/Web/Security/Same-origin_policy に移動することは可能でしょうか…？

**Comment by hmatrjp** [comment]
先に、mar さんと hashedhyphen さんからリクエストのあった2つのページ
The Do Not Track Field Guide と 同一オリジンポリシー について、
移動を済ませました。

**Comment by hmatrjp** [comment]
CSP の重複について、teoli さんに、メールで2つめと3つめのページ：
https://developer.mozilla.org/ja/docs/Web/Security/CSP
https://developer.mozilla.org/ja/docs/Web/Security/CSP_not_connected
の削除をお願いしたところです。うまいこと伝わるといいのですが。
（mar さんと hashedhyphen さんにCc: しておきました）

**Comment by hashedhyphen** [comment]
teoli さん宛のメール確認しました。また、既存の CSP ページへのリダイレクト追加もありがとうございます…m(_ _)m

2016年2月12日 21:57 hmatrjp <notifications@github.com>:

**Comment by hashedhyphen** [comment]
濱崎さんのおかげで、親ページからすべての子ページへリンクが貼られました！つい先程 CSP 日本語版に SEO Summary を追加したところ、親ページにも Summary が反映されたので問題ありません。濱崎さん、mar さん、本当にありがとうございました！

**Comment by hmatrjp** [comment]
teoli さんからお返事ありまして、削除ではなく リダイレクトでうまくいくはず、とのアドバイスをもらいました。
やってみたら、/ja/docs/Web/Security/CSP　のレベルまではうまくいきました。
一昨日は、同じステップでエラーメッセージ（うろ覚えですが、子ページの衝突とやら）が出て、
失敗してたんですが。。。

CSP での子ページへのリンクに支障が出ているようなので、
一度、退避した2つのページのリダイレクトを解除します。

**Comment by hmatrjp** [comment]
https://developer.mozilla.org/ja/docs/Web/Security/CSP/Introducing_Content_Security_Policy
で生じていた無限ループは解消しました。

https://developer.mozilla.org/ja/docs/Web/Security/CSP
のContent Security Policy 関連トピック内にあるリンクも更新して、最新のURLに直接飛ぶようにしたので、
このレベルでは大丈夫です。

あとは、
・子ページの中にある、別の子ページへのリンクを最新のものに更新する必要があります。
　そうしないと、回り回って CSP_not_connected/ 以下の残骸に飛びます。
・子ページそのもののタイトルが英語のままになっているところがあります。（利用方法　と　違反レポート）
　親ページ(CSP)にある日本語タイトルに変更するといいと思います。
これはお任せしていいですか？ @hashedhyphen

**Comment by hashedhyphen** [comment]
@hmartjp
濱崎さんありがとうございます！タイトルの日本語化については一通り終わりまして、子ページのリンクもこちらで張り直します。本当にありがとうございました！

**Comment by hashedhyphen** [comment]
濱崎さんありがとうございます！タイトルの日本語化については先程終わりまして、子ページのリンクもこちらで張り直します。本当にありがとうございました！

**Comment by hashedhyphen** [comment]
@hmatrjp CSP 関連のリンク修正作業が一通り終わりました。CSP_floating のリダイレクトを再適用すれば、ディレクトリ構造のリファクタリングは一段落ということで大丈夫なのでしょうか？

**Comment by hmatrjp** [comment]
@hashedhyphen 
おっとっと、CSP_floating だけ忘れていました。お知らせありがとうございます。
リダイレクトに戻しました。親ページ
https://developer.mozilla.org/ja/docs/Web/Security
 のスーパーリロードを行って、一覧の中でCSPの重複表示が解消するところまでは確かめました。
あとは、何か副作用が残っていなければ大丈夫だと思います。気づいた点ありましたら、お知らせください。

濱崎

**Comment by hashedhyphen** [comment]
現時点において副作用は特に発生していないようです。英語版の Web security 配下に追随できる環境にするという、当初の目標にたどり着けましたので、この Issue も一区切り付けさせていただきたいと思います。ご協力していただいた皆様、特に @satakeh さん、@marsf さん、そして @hmatrjp さん、本当にありがとうございました！
