### ISSUE TITLE
Gaia UI テストの実行の仕方

### ISSUE THREAD

**Issue by keikocanary** [mozilla-japan/translation#93]
2/6 https://developer.mozilla.org/ja/Firefox_OS/Platform/Automated_testing/gaia-ui-tests/Gaia_UI_Tests_Run_Tests$edit

**Comment by keikocanary** [comment]
Gaia UI テストの実行の仕方

https://developer.mozilla.org/ja/Firefox_OS/Platform/Automated_testing/gaia-ui-tests/Gaia_UI_Tests_Run_Tests$edit

**Comment by Uemmra3** [comment]
タイトル変えました。

あとドキュメント内に原文(英語の文)を残されていますが、訳が終わったら、消して行って下さいねー。

もし「訳に自信がない」という事であれば、編集レビューのフラグを付けてみてください。
(編集画面の下の方にチェックボックスあります)

**Comment by keikocanary** [comment]
ありがとうございます！
一通り終わったら、フラグ付けます！

**Comment by Uemmra3** [comment]
ちょっと見てみましたが、かなりの大物ですね。。
個人的に大事と思っている、SEO Summary と　見出しをレビューしました。
Continuous Integration は、継続的インテグレーション(C.I.とも言います)という技術用語です。

あと後学のためにお聞きしますが、
Linux, Mac, and Windows
を
Windows、Mac、及びLinux
のように、逆順に訳されているのはどんな意図があるのでしょうか？

**Comment by keikocanary** [comment]
ありがとうございます！。

そうだったのですね。勉強になります。> Continuous Integration

そこは、英語の文法は日本語の逆、というのが無意識に頭にあったので、逆にしていました。
書いている順で良いのですね。> Linux,Mac, and Windows

**Comment by Uemmra3** [comment]
長いページお疲れ様でした！
今は出先なので、後で見てみようと思います。

andやorの件、住所は逆ですよね...。
ふだんの名詞はそのままでいいと思いますよ～。
あとは私も時々忘れますが、","(半角コロン)は"、"(読点)に置換した方がいいとかくらいですね。

2016年2月11日(木) 16:07 Keikocanary <notifications@github.com>:

**Comment by hmatrjp** [comment]
まだ翻訳途中のようですので、ローカライズフラグの 翻訳途中 を立てました。

内容の詳細は見ていませんが、大枠で気づいた点が3つあります。
1) 日本語側に残っている英文と、英語版の対応する箇所の英文に差があります。
　原文の更新を取り込んでください。

2) MDN内の文書へのリンクは、/ja/向けにしてください。
　例：
　https://developer.mozilla.org/en-US/Firefox_OS/Using_the_B2G_desktop_client
　でなく、
　https://developer.mozilla.org/ja/Firefox_OS/Using_the_B2G_desktop_client
　へ。
　まだ /ja/がないものでも、 MDN のシステムが良きに計らってくれます。
　（実際にどんな動きになるかは試してみてください）
　
3. ページが置かれるべき位置が英語版で変更されていますので、翻訳が一段落したら日本語版も動かします。
　現状）https://developer.mozilla.org/ja/Firefox_OS/Platform/Automated_testing/gaia-ui-tests/Gaia_UI_Tests_Run_Tests
　本来）https://developer.mozilla.org/ja/docs/Mozilla/Firefox_OS/Automated_testing/gaia-ui-tests/Gaia_UI_Tests_Run_Tests

　リンク付きでお知らせしたのは、このIssue の一番上にあるリンクから、毎回編集に飛んでいるのではないかと思ったからです。移動してもいいタイミングになったらお知らせください。

濱崎

**Comment by Uemmra3** [comment]
@keikocanary 

明日の翻訳ミートアップにリモート参加するつもりだったのですが、別の予定とかぶってしまったため、欠席しますm(_ _)m

> 1) 日本語側に残っている英文と、英語版の対応する箇所の英文に差があります。
> 　原文の更新を取り込んでください。

こちらで、未訳の部分(要するに下の方)はざっと対応しておきました。
日本語訳が済んでいる部分でも、en-us版への追従が要るかもしれません。
右上の歯車アイコンの所から変更履歴(history)が見られますので、活用してみてください。

**Comment by Uemmra3** [comment]
残念ながらアーカイブ化されたので閉じます。
