### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by knagato** [mozilla-japan/translation#95]
2016年2月6日 knagato
SVG
https://developer.mozilla.org/ja/docs/Web/SVG

**Comment by knagato** [comment]
2016年2月6日 knagato
HTML の内容への SVG 効果の適用
https://developer.mozilla.org/ja/docs/Applying_SVG_effects_to_HTML_content

**Comment by knagato** [comment]
上記完了しました

**Comment by hmatrjp** [comment]
[SVG](https://developer.mozilla.org/ja/docs/Web/SVG)については、2月10日に原文に改訂が入っていたので、気になった点の修正がてら、追随しました。
[HTML の内容への SVG 効果の適用](https://developer.mozilla.org/ja/docs/Applying_SVG_effects_to_HTML_content)については @knagato さん、対応可能でしょうか？

**Comment by knagato** [comment]
@hmatrjp ありがとうございます！
HTML の内容への SVG 効果の適用のほう、確認します

**Comment by dynamis** [comment]
完了していると思うので close しておきます。

**Comment by hmatrjp** [comment]
HTML の内容への SVG 効果の適用　を、英語版の階層に合わせて
https://developer.mozilla.org/ja/docs/Web/SVG/Applying_SVG_effects_to_HTML_content
へ移動しました。
