### ISSUE TITLE
animation - CSS

### ISSUE THREAD

**Issue by WhiteHawk-taka** [mozilla-japan/translation#97]
2016年2月6日
https://developer.mozilla.org/ja/docs/Web/CSS/animation
翻訳開始します

**Comment by WhiteHawk-taka** [comment]
翻訳終了しました
レビューをお願いします

**Comment by hmatrjp** [comment]
ハンズオンから2ヶ月以上が経ってしまいましたが、見ました。
いくつか表現を直したところがあります。←英語ならではの語順で書かれていて日本語に直すのに苦労するところがありました。@WhiteHawk-taka さんの解釈から ずれてしまっていないか確認をお願いします。

**Comment by WhiteHawk-taka** [comment]
@hmatrjp レビューありがとうございます。
解釈にずれはありません。

**Comment by Uemmra3** [comment]
解決済みなので閉じておきます。
