### ISSUE TITLE
Translating MDN pages

### ISSUE THREAD

**Issue by potappo** [mozilla-japan/translation#98]
https://developer.mozilla.org/ja/docs/MDN/Contribute/Localize/Translating_pages

見出しの「ページの翻訳を始める」が h2 要素でないのを修正、http://fxos.org/hacks/mdn_doc_fest/ へのリンクを追加する。

**Comment by lv7777** [comment]
ページ確認しましたが修正完了してるっぽいですね？
お疲れ様です。
closeします。
