### ISSUE TITLE
[MDN] HTML data要素

### ISSUE THREAD

**Issue by aokashi** [mozilla-japan/translation#99]
- https://developer.mozilla.org/ja/docs/Web/HTML/Element/data

data要素、初めて見たが、ちょっと翻訳してみます。

**Comment by aokashi** [comment]
https://developer.mozilla.org/ja/docs/Web/HTML/Element/code
code要素を元に翻訳してみました。

**Comment by hmatrjp** [comment]
翻訳ありがとうございます。
MDN内にある文書へのリンクが英語に飛ぶようになっていますね。
日本語に飛ぶように直してもらえますか？
それぞれのリンクURLの中の /en-US/ となっているところを /ja/にすればOKです。

濱崎

**Comment by hmatrjp** [comment]
@aokashi /ja/ への変更確認しました。ありがとうございました。
濱崎

**Comment by aokashi** [comment]
data要素、今まで見たことのない要素だったのでまた勉強する機会になりました。
ただ、資料が少ないことと、実際に試していないため、まだ翻訳間違いがあるかもしれません。

**Comment by hmatrjp** [comment]
このIssueの元のタイトルだった[Vendor_Prefix](https://developer.mozilla.org/ja/docs/Glossary/Vendor_Prefix)について、いくつか訳の訂正をしました。
末尾のWikipedia は、日本語版には対応するものがないので、英語版へのリンクを追記しました。もしも日本語で読める他の記事があれば、追記してもいいと思います。

**Comment by potappo** [comment]
HTML data要素について、最新版を反映して更新しました。
Vendor prefix については更新、追記はありません。
本 issue をクローズします。
